### ISSUE TITLE
有关oneflow CI构建的相关资料

### ISSUE THREAD

**Issue by sanbuphy** [Oneflow-Inc/oneflow#10051]
### Description

Hi！ 我正在研究不同开源项目的CI是怎么构建的，我想对比他们的异同和各自的好处，保护程度和适度的抽象程度。请问oneflow有对于CI的一些比较详细的资料讲解吗，非常感谢。

**Comment by jackalcooper** [comment]
主要是这两处
https://github.com/Oneflow-Inc/oneflow/tree/master/.github/workflows
https://github.com/Oneflow-Inc/get-oneflow
