### ISSUE TITLE
New Issue : oneflow._oneflow_internal.exception.RuntimeError: Error: Check failed: (21 == 22) 

### ISSUE THREAD

**Issue by abi98213** [Oneflow-Inc/oneflow#10156]
## Summary

With the new update of Oneflow Nightly this issue has started to occur. With the same code base it was working really fine with previous update. 

## Code to reproduce bug

     `import oneflow as flow
      import cv2
      import numpy as np
      from onediff import OneFlowStableDiffusionPipeline
      from diffusers import StableDiffusionPipeline, EulerAncestralDiscreteScheduler
      import oneflow as flow

    pipe = OneFlowStableDiffusionPipeline.from_pretrained('xyzmodel', torch_dtype=flow.float16)
    pipe = pipe.to('cuda')
    
    pipe.set_graph_compile_cache_size(15)
    pipe.enable_graph_share_mem()
        
    sizes = [512, 648]
    
    for item in sizes:
        img = pipe("A beautiful house", width = item, height = item)
    `

This is the stack trace
`l `accelerate` for faster and less memory-intense model loading. You can do so with: 
    ```
    pip install accelerate
    ```
    .
    tokenizer transformers CLIPTokenizer
    <bound method PreTrainedTokenizerBase.from_pretrained of <class 'transformers.models.clip.tokenization_clip.CLIPTokenizer'>> <class 'method'>
    feature_extractor transformers CLIPFeatureExtractor
    <bound method ImageProcessingMixin.from_pretrained of <class 'transformers.models.clip.feature_extraction_clip.CLIPFeatureExtractor'>> <class 'method'>
    /home/ubuntu/bento/stable-diffusion-bentoml/venv/lib/python3.10/site-packages/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
      warnings.warn(
    unet diffusers UNet2DConditionModel
    <bound method ModelMixin.from_pretrained of <class 'diffusers.models.unet_2d_condition.UNet2DConditionModel'>> <class 'method'>
    The config attributes {'cross_attention_norm': None, 'encoder_hid_dim': None, 'mid_block_only_cross_attention': None, 'resnet_out_scale_factor': 1.0, 'resnet_skip_time_act': False, 'time_embedding_act_fn': None} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
    text_encoder transformers CLIPTextModel
    <bound method PreTrainedModel.from_pretrained of <class 'transformers.models.clip.modeling_clip.CLIPTextModel'>> <class 'method'>
    scheduler diffusers PNDMScheduler
    <bound method SchedulerMixin.from_pretrained of <class 'diffusers.schedulers.scheduling_pndm.PNDMScheduler'>> <class 'method'>
    safety_checker stable_diffusion StableDiffusionSafetyChecker
    <bound method PreTrainedModel.from_pretrained of <class 'diffusers.pipelines.stable_diffusion.safety_checker.StableDiffusionSafetyChecker'>> <class 'method'>
    vae diffusers AutoencoderKL
    <bound method ModelMixin.from_pretrained of <class 'diffusers.models.autoencoder_kl.AutoencoderKL'>> <class 'method'>
    100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:06<00:00,  7.51it/s]
      0%|                                                                                                                                                          | 0/50 [00:01<?, ?it/s]
    Traceback (most recent call last):
      File "/home/ubuntu/bento/stable-diffusion-bentoml/fp16/test_service.py", line 23, in <module>
        img = pipe("A beautiful girl", width = item, height = item)
      File "/home/ubuntu/bento/stable-diffusion-bentoml/venv/lib/python3.10/site-packages/oneflow/autograd/autograd_mode.py", line 154, in wrapper
        return func(*args, **kwargs)
      File "/home/ubuntu/bento/stable-diffusion-bentoml/venv/lib/python3.10/site-packages/onediff/pipeline_stable_diffusion_oneflow.py", line 702, in __call__
        noise_pred = unet_graph(latent_model_input, t, text_embeddings)
      File "/home/ubuntu/bento/stable-diffusion-bentoml/venv/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 268, in __call__
        return self._dynamic_input_graph_cache(*args, **kwargs)
      File "/home/ubuntu/bento/stable-diffusion-bentoml/venv/lib/python3.10/site-packages/oneflow/nn/graph/cache.py", line 115, in __call__
        return graph(*args, **kwargs)
      File "/home/ubuntu/bento/stable-diffusion-bentoml/venv/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 271, in __call__
        self._compile(*args, **kwargs)
      File "/home/ubuntu/bento/stable-diffusion-bentoml/venv/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 841, in _compile
        return self._compile_from_shared(*args, **kwargs)
      File "/home/ubuntu/bento/stable-diffusion-bentoml/venv/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 958, in _compile_from_shared
        self._c_nn_graph.build_with_new_input_from_shared_graph(
    oneflow._oneflow_internal.exception.RuntimeError: Error: Check failed: (21 == 22) `

## System Information

- What is your OneFlow installation (pip, source, dockerhub): Pip
- OS: Ubuntu 20
- OneFlow version (run `python3 -m oneflow --doctor`): 0.9.1.dev20230417+cu117
- Python version: 3.10.10
- CUDA driver version: 11.7
- GPU models: A10
- Other info:

**Comment by abi98213** [comment]
@doombeaker  If you can please see

**Comment by abi98213** [comment]
@jackalcooper

**Comment by abi98213** [comment]
The previously working version was : oneflow==0.9.1.dev20230415+cu117. If you guys can hold the previous versions as well in github or in your staging websites. That will get very easier for people who have been using previous versions
Thanks

**Comment by jackalcooper** [comment]
> The previously working version was : oneflow==0.9.1.dev20230415+cu117. If you guys can hold the previous versions as well in github or in your staging websites. That will get very easier for people who have been using previous versions
> Thanks

I will post a link but the wheels will been delete in 30 days FYI.

**Comment by jackalcooper** [comment]
```
python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu117/2cad0228ed88ad4593e97495bd96aaa3d25b6a8c/index.html
```

**Comment by jackalcooper** [comment]
@abi98213 could you change the resolutions to `[768, 640, 512, 384]` ?  368 and 648 are kind of irregular and some kernels can't support the shape under the responsive settings.

**Comment by mnpenner** [comment]
I'm hitting this too. I think the width and height have to multiples of 64.
