### ISSUE TITLE
liboneflow.so: undefined symbol: _ZN4llvm15itaniumDemangleEPKc when import oneflow 

### ISSUE THREAD

**Issue by raymond1123** [Oneflow-Inc/oneflow#10329]
## Summary
Build on bare metal following the README description, but when I use python to import oneflow, there is an error:
```
>>> import oneflow as flow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/raymond/workspace/my_git/oneflow/python/oneflow/__init__.py", line 26, in <module>
    import oneflow._oneflow_internal
ImportError: /home/raymond/workspace/my_git/oneflow/build/liboneflow.so: undefined symbol: _ZN4llvm15itaniumDemangleEPKc
>>> 
```

## Code to reproduce bug

just import oneflow
```
import oneflow
```

## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS:  Ubuntu 20.04
- OneFlow version: clone from github (2023.09.04)
- Python version: 3.8.5
- CUDA driver version: 11.4 
- GPU models: 3080Ti
- Other info: none

**Comment by levi131** [comment]
Please try add `set(BUILD_SHARED_LIBS YES CACHE BOOL "")` in `cuda.cmake` and build with new cmake file.
