### ISSUE TITLE
能否在graph编译后对权重进行修改，而不需要重新编译？

### ISSUE THREAD

**Issue by zhangvia** [Oneflow-Inc/oneflow#10354]
### Description

在graph.py中只提供了加载静态图模型的方法。能否在编译完成后，随时修改权重，而不需要重新编译？nn_graph.cpp中也只允许新增新的权重参数，不允许修改原有的参数。是因为修改原有参数会有问题吗

**Comment by strint** [comment]
> ### Description
> 在graph.py中只提供了加载静态图模型的方法。能否在编译完成后，随时修改权重，而不需要重新编译？nn_graph.cpp中也只允许新增新的权重参数，不允许修改原有的参数。是因为修改原有参数会有问题吗

你是在什么实际场景下需要修改参数吗？

> 能否在编译完成后，随时修改权重，而不需要重新编译

是可以的，因为 graph 和 eager 是参数显存共享的。存在特殊情况，一些编译优化会破坏显存共享这个设定。

**Comment by zhangvia** [comment]
> > ### Description
> > 在graph.py中只提供了加载静态图模型的方法。能否在编译完成后，随时修改权重，而不需要重新编译？nn_graph.cpp中也只允许新增新的权重参数，不允许修改原有的参数。是因为修改原有参数会有问题吗
> 
> 你是在什么实际场景下需要修改参数吗？
> 
> > 能否在编译完成后，随时修改权重，而不需要重新编译
> 
> 是可以的，因为 graph 和 eager 是参数显存共享的。存在特殊情况，一些编译优化会破坏显存共享这个设定。

我看了oneflow对sd的加速效果，但是对lora的加载都是只能事先fuse参数，然后compile。但如果出现多个lora需要随时卸载加载，但却需要重新编译，那推理加速就没有意义了

**Comment by zhangvia** [comment]
> 是可以的，因为 graph 和 eager 是参数显存共享的。存在特殊情况，一些编译优化会破坏显存共享这个设定。
也就是说如果我在nn_graph.cpp中新增更新权重的接口，可能会在某些编译优化开启情况下导致错误是吗？另外，关于静态图编译优化选项设置有文档吗

**Comment by strint** [comment]
> > > ### Description
> > > 在graph.py中只提供了加载静态图模型的方法。能否在编译完成后，随时修改权重，而不需要重新编译？nn_graph.cpp中也只允许新增新的权重参数，不允许修改原有的参数。是因为修改原有参数会有问题吗
> > 
> > 
> > 你是在什么实际场景下需要修改参数吗？
> > > 能否在编译完成后，随时修改权重，而不需要重新编译
> > 
> > 
> > 是可以的，因为 graph 和 eager 是参数显存共享的。存在特殊情况，一些编译优化会破坏显存共享这个设定。
> 
> 我看了oneflow对sd的加速效果，但是对lora的加载都是只能事先fuse参数，然后compile。但如果出现多个lora需要随时卸载加载，但却需要重新编译，那推理加速就没有意义了

这个我们内部支持了，还没开放出来，因为我们需要优先支持大客户。

**Comment by strint** [comment]
> > 是可以的，因为 graph 和 eager 是参数显存共享的。存在特殊情况，一些编译优化会破坏显存共享这个设定。
> 
> 也就是说如果我在nn_graph.cpp中新增更新权重的接口，可能会在某些编译优化开启情况下导致错误是吗？另外，关于静态图编译优化选项设置有文档吗

有这种可能。当前还没文档，如果有比较深入的需求可以联系 [caishenghang@oneflow.org](mailto:caishenghang@oneflow.org)

参考：https://github.com/Oneflow-Inc/diffusers#business-inquiry

**Comment by strint** [comment]
@zhangvia 

可以看这个例子，已经完全支持动态切换 lora 了：https://github.com/siliconflow/onediff/blob/main/examples/text_to_image_sdxl_lora.py

**Comment by zhangvia** [comment]
> @zhangvia
> 
> 可以看这个例子，已经完全支持动态切换 lora 了：https://github.com/siliconflow/onediff/blob/main/examples/text_to_image_sdxl_lora.py

看了下，确实可以切换了。但是这个切换速度属实有点慢，要接近10s。。。另外就是有个小bug，先import torch 再import oneflow似乎会导致llvm的相关错误

**Comment by strint** [comment]
我们在这里跟踪这个问题：https://github.com/siliconflow/onediff/issues/465
