### ISSUE TITLE
num_images_per_prompt breaks the app

### ISSUE THREAD

**Issue by kopyl** [Oneflow-Inc/oneflow#10376]
When i add `num_images_per_prompt` to my pipeline, in Jupyter Notebook i see "Kernel restarted".

Without patched unet with Oneflow everything works fine.

**Comment by Xiang-cd** [comment]
may same issue https://github.com/Oneflow-Inc/onediff/issues/432

**Comment by kopyl** [comment]
> may same issue [Oneflow-Inc/onediff#432](https://github.com/Oneflow-Inc/onediff/issues/432)

can't confirm, i did not try that specific argument, only `num_images_per_prompt`.


Thank you

**Comment by strint** [comment]
@kopyl Please refer to https://github.com/Oneflow-Inc/onediff/issues/432#issuecomment-1859751584

**Comment by kopyl** [comment]
@strint thank you very much, I'll try this :)
