### ISSUE TITLE
torch包找不到，请问需要哪个版本的torch，基于cuda还是cpu的？

### ISSUE THREAD

**Issue by jinghere11** [Oneflow-Inc/oneflow#10431]
### Description

![image](https://github.com/Oneflow-Inc/oneflow/assets/110647612/3f4c9c32-c189-4fa1-a680-05b0404440ba)

**Comment by levi131** [comment]
autotest 模块在 OneFlow 开源仓库的 CI中有使用，那里用的是 PyTorch v1.0， 基于 cuda 的。本地运行的话，应该是不限制PyTorch版本，基于 cuda 的。
