### ISSUE TITLE
debug时走不到cpp里，并且一旦import oneflow就拉起好多线程

### ISSUE THREAD

**Issue by jinghere11** [Oneflow-Inc/oneflow#10432]
### Description

参考文档：https://mp.weixin.qq.com/s/vHvz-4T-9w8beoxKOwdzdg
![image](https://github.com/Oneflow-Inc/oneflow/assets/110647612/6724ea97-bdee-45bd-bd42-e511c969daa7)

**Comment by levi131** [comment]
参考的文档是22 年7月份的，比较久了。实测了一下，用最新 master 分支，gdb的时候确实会启动很多线程，不过之后还是可以正常进入到 C++ 代码中，通过 bt 命令看调用栈的。可以用最新 master 分支，再试试。

<img width="1430" alt="image" src="https://github.com/Oneflow-Inc/oneflow/assets/83750468/6026a6c4-628a-44ad-990e-2b41d4cbdc5b">

**Comment by jinghere11** [comment]
> 参考的文档是22 年7月份的，比较久了。实测了一下，用最新 master 分支，gdb的时候确实会启动很多线程，不过之后还是可以正常进入到 C++ 代码中，通过 bt 命令看调用栈的。可以用最新 master 分支，再试试。
> 
> <img alt="image" width="1430" src="https://private-user-images.githubusercontent.com/83750468/302235776-6026a6c4-628a-44ad-990e-2b41d4cbdc5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjYxNDgsIm5iZiI6MTcwNzEyNTg0OCwicGF0aCI6Ii84Mzc1MDQ2OC8zMDIyMzU3NzYtNjAyNmE2YzQtNjI4YS00NGFkLTk5MGUtMmI0MWQ0Y2JkYzViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDA5MzcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwMGViY2ViMzIxYWJhNjliMzIyYmQ1MDA3NTk1NjI2MTg3YmRlNTc0NGYwNjViMGNhNmIyNTlhY2JjZDA4MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Byl4u2hHdmCnhqhB2MY3w8-LgOSXu7JXieqTu_OLwkk">

![image](https://github.com/Oneflow-Inc/oneflow/assets/110647612/8f21c8f4-8430-48b4-b82c-bd74c2c65523)

大佬 还是会卡在glibc的文件找不到，这个croot的路径也不知道怎么生成的，能不能把您的构建方式说一下？
