### ISSUE TITLE
oneflow的tensor如何获取其指针

### ISSUE THREAD

**Issue by bjtuwjx** [Oneflow-Inc/oneflow#10483]
### Description

我正在研究oneflow与triton融合的可行性。triton一个重要的特性就是使用了指针。在pytorch中，可以利用tensor.data_ptr()很方便地获取tensor的指针，请问oneflow中有类似的方法获取tensor的指针吗？如果没有，近期有加入这个方法的计划吗？

**Comment by jackalcooper** [comment]
```python
>>> oneflow.Tensor([0,1]).data_ptr
<built-in method data_ptr of Tensor object at 0x7f108c506050>
```
oneflow 也有这个函数

**Comment by bjtuwjx** [comment]
> ```python
> >>> oneflow.Tensor([0,1]).data_ptr
> <built-in method data_ptr of Tensor object at 0x7f108c506050>
> ```
> 
> oneflow 也有这个函数

是最新版的1.0.0才有吗，我用的0.9.0版本好像没有

**Comment by bjtuwjx** [comment]
`>>> oneflow.__version__`
`'0.9.0'`
`>>> oneflow.Tensor([0,1]).data_ptr`
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Tensor' object has no attribute 'data_ptr'`
