### ISSUE TITLE
wide&deep benchmark中的性能测评文档为死链

### ISSUE THREAD

**Issue by MrChengmo** [Oneflow-Inc/oneflow#3357]
- 在wide&deep文档中：https://github.com/Oneflow-Inc/OneFlow-Benchmark/tree/of_develop_py3/ClickThroughRate/WideDeepLearning

- 如图：
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/29789135/89007410-46a57080-d33b-11ea-835f-2d82ca7182f0.png">

**Comment by MARD1NO** [comment]
正确的链接应该在这里
https://github.com/Oneflow-Inc/OneFlow-Benchmark/tree/of_develop_py3/ClickThroughRate/WideDeepLearning
感谢提醒

**Comment by ShawnXuan** [comment]
https://github.com/Oneflow-Inc/OneFlow-Benchmark/tree/master/ClickThroughRate/WideDeepLearning
这是主分支

**Comment by MARD1NO** [comment]
链接已修复~
