### ISSUE TITLE
check and add lambda func return type when return by const reference

### ISSUE THREAD

**Issue by strint** [Oneflow-Inc/oneflow#3390]
After omiting return type in lambda function, all compiling can pass, but running has different behavior:

g++ 4.8.5 is ok; (4.8.5 is what we use in dev)
g++ 6.5.0 raised segmentation fault;
It seems that Return type deduction in higher version gcc will deducte return by value and cause a dangling reference to a local object. Thus omitting return type in lambda seems a bad pratice.

We use omitting return type a lot, and will fix this style gradually.

ref : https://github.com/Oneflow-Inc/oneflow/pull/3388

**Comment by Ldpe2G** [comment]
According to the discussion of : [What is the return type of a lambda expression if an item of a vector is returned?](https://stackoverflow.com/questions/29610318/what-is-the-return-type-of-a-lambda-expression-if-an-item-of-a-vector-is-returne#:~:text=The%20return%20type%20of%20a%20lambda%20uses%20the%20auto%20return,%5D%3B%7D%3B%20returns%20int%20.) .

The return type of lambda will use return type deduction rule similar to "auto" which will strip the referencenes.

**Comment by strint** [comment]
> According to the discussion of : [What is the return type of a lambda expression if an item of a vector is returned?](https://stackoverflow.com/questions/29610318/what-is-the-return-type-of-a-lambda-expression-if-an-item-of-a-vector-is-returne#:~:text=The%20return%20type%20of%20a%20lambda%20uses%20the%20auto%20return,%5D%3B%7D%3B%20returns%20int%20.) .
> 
> The return type of a lambda will use return type deduction rules similar to "auto" which will strip the referencenes.

And a local var was created to accept lambda func return, then a reference to the local var was return to the local var which result in a segment fault at running time.
