### ISSUE TITLE
Can not run oneflow on the machine with only CPU

### ISSUE THREAD

**Issue by wkcn** [Oneflow-Inc/oneflow#3395]
Hi there, the current version of oneflow does not support running on the machine with only CPU.

In our group, we need to submit jobs into clusters and debug the code in the local machine.

It will be more convenient if supporting only CPU : )

```
➜  oneflow python lenet_train.py 
I0804 09:55:52.425000188   25696 ev_epoll_linux.c:82]        Use of signals is disabled. Epoll engine will not be used
E0804 09:55:52.446593 25696 version.cpp:82] Failed to get cuda runtime version: CUDA driver version is insufficient for CUDA runtime version
F0804 09:55:52.945034 25696 improver.cpp:535] Check failed: mem_size > 0 (-524288000 vs. 0) 
*** Check failure stack trace: ***
    @     0x7fecec2a83bd  google::LogMessage::Fail()
```

**Comment by xiejiachen** [comment]
This issue is on our roadmap, we are working on that

**Comment by jackalcooper** [comment]
https://github.com/Oneflow-Inc/oneflow/pull/3398 Here you can check the latest progress of CPU support.

**Comment by wkcn** [comment]
@jackalcooper Thank you! I'm trying to build it.

**Comment by wkcn** [comment]
The issue has been resolved. Thank you!
