### ISSUE TITLE
build with xla:  protobuf_copy_headers_to_destination error when copy `/oneflow/build/protobuf/src/protobuf/src/google/protobuf/wire_format_lite_inl.h`

### ISSUE THREAD

**Issue by qianzhang613** [Oneflow-Inc/oneflow#3400]
build the latest master branch with xla enable  ,  command is :
```
    git submodule update --init --recursive && \
    cd build && \
    echo $CXXFLAGS && \
    cp -f /usr/lib64/libcu*.a /usr/local/cuda/lib64/ && \ 
    cmake .. -DWITH_XLA=ON -DBUILD_RDMA=ON -DWITH_TENSORRT=OFF -DTHIRD_PARTY=ON -DCMAKE_BUILD_TYPE=Release && \
    make -j 1   && \
    make -j 1 VERBOSE=1 && \
    cmake .. -DWITH_XLA=ON -DBUILD_RDMA=ON -DWITH_TENSORRT=0FF -DTHIRD_PARTY=OFF -DCMAKE_BUILD_TYPE=Release && \
    make -j $(lscpu -e=cpu|tail -n 1) VERBOSE=1  && \
    make pip_install
```

there is build error : 
```
Scanning dependencies of target protobuf_copy_headers_to_destinationError copying file (if different) from "/oneflow/build/protobuf/src/protobuf/src/google/protobuf/wire_format_lite_inl.h" to "/oneflow/third_party/protobuf/include/google/protobuf/wire_format_lite_inl.h".make[2]: *** [protobuf_copy_headers_to_destination] Error 1
```

it is same that  protobuf vesion did not match `./cmake/third_party/header_index/protobuf_xla_headers.txt`

sys infor:
```
os: centos 7.7
gcc : 7.5
cuda:10.1 
cudnn 7.6
tensorrt: 6.0.1
with rmda
```

**Comment by jackalcooper** [comment]
I suppose you build oneflow without RDMA before? 
There are two ways to fix this:
1.
```
rm -rf [oneflow source path root]/build/protobuf
rm -rf [oneflow source path root]/third_party
```
and retry.

2.
- Run cmake in another directory(as long as it is not `[oneflow source path root]/build/`). 
- Why you run cmake, add an extra flag `-DTHIRD_PARTY_DIR=[any path you desire]` (as long as it is not `[oneflow source path root]/third_party`).

It is a bit confusing. Due to historic reasons I couldn't make it more straightforward.

**Comment by qianzhang613** [comment]
> I suppose you build oneflow without XLA before?
> There are two ways to fix this:
> 
> 1. Run these  and retry.
> 
> ```
> rm -rf [oneflow source path root]/build/protobuf
> rm -rf [oneflow source path root]/third_party
> ```
> 
> 1. Use another cmake directory
> 
> * Run cmake in another directory(as long as it is not `[oneflow source path root]/build/`).
> * When you run cmake, add an extra flag `-DTHIRD_PARTY_DIR=[any path you desire]` (as long as it is not `[oneflow source path root]/third_party`).
> 
> It is a bit confusing. Due to historic reasons I couldn't make it more straightforward.

thanks that works
