### ISSUE TITLE
Feature : Python Op

### ISSUE THREAD

**Issue by strint** [Oneflow-Inc/oneflow#3402]
### Objective
Python Op is an op than can wrap a block of python code. With this op we can :
* runing pure python code block inside a lazy graph.
* get more dynamic ability (like eager) in OneFlow lazy mode(with cost of performance).
* do fast print or test using python.

### Design
* Input Shape can be infered , output shape needs to be specified.
* This op's actor  just get input, ran by python, put output.
* Interface should look like a normal Op.
* Need to consider multi machine running, this is a challenge. 
  * Accumulate data ?
  * Split data ?
* Reference watch for print.

This issue is something like a draft RFC. Please comment if you have any idea on this.

**Comment by strint** [comment]
Python Op has two mode :

Compute Mode
* Running on every node
* User can define compute in python, good for quick implementation of op

Watch Mode
* Runnig on master node in python
* User can print/debug/plot in python, good for qucik debug

**Comment by strint** [comment]
For comput mode, we need to embed python 3.5+ in multi thread c++. 

Which lib to choose ? 

- python c api
- pybind11
- boost.python

**Comment by jackalcooper** [comment]
Python c api and `ctypes`. That is the most lightweight and portable solution I think.

**Comment by strint** [comment]
c++ run python code through pybind11 demo:

https://github.com/strint/pybind11_examples/tree/master/12_cpp-vector_numpy-2D

**Comment by jackalcooper** [comment]
Cool. One downside of pybind is that it will lock our front-end to python. We might need to support other front-ends like Swift for TensorFlow which is actually pretty cool in areas like autograd. Sticking to C api and `ctypes` will make OneFlow compatible with any front-end language.

**Comment by strint** [comment]
### Python Op的期待两种主要用途 : Compute / Watch
- Compute 
  - User can define compute in python, good for quick implementation of op
  - 这个可能才是pytorch真正受欢迎的地方，构建新op、构建计算图特别容易
  - 实现后，lazy和eager都可以使用
- Watch
  - lazy 的watch，eager的print都可以实现，所以已经被实现，无需再实现

### python compute op
- 所以重点是实现python compute op
- 考虑和原有系统的结合，实现一种python kernel的方案
- 即用户可以添加一种user op，它的kernel是python实现的，调用python interpreter去执行
### pybind11做的一个demo
- 用户实现一个py_kernel.py，运行时c++ actor加载这个py_kernel.py去执行计算
- 接口确定后，项目可以不再编译，改动py_kernel.py文件就能更新kernel的计算
- https://github.com/strint/pybind11_examples/tree/master/13_c%2B%2B_call_py_kernel

**Comment by lixinqi** [comment]
I don't think it's a good idea to embed python3.5 into c++ right now. The same with Making python op run in two mode. It's user's business to write compute code or watch code in python op.
pybind11 is better than ctypes becuase supporting a new front-end for oneflow has a low priority right now.

**Comment by strint** [comment]
As Oneflow has already has a Python interpreter, it call oneflow_internel writted in  c++, then oneflow_internel need to call Python Interpreter to run python code. This make things complex.

When we use PyBind11, the Python frontend interpreter is not under control of PyBind11, PyBind11's [GIL API]( https://pybind11.readthedocs.io/en/stable/advanced/misc.html#global-interpreter-lock-gil) always raise Segment Fault.

When we try to create a separate interpreter, PyBind11 deals poorly with [sub-interpreter](https://pybind11.readthedocs.io/en/stable/advanced/embedding.html#sub-interpreter-support). 

At last, we choosed the original Python C API and the demo passed the test.
