### ISSUE TITLE
Is batch_axis essential? 

### ISSUE THREAD

**Issue by lixinqi** [Oneflow-Inc/oneflow#3415]
batch_axis is helpful when a) infering sbp signature and b) switching between consistent view and mirrored view.  Does it mean we can remove batch_axis if it no long used by sbp signature and mirrored view switching

**Comment by leaves-zwx** [comment]
1. What's the role that batch_axis play in sbp signature inferring
2. How do switching between consistent view and mirrored view without batch_axis. For example, when converting a mirrored blob to a consistent blob，what's the split axis of the consistent blob?

**Comment by lixinqi** [comment]
Q: What's the role that batch_axis play in sbp signature inferring?
A: batch_axis is used for indicating whether a tensor is data tensor. Sbp signature infer algorithm tends to pick up the sbp signature that can avoid spliting non-data tensor by declining the order value of boxing cost on non-data tensor. However, batch axis is no long used in the new version of sbp signature infer algorithm designed by YiPeng 

Q: How do switching between consistent view and mirrored view without batch_axis?
A: Maybe we can create a module called MirroredModule. split_axis is explicitly declared in arg annotation or return annotation
    e.g.
```
class MyModule(oneflow.nn.MirroredModule):
    def forward(x: tp.SplitParallel(0), w: tp.BroadcastParallel) -> tp.SplitParallel(0):
        pass
```

**Comment by lixinqi** [comment]
Ideas hard to explain is hard to be accepted
