### ISSUE TITLE
May OneFlow pub a GPT-3 demo?

### ISSUE THREAD

**Issue by xiejiachen** [Oneflow-Inc/oneflow#3420]
Do not need too much training and production quality promise.

I mean it would be very helpful if OneFlow can provide a demo to running GBT-3, we do not need to train that with big data.

A simple GBT-3 running demo, including how to split that big model to multiple devices.

**Comment by lixinqi** [comment]
GBT3？Do you mean GPT-3? no one knowns what GPT-3 looks like. Because it hasn’t been published yet.

**Comment by lixinqi** [comment]
There’re lots of way to demonstrate oneflow model parallelism. Bert or WideAndDeep are fine.

**Comment by xiejiachen** [comment]
> There’re lots of way to demonstrate oneflow model parallelism. Bert or WideAndDeep are fine.

Refer [this article](https://zhuanlan.zhihu.com/p/31558973), I guess we can run model of 10 billions of parameters with 90 GB gpu memory, which could be 10 Nvidia 2080-Ti.

Might it be more helpful to users than BERT? 
BERT seems can also runs at single machine, as it only have 340 millions of parameters.
