### ISSUE TITLE
What are the fundamental static attributes of LogicalBlob?

### ISSUE THREAD

**Issue by lixinqi** [Oneflow-Inc/oneflow#3429]
A lot of code are heavily relying on the concept logical blob, which is provided as logical view for blobs resided in devices.  We might need to write a data struct LogicalBlob to describe logical blob.
This is My version of LogicalBlob.
```

message SbpParallelList {
    repeated SbpParallel sbp_parallel;
}

message BlobParallelProto {
    required int64 parallel_desc_symbol_id;
    required Shape time_shape;
    oneof {
        // The last several elements of sbp_list always relate to time_shape
        SbpParallelList sbp_list;
        bool is_mirrored;
    }
}

message LogicalBlobProto {
    required BlobParallelProto blob_parallel;
    required BlobDesc blob_tensor;
    // e.g. dynamic image tensor (N, C, H, W), dynamic_axis is (2, 3)
    repeated int64 dynamic_axis;
}
```

**Comment by lixinqi** [comment]
Many current code are messed up because of a lack of well defined LogicalBlobDescriptor

**Comment by lixinqi** [comment]
dynamic_axis should be put into BlobDesc

**Comment by chengtbf** [comment]
Why need a repeated sbp parallel in BlobParallelProto.sbp_list ? And what is the meaning of each sbp_parallel ?

**Comment by lixinqi** [comment]
BlobParallelProto.sbp_list tells us how a logical tensor is divided into physical one specially and temporally.

**Comment by lixinqi** [comment]
e.g. sbp_list (S(0), S(0))  means tensor is S(0) spatially splitted then S(0) temporally splitted

**Comment by chengtbf** [comment]
> e.g. sbp_list (S(0), S(0)) means tensor is S(0) spatially splitted then S(0) temporally splitted

S(0) spatially splitted is producer view？S(0) temporally splitted is consumer view？

**Comment by lixinqi** [comment]
> > e.g. sbp_list (S(0), S(0)) means tensor is S(0) spatially splitted then S(0) temporally splitted
> 
> S(0) spatially splitted is producer view？S(0) temporally splitted is consumer view？

No. tensors are always splitted from producer's view

**Comment by lixinqi** [comment]
We will get (S(0), S(0)) when nn ran in data parallel with minibatch strategy
