### ISSUE TITLE
CUDNN Error when run resnet50 on multi node (n > 2) 

### ISSUE THREAD

**Issue by chengtbf** [Oneflow-Inc/oneflow#3435]
@ShawnXuan Try run resnet50 on multi node for benchmark in LeiNao machines. OneFlow work well on single node and double node, but will get BUG when node number is 3 or 4. Here is error log:
```
F0806 23:42:58.183782 54414 cuda_util.cpp:97] Check failed: error == CUDNN_STATUS_SUCCESS (9 vs. 0) CUDNN_STATUS_NOT_SUPPORTED
```
OneFlow can run BERT squard job on 4 node 32 GPU.

**Comment by chengtbf** [comment]
I guess the reason for the bug is that we may have problems with the conv2d algorithm of CUDNN in the multi machine environment?

**Comment by ShawnXuan** [comment]
I used to test 3 nodes with 24 gpus on v0.1.6, no error.

**Comment by chengtbf** [comment]
> I used to test 3 nodes with 24 gpus on v0.1.6, no error.

v0.1.6 is success but v0.1.8 will error？
