### ISSUE TITLE
cycle in graph detected when run CPU-only test_where.test_where_grad_case_2

### ISSUE THREAD

**Issue by jackalcooper** [Oneflow-Inc/oneflow#3452]
To reproduce: 
1. build with cmake flag `-DBUILD_CUDA=OFF`
2. add env variable
```
export ONEFLOW_TEST_CPU_ONLY=1
```
3. run `test_where.test_where_grad_case_2` for 5 times or so
```
python3 oneflow/python/test/ops/1node_test.py test_where.test_where_grad_case_2
```

Error:
```
F0809 02:34:33.646538 17753 chain_graph.cpp:259] cycle in graph detected
*** Check failure stack trace: ***
    @     0x7f2fc4f001fc  google::LogMessage::Fail()
    @     0x7f2fc4f00158  google::LogMessage::SendToLog()
    @     0x7f2fc4effadc  google::LogMessage::Flush()
    @     0x7f2fc4f02b83  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f2fc3d937c1  oneflow::ChainGraph::CheckNoCycle()
    @     0x7f2fc3d930b1  oneflow::ChainGraph::ChainGraph()
    @     0x7f2fc3ef969c  oneflow::TaskGraph::MergeChainAndSetOrderInGraphForEachNode()
    @     0x7f2fc3ef88e6  oneflow::TaskGraph::TaskGraph()
    @     0x7f2fc3f43e33  std::make_unique<>()
    @     0x7f2fc3f4256f  oneflow::Compiler::Compile()
    @     0x7f2fc4045f8a  oneflow::(anonymous namespace)::CompileCurJobOnMaster()
    @     0x7f2fc404e542  oneflow::(anonymous namespace)::CompileAndMergePlanOnMaster()
    @     0x7f2fc404f19a  oneflow::Oneflow::Init()
    @     0x7f2fc3b5cd80  oneflow::StartGlobalSession()
    @     0x7f2fc3b5fd1a  StartGlobalSession()
    @     0x7f2fc3b7023b  _wrap_StartGlobalSession
    @           0x50a8af  (unknown)
    @           0x50c5b9  _PyEval_EvalFrameDefault
    @           0x509d48  (unknown)
    @           0x50aa7d  (unknown)
    @           0x50c5b9  _PyEval_EvalFrameDefault
    @           0x509d48  (unknown)
    @           0x50aa7d  (unknown)
    @           0x50c5b9  _PyEval_EvalFrameDefault
    @           0x509d48  (unknown)
    @           0x50aa7d  (unknown)
    @           0x50c5b9  _PyEval_EvalFrameDefault
    @           0x508245  (unknown)

```

**Comment by jackalcooper** [comment]
cycle chain graph
![job0_cycle_chain_graph dot](https://user-images.githubusercontent.com/5133557/89724025-70901e80-da30-11ea-8eaf-9b04e4748c1c.png)

**Comment by jackalcooper** [comment]
cycle task graph
![job0_cycle_task_graph dot](https://user-images.githubusercontent.com/5133557/89724029-7ab21d00-da30-11ea-842f-14a717a3f2f5.png)

**Comment by jackalcooper** [comment]
source code:
https://github.com/Oneflow-Inc/oneflow/blob/176ec6e3bc013916f24e6a7cd794fdd3a47cb318/oneflow/python/test/ops/test_where.py

**Comment by chengtbf** [comment]
The "cycle task graph" you show is the total task graph in this job? 

Why task node "... _19 keep header only " and " ..._18 keep header only" CAN merge into chain with node " BroadcastToCompatibleWith_20" ？ 
Chain merge condition is ：
Chain B can merge into Chain A，when the set of Chain A ancestors and itself  include the set of Chain B ancestors.
                               `B ancestors ⊆ (A ancestors + A)`

Maybe you should print the total task graph （with node like "broadcast_add_16" etc...）to find the reason

**Comment by jackalcooper** [comment]
optimized_dlnet_0_op_graph.dot:

![image](https://user-images.githubusercontent.com/5133557/89753251-1a8fa980-db0a-11ea-9815-d4dc2c9916c5.png)

**Comment by jackalcooper** [comment]
`LogicalGraph/28.dot`
![image](https://user-images.githubusercontent.com/5133557/89753305-4ca10b80-db0a-11ea-8005-1ccf9e3f25f5.png)

**Comment by jackalcooper** [comment]
![job0_cycle_task_graph dot](https://user-images.githubusercontent.com/5133557/89753422-ccc77100-db0a-11ea-9cef-e252bfe02a93.png)
![job0_cycle_chain_graph dot](https://user-images.githubusercontent.com/5133557/89753426-cf29cb00-db0a-11ea-88ad-292922dbb2e8.png)

**Comment by chengtbf** [comment]
![Chain Merge Circle BUG](https://user-images.githubusercontent.com/12186261/90127960-a9195a80-dd98-11ea-9130-3c2f1b77dc07.png)

The circle BUG reason is :
    If the merge order is  Chain { 8 } <- Chain { 4->7 } , Chain { 8 } ancestors include Chain { 4->7 } ancestors , so they merge , and then get the circle chain  BUG. ( the back edge is Node{4->7} -> Node{7} )
    If the merge order is Chain { 4->7 } <- Chain { 8 }, Chain { 4->7 } ancestors NOT include Chain { 8 } ancestors , so they NOT merge , then work well.

So, the solution is increase strict constraints of Chain Merge:

We have Chain A   Chain B 
And we try B merge to A
1. if A is B ancestors
       when (B ancestors ⊆ A + A ancestors  ) merge
2. else :
       when (B ancestors ⊆ A + A ancestors  && A ancestors ⊆ B + B ancestors) merge

**Comment by jackalcooper** [comment]
![optimized_dlnet_0_op_graph_colored_nodes_in_cycle](https://user-images.githubusercontent.com/5133557/90128721-ec27fd80-dd99-11ea-8289-9f261f17bf2b.png)

**Comment by jackalcooper** [comment]
note:
规则1 就是现在的规则
```
bool ChainMerger::IsSubset(const ChainIt& lhs, const ChainIt& rhs) const {
  CHECK_EQ(lhs->ancestors_and_this.size(), rhs->ancestors_and_this.size());
  int64_t bitset_num = lhs->ancestors_and_this.size();
  for (int64_t i = 0; i < bitset_num; ++i) {
    if (lhs->ancestors_and_this.at(i) != (lhs->ancestors_and_this.at(i) | rhs->ancestors.at(i))) {
      return false;
    }
  }
  return true;
}
```
规则2 等价于 A ancestors = B ancestors，可能会产生新的环
![image](https://user-images.githubusercontent.com/5133557/90247195-ad14ad80-de68-11ea-8a1e-41e0c821a69a.png)

**Comment by chengtbf** [comment]
For rule 2, your example is incorrect. The Task Graph is DAG (directed acyclic graph), your example of the origin graph is NOT a DAG.

**Comment by jackalcooper** [comment]
rule 2 will produce a circle in this case:
![image](https://user-images.githubusercontent.com/5133557/90249487-26ae9a80-de6d-11ea-93c1-235c1db9d298.png)

**Comment by chengtbf** [comment]
The  topological order of green nodes is not in same level, how can they be merged into same Chain?  The order of Chain merging is topological.

**Comment by jackalcooper** [comment]
sorry for the confusion. I didn't draw every single edge for the clearity. The full graph should be like this:
![image](https://user-images.githubusercontent.com/5133557/90259540-c9bae080-de7c-11ea-89fc-69fdae65d962.png)

**Comment by chengtbf** [comment]
Take the Chain of three yellow nodes as an example,  the ancestors of the Yellow node on the left are { gray }, while the ancestors of the Yellow nodes in the middle are {gray, green,  brown}. The ancestors of the two nodes are inconsistent and cannot be merged.

**Comment by jackalcooper** [comment]
I have found the cause of the bug. Some keep only edges are ignored when collecting ancestors. So these edges are absent when merging chains while they are present when checking cycles.
```
void ChainGraph::CollectTaskNodeAncestors(const TaskGraph& task_gph,
      ....
      if (IsNonSoleKeepHeaderOnlyEdge(in_node, node)) { continue; }
      ....
```
![image](https://user-images.githubusercontent.com/5133557/90282741-7a3adb80-dea1-11ea-847c-5630e3a839a7.png)

**Comment by chengtbf** [comment]
So i think the rule `if (IsNonSoleKeepHeaderOnlyEdge(in_node, node)) { continue; }`  to ignore keep_header_only edge when collecting ancestors is incorrect. 

The  keep_header_only edge should be considered as a normal data side.
