### ISSUE TITLE
16 v100 nodes r50 benchmark speed is `9225 samples/sec` whereas nvidia benchmark can get  `16000+ samples/sec`

### ISSUE THREAD

**Issue by qianzhang613** [Oneflow-Inc/oneflow#3471]
the oneflow benchmark：
```
git clone https://github.com/Oneflow-Inc/OneFlow-Benchmark.git
python3 -u of_cnn_train_val.py  \
    --train_data_dir=data/train --train_data_part_num=256 \
    --val_data_dir=data/val --val_data_part_num=256 \
    --gpu_num_per_node=8 \
    --model_update="momentum" \
    --learning_rate=0.256 \
    --loss_print_every_n_iter=100 \
    --batch_size_per_device=256 \
    --val_batch_size_per_device=50 \
    --num_epoch=90 \
    --model="resnet50" \
    --log_dir=./task_out \
    --node_ips=。。。 \
    --num_nodes=2  --use_fp16
oneflow is build from master , cuda10.1 cudnn7.6.5
```
the first epoch:

0 | 99 | train_loss |   | 6.860359669 | 0
-- | -- | -- | -- | -- | --
0 | 99 | train_throughput |   | 8409.030571 | 0
0 | 99 | train_top_1 |   | 0.002250977 | 0
0 | 99 | train_top_5 |   | 0.008681641 | 0
0 | 199 | train_loss |   | 6.655314445 | 0
0 | 199 | train_throughput |   | 9225.357671 | 0
0 | 199 | train_top_1 |   | 0.008845215 | 0
0 | 199 | train_top_5 |   | 0.031196289 | 0
0 | 299 | train_loss |   | 6.492397308 | 0
0 | 299 | train_throughput |   | 9237.295334 | 0
0 | 299 | train_top_1 |   | 0.017080078 | 0
0 | 299 | train_top_5 |   | 0.054726563 | 0

the nvidia benchmark :  https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/Classification/ConvNets/resnet50v1.5  

so do oneflow has the  benchmark result with two V100  DGX2 same topo  nodes ?

**Comment by yuanms2** [comment]
Thanks for the testing.  Unfortunately, we have not met with DGX2 server. Do you carry out the experiments on DGX2? 

We have carried out some benchmark on some lower-end servers and will release the results soon. Each server has 8 V100 with 16G device memory,  interconnection of100Gbps RDMA networking is supported.

DGX2 mainly have the following strengths:
1, 32GB vs  16GB
2,  Nvlink, Nvswith
3,  high IO bandwidth by SSD

Some tricky configs may also affect the benchmark performance:
1, AMP,  automatic mixed precision
2, with XLA on or off

**Comment by qianzhang613** [comment]
> Thanks for the testing. Unfortunately, we have not met with DGX2 server. Do you carry out the experiments on DGX2?
> 
> We have carried out some benchmark on some lower-end servers and will release the results soon. Each server has 8 V100 with 16G device memory, interconnection of100Gbps RDMA networking is supported.
> 
> DGX2 mainly have the following strengths:
> 1, 32GB vs 16GB
> 2, Nvlink, Nvswith
> 3, high IO bandwidth by SSD
> 
> Some tricky configs may also affect the benchmark performance:
> 1, AMP, automatic mixed precision
> 2, with XLA on or off

lookforward your bench results.  thanks.

**Comment by chengtbf** [comment]
@qianzhang613  Hi~ We have recently optimized the performance of AMP a lot. So you can test again with [oneflow v0.2.0](https://github.com/Oneflow-Inc/oneflow/releases/tag/v0.2.0) and [oneflow-benchmark v0.2.0](https://github.com/Oneflow-Inc/OneFlow-Benchmark/releases/tag/v0.2.0).

You can also go to our new repo [Oneflow-Inc/DLPerf](https://github.com/Oneflow-Inc/DLPerf) to check our benchmark results over 5 deep learning frameworks. OneFlow 0.2.0 benchmark results on single-node and multi-node have exceeded the official data of NVIDIA on 4 nodes with 8x Tesla V100-SXM2-16GB GPUs each.  

Chinese report:
[DLPerf 性能评测报告中文版 v1.0](https://github.com/Oneflow-Inc/DLPerf/blob/master/reports/dlperf_benchmark_test_report_v1_cn.md)

ResNet50-v1.5 AMP batch_size_per_gpu=256 benchmark results:

| node num | device num | [OneFlow](https://github.com/Oneflow-Inc/DLPerf/tree/master/OneFlow) | [NGC<br>TensorFlow 1.x<br>W/O XLA<br>bsz=224](https://github.com/Oneflow-Inc/DLPerf/tree/master/NVIDIADeepLearningExamples/TensorFlow/Classification/ConvNets/resnet50v1.5) | [NGC<br>TensorFlow 1.x<br>with XLA<br>bsz=224](https://github.com/Oneflow-Inc/DLPerf/tree/master/NVIDIADeepLearningExamples/TensorFlow/Classification/ConvNets/resnet50v1.5) | [NGC<br>PyTorch]() | [NGC<br>MXNet](https://github.com/Oneflow-Inc/DLPerf/tree/master/NVIDIADeepLearningExamples/MxNet/Classification/RN50v1.5) | [PaddlePaddle<br>bsz=224](https://github.com/Oneflow-Inc/DLPerf/tree/master/PaddlePaddle/resnet50v1.5) | [TensorFlow 2.x](https://github.com/Oneflow-Inc/DLPerf/tree/master/TensorFlow/resnet50v1.5) |
| -------- | ---------- | ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ |
| 1        | 1          | 1472.72                                                      | 945.18                                                       | 1198.55                                                      | 802.9              | 1393.87                                                      | 1034.64                                                      | 1075.27                                                      |
| 1        | 8          | 10629.32                                                     | 6903.42                                                      | 8588.45                                                      | 6154.66            | 9621.31                                                      | 4380.66                                                      | 6898.00                                                      |
| 2        | 16         | 17920.40                                                     | 12021.09                                                     | 14931.03                                                     | 11991.94           | 16219.03                                                     | 6358.43                                                      | 9870.15                                                      |
| 4        | 32         | 33141.02                                                     | 24734.22                                                     | 29171.69                                                     | 22551.16           | 30713.68                                                     | 10633.22                                                     | 19314.31                                                     |

![r50_amp_bz256_throughput](https://user-images.githubusercontent.com/12186261/96853922-8341bd80-148d-11eb-986e-d2afe03c86cb.png)

**Comment by qianzhang613** [comment]
@chengtbf  Awosome！ you are supper great！

**Comment by qianzhang613** [comment]
thanks
