### ISSUE TITLE
NotImplementedError: All parameters of global function should be annotated

### ISSUE THREAD

**Issue by JiaqingFu** [Oneflow-Inc/oneflow#3547]
什么样的参数会导致这个报错

完整报错如下：
![image](https://user-images.githubusercontent.com/12004134/92673853-ae91a280-f34e-11ea-9467-934fe4fbcb52.png)
主要代码如下：
![image](https://user-images.githubusercontent.com/12004134/92673947-e4cf2200-f34e-11ea-999b-2da5d518021a.png)

**Comment by JiaqingFu** [comment]
![image](https://user-images.githubusercontent.com/12004134/92674061-23fd7300-f34f-11ea-937a-a0d3c1e95ce1.png)
oneflow源码

**Comment by doombeaker** [comment]
作业函数的返回值也是要注解的，比如单个返回值：
```
@flow.global_function(type="train")
def train_job(
    images: tp.Numpy.Placeholder((BATCH_SIZE, 1, 28, 28), dtype=flow.float),
    labels: tp.Numpy.Placeholder((BATCH_SIZE,), dtype=flow.int32),
) -> tp.Numpy:
```
多个返回值：
```
@flow.global_function(type="predict")
def eval_job(
    images: tp.Numpy.Placeholder((BATCH_SIZE, 1, 28, 28), dtype=flow.float),
    labels: tp.Numpy.Placeholder((BATCH_SIZE,), dtype=flow.int32),
) -> Tuple[tp.Numpy, tp.Numpy]:
```

还有其他的异步用法等，具体的可以参考文档：https://docs.oneflow.org/basics_topics/async_get.html

祝好~

**Comment by leaves-zwx** [comment]
不是返回值的问题，代码里面有个地方写错了

![image](https://user-images.githubusercontent.com/7133477/92675716-a3407600-f352-11ea-8093-0b4003b36878.png)

这里应该写成 label: tp.Numpy.Placeholder((1, 400))

需要定义 parameter annotation 而不是 parameter default value

**Comment by JiaqingFu** [comment]
赞，修改之后解决了 @leaves-zwx
