### ISSUE TITLE
Example code can not run

### ISSUE THREAD

**Issue by xiejiachen** [Oneflow-Inc/oneflow#3558]
https://github.com/Oneflow-Inc/oneflow/blob/4511d649a8cc44e184ff0aefc79e78f9988d090b/oneflow/python/ops/array_ops.py#L914

`x: tp.Numpy.Placeholder((4, )` I guess should be `x: tp.Numpy.Placeholder((4, ))` 

@clackhan

**Comment by MARD1NO** [comment]
We have fixed it. Thanks for your issue~
