### ISSUE TITLE
Error in flow.where

### ISSUE THREAD

**Issue by FNLPprojects** [Oneflow-Inc/oneflow#3622]
I met error in running the following code with ***oneflow-cu101-xla   0.2b1***:

```
    student_output_blob = add_student_layer(student_layer_idx, prev_output_blob)
    prev_output_blob = add_teacher_layer(teacher_layer_idx, prev_output_blob)
    prev_output_blob = flow.where(
      sample,
      student_output_blob,
      teacher_output_blob
    )
    prev_output_blob = output_blob
````

If I delete the ***flow.where***, the code would work properly
```
    student_output_blob = add_student_layer(student_layer_idx, prev_output_blob)
    prev_output_blob = add_teacher_layer(teacher_layer_idx, prev_output_blob)
    # prev_output_blob = flow.where(
    #   sample,
    #   student_output_blob,
    #   teacher_output_blob
    # )
    # prev_output_blob = output_blob
````

The error log is as following:
```
F0928 03:00:59.829509  7549 chain_graph.cpp:289] cycle in graph detected, please check:
optimized_dlnet_0_highlighted_cycle_task_nodes_in_chain_graph.dot
job0_cycle_task_graph.dot
job0_cycle_chain_graph.dot
*** Check failure stack trace: ***
    @     0x7f2ac5ddc75d  google::LogMessage::Fail()
    @     0x7f2ac5dddfaa  google::LogMessage::SendToLog()
    @     0x7f2ac5ddc22d  google::LogMessage::Flush()
    @     0x7f2ac5ddf3d9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f2ac4b45043  oneflow::ChainGraph::CheckNoCycle()
    @     0x7f2ac4b45ccf  oneflow::ChainGraph::ChainGraph()
    @     0x7f2ac4bea149  oneflow::TaskGraph::MergeChainAndSetOrderInGraphForEachNode()
    @     0x7f2ac4bee35f  oneflow::TaskGraph::TaskGraph()
    @     0x7f2ac4c1cd9b  oneflow::Compiler::Compile()
    @     0x7f2ac4cad48e  (unknown)
    @     0x7f2ac4cb0da7  (unknown)
    @     0x7f2ac4cb2fd2  oneflow::Oneflow::Init()
    @     0x7f2ac49cc4c6  (unknown)
    @     0x7f2ac49de608  (unknown)
    @     0x555acfa060e1  _PyCFunction_FastCallDict
    @     0x555acfa8d43c  call_function
    @     0x555acfab1a1a  _PyEval_EvalFrameDefault
    @     0x555acfa8747b  fast_function
    @     0x555acfa8d515  call_function
    @     0x555acfab1a1a  _PyEval_EvalFrameDefault
    @     0x555acfa8747b  fast_function
    @     0x555acfa8d515  call_function
    @     0x555acfab1a1a  _PyEval_EvalFrameDefault
    @     0x555acfa8747b  fast_function
    @     0x555acfa8d515  call_function
    @     0x555acfab1a1a  _PyEval_EvalFrameDefault
    @     0x555acfa869b6  _PyEval_EvalCodeWithName
    @     0x555acfa876b1  fast_function
    @     0x555acfa8d515  call_function
    @     0x555acfab1a1a  _PyEval_EvalFrameDefault
    @     0x555acfa87aeb  _PyFunction_FastCallDict
    @     0x555acfa0656f  _PyObject_FastCallDict
```

Any idea about the error?

**Comment by jackalcooper** [comment]
http://oneflow-static.oss-cn-beijing.aliyuncs.com/staging/pr/3616/2020.09.27-17.27.28-2e6eed1c4/oneflow_cu101_xla-0.2b1-cp36-cp36m-manylinux2014_x86_64.whl

**Comment by jackalcooper** [comment]
Could you post the file `optimized_dlnet_0_highlighted_cycle_task_nodes_in_chain_graph.dot` here?

**Comment by jackalcooper** [comment]
You may find it in you log directory

**Comment by FNLPprojects** [comment]
[optimized_dlnet_0_highlighted_cycle_task_nodes_in_chain_graph.zip](https://github.com/Oneflow-Inc/oneflow/files/5290047/optimized_dlnet_0_highlighted_cycle_task_nodes_in_chain_graph.zip)


> You may find it in you log directory

The log is in the zip file

**Comment by jackalcooper** [comment]
the dot file is too big and I can't convert it to svg/pdf, in your code:
```
prev_output_blob = flow.where(
      sample,
      student_output_blob,
      teacher_output_blob
    )
```
Is it possible to add two of these three inputs? It might prevent the cycle from forming. For instance:
```
_ = student_output_blob + teacher_output_blob
_ = sample + teacher_output_blob
prev_output_blob = flow.where(
      sample,
      student_output_blob,
      teacher_output_blob
    )
```

**Comment by FNLPprojects** [comment]
> the dot file is too big and I can't convert it to svg/pdf, in your code:
> 
> ```
> prev_output_blob = flow.where(
>       sample,
>       student_output_blob,
>       teacher_output_blob
>     )
> ```
> 
> Is it possible to add two of these three inputs? It might prevent the cycle from forming. For instance:
> 
> ```
> _ = student_output_blob + teacher_output_blob
> _ = sample + teacher_output_blob
> prev_output_blob = flow.where(
>       sample,
>       student_output_blob,
>       teacher_output_blob
>     )
> ```

Thanks for your replying, I will take a try lately.

**Comment by FNLPprojects** [comment]
> the dot file is too big and I can't convert it to svg/pdf, in your code:
> 
> ```
> prev_output_blob = flow.where(
>       sample,
>       student_output_blob,
>       teacher_output_blob
>     )
> ```
> 
> Is it possible to add two of these three inputs? It might prevent the cycle from forming. For instance:
> 
> ```
> _ = student_output_blob + teacher_output_blob
> _ = sample + teacher_output_blob
> prev_output_blob = flow.where(
>       sample,
>       student_output_blob,
>       teacher_output_blob
>     )
> ```

The method does not work. 

The *job0_cycle_chain_graph.dot* and *job0_cycle_task.graph.dot*
[job0_cycle.zip](https://github.com/Oneflow-Inc/oneflow/files/5388772/job0_cycle.zip)
 are listed below.

**Comment by chengtbf** [comment]
Please test with #3693  (branch dev_cc_rm_checkcycle_chain)
