### ISSUE TITLE
Whether to check the batch axis?

### ISSUE THREAD

**Issue by MARD1NO** [Oneflow-Inc/oneflow#3684]
# 问题引入
当张量与张量之间进行操作，需要对 `batch_axis` 进行一系列检查以及推导

以 `oneflow.math.add` 为例子
```
@oneflow_export("math.add")
def add(
    x: Union[int, float, remote_blob_util.BlobDef],
    y: Union[int, float, remote_blob_util.BlobDef],
    name: Optional[str] = None,
) -> remote_blob_util.BlobDef:
    if isinstance(x, (int, float)):
        return scalar_add(y, x, name)
    elif isinstance(y, (int, float)):
        return scalar_add(x, y, name)
    elif x.shape == y.shape and x.batch_axis == y.batch_axis:
        return element_wise_add(x, y, name)
    elif x.shape == (1,):
        return scalar_add_by_tensor(y, x, name)
    elif y.shape == (1,):
        return scalar_add_by_tensor(x, y, name)
    else:
        return broadcast_add(x, y, name)
```
当进入到最后一个else语句后执行 `broadcast_add` 会调用底层算子 https://github.com/Oneflow-Inc/oneflow/blob/ff1dcbe25440127f2e105dfe470f1e822476fd3e/oneflow/user/ops/math_binary_broadcast_ops.cpp#L174

算子使用 `NaiveInferBatchAxis` 进行BatchAxis推导

具体问题在这句话
https://github.com/Oneflow-Inc/oneflow/blob/4d84afbf654e51241c4826946c4fef965066262e/oneflow/core/framework/batch_axis_context.cpp#L46

这句话continue跳过后面的语句，导致没有检查 `cur_in_batch_axis` 和 `batch_axis`

# 问题示例
```
# 假设有个 Tensor A ，其 batchaxis = None


# 另外有个 Tensor B，其 batchaxis = 0

Tensor A = oneflow.math.add(Tensor A, Tensor B) 
```

由于 https://github.com/Oneflow-Inc/oneflow/blob/4d84afbf654e51241c4826946c4fef965066262e/oneflow/core/framework/batch_axis_context.cpp#L46 的存在，导致 Tensor A 被跳过了

而最终 Tensor A 的 `batch_axis` 来自于 Tensor B的。这一过程是不合理的

和文骁的初步讨论是删除 `if (cur_in_batch_axis->has_value() == false) { continue; }`,不知道是否会引发其他问题。

**Comment by chengtbf** [comment]
broadcast add op 可以不用NaiveInferBatchAxis这个接口吧，自己再实现一个不check batch axis的版本就行了。

**Comment by leaves-zwx** [comment]
你理解错我的意思 😂，不是删除 

```
if (cur_in_batch_axis->has_value() == false) { continue; }
```

而是删除检查

```
CHECK_EQ_OR_RETURN(batch_axis->value(), cur_in_batch_axis->value());
```

而且在这之前还需要确定下是哪个 op infer batch axis 触发了这个问题。

**Comment by chengtbf** [comment]
我的建议是不要改NaiveInferBatchAxis里的逻辑，而是再实现一个弱化版本的InferBatchAxis的函数，里面不做该CHECK。

**Comment by leaves-zwx** [comment]
> 我的建议是不要改NaiveInferBatchAxis里的逻辑，而是再实现一个弱化版本的InferBatchAxis的函数，里面不做该CHECK。

先调试看看是哪个 op 出了这个问题，再看一下这是个普遍性问题还是特例。
