### ISSUE TITLE
oneflow.data.coco_reader

### ISSUE THREAD

**Issue by liuao520** [Oneflow-Inc/oneflow#3771]
I want to know the specific parameter descriptions and application examples of `oneflow.data.coco_reader`, and whether there are operators similar to `tf.data.TextLineDataset` that read files and load data sets

**Comment by simonJJJ** [comment]
@liuao520 Hi, there is one example of coco_reader: https://github.com/Oneflow-Inc/oneflow/blob/master/oneflow/python/benchmarks/coco_data_load/coco_data_loader.py
If you want to run it, please add the 'name' argument in line 61.

**Comment by ScXfjiang** [comment]
`oneflow.data.coco_reader` is used in detection applications used [COCO Dataset](https://cocodataset.org/) such as FasterRCNN, MaskRCNN which we are working on and will release soon.

**Comment by liuao520** [comment]
> `oneflow.data.coco_reader` is used in detection applications used [COCO Dataset](https://cocodataset.org/) such as FasterRCNN, MaskRCNN which we are working on and will release soon.
