### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by liuao520** [Oneflow-Inc/oneflow#3779]
当前我已经把coco系列标记和信息建立了txt文件,,我现在想使用一个类似tf.data.TextLineDataset()的api,读取text,建立dataset进行训练,,有类似提供吗

**Comment by leaves-zwx** [comment]
oneflow 里面支持直接从 coco 数据集读取数据，用法示例可以见 `oneflow/python/benchmarks/coco_data_load/coco_data_loader.py`。

**Comment by leaves-zwx** [comment]
老版本的 tf 中由于仅支持几种抽象的 Dataset 类型 (Text Dataset, Image Dataset, Vedio Dataset, Audio Dataset 等)，所以老的一些示例代码中针对特定数据集会将其转换成抽象的 Dataset 类型再读取。oneflow 的设计是可以通过通用的数据集格式 (ofrecord) 读取数据，或是针对部分特定的数据集有特定的读取接口（比如 [data.coco_reader](https://github.com/Oneflow-Inc/oneflow/blob/fcd69d51537c317dafca37bb72d05608b30ba268/oneflow/python/ops/user_data_ops.py#L2122)）。目前新版本的 tf 也支持专门读取 coco 的数据集类型 [tfds.object_detection.Coco](https://www.tensorflow.org/datasets/catalog/coco)。
