### ISSUE TITLE
oneflow.transpose是否不支持高维对象

### ISSUE THREAD

**Issue by kanagi2587** [Oneflow-Inc/oneflow#3800]
在docs的例子中的低维对象中测试运行一切正常，但是传入6维数据就报错了。
import oneflow as flow
import numpy as np
import oneflow.typing as tp

@flow.global_function()
def transpose_Job(x: tp.Numpy.Placeholder(shape=(1, 2, 3,4,5,6), dtype=flow.float32)
) -> tp.Numpy:
    transpose_blob = flow.transpose(x,
                                    perm=[2, 0, 1,5,3,4])
    return transpose_blob

x = np.random.randn(1, 2, 3,4,5,6).astype(np.float32)
out = transpose_Job(x)

terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
已放弃 (核心已转储)

**Comment by MARD1NO** [comment]
您好，感谢您使用OneFlow。 目前我们系统限制是不支持6维的运算，6维以下的运算是正常的。

能否问下您6维Tensor的使用场景是哪些呢？如果有必要我们后续会考虑新增这个特性

**Comment by kanagi2587** [comment]
> 您好，感谢您使用OneFlow。 目前我们系统限制是不支持6维的运算，6维以下的运算是正常的。
> 
> 能否问下您6维Tensor的使用场景是哪些呢？如果有必要我们后续会考虑新增这个特性

在Re-ID对视频帧进行特征图重建和余弦相似度计算过程中

**Comment by chengtbf** [comment]
Transpose的Kernel实现是根据Tensor的维度不同而分别用宏展开定义的。见：

https://github.com/Oneflow-Inc/oneflow/blob/066c36bf5343116e90da91afbb23a311201cc70e/oneflow/core/kernel/util/cuda_arithemetic_interface.cu#L80

其中的DIM_SEQ定义假设了最高5维。
https://github.com/Oneflow-Inc/oneflow/blob/066c36bf5343116e90da91afbb23a311201cc70e/oneflow/core/common/util.h#L146

维度越高，相关Kernel的实现会越多（有些Kernel是根据各种属性导致模版展开数量很大，笛卡尔积相乘会爆炸）。我很快把这个6维的需求支持了。
