### ISSUE TITLE
oneflow.math.argmax

### ISSUE THREAD

**Issue by 15168387900** [Oneflow-Inc/oneflow#3814]
How can I use oneflow.math.argmax to compute the index with the largest value of a Blob in a specific axis?

**Comment by ScXfjiang** [comment]
Hi, thank for you feedback. We only support sort ops (e.g. argmax, sort, argsort, top_k) in the last dimension for now, and we will enhance these ops to allow users specify axis in this week.

**Comment by MARD1NO** [comment]
If you want to use `oneflow.math.argmax` in a specific axis. You can use `oneflow.transpose` to change to your specific axis, and use `oneflow.math.argmax`. Finally you should use `oneflow.transpose` again to convert the Tensor back.

**Comment by 15168387900** [comment]
> If you want to use `oneflow.math.argmax` in a specific axis. You can use `oneflow.transpose` to change to your specific axis, and use `oneflow.math.argmax`. Finally you should use `oneflow.transpose` again to convert the Tensor's axis back.
> 
> Here is an example:
> 
> ```
> import oneflow as flow
> import oneflow.typing as tp 
> import numpy as np 
> 
> 
> @flow.global_function()
> def argmax_axis(x: tp.Numpy.Placeholder(shape=(3, 3)))->tp.Numpy: 
>     x = flow.transpose(x, perm=[1, 0])
>     out = flow.math.argmax(x)
>     # To convert back the tensor
>     x = flow.transpose(x, perm=[1, 0])
>     return out 
> 
> x = np.array([[10, 7, 5], 
>               [5, 9, 13], 
>               [3, 6, 4]]).astype(np.float32)
> 
> out = argmax_axis(x)
> print(out) # return [0 2 1], it computes the max element index in each row
> ```

Thank you! I think I misunderstood the function of `oneflow.math.argmax` before.

**Comment by MARD1NO** [comment]
> > If you want to use `oneflow.math.argmax` in a specific axis. You can use `oneflow.transpose` to change to your specific axis, and use `oneflow.math.argmax`. Finally you should use `oneflow.transpose` again to convert the Tensor's axis back.
> > Here is an example:
> > ```
> > import oneflow as flow
> > import oneflow.typing as tp 
> > import numpy as np 
> > 
> > 
> > @flow.global_function()
> > def argmax_axis(x: tp.Numpy.Placeholder(shape=(3, 3)))->tp.Numpy: 
> >     x = flow.transpose(x, perm=[1, 0])
> >     out = flow.math.argmax(x)
> >     # To convert back the tensor
> >     x = flow.transpose(x, perm=[1, 0])
> >     return out 
> > 
> > x = np.array([[10, 7, 5], 
> >               [5, 9, 13], 
> >               [3, 6, 4]]).astype(np.float32)
> > 
> > out = argmax_axis(x)
> > print(out) # return [0 2 1], it computes the max element index in each row
> > ```
> 
> Thank you! I think I misunderstood the function of `oneflow.math.argmax` before.

I make a mistake in final annotation. it should be `it computes the max element index in each column`. Because we use `oneflow.transpose` to transpose the column axis as the first axis. The `flow.argmax` computes the max element index in column axis.

**Comment by ScXfjiang** [comment]
https://github.com/Oneflow-Inc/oneflow/pull/3828
We support sort, argsort, argmax, top_k at specified dimensioin
