### ISSUE TITLE
算法复现过程中无法使用numpy的算子

### ISSUE THREAD

**Issue by fyc1997** [Oneflow-Inc/oneflow#3836]
经过询问，算法中不支持同时使用numpy和oneflow操作，请求开发以下numpy（np）算子：

1. np.arange
2. np.meshgrid
3. np.squeeze
4. np.nonzero
5. np.where

以及 oneflow.stack, 目前仅支持axis=0，且axis使用0时 报 getattr(op_conf.stack_conf, "in").extend([input.unique_name for input in inputs]) 错误，这个in是不明的输入对象。

**Comment by MARD1NO** [comment]
1. flow.range 正在跑CI，参见 #3725 
2. 这个我没记错的话是生成网格，后续可以开发。但我觉得如果有了range，可以暂时拿两个range拼起来
3. squeeze在 `oneflow.squeeze`， API 文档暂时还没同步上来，可以参考 [oneflow.squeeze](https://github.com/Oneflow-Inc/oneflow/blob/master/oneflow/python/ops/array_ops.py#L1922)
4. nonzero在`oneflow.nonzero`, [oneflow.nonzero](https://github.com/Oneflow-Inc/oneflow/blob/master/oneflow/python/ops/array_ops.py#L1432)
5. where在`oneflow.where`, [oneflow.where](https://github.com/Oneflow-Inc/oneflow/blob/master/oneflow/python/ops/array_ops.py#L1455)
