### ISSUE TITLE
oneflow中有上采样吗

### ISSUE THREAD

**Issue by 416047850** [Oneflow-Inc/oneflow#3845]
oneflow中有上采样吗

**Comment by MARD1NO** [comment]
有的，你可以使用`oneflow.upsample_2d`，具体用法可参考 [upsample_2d](https://oneflow-api.readthedocs.io/en/latest/layers.html?highlight=upsample#oneflow.layers.upsample_2d)
如果还有其他问题，欢迎您继续留言

**Comment by xunhen** [comment]
> 有的，你可以使用`oneflow.upsample_2d`，具体用法可参考 [upsample_2d](https://oneflow-api.readthedocs.io/en/latest/layers.html?highlight=upsample#oneflow.layers.upsample_2d)
> 如果还有其他问题，欢迎您继续留言

你好，当我使用上采样时，出现以下未注册问题：
`
error_summary: "There is no kernel registered for Current OperatorConf. "
msg: " The Info of OperatorConf are \n op_name: yolo-detect2-upsample\n op_type_name: upsample\n DeviceType_Name: kCPU\n DataType_Name of x_0: kFloat\n DataType_Name of y_0: kFloat"
stack_frame {
  location: "/home/ci-user/actions-runner-rel/_work/oneflow/oneflow/oneflow/core/operator/user_op.cpp:410"
  function: "InferBlobDescs"
}
stack_frame {
  location: "/home/ci-user/actions-runner-rel/_work/oneflow/oneflow/oneflow/core/graph/exec_graph.cpp:78"
  function: "InferBlobDescs"
}
op_kernel_not_found_error {
}
*** Check failure stack trace: ***
    @     0x7f09d27a088d  google::LogMessage::Fail()
    @     0x7f09d27a49cc  google::LogMessage::SendToLog()
    @     0x7f09d27a03b3  google::LogMessage::Flush()
    @     0x7f09d27a53e9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f09d1a6d76b  oneflow::ExecNode::InferBlobDescs()
    @     0x7f09d1a68cba  _ZNSt17_Function_handlerIFN7oneflow5MaybeIvvEEPNS0_8ExecNodeEEZNKS0_5GraphIS3_NS0_8ExecEdgeEE15TopoForEachNodeERKSt4listIS4_SaIS4_EERKSt8functionIFvS4_RKSE_IFvS4_EEEESM_SI_EUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
    @     0x7f09d1a69b8c  oneflow::Graph<>::TopoForEachNodeWithErrorCaptured()
    @     0x7f09d1a6a141  oneflow::Graph<>::TopoForEachNode()
    @     0x7f09d1a6a3ea  oneflow::Graph<>::TopoForEachNode()
    @     0x7f09d1a966c2  oneflow::NormalForwardCompTaskNode::BuildExecGphAndRegst()
    @     0x7f09d1ae5dc8  oneflow::TaskNode::Build()
    @     0x7f09d1a5544a  _ZNSt17_Function_handlerIFN7oneflow5MaybeIvvEEPNS0_8TaskNodeEEZNKS0_5GraphIS3_NS0_8TaskEdgeEE15TopoForEachNodeERKSt4listIS4_SaIS4_EERKSt8functionIFvS4_RKSE_IFvS4_EEEESM_SI_EUlS4_E_E9_M_invokeERKSt9_Any_dataS4_
    @     0x7f09d1a5e4ec  oneflow::Graph<>::TopoForEachNodeWithErrorCaptured()
    @     0x7f09d1a5eaa1  oneflow::Graph<>::TopoForEachNode()
    @     0x7f09d1afb13a  oneflow::Graph<>::TopoForEachNode()
    @     0x7f09d1af7d7b  oneflow::Compiler::Compile()
    @     0x7f09d1b81aca  (unknown)
    @     0x7f09d1b8640c  (unknown)
    @     0x7f09d1b883db  oneflow::Oneflow::Init()
    @     0x7f09d18e1b84  (unknown)
    @     0x7f09d184f011  StartLazyGlobalSession()
    @     0x7f09d1549b67  (unknown)
    @     0x7f09d17eb0b3  (unknown)
    @     0x55fc38b6ef76  PyCFunction_Call
    @     0x55fc38b2c85f  _PyObject_MakeTpCall
    @     0x55fc38bb3f56  _PyEval_EvalFrameDefault
    @     0x55fc38b7a86b  _PyFunction_Vectorcall.localalias.355
    @     0x55fc38aef75e  _PyEval_EvalFrameDefault.cold.2790
    @     0x55fc38b7a86b  _PyFunction_Vectorcall.localalias.355
    @     0x55fc38aef75e  _PyEval_EvalFrameDefault.cold.2790
    @     0x55fc38b79e19  _PyEval_EvalCodeWithName
    @     0x55fc38b7a943  _PyFunction_Vectorcall.localalias.355
`
这是为什么？

**Comment by Flowingsun007** [comment]
您好，目前已支持多种模式的upsample，可选：'nearest', 'linear', 'bilinear', 'bicubic' and 'trilinear'。
使用方式见文档：
https://oneflow.readthedocs.io/en/master/functional.html?highlight=Upsample#oneflow.nn.functional.upsample
https://oneflow.readthedocs.io/en/master/nn.html?highlight=upsample#oneflow.nn.Upsample
