### ISSUE TITLE
建议将贵公司的产品名称改成 "一刀流" ~

### ISSUE THREAD

**Issue by yarcowang** [Oneflow-Inc/oneflow#3881]
哈哈~ 在微信公众号里看到有介绍 OneFlow 文章... 英文名称自然没啥问题, 但假如中文名称也翻成 "一流"框架, 未免有点俗气.
再说, 如果公司叫"一流公司", 产品也叫"一流", 听起来未免单薄 ---- 难道就只有一个产品吗?
所以我感觉 "一刀流" 听起来很霸气, NB, 符合框架的定位: 高效率. （还稍微带点二次元/宅男的属性).
对于贵司品牌推广, 形象塑造有帮助.

(若接受本条建议，请我吃一年饭)

**Comment by jackalcooper** [comment]
Excellent idea! We will take it into consideration.
