### ISSUE TITLE
oneflow是否有支持行人重识别reid的数据集载入的手段

### ISSUE THREAD

**Issue by kanagi2587** [Oneflow-Inc/oneflow#3887]
比如说常见的Market-1501和MARS等数据集，由于reid的特殊性，虽然是图片但似乎也无法转换成OFRecord

**Comment by kanagi2587** [comment]
或者是其它无监督学习的数据库，因为目前的算子好像只是支持监督学习的图片数据及进行转换

**Comment by wyg1997** [comment]
ReID的数据特殊在训练的时候需要在一个batch内均匀放入几个pid的数据。只考虑数据格式的话，还是可以使用 `OFRecord` 转换的，encode 的时候可以按照 `{'images': BytesList(encode_img), 'labels': floatList([pid, camid])}` 的方式保存数据。数据转换的方式可以参考这个文档 [https://docs.oneflow.org/extended_topics/how_to_convert_image_to_ofrecord.html](https://docs.oneflow.org/extended_topics/how_to_convert_image_to_ofrecord.html) 。

但因为采样方式的特殊性，就不能使用上述文档中的 `DataLoader` 了，需要相应的实现一个自定义DataLoader。可以参考 [https://docs.oneflow.org/extended_topics/implement_data_loader.html](https://docs.oneflow.org/extended_topics/implement_data_loader.html)，实现后编译成 `.so` 文件在实际项目中使用即可。

**Comment by kanagi2587** [comment]
> ReID的数据特殊在训练的时候需要在一个batch内均匀放入几个pid的数据。只考虑数据格式的话，还是可以使用 `OFRecord` 转换的，encode 的时候可以按照 `{'images': BytesList(encode_img), 'labels': floatList([pid, camid])}` 的方式保存数据。数据转换的方式可以参考这个文档 https://docs.oneflow.org/extended_topics/how_to_convert_image_to_ofrecord.html 。
> 
> 但因为采样方式的特殊性，就不能使用上述文档中的 `DataLoader` 了，需要相应的实现一个自定义DataLoader。可以参考 https://docs.oneflow.org/extended_topics/implement_data_loader.html，实现后编译成 `.so` 文件在实际项目中使用即可。

你好 请问能不能解释一下为什么具有采样方式的特殊性。这是我第一次接触ReID方面的内容。在我原本的构想下，我也觉得可以用images对应[pid，camid]的方式进行对应，在利用OFRECORD的dataloader进行解决。

**Comment by kanagi2587** [comment]
好的，按照我的理解是 现有的ofrecord的dataloader无法reader出[pid, camid]这样的数据。
但是自定义dataloader的文档有些晦涩难懂难以理解，以我的能力好像不足以自定义。有没有其它替代的方法可以解决。

**Comment by wyg1997** [comment]
先说OFRecord的制作：这一步其实只是把数据转一种格式保存，ReID数据和分类数据不同的地方只在于一张图片对应的是 `[pid, camid]` 还是 `cls` 类别。所以在制作OFRecord数据时没有什么特殊的地方。

然后是DataLoader采样的过程：ReID根据不同的算法，有不同的采样方式，比如如果直接训练一个分类网络，用feature map作为特征的话，在采样的时候就可以使用和分类算法一样的采样方式，设置一个batch size，从数据集中随机采样即可，可以完全参考分类网络使用OFRecord训练的代码；如果使用Triplet Loss的话，采样方式就比较特殊了，有一种用的比较多的，是一个batch内，采n个pid，每个pid采k个camid，这样Oneflow内置的DataLoader就不能满足要求了，就需要自己按照DataLoader的实现方式，对特定的任务使用特殊的采样方案。

如果DataLoader实现起来有难度的话，可以放弃一小部分性能，参考 [https://github.com/Oneflow-Inc/oneflow_vision_model/tree/main/Re-ID](https://github.com/Oneflow-Inc/oneflow_vision_model/tree/main/Re-ID) 直接用numpy输入也是可以的。
