### ISSUE TITLE
code复现过程中算子问题

### ISSUE THREAD

**Issue by fyc1997** [Oneflow-Inc/oneflow#3888]
1. 请问 oneflow 有 torch.nn.BCEWithLogitsLoss 损失函数吗？

2. 是否可以开发下flow.stack(现在仍不支持使用，现在用的 flow.concat+flow.reshape 替代)

3. 无法解决的numpy算子：

> np.hanning

> np.outer

> np.unravel_index

> np.linalg.norm

**Comment by MARD1NO** [comment]
1. BCELoss可参考这个 PR #3804 
2. stack 是可以通过 expand_dims + concat来拼的，后续会加到任务清单内
3. 这几个算子并不是很熟悉， 对于 np.linalg.norm 应该也是可以拼出来的

**Comment by doombeaker** [comment]
`np.unravel_index` 作为高维坐标和一维坐标的转换，可以举例下你的应用场景吗（比如贴下示例代码）？我们内部是有现成的转换功能的。但是静态图机制下可能用处不大，就没有暴露给Python API。

**Comment by fyc1997** [comment]
> np.unravel_index

def getCenter(self,hp_cls_up,score_up,scale_score,lrtbs):
        # corse location
        score_up = self.coarse_location(hp_cls_up,score_up,scale_score,lrtbs)
        # accurate location
        max_r_up, max_c_up = np.unravel_index(score_up.argmax(), score_up.shape)
        disp = self.accurate_location(max_r_up,max_c_up)
        disp_ori = disp / self.scale_z
        new_cx = disp_ori.shape[1] + self.center_pos.shape[0]
        new_cy = disp_ori.shape[0] + self.center_pos.shape[1]
        return max_r_up, max_c_up, new_cx, new_cy

在目标跟踪算法中使用，计算目标中心位置中会使用到
