### ISSUE TITLE
split

### ISSUE THREAD

**Issue by liuao520** [Oneflow-Inc/oneflow#3890]
```bash
2020-11-22 07:41:17.395916: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
17
(10, 4096, 17)
Traceback (most recent call last):
  File "loss_test.py", line 59, in <module>
    outputs = test_job(images,target,target_weight,y_pred)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/function_util.py", line 158, in Func
    return _RunLazyJob(sess, job_func, *args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/function_util.py", line 218, in _RunLazyJob
    return session.TryInit().LazyRun(job_func, *args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 212, in TryInit
    self.Init()
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 225, in Init
    compiler.Compile(self, func_desc, self.config_proto)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 44, in Compile
    _CompileJob(function_desc)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 102, in _CompileJob
    ret = func(*inputs)
  File "loss_test.py", line 29, in test_job
    loss_metric = loss.call(y_pred, target, target_weight)
  File "/content/drive/MyDrive/mycode/core/loss.py", line 17, in call
    heatmap_pred_list = pred.with_distribue(distribute.split(-1))
AttributeError: 'LazyConsistentBlob' object has no attribute 'with_distribue
```
这里 我本来想使用split,把blob划分成指定的几个子张量,类似于tf.split(value,num_or_size_splits,axis)
但使用onefliw.distribute.split出现了问题

**Comment by Flowingsun007** [comment]
您好，目前oneflow中类似tf.split的api有：flow.slice、flow.experimental.logical_slice等，具体使用方式可参考api文档：
- [flow.slice](https://oneflow.readthedocs.io/en/master/oneflow.html?highlight=slice#oneflow.slice)
- [flow.experimental.logical_slice](https://oneflow.readthedocs.io/en/master/experimental.html?highlight=slice#oneflow.experimental.logical_slice)

以下是简单的使用示例：
```python
import numpy as np
import oneflow.typing as tp


@flow.global_function()
def slice_Job(x: tp.Numpy.Placeholder(shape=(3, 3), dtype=flow.float32)
) -> tp.Numpy:
    slice_blob = flow.slice(x,
                            begin=[None, 0],
                            size=[None, 2])
    return slice_blob

x = np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]]).astype(np.float32)
out = slice_Job(x)

# out [[1. 2.]
#      [4. 5.]
#      [7. 8.]]
```
在实际项目中的使用示例，可参考：https://github.com/Oneflow-Inc/OneFlow-Benchmark/blob/dev_support_res2net/Classification/cnns/res2net_model.py#L151

**Comment by liuao520** [comment]
@Flowingsun007 我现在需要将一个例如(10, 4096, 17)的张量,分割成一个长度为17的列表,列表的每个元素是个三位张量,按列分割
如这般
tf.Tensor(
[[[ 1.6735264   5.812049    8.012602   ... -2.4496655   4.017882
    3.2852788 ]
  [ 3.2737134  -2.164178    5.781535   ...  5.1410394  -2.890772
    4.829506  ]
  [ 1.1894827  -8.387105    4.367958   ... -8.732471   -4.835445
    6.4476132 ]
  ...
  [-3.2799067   9.495359    9.749777   ... -3.613246   -5.851718
    2.6661172 ]
  [ 0.6294455  -4.8047314  -7.973309   ...  2.7527313  -6.8180113
   -1.3155993 ]
  [-0.63602906  8.49356     9.819604   ... -5.45195    -3.1389058
   -9.67363   ]]

(10, 4096, 17)
[<tf.Tensor: shape=(10, 4096, 1), dtype=float32, numpy=
array([[[ 1.6735264 ],
        [ 3.2737134 ],
        [ 1.1894827 ],
        ...,
        [-3.2799067 ],
        [ 0.6294455 ],
        [-0.63602906]],

       [[ 3.6765368 ],
        [ 7.5067964 ],
        [-1.9812452 ],
        ...,
        [-6.4976873 ],
        [ 5.45827   ],
        [ 4.539748  ]],

       [[ 5.4437    ],
        [ 9.163472  ],
        [-7.3754864 ],
        ...,
        [ 8.395564  ],
        [ 4.9938793 ],
        [ 8.221973  ]],

       ...,

       [[-4.891597  ],
        [ 6.850243  ],
        [-8.852727  ],
        ...,
        [ 9.383636  ],
        [ 4.769296  ],
        [ 9.240962  ]],

       [[-1.5046568 ],
        [-5.0052977 ],
        [ 5.774141  ],
        ...,
        [ 7.769773  ],
        [-3.9416306 ],
        [ 9.787209  ]],

       [[-8.245377  ],
        [ 2.4817643 ],
        [-3.4034617 ],
        ...,
        [-7.051639  ],
        [-4.3583107 ],
        [-3.4105005 ]]], dtype=float32)>, <tf.Tensor: shape=(10, 4096, 1), dtype=float32, numpy=
array([[[ 5.812049  ],
        [-2.164178  ],
        [-8.387105  ],
        ...,
        [ 9.495359  ],
        [-4.8047314 ],
        [ 8.49356   ]],

       [[ 7.2861366 ],
        [ 7.4603105 ],
        [ 0.14948206],
        ...,
        [-0.8667697 ],
        [ 2.7236104 ],
        [ 1.7630893 ]],

       [[-4.5586514 ],
        [ 3.7482944 ],
        [ 3.1653461 ],
        ...,
        [ 9.260427  ],
        [-8.992619  ],
        [-8.968865  ]],

       ...,

       [[ 4.739694  ],
        [ 6.52232   ],
        [-5.2703295 ],
        ...,
        [-7.0255218 ],
        [-3.1152287 ],
        [ 0.61549026]],

       [[ 1.6563088 ],
        [ 8.387326  ],
        [-2.7602327 ],
        ...,
        [-9.60498   ],
        [ 7.283268  ],
        [ 7.3507614 ]],

       [[ 0.08716697],
        [-7.2017765 ],
        [-0.97930676],
        ...,
        [ 8.385507  ],
        [ 5.6459694 ],
        [ 3.7063375 ]]], dtype=float32)>

好像切片实现不了这样的操作

**Comment by liuao520** [comment]
y_pred = np.random.uniform(-10, 10, (10,64,64,17)).astype(np.float32)
pred = tf.reshape(tensor=y_pred, shape=(10, -1, 17))
print(pred)
print(pred.shape)
heatmap_pred_list = tf.split(value=pred, num_or_size_splits=17, axis=-1)
print(heatmap_pred_list)
print(len(heatmap_pred_list))

**Comment by Flowingsun007** [comment]
您好，可用类似如下的方式实现：
```python
import oneflow as flow
import numpy as np
import oneflow.typing as tp


@flow.global_function()
def slice_Job(x: tp.Numpy.Placeholder(shape=(10, 4096, 17), dtype=flow.float32)
):
    tensor_list = []
    for i in range(17):
    	tensor = flow.slice(x, begin=[None, None, i*1], size=[None, None, 1])
    	tensor_list.append(tensor)
    	print("tensor.shape:", tensor.shape)

x = np.arange(696320).reshape(10, 4096, 17).astype(np.float32)
print("in.shape:", x.shape)
slice_Job(x)
```
output:
in.shape: (10, 4096, 17)
tensor.shape: (10, 4096, 1)
tensor.shape: (10, 4096, 1)
....

使用示例还可参考：https://github.com/Oneflow-Inc/OneFlow-Benchmark/blob/dev_support_res2net/Classification/cnns/res2net_model.py#L151

**Comment by liuao520** [comment]
您好,,类似的切片,比如说当前a的shape是(10, 17, 1),tensorflow我可可以通过 i 次循环a[:,i]的切片操作得到shape为 (10,1)的i个tensor
因为我看oneflow好像不能用静态图切片操作,那我如何通过仅有的slice来实现  谢谢
@Flowingsun007

**Comment by liuao520** [comment]
import tensorflow as tf
# a = tf.random.normal([10, 4096], 0, 1, tf.float32)
# b = tf.random.normal([10, 4096], 0, 1, tf.float32)
c = tf.random.normal([10, 17, 1], 0, 1, tf.float32)
print(a.shape)
print(b.shape)
print(c)
for i in range(17):
#   # print(c)
  print(c[:, i])
#   print(c[:, i].shape)
#   print(a.shape)
#   print(a * c[:, i])
#    print((a * c[:, i]).shape)

**Comment by liuao520** [comment]
import tensorflow as tf
# a = tf.random.normal([10, 4096], 0, 1, tf.float32)
# b = tf.random.normal([10, 4096], 0, 1, tf.float32)
c = tf.random.normal([10, 17, 1], 0, 1, tf.float32)
print(a.shape)
print(b.shape)
print(c)
for i in range(17):
#   # print(c)
  print(c[:, i])
#   print(c[:, i].shape)
#   print(a.shape)
#   print(a * c[:, i])
#    print((a * c[:, i]).shape)

**Comment by liuao520** [comment]
import tensorflow as tf
# a = tf.random.normal([10, 4096], 0, 1, tf.float32)
# b = tf.random.normal([10, 4096], 0, 1, tf.float32)
c = tf.random.normal([10, 17, 1], 0, 1, tf.float32)
print(a.shape)
print(b.shape)
print(c)
for i in range(17):
#   # print(c)
  print(c[:, i])
#   print(c[:, i].shape)
#   print(a.shape)
#   print(a * c[:, i])
#    print((a * c[:, i]).shape)

**Comment by Flowingsun007** [comment]
> 您好,,类似的切片,比如说当前a的shape是(10, 17, 1),tensorflow我可可以通过 i 次循环a[:,i]的切片操作得到shape为 (10,1)的i个tensor
> 因为我看oneflow好像不能用静态图切片操作,那我如何通过仅有的slice来实现 谢谢
> @Flowingsun007

您好，目前对齐pytorch的split操作已经支持，参考文档：https://oneflow.readthedocs.io/en/master/oneflow.html?highlight=split#oneflow.split
