### ISSUE TITLE
Check failed: (logical_blob_desc.shape().At(axis)) >= (blob_parallel_num)    (0 vs 1) op_name: dense_54-weight blob_name: out cannot split blob by parallel_num: 1

### ISSUE THREAD

**Issue by Lkinyuu** [Oneflow-Inc/oneflow#3909]
Check failed: (logical_blob_desc.shape().At(axis)) >= (blob_parallel_num)    (0 vs 1) op_name: dense_54-weight blob_name: out cannot split blob by parallel_num: 1
使用dense时出错，这是一个什么样的错误

**Comment by MARD1NO** [comment]
您好，能否把相关代码，运行环境信息发一下呢，这样可以帮助我们更好的定位问题

**Comment by chengtbf** [comment]
你的dense的weight tensor的shape有一维是0？看报错信息大概是这个原因。

**Comment by Lkinyuu** [comment]
> 你的dense的weight tensor的shape有一维是0？看报错信息大概是这个原因。

 y=flow.layers.dense(        out, 
                                   self.num_classes, 
                                   use_bias=True,
                                   bias_initializer=kernel_initializer,
                                   kernel_regularizer=weight_regularizer,
                                   bias_regularizer=weight_regularizer,                                   
                                   trainable=True,
                                   name="dense_"+str(time))

out进入dense之前的尺寸是（batchsize,2048）,当前在以2为batchsize测试 所以是（2,2048）

**Comment by chengtbf** [comment]
weight的shape仅跟输入tensor.shape的第1维和输出units的值相关：

https://github.com/Oneflow-Inc/oneflow/blob/17f436e248357a59edcce5aa9e0b1f3b9f6fbd55/oneflow/python/ops/layers.py#L120

在您给的这个例子里应该是 `(out.shape[1], self.num_classes)`，out.shape[1] 您可以print一下看看是不是2048，另外self.num_classes 您也print一下，看不是设成0了。
