### ISSUE TITLE
AssertionError: only fixed shaped blob compatible to oneflow.typing.Numpy. you can change annotation to oneflow.typing.ListNumpy or oneflow.typing.ListListNumpy

### ISSUE THREAD

**Issue by Lkinyuu** [Oneflow-Inc/oneflow#3910]
AssertionError: only fixed shaped blob compatible to oneflow.typing.Numpy. you can change annotation to oneflow.typing.ListNumpy or oneflow.typing.ListListNumpy  请问这个报错是在什么情况下出现，返回前的数据确定是oneflow.python.framework.remote_blob.LazyConsistentBlob

**Comment by MARD1NO** [comment]
您好，方便贴一下代码上下文吗，是不是用到了关于图片读取的API呢

**Comment by Lkinyuu** [comment]
> 您好，方便贴一下代码上下文吗，是不是用到了关于图片读取的API呢

是在checkpoint.init时出错，所以应该是定位到了train的作业函数的返回处。

input_image = tp.Numpy.Placeholder((args.train_batch , 3, args.seq_len, args.height,args.width))
input_pid = tp.Numpy.Placeholder((args.train_batch,))

@flow.global_function(type="train",function_config=func_config)
def train_job(image:input_image,pids:input_pid
)->Tuple[tp.Numpy,tp.Numpy,tp.Numpy,tp.Numpy]:

    #weight_decay=5e-04 lr=0.0003

    model = models.init_model(name=args.arch, num_classes=dataset.num_train_pids,training=True)

    outputs,features=model.build_network(image)
        # combine hard triplet loss with cross entropy loss

    xent_loss=_CrossEntropyLoss(
        num_classes=dataset.num_train_pids
            ).forward(outputs,pids)
        
    htri_loss=TripletLoss(margin=args.margin).build(features, pids)
    loss=xent_loss + htri_loss
    len_stepsize=len(args.stepsize)
    lr_scheduler=flow.optimizer.PiecewiseScalingScheduler(
            base_lr=args.lr,boundaries=args.stepsize,
            scale=[args.gamma]*len_stepsize
        )
    flow.optimizer.AdamW(lr_scheduler, do_bias_correction=False,weight_decay=args.weight_decay).minimize(loss)
    print(loss)
    print(xent_loss)
    print(htri_loss)
    print(outputs)
    return loss,xent_loss,htri_loss,outputs

**Comment by Flowingsun007** [comment]
您好，可以尝试：
```python
def train_job(image:input_image,pids:input_pid
)->Tuple[tp.Numpy,tp.Numpy,tp.Numpy,tp.Numpy]:
改成
->tp.ListNumpy:

**Comment by Lkinyuu** [comment]
> ```python
> def train_job(image:input_image,pids:input_pid
> )->Tuple[tp.Numpy,tp.Numpy,tp.Numpy,tp.Numpy]:
> 改成
> ->tp.ListNumpy
> ```

在测试文件中测试使用4个tp.Numpy组成的Tuple时并未出现这个错误。应该不是这个问题

不过 想顺便请问一下若使用tp.ListNumpy的话return 部分应该怎么书写，docs中不太清楚，自己试验的话使用
return [loss,xent_loss,htri_loss,outputs]会说类型有误

**Comment by doombeaker** [comment]
你好，所有的返回方法（包括少见所以文档中没有提及的）用法，都可以在这里找到例子：
https://github.com/Oneflow-Inc/oneflow/blob/master/oneflow/python/test/ops/test_global_function_signature.py

另外，注意job function的参数是注解（用冒号":"），而不是默认参（等号“=”），这也是一个常见笔误，我们也在想办法怎样做更严格的检查及更友好的提示。

谢谢反馈

**Comment by MARD1NO** [comment]
CrossEntropyLoss 和 TripletLoss 部分的代码可以一并贴一下吗

**Comment by Lkinyuu** [comment]
> CrossEntropyLoss 和 TripletLoss 部分的代码可以一并贴一下吗

这两个loss是参考的https://github.com/Oneflow-Inc/oneflow_vision_model/tree/main/Re-ID中的loss

**Comment by Lkinyuu** [comment]
> 你好，所有的返回方法（包括少见所以文档中没有提及的）用法，都可以在这里找到例子：
> https://github.com/Oneflow-Inc/oneflow/blob/master/oneflow/python/test/ops/test_global_function_signature.py
> 
> 谢谢反馈

这个文件中的例子都是 占位符设置成了ListNumpy，将list传入作业函数后后直接return，这好像没有参考的价值，因为无法体现globalfuction中如何产生一个ListNumpy

**Comment by Lkinyuu** [comment]
经过测试，可能是损失函数中出了问题，单独return loss 出现以下错误：
gradient_function_not_found_error {
}

name: "BroadcastLike_597"
device_tag: "gpu"
enable_cudnn: true
scope_symbol_id: 4611686018427420670
user_conf {
  op_type_name: "broadcast_like"
  input {
    key: "like"
    value {
      s: "Constant_596/out_0"
    }
  }
  input {
    key: "x"
    value {
      s: "ReduceSum_595/output_tensor_0"
    }
  }
  output {
    key: "y"
    value {
      s: "BroadcastLike_597/y_0"
    }
  }
  attr {
    key: "broadcast_axes"
    value {
      at_list_int32 {
        val: 1
      }
    }
  }
}

**Comment by Lkinyuu** [comment]
感谢各位的解答，经过排查应该是在旧版本下自以为是的删除了 损失函数中的transpose中的新参数batch_axis_non_change所导致的问题，在更新为0.2b2后解决该问题。

**Comment by Lkinyuu** [comment]
> CrossEntropyLoss 和 TripletLoss 部分的代码可以一并贴一下吗

经过测试单独return loss是正常的，所以可能还是作业函数的返回类型的问题
