### ISSUE TITLE
Check failed: blob->shape().NumAxes() == 2 (1 vs. 2) 

### ISSUE THREAD

**Issue by Lkinyuu** [Oneflow-Inc/oneflow#3914]
由于oneflow的提示的不够明显无法定位这个问题，是否是在global_fuction传入blob的时候出现尺寸问题

**Comment by MARD1NO** [comment]
您好，能否把整个C++报错栈发出来呢，报错的上下文信息是否有提到相关OP呢

**Comment by Lkinyuu** [comment]
> 您好，能否把整个C++报错栈发出来呢，报错的上下文信息是否有提到相关OP呢

Check failure stack trace: ***
    @     0x7f22da5f1f9d  google::LogMessage::Fail()
    @     0x7f22da5f60dc  google::LogMessage::SendToLog()
    @     0x7f22da5f1ac3  google::LogMessage::Flush()
    @     0x7f22da5f6af9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f22d9306bb8  (unknown)
    @     0x7f22d9310f6b  oneflow::KernelUtil<>::InitializeWithConf()
    @     0x7f22d9314b9b  oneflow::ModelInitKernel::ForwardDataContent()
    @     0x7f22d931519e  oneflow::ModelInitKernel::Forward()
    @     0x7f22d9303791  oneflow::Kernel::Launch()
    @     0x7f22d8f6838c  oneflow::Actor::AsyncLaunchKernel()
    @     0x7f22d8f7c6dc  oneflow::NormalForwardCompActor::Act()
    @     0x7f22d8f697ce  oneflow::Actor::TryLogActEvent()
    @     0x7f22d8f6c3c6  oneflow::Actor::ActUntilFail()
    @     0x7f22d8f6c4b5  oneflow::Actor::HandlerNormal()
    @     0x7f22d94d0901  oneflow::Thread::PollMsgChannel()
    @     0x7f22d94cda83  (unknown)
    @     0x7f231e9b8c80  (unknown)
    @     0x7f2324d616ba  start_thread
    @     0x7f2323f4441d  clone
    @              (nil)  (unknown)

就这些了

**Comment by MARD1NO** [comment]
确实看不出来，代码方便公开吗，能否放一份到github上呢？

**Comment by MARD1NO** [comment]
另外是否有用到 xavier_initializer 或 kaiming_initializer 呢？如果用了，是不是data_format指定有问题？

**Comment by doombeaker** [comment]
可以贴到 https://paste.ubuntu.com/ 再把链接发在这里，谢谢

**Comment by Lkinyuu** [comment]
> 另外是否有用到 xavier_initializer 或 kaiming_initializer 呢？如果用了，是不是data_format指定有问题？

可能是这方面的问题，底层的几个data_format未设置，设置为NCDHW后开始出现
Check failed: 0 <= begin_axis && begin_axis <= end_axis && end_axis <= this->NumAxes()

**Comment by Lkinyuu** [comment]
感谢解答，定位到错误是用variance_scaling_initializer对dense进行了初始化。

**Comment by yuanms2** [comment]
> 感谢解答，定位到错误是用variance_scaling_initializer对dense进行了初始化。

谢谢反馈，这是我们系统设计考虑不周，后续会优化用户接口。
