### ISSUE TITLE
Check failed: NeedBackwardOp(loss_node)

### ISSUE THREAD

**Issue by liuao520** [Oneflow-Inc/oneflow#3919]
测试一下 (https://github.com/liuao520/test/blob/main/loss_test.py)
有下面问题 
2020-11-26 06:54:06.284753: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
(10, 64, 64, 17)
!!!!!!
(10, 64, 64, 17)
10 17
---
(10, 17, 1)
-----------------
<oneflow.python.framework.remote_blob.LazyConsistentBlob object at 0x7f4f70138d30> <oneflow.python.framework.remote_blob.LazyConsistentBlob object at 0x7f4f701570b8> <oneflow.python.framework.remote_blob.LazyConsistentBlob object at 0x7f4f706399e8>
F1126 06:54:33.643579  3159 autograd.cpp:568] Check failed: NeedBackwardOp(loss_node) ScalarMul_439
*** Check failure stack trace: ***
    @     0x7f4fc3db3b8d  google::LogMessage::Fail()
    @     0x7f4fc3db7ccc  google::LogMessage::SendToLog()
    @     0x7f4fc3db36b3  google::LogMessage::Flush()
    @     0x7f4fc3db86e9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f4fc2de94cb  oneflow::AutoGrad()
    @     0x7f4fc2e0ecd9  (unknown)
    @     0x7f4fc2dd6237  oneflow::OpGraphPass::Apply()
    @     0x7f4fc2dd678c  oneflow::OpGraphPass::Apply()
    @     0x7f4fc2d4dc58  (unknown)
    @     0x7f4fc2d640d5  oneflow::LazyJobBuildAndInferCtx::Complete()
    @     0x7f4fc2b2dba1  (unknown)
    @           0x50a12f  (unknown)
    @           0x50beb4  _PyEval_EvalFrameDefault
    @           0x5095c8  (unknown)
    @           0x50a2fd  (unknown)
    @           0x50beb4  _PyEval_EvalFrameDefault
    @           0x5095c8  (unknown)
    @           0x50a2fd  (unknown)
    @           0x50beb4  _PyEval_EvalFrameDefault
    @           0x5095c8  (unknown)
    @           0x50a2fd  (unknown)
    @           0x50beb4  _PyEval_EvalFrameDefault
    @           0x5095c8  (unknown)
    @           0x50a2fd  (unknown)
    @           0x50beb4  _PyEval_EvalFrameDefault
    @           0x507be4  (unknown)
    @           0x588d41  (unknown)
    @           0x59fd0e  PyObject_Call
    @           0x50d256  _PyEval_EvalFrameDefault
    @           0x507be4  (unknown)
    @           0x509900  (unknown)
    @           0x50a2fd  (unknown)

**Comment by MARD1NO** [comment]
你好，该问题是如果用优化器去minimize loss，需要将global_function中的 type设置为 train 模式，即
```
@flow.global_function(type="train")
def xxxx_job(...)
```
