### ISSUE TITLE
0.3b1 for cu101

### ISSUE THREAD

**Issue by 15168387900** [Oneflow-Inc/oneflow#3922]
I saw that `oneflow.math.argmax` has a parameter named `axis` in the API documentation
It seems that it has been merged in 0.3b1
Can i get 0.3b1 for cu101? : )

**Comment by jackalcooper** [comment]
https://oneflow-staging.oss-cn-beijing.aliyuncs.com/build_master_whl_once_a_day/60f68ce32c370a57597c9c20a698c268aee61deb/oneflow_cu101-0.3b1-cp36-cp36m-manylinux2014_x86_64.whl

https://oneflow-staging.oss-cn-beijing.aliyuncs.com/build_master_whl_once_a_day/60f68ce32c370a57597c9c20a698c268aee61deb/oneflow_cu101-0.3b1-cp37-cp37m-manylinux2014_x86_64.whl

https://oneflow-staging.oss-cn-beijing.aliyuncs.com/build_master_whl_once_a_day/60f68ce32c370a57597c9c20a698c268aee61deb/oneflow_cu101-0.3b1-cp38-cp38-manylinux2014_x86_64.whl

**Comment by 15168387900** [comment]
> https://oneflow-staging.oss-cn-beijing.aliyuncs.com/build_master_whl_once_a_day/60f68ce32c370a57597c9c20a698c268aee61deb/oneflow_cu101-0.3b1-cp35-cp35m-manylinux2014_x86_64.whl
> 
> https://oneflow-staging.oss-cn-beijing.aliyuncs.com/build_master_whl_once_a_day/60f68ce32c370a57597c9c20a698c268aee61deb/oneflow_cu101-0.3b1-cp36-cp36m-manylinux2014_x86_64.whl
> 
> https://oneflow-staging.oss-cn-beijing.aliyuncs.com/build_master_whl_once_a_day/60f68ce32c370a57597c9c20a698c268aee61deb/oneflow_cu101-0.3b1-cp37-cp37m-manylinux2014_x86_64.whl
> 
> https://oneflow-staging.oss-cn-beijing.aliyuncs.com/build_master_whl_once_a_day/60f68ce32c370a57597c9c20a698c268aee61deb/oneflow_cu101-0.3b1-cp38-cp38-manylinux2014_x86_64.whl

Thanks!

**Comment by 15168387900** [comment]
> https://oneflow-staging.oss-cn-beijing.aliyuncs.com/build_master_whl_once_a_day/60f68ce32c370a57597c9c20a698c268aee61deb/oneflow_cu101-0.3b1-cp35-cp35m-manylinux2014_x86_64.whl
> 
> https://oneflow-staging.oss-cn-beijing.aliyuncs.com/build_master_whl_once_a_day/60f68ce32c370a57597c9c20a698c268aee61deb/oneflow_cu101-0.3b1-cp36-cp36m-manylinux2014_x86_64.whl
> 
> https://oneflow-staging.oss-cn-beijing.aliyuncs.com/build_master_whl_once_a_day/60f68ce32c370a57597c9c20a698c268aee61deb/oneflow_cu101-0.3b1-cp37-cp37m-manylinux2014_x86_64.whl
> 
> https://oneflow-staging.oss-cn-beijing.aliyuncs.com/build_master_whl_once_a_day/60f68ce32c370a57597c9c20a698c268aee61deb/oneflow_cu101-0.3b1-cp38-cp38-manylinux2014_x86_64.whl

It seems that those link no longer works
One of my friends also wants to download them : )

**Comment by jackalcooper** [comment]
```
python3 -m pip install --find-links https://oneflow-staging.oss-cn-beijing.aliyuncs.com/branch/master/index.html oneflow_cu101 --user
```
