### ISSUE TITLE
keypoint

### ISSUE THREAD

**Issue by liuao520** [Oneflow-Inc/oneflow#3926]
我在coco上的关键点测试上,需要关键点(包括位置,和num)(至于id bbox当前onflow的cocoreader已经有),其次对于每一个类别,categories的两个字段,希望你们可以解析开发出来,方便我们直接使用,比如不用自定义连接,可视化等

**Comment by ZhengJianwei2** [comment]
算子：coco_reader
需求：用于姿态估计算法复现，目前仅返回目标检测任务的Box值，并无Pose值，烦请在算子中将姿态估计所需的参数从coco数据集中一起返回出来，具体参数包括：
Key_points、Key_points_Number、categories的两个字段

**Comment by leaves-zwx** [comment]
谢谢反馈，我们将尽快为 coco reader 添加 keypoint 相关字段的读取，敬请期待。

**Comment by ScXfjiang** [comment]
KeyPoint数据集加载问题统一在这个issue下讨论：https://github.com/Oneflow-Inc/oneflow/issues/3784
