### ISSUE TITLE
train问题

### ISSUE THREAD

**Issue by liuao520** [Oneflow-Inc/oneflow#3962]
我尝试自己coco数据集得到了images, target, target_weight, shape和dtype都是对应的,然而然后我在进行训练的时候,有下面的问题
我的train
```python3
# import tensorflow as tf
import oneflow as flow
import oneflow.typing as tp
from typing import Tuple

from core.loss import JointsMSELoss
from core.make_dataset import CocoDataset
from core.make_ground_truth import GroundTruth
from core.metric import PCK
from test import test_during_training
from core.hrnet import HRNet
from utils.work_flow import get_model, print_model_summary
from configuration.base_config import Config
from utils.tools import get_config_params


cfg = get_config_params(Config.TRAINING_CONFIG_NAME)

if __name__ == '__main__':
    # # GPU settings
    # gpus = tf.config.list_physical_devices("GPU")
    # if gpus:
    #     for gpu in gpus:
    #         tf.config.experimental.set_memory_growth(gpu, True)

    cfg = get_config_params(Config.TRAINING_CONFIG_NAME)
    # hrnet = get_model(cfg)
    # print_model_summary(hrnet)

    # Dataset
    coco = CocoDataset(config_params=cfg, dataset_type="train")
    dataset, dataset_length = coco.generate_dataset()

    # loss and optimizer
    loss = JointsMSELoss()
    # optimizer = flow.optimizer.Adam(lr_scheduler=1e-3)
    # metircs
    # loss_metric = tf.metrics.Mean()
    pck = PCK()
    # accuracy_metric = tf.metrics.Mean()
    
    @flow.global_function(type="train")
    def train_step(images: tp.Numpy.Placeholder((cfg.BATCH_SIZE, 256, 256, 3), dtype=flow.float32),
            target: tp.Numpy.Placeholder((cfg.BATCH_SIZE, 64, 64, 17), dtype=flow.float32),
            target_weight: tp.Numpy.Placeholder((cfg.BATCH_SIZE, 17, 1), dtype=flow.float32),
            # y_pred: tp.Numpy.Placeholder((10,64,64,17), dtype=flow.float),
            ) -> Tuple[tp.Numpy, tp.Numpy, tp.Numpy]:
        
        y_pred = HRNet(images, training=True)
        loss_metric = loss.call(y_pred, target, target_weight)
        loss_metric = flow.math.reduce_mean(loss_metric)
        # Set learning rate as 0.001
        lr_scheduler = flow.optimizer.PiecewiseConstantScheduler([], [0.001])
        # Set Adam optimizer
        # print(loss_metric.shape)
        flow.optimizer.Adam(lr_scheduler, do_bias_correction=False).minimize(loss_metric)
        return loss_metric, y_pred, target
        

    check_point = flow.train.CheckPoint()
    start_epoch = cfg.LOAD_WEIGHTS_FROM_EPOCH

    if cfg.LOAD_WEIGHTS_BEFORE_TRAINING:
        # hrnet.load_weights(filepath=cfg.save_weights_dir + "epoch-{}".format(start_epoch))
        check_point.load(cfg.save_weights_dir + "epoch-{}".format(start_epoch))
        print("Successfully load weights!")
    else:
        start_epoch = -1

    # check_point.init()
    for epoch in range(start_epoch + 1, cfg.EPOCHS):
        for step, batch_data in enumerate(dataset):
            gt = GroundTruth(cfg, batch_data)
            images, target, target_weight = gt.get_ground_truth()
            print(images.dtype, target.dtype, target_weight.dtype)
            print(images.shape, target.shape, target_weight.shape)
            loss_metric, y_pred, target = train_step(images, target, target_weight)

            _, accuracy_metric, _, _ = pck.call(network_output=y_pred, target=target)
            accurary = np.mean(accuracy_metric)

           
            print("Epoch: {}/{}, step: {}/{}, loss: {:.10f}, accuracy: {:.5f}".format(epoch,
                                                    cfg.EPOCHS,
                                                    step,
                                                    flow.math.ceil(dataset_length / cfg.BATCH_SIZE),
                                                    loss_metric,
                                                    accurary))
            flow.optimizer.Adam(lr_scheduler=1e-3).minimize(loss_metric)

        if epoch % cfg.SAVE_FREQUENCY == 0:
            check_point.save(cfg.save_weights_dir + "epoch-{}".format(epoch))
        if cfg.TEST_DURING_TRAINING:
            test_during_training(cfg=cfg, epoch=epoch, model=hrnet)


    check_point.save(cfg.save_weights_dir+"saved_model")
```
出现的错误
```bash
(8, 256, 256, 3) (8, 64, 64, 17) (8, 17, 1)
Traceback (most recent call last):
  File "train.py", line 77, in <module>
    loss_metric, y_pred, target = train_step(images, target, target_weight)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/function_util.py", line 158, in Func
    return _RunLazyJob(sess, job_func, *args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/function_util.py", line 218, in _RunLazyJob
    return session.TryInit().LazyRun(job_func, *args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 212, in TryInit
    self.Init()
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 225, in Init
    compiler.Compile(self, func_desc, self.config_proto)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 44, in Compile
    _CompileJob(function_desc)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 92, in _CompileJob
    func.__oneflow_input_blob_defs__ = _GetArgDefault(func)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 146, in _GetArgDefault
    return _CloneArgBlobDef(func_inspect_util.GetArgDefaults(func))
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 153, in _CloneArgBlobDef
    return type(args)(_CloneArgBlobDef(x) for x in args)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 153, in <genexpr>
    return type(args)(_CloneArgBlobDef(x) for x in args)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 157, in _CloneArgBlobDef
    "oneflow.global_function only accepts nested input blob defs"
NotImplementedError: oneflow.global_function only accepts nested input blob defs
```

**Comment by liuao520** [comment]
这是什么原因呢  我尝试相同类型和形状的随机numpy数据输入,,他是可以运行的

**Comment by MARD1NO** [comment]
有几个疑问的点
```
# check_point.init()
for epoch in range(start_epoch + 1, cfg.EPOCHS):
    for step, batch_data in enumerate(dataset):
        gt = GroundTruth(cfg, batch_data)
        images, target, target_weight = gt.get_ground_truth()
        print(images.dtype, target.dtype, target_weight.dtype)
        print(images.shape, target.shape, target_weight.shape)
        loss_metric, y_pred, target = train_step(images, target, target_weight)

        _, accuracy_metric, _, _ = pck.call(network_output=y_pred, target=target)
        accurary = np.mean(accuracy_metric)

       # 这里不要用flow.math.ceil了，直接用python自带的库
        print("Epoch: {}/{}, step: {}/{}, loss: {:.10f}, accuracy: {:.5f}".format(epoch,
                                                cfg.EPOCHS,
                                                step,
                                                flow.math.ceil(dataset_length / cfg.BATCH_SIZE),
                                                loss_metric,
                                                accurary))
        # 这里是不是重复了？ train_step已经minimize loss了
        flow.optimizer.Adam(lr_scheduler=1e-3).minimize(loss_metric)

```

**Comment by liuao520** [comment]
不是这个问题   确实我疏忽了   但是改了之后  还是在 loss_metric, y_pred, target = train_step(images, target, target_weight)在这里报错了
而且是这个错误 
NotImplementedError: oneflow.global_function only accepts nested input blob defs

**Comment by liuao520** [comment]
@MARD1NO

**Comment by liuao520** [comment]
还是这个问题,,感觉是numpy数据没有传到train_step里面去?这是为什么呢..我随机初始化几个对应的numpy数据是可以运行的
float32 float32 float32
(8, 256, 256, 3) (8, 64, 64, 17) (8, 17, 1)
Traceback (most recent call last):
  File "train.py", line 78, in <module>
    loss_metric, y_pred, target = train_step(images, target, target_weight)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/function_util.py", line 158, in Func
    return _RunLazyJob(sess, job_func, *args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/function_util.py", line 218, in _RunLazyJob
    return session.TryInit().LazyRun(job_func, *args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 212, in TryInit
    self.Init()
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 225, in Init
    compiler.Compile(self, func_desc, self.config_proto)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 44, in Compile
    _CompileJob(function_desc)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 92, in _CompileJob
    func.__oneflow_input_blob_defs__ = _GetArgDefault(func)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 146, in _GetArgDefault
    return _CloneArgBlobDef(func_inspect_util.GetArgDefaults(func))
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 153, in _CloneArgBlobDef
    return type(args)(_CloneArgBlobDef(x) for x in args)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 153, in <genexpr>
    return type(args)(_CloneArgBlobDef(x) for x in args)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 157, in _CloneArgBlobDef
    "oneflow.global_function only accepts nested input blob defs"
NotImplementedError: oneflow.global_function only accepts nested input blob defs

**Comment by Ldpe2G** [comment]
@liuao520 能简单看下你的 `JointsMSELoss` 和 `HRNet` 的定义吗

**Comment by liuao520** [comment]
我详细阅读了相关文档,,这是oneflow自定义的一个error,能说一下这个问题怎么处理吗
我现在的所能想到的处理数据和训练的方法,便是这样,先离线获得训练数据(numpy数据),然后global_function,通过oneflow来训练和计算loss  
原本测试loss,是可行的,但现在出现的这个问题

**Comment by liuao520** [comment]
[loss](https://github.com/liuao520/test/blob/main/core/loss.py)
[net](https://github.com/liuao520/test/blob/main/core/hrnet.py)
@Ldpe2G

**Comment by liuao520** [comment]
我感觉不是loss和net的问题  这两个我测试都通过了,  问题是这个numpy数据(images, target, target_weight),根本没有传到训练函数里面去
我想知道oneflow这个自定义的错误NotImplementedError: oneflow.global_function only accepts nested input blob defs
return type(args)(_CloneArgBlobDef(x) for x in args)等是什么意思   
numpy数据为什么导入不进去

**Comment by MARD1NO** [comment]
能否在每个子文件设置一个global_function单独进行测试呢

可参考 https://github.com/MARD1NO/OneFlow_Transformer/blob/master/model/Decoder.py  形式进行测试。 

另外是否有定义多个job_function？

**Comment by liuao520** [comment]
在我这个代码里面,我仅仅只需要一个global_function,也就是最后的train和loss,我离线操作,获取了系列coco数据集的图像 关键点链接等nunpy类型数据,导入 train_step这一个job_function里面计算,没有任何其他的操作
@MARD1NO

**Comment by Ldpe2G** [comment]
> 我感觉不是loss和net的问题 这两个我测试都通过了, 问题是这个numpy数据(images, target, target_weight),根本没有传到训练函数里面去
> 我想知道oneflow这个自定义的错误NotImplementedError: oneflow.global_function only accepts nested input blob defs
> return type(args)(_CloneArgBlobDef(x) for x in args)等是什么意思
> numpy数据为什么导入不进去

这个错误是在编译  global_function 分析输入参数阶段，检查参数类型的时候出错的，还没到运行函数的阶段。

**Comment by liuao520** [comment]
@Ldpe2G 
检查参数类型?
占位符和类型吗?
我也想过,但是这个都对应了呀
float32 float32 float32
(8, 256, 256, 3) (8, 64, 64, 17) (8, 17, 1)E1203 02:40:44.337621   945 version.cpp:72] Failed to get cuda runtime version: no CUDA-capable device is detected
Traceback (most recent call last):
  File "train.py", line 78, in <module>
    loss_metric, y_pred, target = train_step(images, target, target_weight)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/function_util.py", line 158, in Func
    return _RunLazyJob(sess, job_func, *args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/function_util.py", line 218, in _RunLazyJob
    return session.TryInit().LazyRun(job_func, *args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 212, in TryInit
    self.Init()
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 225, in Init
    compiler.Compile(self, func_desc, self.config_proto)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 44, in Compile
    _CompileJob(function_desc)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 92, in _CompileJob
    func.__oneflow_input_blob_defs__ = _GetArgDefault(func)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 146, in _GetArgDefault
    return _CloneArgBlobDef(func_inspect_util.GetArgDefaults(func))
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 153, in _CloneArgBlobDef
    return type(args)(_CloneArgBlobDef(x) for x in args)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 153, in <genexpr>
    return type(args)(_CloneArgBlobDef(x) for x in args)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 157, in _CloneArgBlobDef
    "oneflow.global_function only accepts nested input blob defs"
NotImplementedError: oneflow.global_function only accepts nested input blob defs

**Comment by liuao520** [comment]
@Ldpe2G 
有什么方法可以处理吗?

**Comment by MARD1NO** [comment]
你的dataset弄错了吧，不能拿tf的API来读到oneflow的

**Comment by liuao520** [comment]
没有没有   我自己重新写的一个简单的数据集载入,在数据集的标签文件上下功夫,使用PIL读取图像,没有使用tf,最后得到的图像和关节点连接等都转换成了numpy 再读到oneflow的
因为没有cocoreader的keypoint  我自己尝试解析的  返回的参数也都对应  没有使用tf的api
@MARD1NO

**Comment by MARD1NO** [comment]
你能否给出一个最简的复现示例？
我这边简单写了个读图片的reader，运作是正常的
```
import cv2
import os
import numpy as np

path = "/home/zzk/Code/OneFlow_test/test_issue/img"


def read_data(data_dir):
    batch_num = 10

    def reader():
        _batch_num = 0
        _batch_input = []
        img_path = os.listdir(data_dir)

        for i in range(len(img_path)):
            full_path = os.path.join(data_dir, img_path[i])
            img = cv2.imread(full_path)
            img = cv2.resize(img, (224, 224))
            _batch_input.append(img)
            _batch_num += 1
            if _batch_num == batch_num:
                # Generate a batch data
                yield np.array(_batch_input).astype(np.float32)
                # Reset
                _batch_num = 0
                _batch_input = []

    return reader


#
import oneflow as flow
import oneflow.typing as tp


@flow.global_function()
def test_data_read(img: tp.Numpy.Placeholder(shape=(10, 224, 224, 3))) -> tp.Numpy:
    return img


reader = read_data(path)
for epoch in range(2):
    for index, data in enumerate(reader()):
        print("Index is: ", index)
        print("Data shape is: ", data.shape)
        oneflow_out = test_data_read(data)
        print("Oneflow out shape is: ", oneflow_out.shape)

```

**Comment by liuao520** [comment]
是我的版本有问题吗   我单纯的传参都不行
def metric(images,target,target_weight,y_pred):
  print("-!!!!!!!!!!!!!")
  @flow.global_function(type="train")
  def test_job(
      images: tp.Numpy.Placeholder((10, 256, 256, 3), dtype=flow.float32),
      target: tp.Numpy.Placeholder((10, 64, 64, 17), dtype=flow.float32),
      target_weight: tp.Numpy.Placeholder((10, 17, 1), dtype=flow.float32),
      y_pred: tp.Numpy.Placeholder((10,64,64,17), dtype=flow.float32),
      ) -> Tuple[tp.Numpy, tp.Numpy, tp.Numpy]:
      # loss = JointsMSELoss()
      # print("------------")
      
      # print("!!!!!!")
      # print(y_pred.shape)
      # loss_metric = loss.call(y_pred, target, target_weight)
      
      # loss_metric = flow.math.reduce_mean(loss_metric)
      # # Set learning rate as 0.001
      # lr_scheduler = flow.optimizer.PiecewiseConstantScheduler([], [0.001])
      # # Set Adam optimizer
      # # print(loss_metric.shape)
      # flow.optimizer.Adam(lr_scheduler, do_bias_correction=False).minimize(loss_metric)

      # print("-----------------")
      # print(loss_metric, y_pred, target)
      return y_pred, target
  y_pred, target = test_job(images,target,target_weight,y_pred)
  # pck = PCK()
  # _, accuracy_metric, _, _ = pck.call(network_output=y_pred, target=target)
  # accurary = np.mean(accuracy_metric)
  print("--@@-")
  print(y_pred.shape)
  print("--!-")
  # print(y_pred)
  # print("----%------")
  # print(target)
  # print("--!-")
  # return(loss_metric)

if __name__ == "__main__":
    # cfg = get_config_params(Config.TRAINING_CONFIG_NAME)
    # hrnet = get_model(cfg)
    #print_model_summary(hrnet)
    
    images = np.random.uniform(-10, 10, (10, 256, 256, 3)).astype(np.float32)
    target = np.random.uniform(-10, 10, (10, 64, 64, 17)).astype(np.float32)
    target_weight = np.random.uniform(-10, 10, (10, 17, 1)).astype(np.float32)
    y_pred = np.random.uniform(-10, 10, (10,64,64,17)).astype(np.float32)
    print(images.dtype, target.dtype, target_weight.dtype)
    print(images.shape, target.shape, target_weight.shape)
    outputs = metric(images,target,target_weight,y_pred)
    print(outputs)

**Comment by liuao520** [comment]
当初我测试我的loss的时候,是可行的   现在怎么都不行
是我版本的问题吗 最近不是更新了  单纯的传参都有问题
def metric(images,target,target_weight,y_pred):
  print("-!!!!!!!!!!!!!")
  @flow.global_function(type="train")
  def test_job(
      images: tp.Numpy.Placeholder((10, 256, 256, 3), dtype=flow.float32),
      target: tp.Numpy.Placeholder((10, 64, 64, 17), dtype=flow.float32),
      target_weight: tp.Numpy.Placeholder((10, 17, 1), dtype=flow.float32),
      y_pred: tp.Numpy.Placeholder((10,64,64,17), dtype=flow.float32),
      ) -> Tuple[tp.Numpy, tp.Numpy, tp.Numpy]:

      return images,y_pred, target
  images,y_pred, target = test_job(images,target,target_weight,y_pred)
  print("--@@-")
  print(y_pred.shape)
  print("--!-")


if __name__ == "__main__":
    
    images = np.random.uniform(-10, 10, (10, 256, 256, 3)).astype(np.float32)
    target = np.random.uniform(-10, 10, (10, 64, 64, 17)).astype(np.float32)
    target_weight = np.random.uniform(-10, 10, (10, 17, 1)).astype(np.float32)
    y_pred = np.random.uniform(-10, 10, (10,64,64,17)).astype(np.float32)
    print(images.dtype, target.dtype, target_weight.dtype)
    print(images.shape, target.shape, target_weight.shape)
    outputs = metric(images,target,target_weight,y_pred)
    print(outputs)

**Comment by liuao520** [comment]
当初我测试我的loss的时候,是可行的 现在怎么都不行
是我版本的问题吗 最近不是更新了 单纯的传参都有问题

def metric(images,target,target_weight,y_pred):
  print("-!!!!!!!!!!!!!")
  @flow.global_function(type="train")
  def test_job(
      images: tp.Numpy.Placeholder((10, 256, 256, 3), dtype=flow.float32),
      target: tp.Numpy.Placeholder((10, 64, 64, 17), dtype=flow.float32),
      target_weight: tp.Numpy.Placeholder((10, 17, 1), dtype=flow.float32),
      y_pred: tp.Numpy.Placeholder((10,64,64,17), dtype=flow.float32),
      ) -> Tuple[tp.Numpy, tp.Numpy, tp.Numpy]:

      return images,y_pred, target

  images,y_pred, target = test_job(images,target,target_weight,y_pred)
  return y_pred.shape
  


if __name__ == "__main__":
    
    images = np.random.uniform(-10, 10, (10, 256, 256, 3)).astype(np.float32)
    target = np.random.uniform(-10, 10, (10, 64, 64, 17)).astype(np.float32)
    target_weight = np.random.uniform(-10, 10, (10, 17, 1)).astype(np.float32)
    y_pred = np.random.uniform(-10, 10, (10,64,64,17)).astype(np.float32)
    print(images.dtype, target.dtype, target_weight.dtype)
    print(images.shape, target.shape, target_weight.shape)
    outputs = metric(images,target,target_weight,y_pred)
    print(outputs)

**Comment by liuao520** [comment]
当初我测试我的loss的时候,是可行的 现在怎么都不行
是我版本的问题吗 最近不是更新了 单纯的传参都有问题

`def metric(images,target,target_weight,y_pred):
  print("-!!!!!!!!!!!!!")
  @flow.global_function(type="train")
  def test_job(
      images: tp.Numpy.Placeholder((10, 256, 256, 3), dtype=flow.float32),
      target: tp.Numpy.Placeholder((10, 64, 64, 17), dtype=flow.float32),
      target_weight: tp.Numpy.Placeholder((10, 17, 1), dtype=flow.float32),
      y_pred: tp.Numpy.Placeholder((10,64,64,17), dtype=flow.float32),
      ) -> Tuple[tp.Numpy, tp.Numpy, tp.Numpy]:

      return images,y_pred, target

  images,y_pred, target = test_job(images,target,target_weight,y_pred)
  return y_pred.shape
  


if __name__ == "__main__":
    
    images = np.random.uniform(-10, 10, (10, 256, 256, 3)).astype(np.float32)
    target = np.random.uniform(-10, 10, (10, 64, 64, 17)).astype(np.float32)
    target_weight = np.random.uniform(-10, 10, (10, 17, 1)).astype(np.float32)
    y_pred = np.random.uniform(-10, 10, (10,64,64,17)).astype(np.float32)
    print(images.dtype, target.dtype, target_weight.dtype)
    print(images.shape, target.shape, target_weight.shape)
    outputs = metric(images,target,target_weight,y_pred)
    print(outputs)`

**Comment by liuao520** [comment]
当初我测试我的loss的时候,是可行的 现在怎么都不行
是我版本的问题吗 最近不是更新了 单纯的传参都有问题
def metric(images,target,target_weight,y_pred):
  print("-!!!!!!!!!!!!!")
  @flow.global_function(type="train")
  def test_job(
      images: tp.Numpy.Placeholder((10, 256, 256, 3), dtype=flow.float32),
      target: tp.Numpy.Placeholder((10, 64, 64, 17), dtype=flow.float32),
      target_weight: tp.Numpy.Placeholder((10, 17, 1), dtype=flow.float32),
      y_pred: tp.Numpy.Placeholder((10,64,64,17), dtype=flow.float32),
      ) -> Tuple[tp.Numpy, tp.Numpy, tp.Numpy]:

      return images,y_pred, target

  images,y_pred, target = test_job(images,target,target_weight,y_pred)
  return y_pred.shape
  
if __name__ == "__main__":
    
    images = np.random.uniform(-10, 10, (10, 256, 256, 3)).astype(np.float32)
    target = np.random.uniform(-10, 10, (10, 64, 64, 17)).astype(np.float32)
    target_weight = np.random.uniform(-10, 10, (10, 17, 1)).astype(np.float32)
    y_pred = np.random.uniform(-10, 10, (10,64,64,17)).astype(np.float32)
    print(images.dtype, target.dtype, target_weight.dtype)
    print(images.shape, target.shape, target_weight.shape)
    outputs = metric(images,target,target_weight,y_pred)
    print(outputs)

**Comment by leaves-zwx** [comment]
```
import oneflow as flow
import numpy as np


@flow.global_function(type='predict')
def identity(x: flow.typing.Numpy.Placeholder(shape=(2, 5), dtype=flow.float32)) -> flow.typing.Numpy:
    return flow.identity(x)


if __name__ == "__main__":
    x = np.random.rand(2, 5).astype(np.float32)
    y = identity(x)
    print("x:", x)
    print("y:", y)
```

运行这段最简单的代码示例看看可以跑通吗？ @liuao520

**Comment by liuao520** [comment]
可以  这里的type='predict'都是可以的
[test](https://github.com/liuao520/test/blob/main/loss_test.py)
这是我写的一个小的  test ,简单的numpy数据传入  相同的train问题
相关loss均在 
可以帮我看看吧

**Comment by JiaqingFu** [comment]
self 不能被识别为 global_function 的正常参数
