### ISSUE TITLE
flow.math.argmax

### ISSUE THREAD

**Issue by 15168387900** [Oneflow-Inc/oneflow#3963]
更新到0.3.1版本后报了这样的错误：
`F1202 13:51:36.058085   720 argmax_kernel.cu:81] Check failed: err : invalid device function (98) `

**Comment by jackalcooper** [comment]
请问cuda版本是？

**Comment by 15168387900** [comment]
> 请问cuda版本是？

cuda版本为10.1

**Comment by jackalcooper** [comment]
拿0.3.1的包尝试复现，argmax 的单元测试 (`oneflow/python/test/ops/test_argmax.py`) 可以运行

nvidia-smi 的结果：
```
| NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.1     |
```
安装命令：
```
python3 -m pip install --find-links https://release.oneflow.info oneflow_cu101==0.3.1 --user
```
可以提供一下你安装的命令，nvidia-smi 等信息吗

**Comment by 15168387900** [comment]
> 拿0.3.1的包尝试复现，argmax 的单元测试 (`oneflow/python/test/ops/test_argmax.py`) 可以运行
> 
> nvidia-smi 的结果：
> 
> ```
> | NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.1     |
> ```
> 
> 安装命令：
> 
> ```
> python3 -m pip install --find-links https://release.oneflow.info oneflow_cu101==0.3.1 --user
> ```
> 
> 可以提供一下你安装的命令，nvidia-smi 等信息吗

我把版本升到了0.3.2似乎就没有这样的问题了

nvidia-smi 结果：

`| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |`

我之前用的安装命令：

`python3 -m pip install --find-links https://oneflow-staging.oss-cn-beijing.aliyuncs.com/branch/master/index.html oneflow_cu101 --user`

（但现在用这个指令已经是下载0.3.2版本了）
