### ISSUE TITLE
有和.to()实现一样功能的算子吗

### ISSUE THREAD

**Issue by drjak-brown** [Oneflow-Inc/oneflow#3966]
遇到了一段代码
            if self.weight_maskUpdater.type() != input.type():
                self.weight_maskUpdater = self.weight_maskUpdater.to(input) 
要求保持self.weight_maskUpdater的type类型和input要相同
有和.to（）实现一样功能的算子吗

**Comment by jackalcooper** [comment]
`oneflow.cast` 可以满足需求吗

**Comment by drjak-brown** [comment]
cast 确实可以改变dtype，但是python的type()方法对blob不适用，需要知道blob中的数据类型，但是测试时就会报错AttributeError: 'LazyConsistentBlob' object has no attribute 'type'

**Comment by drjak-brown** [comment]
> `oneflow.cast` 可以满足需求吗

cast 确实可以改变dtype，但是python的type()方法对blob不适用，需要知道blob中的数据类型，但是测试时就会报错AttributeError: 'LazyConsistentBlob' object has no attribute 'type'

**Comment by daquexian** [comment]
> cast 确实可以改变dtype，但是python的type()方法对blob不适用，需要知道blob中的数据类型，但是测试时就会报错AttributeError: 'LazyConsistentBlob' object has no attribute 'type'

blob 有 dtype 这个属性，可以使用 blob.dtype 获取数据类型

**Comment by drjak-brown** [comment]
> > cast 确实可以改变dtype，但是python的type()方法对blob不适用，需要知道blob中的数据类型，但是测试时就会报错AttributeError: 'LazyConsistentBlob' object has no attribute 'type'
> 
> blob 有 dtype 这个属性，可以使用 blob.dtype 获取数据类型
多谢
