### ISSUE TITLE
Implementation of 'Training Deep Nets with Sublinear Memory Cost' in oneflow framework.

### ISSUE THREAD

**Issue by cydiachen** [Oneflow-Inc/oneflow#3968]
Dear friends, 
I am curious that whether it is possible for oneflow to implement the 'sublinear memory cost' operations to save gpu memory costs. I will be grateful if the framework supports this feature.

**Comment by chengtbf** [comment]
Thank you very much for your advice! We have been discussing the design and implementation of  'sublinear memory cost' optimization several days ago. We should have a first version in the next few days.
