### ISSUE TITLE
3D卷积网络无法拟合，loss降了一会儿就开始上下浮动

### ISSUE THREAD

**Issue by ximu1211** [Oneflow-Inc/oneflow#3982]
请问是什么原因，base_lr为0.0003，优化器为AdamW，loss在第二个epoch开始就会开始无法下降，想要加大学习率训练时交叉熵损失函数会碰到nan值，用flow.math.clip_by_value(inputs,1e-10,1.0)限制0值时，loss虽然下降但是优化器又不会好好工作，现在不知道有什么解决方法

**Comment by MARD1NO** [comment]
有没有可能在你们的代码，部分混用了numpy的API导致反向传播不正确？ 

如果有相关API是用numpy来作的话，麻烦列一下使用的OP以及对应的代码位置

**Comment by ximu1211** [comment]
> 有没有可能在你们的代码，部分混用了numpy的API导致反向传播不正确？
> 
> 如果有相关API是用numpy来作的话，麻烦列一下使用的OP以及对应的代码位置

templist=[np.arange(0,t)+i for i in range(N) if i!=N//2]
        templist=np.expand_dims(templist,axis=0)
        neighbor_time_index=np.concatenate(
            templist,axis=0
        )
        neighbor_time_index=np.transpose(neighbor_time_index)
        neighbor_time_index=np.ndarray.flatten(neighbor_time_index)
   
        neighbor_time_index=np.int64(neighbor_time_index)

在网络中有部分是用如上的代码实现的，（由于缺少arange等相关算子）

**Comment by MARD1NO** [comment]
目前是有range算子的，`oneflow.range`，不过不支持浮点数，只支持整数。如果需要浮点数，可以配合乘除法进行拼凑

expand_dims， concat，transpose，flatten在oneflow都有对应的API，这部分应该是完全可以在oneflow内部实现的。

如果遇到浮点数range困难，你可以把示例数据发下，我们看下如何拼

**Comment by ximu1211** [comment]
> 目前是有range算子的，`oneflow.range`，不过不支持浮点数，只支持整数。如果需要浮点数，可以配合乘除法进行拼凑
> 
> expand_dims， concat，transpose，flatten在oneflow都有对应的API，这部分应该是完全可以在oneflow内部实现的。
> 
> 如果遇到浮点数range困难，你可以把示例数据发下，我们看下如何拼

可以尝试，但是我认为不是这个造成的原因，因为这是几个卷积核中的一种当中的代码，在其它方法中没有混用的情况，即使没有用该卷积核，依然存在loss无法下降（上下浮动）的情况。

**Comment by MARD1NO** [comment]
有没有可能尝试Momentum优化器，并加大学习率呢？

之前你提过小数据集上能收敛，能否给出小数据集和大数据集各自的量级是多少。

另外Loss无法下降是多少个epoch的情况？如果条件允许，可以放着多跑几十个Epoch试试

**Comment by ximu1211** [comment]
> 有没有可能尝试Momentum优化器，并加大学习率呢？
> 
> 之前你提过小数据集上能收敛，能否给出小数据集和大数据集各自的量级是多少。
> 
> 另外Loss上下浮动是多少个epoch的情况？如果条件允许，可以放着多跑几十个Epoch试试

可以考虑尝试一下这个优化器。

**Comment by xunhen** [comment]
你好，我与遇到同样的问题。在我从tensorflow上将yolo装换到oneflow时，出现loss无法下降的问题。在tensorflow上从scratch开始训练几个epoch就可以得到比较好的检查效果。但是在oneflow上loss却表示出值很大，无法收敛（或者说是收敛到一个比较大的值）。
在我尝试值训练8张图片时，oneflow上转换的yolo是可以收敛的，但是全部8000张图片放入训练，却无法收敛。

**Comment by yuanms2** [comment]
这个问题我们复现过吗？

**Comment by xunhen** [comment]
> 这个问题我们复现过吗？

复现是说什么意思？你最后解决了吗

**Comment by yuanms2** [comment]
复现的意思是，我们重现过这个问题吗。 我也想问，是否已解决了。

**Comment by xunhen** [comment]
> 复现的意思是，我们重现过这个问题吗。 我也想问，是否已解决了。

我目前就是卡到上述无法收敛的情况？

**Comment by xunhen** [comment]
> 请问是什么原因，base_lr为0.0003，优化器为AdamW，loss在第二个epoch开始就会开始无法下降，想要加大学习率训练时交叉熵损失函数会碰到nan值，用flow.math.clip_by_value(inputs,1e-10,1.0)限制0值时，loss虽然下降但是优化器又不会好好工作，现在不知道有什么解决方法

楼主，可以问一下最后是怎么解决的吗

**Comment by simonJJJ** [comment]
@xunhen bug很可能出现在batchnorm, anchor, gt matching, nms上, 可以从这些方向去debug.
