### ISSUE TITLE
mlp_mnist.py stuck

### ISSUE THREAD

**Issue by lmatz** [Oneflow-Inc/oneflow#4070]
```
 Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0103 21:17:47.181195 20165 global.h:36] NewGlobal 14cudaDeviceProp
I0103 21:17:47.201279 20165 global.h:36] NewGlobal N7oneflow7EnvDescE
I0103 21:17:47.201393 20165 global.h:36] NewGlobal N7oneflow10CtrlServerE
I0103 21:17:47.203307 20165 ctrl_server.cpp:53] CtrlServer listening on 0.0.0.0:45549
I0103 21:17:47.203423 20165 global.h:36] NewGlobal N7oneflow10CtrlClientE
I0103 21:17:47.210516 20165 ctrl_client.cpp:234] LoadServer 127.0.0.1 Failed at 0 times error_code 14 error_message failed to connect to all addresses
I0103 21:17:57.216329 20165 ctrl_client.cpp:234] LoadServer 127.0.0.1 Failed at 1 times error_code 14 error_message failed to connect to all addresses
I0103 21:18:07.221289 20165 ctrl_client.cpp:234] LoadServer 127.0.0.1 Failed at 2 times error_code 14 error_message failed to connect to all addresses
I0103 21:18:21.578745 20165 ctrl_client.cpp:234] LoadServer 127.0.0.1 Failed at 3 times error_code 14 error_message failed to connect to all addresses
```

The script is stuck before/during entering the `train_job` function?
Built from source.

**Comment by yuanms2** [comment]
It seems to be a networking issue.  Oneflow can not connect to itself through the loopback connection.

Did you run the script in a docker?

**Comment by chengtbf** [comment]
If you use the proxy setting in your `./bashrc`: 
```bash
export all_ proxy = xxx.xxx
```
Please try to replace it with uppercase：
```bash
export ALL_PROXY = xxx.xxx
export HTTP_PROXY = xxx.xxx
export HTTPS_PROXY = xxx.xxx
```

**Comment by lmatz** [comment]
> It seems to be a networking issue. Oneflow can not connect to itself through the loopback connection.
> 
> Did you run the script in a docker?

It is not in the docker. 

> If you use the proxy setting in your `./bashrc`:
> 
> ```shell
> export all_proxy = xxx.xxx
> ```
> 
> Please try to replace it with uppercase：
> 
> ```shell
> export ALL_PROXY = xxx.xxx
> export HTTP_PROXY = xxx.xxx
> export HTTPS_PROXY = xxx.xxx
> ```


It works like a charm! Didn't expect this. Thanks!

**Comment by yuanms2** [comment]
Users frequently meet with such issues. Should we disable the ctrlclient, ctrlserver in single-node setting?

**Comment by zte-tcb** [comment]
> If you use the proxy setting in your `./bashrc`:
> 
> ```shell
> export all_proxy = xxx.xxx
> ```
> 
> Please try to replace it with uppercase：
> 
> ```shell
> export ALL_PROXY = xxx.xxx
> export HTTP_PROXY = xxx.xxx
> export HTTPS_PROXY = xxx.xxx
> ```

this works!
