### ISSUE TITLE
check_point.save

### ISSUE THREAD

**Issue by ruizewang** [Oneflow-Inc/oneflow#4100]
请问 check_point.save是异步操作嘛？我经常发现check_point.save模型还没保存完，代码就已经继续往后执行了。有没有什么方法能避免这种情况呢?
想要实现的是等待保存完模型，然后再执行后面的代码

**Comment by daquexian** [comment]
建议升级到 0.3.1 或者更高版本，已经变成同步的了

不能升级的话，checkpoint.save 之后运行一句 flow.sync_default_session() 会等待 save 完成

**Comment by ruizewang** [comment]
已解决，感谢回复~
