### ISSUE TITLE
Ubuntu 18.04, Cuda 10.2, cudnn 7.5 编译失败

### ISSUE THREAD

**Issue by BBuf** [Oneflow-Inc/oneflow#4101]
编译失败的日志:

[ 27%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/common/error.cfg.cpp.o
[ 27%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/vm/instruction.cfg.cpp.o
[ 27%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/eager/eager_symbol.cfg.cpp.o
[ 27%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/job/job_conf.cfg.cpp.o
[ 27%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/job/placement.cfg.cpp.o
[ 27%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/operator/op_conf.cfg.cpp.o
[ 27%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/common/shape.cfg.cpp.o
[ 27%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/record/image.cfg.cpp.o
[ 27%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/record/record.cfg.cpp.o
[ 27%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/job/resource.cfg.cpp.o
[ 27%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/register/logical_blob_id.cfg.cpp.o
[ 27%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/register/tensor_slice_view.cfg.cpp.o
[ 27%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/common/range.cfg.cpp.o
[ 28%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/framework/user_op_conf.cfg.cpp.o
[ 28%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/framework/user_op_attr.cfg.cpp.o
[ 28%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/job/sbp_parallel.cfg.cpp.o
[ 28%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/graph/boxing/collective_boxing.cfg.cpp.o
[ 28%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/register/blob_desc.cfg.cpp.o
[ 28%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/register/pod.cfg.cpp.o
[ 28%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/job/scope.cfg.cpp.o
[ 28%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/job/mirrored_parallel.cfg.cpp.o
[ 28%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/operator/op_attribute.cfg.cpp.o
[ 28%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/register/batch_axis_signature.cfg.cpp.o
[ 28%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/operator/arg_modifier_signature.cfg.cpp.o
[ 28%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/job/blob_lifetime_signature.cfg.cpp.o
[ 28%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/job/parallel_signature.cfg.cpp.o
[ 29%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/eager/eager_instruction.cfg.cpp.o
[ 29%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/job/cluster_instruction.cfg.cpp.o
[ 29%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/job/initializer_conf.cfg.cpp.o
[ 29%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/job/regularizer_conf.cfg.cpp.o
[ 29%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/job/learning_rate_schedule_conf.cfg.cpp.o
[ 29%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/common/cfg_reflection_test.cfg.cpp.o
[ 29%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/common/data_type.cfg.cpp.o
[ 29%] Building CXX object CMakeFiles/of_cfgobj.dir/oneflow/core/common/device_type.cfg.cpp.o
[ 29%] Linking CXX static library libof_cfgobj.a
[ 29%] Built target of_cfgobj
[ 29%] Built target of_git_version_create_dir
[ 29%] Generating of_git_version/_version.cpp
[ 29%] Built target of_git_version
[ 29%] Building NVCC (Device) object CMakeFiles/of_ccobj.dir/oneflow/user/kernels/of_ccobj_generated_where_kernel_util.cu.o
Segmentation fault (core dumped)
CMake Error at of_ccobj_generated_where_kernel_util.cu.o.cmake:279 (message):
  Error generating file
  /home/pc/bbuf_project/OneFlow/oneflow-src/build/CMakeFiles/of_ccobj.dir/oneflow/user/kernels/./of_ccobj_generated_where_kernel_util.cu.o

CMakeFiles/of_ccobj.dir/build.make:588: recipe for target 'CMakeFiles/of_ccobj.dir/oneflow/user/kernels/of_ccobj_generated_where_kernel_util.cu.o' failed
make[2]: *** [CMakeFiles/of_ccobj.dir/oneflow/user/kernels/of_ccobj_generated_where_kernel_util.cu.o] Error 1
CMakeFiles/Makefile2:107: recipe for target 'CMakeFiles/of_ccobj.dir/all' failed
make[1]: *** [CMakeFiles/of_ccobj.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Flowingsun007** [comment]
您好，刚刚我拉取了master上的最新oneflow代码，在本地Ubuntu18.04尝试了是可以正常编译的，我的系统配置如下：
```shell
Cuda Version: release 10.2, V10.2.89
Cudnn:v7.6.5
Driver Version: 450.80.02
cmake version 3.14.0
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
```
请尝试清空cmake相关文件，譬如：
```shell
rm -rf CTestTestfile.cmake cmake_install.cmake  CMakeCache.txt  cached_filename_lists CMakeFiles
```
然后再尝试重新编译安装：
```shell
cmake .. -DTHIRD_PARTY_MIRROR=aliyun  -DCMAKE_BUILD_TYPE=Release
make -j$(nproc)
make pip_install
```

**Comment by BBuf** [comment]
`
Cuda Version: release 10.2, V10.2.89
Cudnn:v7.6.5
Driver Version: 440.100
cmake version 3.14.4
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)/gcc version 4.5.0 (Ubuntu 4.5.0-3ubuntu1~18.04)
`
然后

`
mkdir build
cmake .. -DTHIRD_PARTY_MIRROR=aliyun  -DCMAKE_BUILD_TYPE=Release
make
`

仍然是报这个错误, 编译CPU版本可以成功, 我现在尝试一下PIP安装看看不能成功调用

**Comment by BBuf** [comment]
我试了一下pip安装cuda10.2的oneflow，可以成功调用gpu训练模型，目前只怀疑最后一个问题了，就是cmake的版本，后续再试试。
