### ISSUE TITLE
AttributeError: 'google.protobuf. pyext._message.RepeatedCompositeCo’ object has no attribute 'append。

### ISSUE THREAD

**Issue by BBuf** [Oneflow-Inc/oneflow#4123]
成功编译了oneflow cpu版本源码，可以正常`import oneflow`，但是运行单测python脚本如`oneflow\oneflow\python\test\ops\test_relu6.py`时报错如下：

![图片](https://user-images.githubusercontent.com/35585791/104794963-16b53100-57e6-11eb-8ee3-b0f15d2ea46c.png)

**Comment by BBuf** [comment]
补充一下，我的编译选项是：

**Comment by yuanms2** [comment]
貌似是eager 执行的问题

**Comment by daquexian** [comment]
窝之前遇到过这个问题，可能是 pip 安装 protobuf 过程中发生了什么异常。pip 卸载掉 protobuf 再重新安装就好了

**Comment by BBuf** [comment]
已按照大老师方法解决。再贴一下报错的文字然后关闭这个issue。
