### ISSUE TITLE
Pool OP关于ceil_mode问题

### ISSUE THREAD

**Issue by BBuf** [Oneflow-Inc/oneflow#4307]
在做onnx_to_oneflow的pr时，发现oneflow的max pool op和pytorch未对齐，当pytorch模型这样调用Pooling时：
`self.pool = nn.MaxPool2d(kernel_size=3, stride=2, ceil_mode=False, padding=0)`

oneflow和pytorch的输出维度和特征值就会不一致，这是因为这个参数设置为true，在pytorch中计算输出shape是向上取整，而oneflow目前只支持输出shape向下取整。其它的pool相关的op比如avg pool开发者也需要check。

![图片](https://user-images.githubusercontent.com/35585791/109636225-49dd3500-7b86-11eb-8587-5b8277584498.png)

![图片](https://user-images.githubusercontent.com/35585791/109636243-4f3a7f80-7b86-11eb-8eb5-618f50402100.png)

**Comment by leaves-zwx** [comment]
是的，ceil_mode 这个问题是一直存在的，之前没有人手去解决。

除了这个问题外，oneflow 的 pool 还不支持 dilation，因为之前 gpu 上的实现都是直接调用的 cudnn，cudnn 的接口不支持 dilation。

后来 @Flowingsun007 在 #4053 里面也测试过，目前 pytorch 的 pool (它手动实现的版本) 比 cudnn 版本是要快的，所以 pool 后面的实现都需要替换成手动实现的版本。
 
avg pool 和 max pool 的代码也需要整理统一一下，里面关于求 padding 的代码目前也很混乱，需要整理。

**Comment by BBuf** [comment]
好的。
