### ISSUE TITLE
如何启用OneFlow中的自动并行功能？

### ISSUE THREAD

**Issue by zzqq2199** [Oneflow-Inc/oneflow#4365]
尊敬的开发者：您好！
我在阅读了你们在[知乎上的技术分享](https://zhuanlan.zhihu.com/p/337851255)后，对里面提到的`实验证明了OneFlow这一套简洁的抽象（SBP + Actor）在支持各种模型并行、混合并行、流水并行自动并行、ZeRO等方面是如此的简单高效`中的**自动并行**很感兴趣，但是没有找到相应的代码demo，也没有在文档中找到API接口。
请问你们能给一个OneFlow+自动并行的demo链接吗？

**Comment by Yipeng1994** [comment]
你好, 感谢你对我们oneflow的兴趣。
目前我们oneflow关于自动并行的代码还未完全公开, 相关的技术细节请留意下半年的分享以及新版本发布。
如果迫切希望了解技术原理, 也可以查询oneflow的专利《用于分布式数据处理的并行决策系统及其方法》。

祝好

**Comment by zzqq2199** [comment]
谢谢您的回复，我会持续关注的！
