### ISSUE TITLE
九合创投王啸对话一流科技袁进辉：深耕基础研

### ISSUE THREAD

**Issue by MaoXianXin** [Oneflow-Inc/oneflow#4411]
这篇文章有问题，看起来像个复读机，在这里反馈下这个问题: https://www.oneflow.org/a/share/new/39.html
自被称为 AI 元年的 2017 年至今，AI 始终是一个非常热门的话题。当下 AI 仍然以每年 45% 的高复合增长率而增长。根据权威机构报告显示，预计到 2030 年，人工智能将推动全球 GDP 增长 14% 。到 2035 年，将推动全球生产效率提高 40% 。AI 已经成为推动经济的新增长引擎。自被称为 AI 元年的 2017 年至今，AI 始终是一个非常热门的话题。当下 AI 仍然以每年 45% 的高复合增长率而增长。根据权威机构报告显示，预计到 2030 年，人工智能将推动全球 GDP 增长 14% 。

到 2035 年，将推动全球生产效率提高 40% 。AI 已经成为推动经济的新增长引擎。自被称为 AI 元年的 2017 年至今，AI 始终是一个非常热门的话题。当下 AI 仍然以每年 45% 的高复合增长率而增长。根据权威机构报告显示，预计到 2030 年，人工智能将推动全球 GDP 增长 14% 。到 2035 年，将推动全球生产效率提高 40% 。AI 已经成为推动经济的新增长引擎。自被称为 AI 元年的 2017 年至今，AI 始终是一个非常热门的话题。当下 AI 仍然以每年 45% 的高复合增长率而增长。根据权威机构报告显示，预计到 2030 年，人工智能将推动全球 GDP 增长 14% 。到 2035 年，将推动全球生产效率提高 40% 。AI 已经成为推动经济的新增长引擎。自被称为 AI 元年的 2017 年至今，AI 始终是一个非常热门的话题。当下 AI 仍然以每年 45% 的高复合增长率而增长。根据权威机构报告显示，预计到 2030 年，人工智能将推动全球 GDP 增长 14%

**Comment by yuanms2** [comment]
谢谢反馈，我们看看

**Comment by yuanms2** [comment]
谢谢反馈，确实存在这个问题，是当时测试的文章没有删除所致，抱歉。

**Comment by MaoXianXin** [comment]
![image](https://user-images.githubusercontent.com/22192610/111115735-ffa17e00-859f-11eb-99a4-04376aa280b2.png)

这篇文章的图片是我这边的问题，还是网站后台的问题啊，链接: https://www.oneflow.org/a/share/jishuboke/59.html

**Comment by doombeaker** [comment]
> 这篇文章的图片是我这边的问题，还是网站后台的问题啊，链接: https://www.oneflow.org/a/share/jishuboke/59.html

感谢反馈，这个问题是我们之前引用的图片在cdn服务器上，cdn服务器失效后，图片就显示不了。这是我们的疏忽，不好意思。
相关图片地址正在紧急修复。

在修复前，您也可以通过
https://www.zhihu.com/org/oneflow-17/posts 查看内容一致的技术文章：

InsightFace：  https://zhuanlan.zhihu.com/p/352919555

**Comment by MaoXianXin** [comment]
![image](https://user-images.githubusercontent.com/22192610/111119624-5067a580-85a5-11eb-8f5b-838c6b8036b7.png)
还有个问题，感觉这里的两段内容重复了，虽然都是讲的分布式，但还是有点怪怪的感觉

**Comment by MaoXianXin** [comment]
https://www.oneflow.org/a/chanpin/oneflow/
上面的问题是这个链接

**Comment by MaoXianXin** [comment]
> > 这篇文章的图片是我这边的问题，还是网站后台的问题啊，链接: https://www.oneflow.org/a/share/jishuboke/59.html
> 
> 感谢反馈，这个问题是我们之前引用的图片在cdn服务器上，cdn服务器失效后，图片就显示不了。这是我们的疏忽，不好意思。
> 相关图片地址正在紧急修复。
> 
> 在修复前，您也可以通过
> https://www.zhihu.com/org/oneflow-17/posts 查看内容一致的技术文章：
> 
> InsightFace： https://zhuanlan.zhihu.com/p/352919555

好的，原来在知乎上也有文章啊，那方便很多了

**Comment by MaoXianXin** [comment]
![image](https://user-images.githubusercontent.com/22192610/111121471-a63d4d00-85a7-11eb-9bce-31aa6ca3e51f.png)
这个单词hardware写错了

![image](https://user-images.githubusercontent.com/22192610/111121529-bb19e080-85a7-11eb-9ded-7194cef20465.png)
这个是千人千面

略微有点强迫症，所以，，，，就都给你们反馈了

**Comment by MaoXianXin** [comment]
https://www.oneflow.org/a/chanpin/oneflow/
https://www.oneflow.org/a/chanpin/onebrain/
这两个链接对应上面的两个错别字问题

**Comment by MaoXianXin** [comment]
![image](https://user-images.githubusercontent.com/22192610/111121977-5743e780-85a8-11eb-872d-62cfe1ff5d00.png)
https://www.oneflow.org/a/jobs/
这个文字太小，看不清

**Comment by yuanms2** [comment]
非常感谢反馈，感到脸红

**Comment by MaoXianXin** [comment]
> 非常感谢反馈，感到脸红

没事，那我就把这个Issue给关闭了哈，就是看到一些有问题的地方，然后给你们反馈一下

**Comment by yuanms2** [comment]
> > 非常感谢反馈，感到脸红
> 
> 没事，那我就把这个Issue给关闭了哈，就是看到一些有问题的地方，然后给你们反馈一下

谢谢。我们加个联系方式。 请加微信：oneflowXZS  然后会推给我。
