### ISSUE TITLE
关于数据集加载的疑问

### ISSUE THREAD

**Issue by luozhouyang** [Oneflow-Inc/oneflow#4813]
`tf.data`可以加载大数据集（机器内存放不下），我想知道oneflow的数据集加载，也可以很方便地加载大数据集吗？

**Comment by chengtbf** [comment]
完全没问题。 OneFlow的数据加载、模型保存/加载 都是为超大规模设计的，使用OFRecord制作的数据集，是不限制其最大规模的，只要分布式集群的磁盘能装下就没问题。

OneFlow并不会将整个大数据集都同时、全部加载到内存中，事实上只会预加载**最近几个Batch**的数据，所以只要几个Batch的数据内存可以装下就没问题。对于分布式训练，每个设备都会有自己的data reader op来供给数据。

数据集加载可以参考文档：http://docs.oneflow.org/extended_topics/how_to_make_ofdataset.html

对于超大规模的数据集，可以制作多个part文件，比如从 part-0 到 part-256， 每个part存放数量相近的数据样例即可。 对于分布式训练，每个reader只会读自己段的part文件，不同的reader之间互不干扰。 数据的shuffle是在part内和part间做的，即使没有加载全部的数据也可以做到每个epoch都随机。

另外 我认为tf的模型保存文件 .ckpt 并不是为了超大规模的模型而设计的，因为超大模型可能总的模型大小要超过内存的大小，使用单个文件做分布式的模型加载和保存是会造成低效甚至会挂掉。OneFlow里的模型是一个目录，目录下每个子目录对应一个Variable， 分布式训练场景下不同的Variable会分别保存和加载，多文件的读写也保证了大模型checkpoint的效率。

参考： http://docs.oneflow.org/basics_topics/model_load_save.html

**Comment by luozhouyang** [comment]
了解了，多谢！
