### ISSUE TITLE
flow.Tensor(x.transpose(*)).numpy() != x.transpose(*)

### ISSUE THREAD

**Issue by yayeoCddy** [Oneflow-Inc/oneflow#5330]
wrong codes as following:
- In eager mode:
```python
import numpy as np
import oneflow.experimental as flow
from oneflow.python.framework.tensor import Tensor
flow.enable_eager_execution()
x = np.random.random((1, 256, 256, 3)).astype(np.float32)
x = x.transpose(0, 3, 1, 2)
# x = np.ascontiguousarray(x, 'float32')
x_tensor = flow.Tensor(x).numpy()
print((x==x_tensor).all())
```
Result is: False

- In lazy mode:
```python
import oneflow as flow
import oneflow.typing as tp
import numpy as np
@flow.global_function()
def test(x: tp.Numpy.Placeholder((4, 3, 2, 5)))->tp.Numpy:
    return x
arr = np.random.randn(3, 4, 2, 5).astype(np.float32)
arr = arr.transpose(1, 0, 2, 3)
# arr = np.ascontiguousarray(arr, 'float32')
res = test(arr)
print((arr==res).all())
```
Result is: False

But add `x = np.ascontiguousarray(x, 'float32')`, everything is ok

**Comment by Flowingsun007** [comment]
这块其实是设计没对齐，pytorch的tensor和numpy类似是有stirde的设计。
- pytorch从ndarray构造tensor时，对numpy array的stride做了处理，基于同样的stride生成的tensor，
```c++
int ndim = PyArray_NDIM(array);
auto sizes = to_aten_shape(ndim, PyArray_DIMS(array));
auto strides = to_aten_shape(ndim, PyArray_STRIDES(array));
...
```
所以无论在构造之前对ndarray做了啥transpose或改变内存存储方式的操作，构造tensor时都会做到对齐，所以不用手动ascontiguousarray；
- 我们的tensor是暂时没有stirde，所以需要手动ascontiguousarray，否则构造出的tensor还是和transpose之前的ndarray一样的排列
- stride的优势：在做类似reshape,transpose,permute.view等这样改变视图但不改变tensor实际存储内存的时候，省了copy整个tensor内存的行为，直接返回不同stride就OK

一个比较临时的方案是我们在构造的时候判断一下numpy array是不是连续的，不连续我们让它连续就行了by@BBuf

**Comment by JiaqingFu** [comment]
实测bug已经解决，赞的
