### ISSUE TITLE
无法创建一个空的 tensor

### ISSUE THREAD

**Issue by puchapu** [Oneflow-Inc/oneflow#5399]
在一些算子中可能需要返回一个空的 tensor，如 `nonzero` 、`argwhere`。
但在执行 `flow.tensor(np.array([]))` 以及 `flow.tensor([])` 均会报以下错误
![image](https://user-images.githubusercontent.com/35329085/124529585-7e674300-de3d-11eb-9720-75e390c112bf.png)

**Comment by wyg1997** [comment]
这个特性在上面的PR中已经支持，可以再试一下
