### ISSUE TITLE
logical_slice_assign Op缺少后向

### ISSUE THREAD

**Issue by wyg1997** [Oneflow-Inc/oneflow#5416]
在搬模型中有时要直接原地对权重赋值，会用到 logical_slice_assign functional（对应Pytorch底层的CopySlices Op），例如：

```python
for param in self.parameters:
    param[:] -= lr * param.grad / batch_size
```

但由于 logical_slice_assign 没有后向kernel，目前这种写法已经失效，实际使用时会报 `gradient function not found` 错误。

等inplace的PR #5204 合并后这个需求可以先用inplace op替代，后续有空再支持，这里先记录一下。

**Comment by hjchen2** [comment]
可以在注册logical_slice_assign这个op时，使用REGISTER_NO_GRAD_USER_OP代替REGISTER_USER_OP，这样就不会报错了

**Comment by hjchen2** [comment]
其他没有后向的op我基本都已经改了，logical_slice_assign和logical_slice被漏掉了

**Comment by wyg1997** [comment]
> 可以在注册logical_slice_assign这个op时，使用REGISTER_NO_GRAD_USER_OP代替REGISTER_USER_OP，这样就不会报错了

不是报错的问题，这个Op应该是有后向的，报错应该保留。目前就只支持 `with flow.no_grad()` 这种用法。

**Comment by wyg1997** [comment]
master 已经合并 logical_slice 和 slice，支持了后向
