### ISSUE TITLE
宏展开超过限制大小 512

### ISSUE THREAD

**Issue by puchapu** [Oneflow-Inc/oneflow#5553]
开发 fmod kernel [[PR](https://github.com/Oneflow-Inc/oneflow/pull/5404)] 遇到一个宏展开限制问题，就是在新增一个二元 op 的 kernel时，在 `oneflow/user/ops/math_binary_broadcast_seq.h` 和 `oneflow/core/ndarray/binary_func.h` 里分别做了下图的修改。
![image (5)](https://user-images.githubusercontent.com/35329085/126447748-5161bcf3-f9c8-4aed-afe2-5262ac814c48.png)

但是在编译的时候会报错。定位到是 `oneflow/core/ndarray/ndarray_apply_broadcast_binary_core.cpp` 第 41 行的宏没办法展开。
![image (4)](https://user-images.githubusercontent.com/35329085/126447807-66d48115-0ab9-4de6-879c-ef9f250c9738.png)

应该是 `oneflow/core/common/preprocessor_internal.h` 限制了这个宏展开的大小为 512，原来 14 个算子，每个 36 种情况。现在新增一个的话 15*36=540 就大于 512 了。

请问这种情况要怎么解决呢？

**Comment by Flowingsun007** [comment]
你找到322行的代码，把`<?php $limit = 512; for ($i = 0; $i < $limit; ++$i) {?>` 中的512换成更大的数，譬如576试试

**Comment by lixinqi** [comment]
把LOGICAL_BINARY_FUNC_NAME_SEQ拆解成LOGICAL_BINARY_FUNC_NAME_SEQ0 LOGICAL_BINARY_FUNC_NAME_SEQ1 LOGICAL_BINARY_FUNC_NAME_SEQ2 ...
在超限的使用处不断调用小的宏。

**Comment by lixinqi** [comment]
512次宏展开已经很恐怖，那个文件是在不能再长了。只好想办法在外部解决问题。

**Comment by puchapu** [comment]
嗯嗯，好的
