### ISSUE TITLE
是否需要将flow.Tensor对整数参数的处理对齐到torch？

### ISSUE THREAD

**Issue by tea321000** [Oneflow-Inc/oneflow#5573]
oneflow目前具有Tensor和tensor两个接口，其中Tensor是未完全实例化的，根据op来决定是mirror还是consistent，而tensor是完全实例化的。

当Tensor的参数是整数的时候，容易把数值误认为是Shape而出现一些不可预料的结果，必须改为小写的tensor接口才能得到预期的结果。但我们目前大多数程序都是使用的Tensor接口，且并未明确说明两者的区别，用户容易建立flow.Tensor==torch.tensor的印象，会对程序的迁移造成一定的麻烦。是否可以考虑在参数的处理上对齐torch，或者显式地与用户说明这两个接口的区别以免混淆？

以下是调试程序时遇到的一些情况：

![image](https://user-images.githubusercontent.com/19517302/126625335-25763da4-950a-4733-8c32-1d803a7f7b4f.png)

![image](https://user-images.githubusercontent.com/19517302/126625308-0ea863dd-bcf7-4306-a7cc-917a6e8a0c8e.png)

**Comment by chengtbf** [comment]
> 但我们目前大多数程序都是使用的Tensor接口，且并未明确说明两者的区别，用户容易建立flow.Tensor==torch.tensor的印象，会对程序的迁移造成一定的麻烦。是否可以考虑在参数的处理上对齐torch，或者显式地与用户说明这两个接口的区别以免混淆？

非常好的建议 ！  如果是 参数的处理上 对齐 torch，具体是指哪个呢？ flow.Tensor 的传参究竟是怎样的呢

**Comment by tea321000** [comment]
> > 但我们目前大多数程序都是使用的Tensor接口，且并未明确说明两者的区别，用户容易建立flow.Tensor==torch.tensor的印象，会对程序的迁移造成一定的麻烦。是否可以考虑在参数的处理上对齐torch，或者显式地与用户说明这两个接口的区别以免混淆？
> 
> 非常好的建议 ！ 如果是 参数的处理上 对齐 torch，具体是指哪个呢？ torch.Tensor 的传参是怎样的呢，我在官网的文档里没有扎到。
> 
> https://pytorch.org/docs/master/tensors.html?highlight=tensor#torch.Tensor

整数用Tensor会被认为是shape，而numpy, list, tuple类型用Tensor会被认为是数据。比如：
```python
>>> test_int = 3
>>> test_list = [4, 5]
>>> test_tuple = (7, 0)
>>> test_tuple2 = (0, 7, 0)
>>> for input in (test_int, test_list, test_tuple, test_tuple2):
...     print("out_of_T",flow.Tensor(input))
...     print("out_of_t",flow.tensor(input))
...     print("out_pt", torch.tensor(input), torch.tensor(input).dtype)
... 
out_of_T tensor([1.e-44, 0.e+00, 0.e+00], dtype=oneflow.float32)
out_of_t tensor([3], dtype=oneflow.int64)
out_pt tensor(3) torch.int64
out_of_T tensor([4., 5.], dtype=oneflow.float32)
out_of_t tensor([4, 5], dtype=oneflow.int64)
out_pt tensor([4, 5]) torch.int64
out_of_T tensor([7., 0.], dtype=oneflow.float32)
out_of_t tensor([7, 0], dtype=oneflow.int64)
out_pt tensor([7, 0]) torch.int64
out_of_T tensor([0., 7., 0.], dtype=oneflow.float32)
out_of_t tensor([0, 7, 0], dtype=oneflow.int64)
out_pt tensor([0, 7, 0]) torch.int64
```
可以看到flow.tensor与torch.tensor才是对齐的，而flow.Tensor的输出在数据类型以及数值等方面并不一定正确。

对于一些不太寻常的输入，Tensor会由于误认Size而出错；对于空数组， Tensor和tensor都会报错：
```python
>>> flow.tensor(0)
tensor([0], dtype=oneflow.int64)
>>> flow.tensor(0.)
tensor([0.], dtype=oneflow.float32)
>>> torch.tensor(0), torch.tensor(0).dtype
(tensor(0), torch.int64)
>>> torch.tensor(0.), torch.tensor(0.).dtype
(tensor(0.), torch.float32)
>>> flow.Tensor(0)
F0723 14:12:44.831919  4203 empty_kernel.cpp:32] Check failed: elem_cnt > 0 (0 vs. 0) 
...
Aborted (core dumped)

>>> torch.tensor([])
tensor([])
>>> flow.tensor([])
F0723 14:29:20.108641  5102 empty_kernel.cpp:32] Check failed: elem_cnt > 0 (0 vs. 0)
Aborted (core dumped)
>>> flow.Tensor([])
F0723 14:31:28.969350  6130 empty_kernel.cpp:32] Check failed: elem_cnt > 0 (0 vs. 0)
Aborted (core dumped)

```

**Comment by wyg1997** [comment]
flow.tensor和torch.tensor都是把输入当作数据来创建Tensor，这一接口是对齐的。

flow.Tensor和torch.Tensor 的输入以下几种情况：

1. 输入为numpy，这时会把numpy当作数据。
  ```python
a = np.array([2, 3], dtype=int)
flow.Tensor(a)  # tensor([2., 3.], dtype=oneflow.float32)
torch.Tensor(a)  # tensor([2., 3.])
  ```
2. 输入为tuple或list，这时也会当成是数据。
  ```python
flow.Tensor([2, 3, 4])  # tensor([2., 3., 4.], dtype=oneflow.float32)
torch.Tensor([2, 3, 4])  # tensor([2., 3., 4.])
  ```

3. 输入为多个整数，这时会把这些整数打包，当作Tensor的Size。
  ```python
flow.Tensor(2, 3)  # tensor([[0., 0., 0.], [0., 0., 0.]], dtype=oneflow.float32)
torch.Tensor(2, 3)  # tensor([[2.9427e-44, 0.0000e+00, 4.2039e-44], [0.0000e+00, 0.0000e+00, 0.0000e+00]])
  ```

4. 输入为其它Tensor，这个就是用其它Tensor的属性来构建新Tensor，和上述问题无关，就不讨论了。

可以看到 flow.Tensor 和 torch.Tensor 这些行为是对齐的，只是数据初始化的方式可能有一些区别。

上述说输入的shape比较特殊时（shape.elements() == 0），这个是个特殊的机制，我们正在支持，可以关注一下 #5429 这个PR。

其他还有什么没有对齐的情况呢？还麻烦进一步说明一下。

**Comment by tea321000** [comment]
> flow.tensor和torch.tensor都是把输入当作数据来创建Tensor，这一接口是对齐的。
> 
> flow.Tensor和torch.Tensor 的输入以下几种情况：
> 
> 1. 输入为numpy，这时会把numpy当作数据。
> 
> ```python
> a = np.array([2, 3], dtype=int)
> flow.Tensor(a)  # tensor([2., 3.], dtype=oneflow.float32)
> torch.Tensor(a)  # tensor([2., 3.])
> ```
> 
> 1. 输入为tuple或list，这时也会当成是数据。
> 
> ```python
> flow.Tensor([2, 3, 4])  # tensor([2., 3., 4.], dtype=oneflow.float32)
> torch.Tensor([2, 3, 4])  # tensor([2., 3., 4.])
> ```
> 
> 1. 输入为多个整数，这时会把这些整数打包，当作Tensor的Size。
> 
> ```python
> flow.Tensor(2, 3)  # tensor([[0., 0., 0.], [0., 0., 0.]], dtype=oneflow.float32)
> torch.Tensor(2, 3)  # tensor([[2.9427e-44, 0.0000e+00, 4.2039e-44], [0.0000e+00, 0.0000e+00, 0.0000e+00]])
> ```
> 
> > 如果输入是浮点数的话，torch和oneflow都会报错
> > ```
> >  flow.Tensor(2.0, 3.0)  # TypeError: new() received an invalid combination of arguments
> >  torch.Tensor(2.0, 3.0)  # TypeError: new() received an invalid combination of arguments ......
> > ```
> 
> 1. 输入为其它Tensor，这个就是用其它Tensor的属性来构建新Tensor，和上述问题无关，就不讨论了。
> 
> 可以看到 flow.Tensor 和 torch.Tensor 这些行为是对齐的，只是数据初始化的方式可能有一些区别。
> 
> 上述说输入的shape比较特殊时（shape.elements() == 0），这个是个特殊的机制，我们正在支持，可以关注一下 #5429 这个PR。
> 
> 其他还有什么没有对齐的情况呢？还麻烦进一步说明一下。

在torch中，Tensor是所有张量的类，Tensor()是类的实例化，tensor()是以参数构造Tensor的一个函数，这些方面oneflow确实是对齐的。

但torch中的Tensor不包含根据op来决定是mirror还是consistent这一特性，这就导致了在torch的程序中基本都以使用tensor()而不是类实例化的Tensor()为主，而oneflow中可能因为考虑了这一点，程序中都使用大写的Tensor()，但并未对此进行说明。这会对不知道这一上下文的用户造成一定的困扰，不怎么关注底层实现的用户有可能分不清Tensor()和tensor()，直接当作torch.tensor()进行使用。我所关注的点在于是否需要把这一信息显式地告诉用户，让用户知道这一区别。

实现细节方面，```tensor_without_data = torch.Tensor()```这个实例化oneflow尚未支持，可能与pr尚未合并有关。

**Comment by wyg1997** [comment]
使用Tensor()还是tensor()接口都是个人喜好，oneflow没有做什么规定，只要接口用法对齐，用户可以随意选择，不会有的困扰。

**Comment by tea321000** [comment]
根据op来决定是mirror还是consistent这一特性，和使用 tensor() 还是 Tensor() 接口没有关系。Oneflow之前的第一个例子用了Tensor()接口，所以后面大都跟着用了:joy:
