### ISSUE TITLE
如何搭配kubeflow / kubernete使用

### ISSUE THREAD

**Issue by fzhan** [Oneflow-Inc/oneflow#5584]
是否需要在每个节点开启一个deployment，然后配置成服务呢？

没有在kubernete上的介绍，着急啊。

**Comment by xxmyjk** [comment]
1. 打包Docker镜像, 需要cuda/cudnn基础环境, 建议在nvidia-cuda基础镜像上打包
2. 配置启动命令, 多机多节点注意配置启动cmd为正确启动命令, 测试过程可以使用`sleep` 测试, 通过之后配置正确cmd
3. 小规模数据集可以直接打入镜像, 大规模数据集建议使用pvc或者nfs/ceph等csi完备的存储方案
4. kubernetes集群需要`nvidia-device-plugin`支持gpu调度, 并且对应节点配置默认`nvidia-container-runtime`
5. 可以基于deployment或statefulset, 建议使用statefulset, 避免网络发现的bootstrap问题(脚本启动需要预知各训练节点hostname/IP, 而hostname/IP需要在Pod启动之后才能获取, statefulset可以避免获取IP的问题)

其他:
- 简单测试建议直接使用daemonset分配Node所有的显卡计算资源, 避免额外的启动逻辑
- 基于docker虚拟化以及kubernetes虚拟网络会对性能有一定影响

**Comment by fzhan** [comment]
@xxmyjk 非常感谢，虽然不是一个实操的教程或手册，但至少给我一个很好的方向。如果有后续的官方的手册也请更新一下。
