### ISSUE TITLE
请问一下oneflow release版本的whl包链接地址有吗~

### ISSUE THREAD

**Issue by gentelyang** [Oneflow-Inc/oneflow#5695]
求一个oneflow release版本的whl包链接地址

**Comment by jackalcooper** [comment]
请访问 https://start.oneflow.org/ 查询根据 CUDA 版本安装命令

**Comment by gentelyang** [comment]
```
![image](https://user-images.githubusercontent.com/25795827/127952261-03a84c9b-994e-422b-9524-5d255d0d8c67.png)

```
```
![image](https://user-images.githubusercontent.com/25795827/127952537-d2a6c4a5-9107-4434-af6a-be9457960dd3.png)

```
好吧，只有这两个办法的话我这边源码编译一个oneflow whl包吧；我这边开代理后安装特别慢，不开代理装不上，这个目录下的whl包wget不下来，链接点开报错...

**Comment by jackalcooper** [comment]
> 好吧，只有这两个办法的话我这边源码编译一个oneflow whl包吧；我这边开代理后安装特别慢，不开代理装不上，这个目录下的whl包wget不下来，链接点开报错...
> https://oneflow-release.oss-cn-beijing.aliyuncs.com/pip/0.4.0/cu100/87d4ab1793fcdd62adc1ca621bd86063825c66ca/oneflow-0.4.0+cu100-cp37-cp37m-manylinux2014_x86_64.whl

建议把代理关了，然后设置tuna为pip镜像然后安装
```
python3 -m pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
```
直接使用地址需要escape一下，比如：
https://oneflow-release.oss-cn-beijing.aliyuncs.com/pip/0.4.0/cu100/87d4ab1793fcdd62adc1ca621bd86063825c66ca/oneflow-0.4.0%2Bcu100-cp37-cp37m-manylinux2014_x86_64.whl

**Comment by gentelyang** [comment]
> > 好吧，只有这两个办法的话我这边源码编译一个oneflow whl包吧；我这边开代理后安装特别慢，不开代理装不上，这个目录下的whl包wget不下来，链接点开报错...
> > https://oneflow-release.oss-cn-beijing.aliyuncs.com/pip/0.4.0/cu100/87d4ab1793fcdd62adc1ca621bd86063825c66ca/oneflow-0.4.0+cu100-cp37-cp37m-manylinux2014_x86_64.whl
> 
> 建议把代理关了，然后设置tuna为pip镜像然后安装
> 
> ```
> python3 -m pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
> ```
> 
> 直接使用地址需要url encode一下，比如：
> https://oneflow-release.oss-cn-beijing.aliyuncs.com/pip/0.4.0/cu100/87d4ab1793fcdd62adc1ca621bd86063825c66ca/oneflow-0.4.0%2Bcu100-cp37-cp37m-manylinux2014_x86_64.whl

好的多谢~
