### ISSUE TITLE
Eager 模式下动态输入的问题

### ISSUE THREAD

**Issue by carefree0910** [Oneflow-Inc/oneflow#6031]
您好，之前就一直有关注 OneFlow，看到最近终于支持面向对象编程了，感觉甚是欣喜，所以想问一下这个模式下的一些动态输入的支持问题。具体而言：
+ 是否支持输入是一个 Tensor dict？
+ 是否支持输入是一个 mixed dict？
+ 是否支持输入的 dict 在 forward 的过程中被修改？

这三个场景都是我之前写[基于 PyTorch 的深度学习库](https://github.com/carefree0910/carefree-learn)时会遇到的场景，对于写框架而言，我个人感觉这三个 feature 对于灵活性而言还挺重要的；但另一方面我也知道这对静态图恐怕没有那么友好，所以想问一问

举个栗子，我想实现的是类似这样的功能：

```python
class A(nn.Module):
    def __init__(self, ...):
        self.m = B(...)

   def forward(self, tensor_dict):
        tensor_dict["b_key"] = ...
        return self.m(tensor_dict)


class B(nn.Module):
    def __init__(self, ...):
        ...

   def forward(self, tensor_dict):
        ...
```

**Comment by strint** [comment]
对于eager执行：
- 内置的Module(https://oneflow.readthedocs.io/en/master/nn.html)，都是以Tensor为forward函数的输入类型的
- 自定义的Module，forward接口约束了是positional arguments，所以传dict也是可以的，只要自己处理好参数传递关系，比如下面的代码是可以执行的
```
import oneflow as flow
import oneflow.nn as nn

class A(nn.Module):
    def __init__(self):
        super().__init__()
        self.m = nn.Linear(3, 8, False)

    def forward(self, tensor_dict):
        t = tensor_dict["key"]
        return self.m(t)

m_a = A()

x = flow.ones(8, 3)
tensor_dict = {"key": x}

out = m_a(tensor_dict)

print(out.numpy())
```

对于静态执行：
- oneflow对应的抽象是nn.Graph，参考例子 https://github.com/Oneflow-Inc/oneflow/blob/master/python/oneflow/test/graph/test_graph_linear.py
- 对动态情况有约束，静态图是第一次forward执行时的执行路径形成的，如果本意是多次执行的执行路径不同，就会出现不一致；
- 当前的nn.Graph的接口支持Tensor、None、TensorTuple、List[Tensor] ，参考：https://github.com/Oneflow-Inc/oneflow/pull/5803
- dict当前还没支持，它无序、可以嵌套，过于灵活，里面含有太多业务逻辑，这样在接口处的构图、问题定位都会带来麻烦，所以dict最好是懂业务的使用者转为序列传入nn.Graph，dict转为序列如list和tuple在python下是很容易的操作，取舍之下，没有支持dict。

**Comment by carefree0910** [comment]
非常感谢您的耐心解答！真的是非常详细而完整，我的问题已经得到了解决；确实 dict 对业务来说是很不好的使用方法，我也一直想着看怎样把 dict 给更好地序列化

刚好 OneFlow 这边不支持 dict，某种意义上也算是 push 我去重新设计这一块的接口了🤣

感觉现在的 OneFlow 在易用性上已经相当完整了，我也会尝试把之前基于 PyTorch 的框架往 OneFlow 上迁移，希望能为国产深度学习框架尽一份绵薄之力😄

> 希望我不要咕咕咕🤣

**Comment by strint** [comment]
> 我也会尝试把之前基于 PyTorch 的框架往 OneFlow 上迁移

赞，如果有兴趣 or 可以合作，可以向oneflow的模型库提Pull Request：https://github.com/Oneflow-Inc/models

**Comment by strint** [comment]
这个问题已经ok，issue就close了哈。中文交流有个QQ群：331883，可以做后续交流~
