### ISSUE TITLE
易用性框架的问题

### ISSUE THREAD

**Issue by carefree0910** [Oneflow-Inc/oneflow#6050]
今早在 #6031 的讨论之后，觉得现在的 `oneflow` 可以支撑起一个易用性框架了，于是[试着写了一个](https://github.com/carefree0910/carefree-flow)；当然，秉承着不重复造轮子的原则，还是想和贵团队进行一下探讨

> p.s. QQ 群我其实早就加了，如果觉得 QQ 群更方便的话也可以在 QQ 群里讨论🤣（我的 QQ id 是 Carefree0910）

1. 官方是否已经有这种类似的易用性框架
2. 这种易用性框架在当前时间点是否合适（我用的是 nightly build，因为 `0.4.0` 版本的功能似乎和文档对不上，缺失了不少
3. 这种易用性框架是否破坏了 `oneflow` 的美学

> 当然现在这个 repo 肯定还有很多 bug（毕竟开发的时间着实有限🤣），所以根据必要性，我再康康要不要继续进行开发

下面我会展示一些该易用性框架的功能，以作参考

---

+ 内置（带 metrics 的）`tqdm`：

<img width="850" alt="mnist_tqdm" src="https://user-images.githubusercontent.com/15677328/130776881-5d6d2c8e-a8b7-4de6-a792-e82074e5b982.png">

+ 支持回滚到最优的 checkpoint：

<img width="401" alt="mnist_final" src="https://user-images.githubusercontent.com/15677328/130776942-873dca0d-8ba1-4798-9dc8-958e0b0b19df.png">

+ 会自动地记录很多信息，以便后续查看：

<img width="186" alt="cflow_artifacts" src="https://user-images.githubusercontent.com/15677328/130777248-e32c6653-4e1e-42d8-a22c-3456ff05a1b7.png">

<img width="129" alt="cflow_checkpoints" src="https://user-images.githubusercontent.com/15677328/130777264-0e8694be-6673-4eea-b3dc-346726845acb.png">

<img width="617" alt="cflow_metrics_log" src="https://user-images.githubusercontent.com/15677328/130777292-6412c4d1-04f3-4239-85f8-df8be8d61ecc.png">

+ 支持自定义一些 callback，能够进行定制化的可视化：

<img width="120" alt="cflow_img_callback" src="https://user-images.githubusercontent.com/15677328/130777408-744caef1-6d8d-4055-85fd-2795ca7a2bae.png">

<img width="447" alt="cflow_img_callback2" src="https://user-images.githubusercontent.com/15677328/130777505-70baa79b-0768-43b7-8ba9-70883887ca9b.png">

+ 以上功能所对应的代码（MNIST 示例，在[那个 repo ](https://github.com/carefree0910/carefree-flow)里的 README 里也有）：

```python
import cflow

import numpy as np
import oneflow.data as data


(x_train, y_train), (x_test, y_test) = data.load_mnist()
x_train, x_test = np.concatenate(x_train, axis=0), np.concatenate(x_test, axis=0)
y_train = np.concatenate(y_train, axis=0)[..., None]
y_test = np.concatenate(y_test, axis=0)[..., None]

data = cflow.cv.TensorData(x_train, y_train, x_test, y_test)
m = cflow.cv.CarefreePipeline(
    "clf",
    dict(
        in_channels=1,
        num_classes=10,
        img_size=28,
        latent_dim=128,
        encoder1d="lenet",
    ),
    fixed_epoch=5,
    loss_name="cross_entropy",
    metric_names=["acc", "auc"],
    tqdm_settings={"use_tqdm": True, "use_step_tqdm": True},
)
m.fit(data, cuda=0)
```

**Comment by strint** [comment]
赞，在issue讨论蛮好的，可以留有记录，可以被后来人检索到。

> 这种易用性框架在当前时间点是否合适（我用的是 nightly build，因为 0.4.0 版本的功能似乎和文档对不上，缺失了不少
没错，使用nightly build就好，也就是准备发布的0.5.0，会更为完善和稳定。

开发一个更高层一点，更易用的接口，我觉得时间总是合适的，只要它可以解决你关心的问题。看到了你在开发的仓库，关注度还挺高的（https://github.com/carefree0910/carefree-learn）。

你在日常工作中会使用它吗？

> 官方是否已经有这种类似的易用性框架

也是从需求出发，之前为了支持一键动静转换、支持运行新老版本代码，掩盖动静转换的差异性，实验性的实现了一个high levle api，[nn.Model](https://github.com/Oneflow-Inc/oneflow/blob/master/python/oneflow/framework/model.py) ，类PyTorch Lightling的接口：
- 这是支持老function接口一个alexnet的例子：https://github.com/Oneflow-Inc/oneflow/blob/master/python/oneflow/test/models/test_alexnet_model.py
- 这是支持新OOP eager接口的一个测试例子：https://github.com/Oneflow-Inc/oneflow/blob/master/python/oneflow/compatible/single_client/test/ops/test_model.py

目前个人感觉一键动静切换不一致的地方很多，多到使其不可用：
- eager可以做很不规则、细粒度的控制，比如多轮迭代间任意调整lr/grad accumulation/网络结构，静态图只能解决其中比较规则的问题；
- 高级特性比如AMP/自动并行/流水并行，eager的会用手动控制，静态图则倾向于配置策略或者自动图优化，二者也差别比较大；

当前我们也调整了动静转换的思路，没有承诺一键转换。而是采用两阶段式的：
- 承认动态到静态的差异，认可静态图可以处理的任务是动态图的子集，动态执行和静态优化相互限制就少了（nn.Model可以自由实现逻辑，nn.Graph提供更好的性能优化）。
- 先基于nn.Module写eager动态代码，这里可以完成算法原型开发和逻辑验证；
- 需要更多性能优化、更大规模部署时，nn.Module的算法逻辑代码放进nn.Graph进行静态图生成、优化、执行，这里nn.Graph能处理大部分成熟模型的nn.Module（我们能做的是不断扩大nn.Graph的能力）；
- 这样不是一键切换，承认动态到静态的差异，提供可组合的工具（nn.Module -> nn.Graph），做增量的开发；

基于此，因为承认了动静的差异，nn.Model想屏蔽的差异就变得不可控了，所以nn.Model还没想好其现在的位置。

> 这种易用性框架是否破坏了 oneflow 的美学

个人感觉不会破坏什么，基于oneflow做更好的工具肯定是欢迎的，能方便更多开发者使用。

**Comment by carefree0910** [comment]
> 你在日常工作中会使用它吗？

现在我在我这边的初创团队里头基本就是在用它，感觉能够 cover 住挺多需求（包括 GAN、SSL 这种比较特殊的训练范式）

> 类 PyTorch Lightling 的接口

这个感觉如果真的做出来还是很厉害的，我这一套充其量只是一个简化版本的封装😄

不过我当年弃用 PyTorch Lightling 的很大一个原因就是，即使它是基于 PyTorch 的，但是遇到特殊的训练范式还是会非常棘手，或者说至少当年它设计得还是有些过于耦合的感觉（比如当年用它来写 GAN 的体验就非常差）

> 承认动态到静态的差异，提供可组合的工具（nn.Module -> nn.Graph），做增量的开发

不知道能不能理解为类似于 PyTorch 的 TorchScript，只是您这边刚好反过来（是先有静态图，再有的动态图以及相应的转化）；如果是的话，我感觉可能前期只想着动态图也就可以了

---

我原先想的规划是，如果从逻辑上可行，那就只需验证是否能比较方便地把并行跑起来（`oneflow` 的核心优势）就行；然后我看了看好像也是有类似于 `DistributedDataParallel` 这种直接作用于动态模型上的东西的。不过我不太确定的是：
1. 如果整个 code base 里面没有出现过静态图的任何东西（相当于直接用 PyTorch 那套语言进行编写），能够发挥出 `oneflow` 在并行上的优势么？
2. 官方未来打算让用户做的是纯粹动态编程、同时提供很多实用的工具完成静态的优化，还是要求用户也拥有静态编程的知识、并在开发中体现出来？如果是后者的话，可能对易用性框架开发的要求就会高很多，我目测就胜任不了了（因实力不足而被迫咕咕咕🤣
