### ISSUE TITLE
flow.save supports arbitrary picklable object

### ISSUE THREAD

**Issue by daquexian** [Oneflow-Inc/oneflow#6272]
目前 optimizer 的保存不能用 flow.save，而是通过

```python
import pickle
with open("optim_state.pkl", "wb") as f:
    pickle.dump(sgd.state_dict(), f)
```

这和 pytorch 不对齐。pytorch 是通过 python 内置的 pickle 模块对 tensor 和其它数据类型来做序列化/反序列化的，所以可以支持任何实现了相关接口的容器和数据类型。我们也应该这么做，但同时也要考虑模型尺寸特别大的情况。

**Comment by chengtbf** [comment]
这个问题挺重要的。另外还需要考虑 nn.Graph，Optimizer 的状态（比如  bn 的衍生 weight tensor， train step，lr 等）也需要跟 Lazy 在 job pass 中插入的 Variable op 做绑定。这个需要讨论一下  @strint @leaves-zwx @daquexian @wyg1997
