### ISSUE TITLE
对齐 Kernel 所支持的数据类型

### ISSUE THREAD

**Issue by chengtbf** [Oneflow-Inc/oneflow#6279]
问题示例： 

- #6247   flow.abs 没有支持 int 类型
- #6246   flow.tril 没有支持 uint8 类型（我们大量的算子都没有支持 uint8 数据类型）

对于已经发现的缺失数据类型的算子（一般是有模型用到了），可以优先支持。其余我们自己查缺补漏发现的，可以作为新手任务完成。

除了常见 算子的 接口跟 torch 对齐以外，我们需要组织人力统一过一遍 我们所有的 kernel 所支持的 数据类型，将未支持的按计划补齐。这也是完备性的一个重要部分。未来新增的 算子，除了 接口 和 常见类型（float）测试通过以外，也需要测试 torch 的该算子支持的 全部数据类型 我们是否都对齐了。

@doombeaker @BBuf @MARD1NO 组织一下，形式和进度跟踪类似 #4936

**Comment by MARD1NO** [comment]
issue 6281 已解决
