### ISSUE TITLE
/ 有bug，// 不支持

### ISSUE THREAD

**Issue by WangYizhang01** [Oneflow-Inc/oneflow#6440]
oneflow.Tensor / int有bug。当Tensor是oneflow.int类型时结果不对。
```python
a = flow.randint(3, 10, (3, 8))
print(a)
tensor([[3, 3, 8, 9, 3, 6, 6, 7],
        [7, 5, 5, 6, 4, 8, 9, 6],
        [3, 3, 4, 3, 9, 8, 6, 9]], dtype=oneflow.int64)

print(a / 2)
tensor([[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]], dtype=oneflow.int64)

print(a // 2)
TypeError: unsupported operand type(s) for //: 'oneflow._oneflow_internal.Tensor' and 'int'
```

**Comment by MARD1NO** [comment]
先试试
```python
flow.div(a, 2)
```
看下结果是否符合预期呢

**Comment by WangYizhang01** [comment]
> 先试试
> 
> ```python
> flow.div(a, 2)
> ```
> 
> 看下结果是否符合预期呢

div和 / 结果是一样的。

**Comment by wyg1997** [comment]
请问下当前 oneflow commit 是哪个呢？我在 master 上试了 `/` 结果是正确的：

![image](https://user-images.githubusercontent.com/39889784/135223511-b06b731a-3578-4efc-bdde-b311b74fc71c.png)

**Comment by MARD1NO** [comment]
> > 先试试
> > ```python
> > flow.div(a, 2)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 看下结果是否符合预期呢
> 
> div和 / 结果是一样的。

这边能够复现问题，我快速修复下

**Comment by WangYizhang01** [comment]
> 请问下当前 oneflow commit 是哪个呢？我在 master 上试了 `/` 结果是正确的：
> 
> ![image](https://user-images.githubusercontent.com/39889784/135223511-b06b731a-3578-4efc-bdde-b311b74fc71c.png)

我用的是最新的nightly版本，刚又源码编译了下master分支好像也有这问题。

**Comment by MARD1NO** [comment]
> > 请问下当前 oneflow commit 是哪个呢？我在 master 上试了 `/` 结果是正确的：
> > ![image](https://user-images.githubusercontent.com/39889784/135223511-b06b731a-3578-4efc-bdde-b311b74fc71c.png)
> 
> 我用的是最新的nightly版本，刚又源码编译了下master分支好像也有这问题。

使用了你提供的代码：
```python
import oneflow as flow 

a = flow.randint(3, 10, (3, 8))
print(a)
print(a / 2)

tensor([[5, 9, 9, 9, 7, 7, 9, 7],
        [5, 5, 3, 8, 5, 8, 9, 9],
        [4, 5, 3, 9, 8, 9, 5, 6]], dtype=oneflow.int64)
tensor([[2.5000, 4.5000, 4.5000, 4.5000, 3.5000, 3.5000, 4.5000, 3.5000],
        [2.5000, 2.5000, 1.5000, 4.0000, 2.5000, 4.0000, 4.5000, 4.5000],
        [2.0000, 2.5000, 1.5000, 4.5000, 4.0000, 4.5000, 2.5000, 3.0000]],
       dtype=oneflow.float32)
```

**Comment by MARD1NO** [comment]
floordiv这个算子我支持下

**Comment by WangYizhang01** [comment]
30日的nightly版本中 / 结果没问题。
