### ISSUE TITLE
GLM推理 单卡速度慢

### ISSUE THREAD

**Issue by lcylcy** [Oneflow-Inc/oneflow#6482]
| glm性能对比    | torch          | oneflow | 
| --------------- | ------------------- | ------ | 
|  使用dataloader |    3.95                |    19       | 
|使用dataloader,torch去掉混合精度|10.9|19|
| 不使用dataloader | 13.8                | 49         |
|不适用dataloader,torch去掉混合精度 | 43|49|

**Comment by Flowingsun007** [comment]
这里需要贴一下GLM的代码链接，以及对比速度时方便复现的关键代码等

**Comment by lcylcy** [comment]
好的，一会儿和露阳开个会议

**Comment by Flowingsun007** [comment]
这个贴出 @lcylcy 给出的，不使用dataloader的最小复现demo: [glm_flow.py.zip](https://github.com/Oneflow-Inc/oneflow/files/7314773/glm_flow.py.zip)。可直接`python3 glm_flow.py`运行；为了方便对比，我这里给出了这个demo的torch版实现：[glm_torch.py.zip](https://github.com/Oneflow-Inc/oneflow/files/7314762/glm_torch.py.zip)。
二者代码部分完全一样，都是跑100iter，中间不打印loss，只在L117-L118有一处差异：
```python
# torch
output_parallel[input_mask, :] = 0.0
# oneflow
output_parallel[input_mask[...,None].expand(*output_parallel.shape).to(flow.int8)] = 0
```
torch版实现用的是上面的`output_parallel[input_mask, :] = 0.0`这行；oneflow版实现用的则是下面一行。

### nsight结果
从nsight结果来看，kernel执行时间oneflow在7.6s左右；
<img width="1043" alt="flow" src="https://user-images.githubusercontent.com/28823622/136639043-0007d5f6-f0fc-46ce-83b6-d8481c30d60c.png">

[report1.qdrep.zip](https://github.com/Oneflow-Inc/oneflow/files/7314786/report1.qdrep.zip)

torch在6.4s左右：

<img width="1050" alt="torch" src="https://user-images.githubusercontent.com/28823622/136639052-a3e33e36-26ef-4336-a3a9-de5b6378a14b.png">

[report3_torch.qdrep.zip](https://github.com/Oneflow-Inc/oneflow/files/7314789/report3_torch.qdrep.zip)

oneflow vs torch慢了1s多，接近19%的差距。从LineProfiler观察到的结果，也是类似。

注释掉L106的：`masked_input[input_mask] = 0` 和L118的：`output_parallel[input_mask[...,None].expand(*output_parallel.shape).to(flow.int8)] = 0`
速度有所提升，100iter耗时在7.1s左右：
<img width="1026" alt="flow_2" src="https://user-images.githubusercontent.com/28823622/136639233-a1754503-aab6-4d39-932a-50627b1ca1db.png">

[report2.qdrep.zip](https://github.com/Oneflow-Inc/oneflow/files/7314788/report2.qdrep.zip)

**Comment by lcylcy** [comment]
找到主要问题了，torch模型使用混合精度时间14s,不使用混合精度为43s,这样看来时间总体差距不大

**Comment by hjchen2** [comment]
> 这里贴出 @lcylcy 最小复现代码oneflow 和torch transform部分的耗时对比 [GLM.zip](https://github.com/Oneflow-Inc/oneflow/files/7315235/GLM.zip) 两个最小代码对比： oneflow transformer 添加了LeakyReLU 来方便定位kernel耗时 ![image](https://user-images.githubusercontent.com/9412577/136650087-2c805ea1-ed8a-4ea5-86a1-8cb2866ccdfe.png)
> 
> ## nsight结果
> * torch 每个Iter transformer 耗时18ms
>   ![image](https://user-images.githubusercontent.com/9412577/136650180-52002ff3-a0e2-4399-ae9b-cb8c52ef36e8.png)
> * oneflow 每个Iter transformer 耗时 34ms
>   ![image](https://user-images.githubusercontent.com/9412577/136650280-8572c39a-327b-46ad-a9e8-b8d14f7003c3.png)

pytorch transformer直接看nvtx range的结果不大准，kernel都是异步执行的，你nvtx那个统计的应该是cpu的时间，其实可以数v olta_sgemm_128x64_tn的个数来大致对齐oneflow和pytorch transformer的kernel执行区间的。

**Comment by mechigonft** [comment]
@lcylcy @Flowingsun007 @hjchen2 @luqiang-guo @yuanms2 哈喽，各位，请问这个问题有答案了吗，one-flow能加速glm-large-chinese模型的推理速度吗？

**Comment by yuanms2** [comment]
> @lcylcy @Flowingsun007 @hjchen2 @luqiang-guo @yuanms2 哈喽，各位，请问这个问题有答案了吗，one-flow能加速glm-large-chinese模型的推理速度吗？

不好意思，团队工作重心有一些调整，我们不会基于通用框架来解决大模型推理，后续会推出一个专门用于大模型推理的系统
