### ISSUE TITLE
Feature request: svd operator

### ISSUE THREAD

**Issue by hiyyg** [Oneflow-Inc/oneflow#6704]

**Comment by hiyyg** [comment]
@yuanms2 Hey, I need to re-implement a method originally writtent in pytorch. It has `torch.linalg.svd`. However, no svd can be found in oneflow.

**Comment by hiyyg** [comment]
Nevermind, I just give up using oneflow...

**Comment by yuanms2** [comment]
Thanks for your feedback. We are sorry that the OPs of oneflow are not as complete as others. Oneflow team will study the svd operator.
