### ISSUE TITLE
different results of flow.matmul() between stable and nightly version

### ISSUE THREAD

**Issue by kaijieshi7** [Oneflow-Inc/oneflow#6722]
## Summary

嗨，最近在做model库，在transformer中，常用 mamul 功能(用稳定版不会出现问题，下午安装的nightly版本会出现问题)。
发现nightly版本的matmul在GPU和CPU上的结果不一样，nightly版本的GPU结果和稳定版的GPU结果也不一样。个人猜测nightly版本的matmul有问题。
在cswin-tiny-224模型中中导致Top-1准确率会误差两个点。
## Code to reproduce bug

```
import oneflow as flow
import numpy as np

q = flow.tensor(np.load('./q_night.npy'))
k = flow.tensor(np.load('./k_night.npy'))
z_cpu = flow.matmul(q, k.transpose(-2, -1))
z_gpu = flow.matmul(q.cuda(), k.transpose(-2, -1).cuda())
```

Please post a minimal example to repro the bug. GitHub Gist or repo is highly recommended.

## System Information

- What is your OneFlow installation (pip, source, dockerhub): pip
- OS: ubuntu16
- OneFlow version (run `python3 -m oneflow --doctor`): version: 0.6.0.dev20211107+cu102
- Python version: 3.8
- CUDA driver version: 440.64
- GPU models: 2080ti
- Other info:

**Comment by BBuf** [comment]
@hjchen2

**Comment by liujuncheng** [comment]
https://github.com/Oneflow-Inc/oneflow/pull/6723 这个分支可以修复这个问题，可以测试一下

**Comment by kaijieshi7** [comment]
> #6723 这个分支可以修复这个问题，可以测试一下

我该怎么安装你修改过的那个

**Comment by guo-ran** [comment]
```
https://oneflow-staging.oss-cn-beijing.aliyuncs.com/branch/fix_broadcast_matmul/cu102/28085af45e5277f872ba2ab0945ab97e015f5700/oneflow-0.6.0.dev20211108%2Bcu102-cp38-cp38-manylinux2014_x86_64.whl
```
安装这个包试试
