### ISSUE TITLE
different results of combine ops between cpu and gpu in 20111109 nightly version

### ISSUE THREAD

**Issue by kaijieshi7** [Oneflow-Inc/oneflow#6751]
## Summary
different results of .view().transpose().contiguous() between cpu and gpu

## Code to reproduce bug
`import numpy as np
import oneflow as flow

x_cpu = flow.tensor(np.load('./vision/x_input3.npy'))
x_gpu = flow.tensor(np.load('./vision/x_input3.npy')).cuda()
x_cpu = x_cpu.view(64, 256, -1).transpose(-2, -1).contiguous()
x_gpu = x_gpu.view(64, 256, -1).transpose(-2, -1).contiguous()
print(flow.sum(x_cpu-x_gpu.cpu()))`

## System Information

- What is your OneFlow installation (pip, source, dockerhub):pip
- OS:ubuntu16
- OneFlow version (run `python3 -m oneflow --doctor`):20111109
- Python version:
- CUDA driver version:
- GPU models:
- Other info:

**Comment by MARD1NO** [comment]
> ## Summary
> different results of .view().transpose().contiguous() between cpu and gpu
> 
> ## Code to reproduce bug
> `import numpy as np import oneflow as flow
> 
> x_cpu = flow.tensor(np.load('./vision/x_input3.npy')) x_gpu = flow.tensor(np.load('./vision/x_input3.npy')).cuda() x_cpu = x_cpu.view(64, 256, -1).transpose(-2, -1).contiguous() x_gpu = x_gpu.view(64, 256, -1).transpose(-2, -1).contiguous() print(flow.sum(x_cpu-x_gpu.cpu()))`
> 
> ## System Information
> * What is your OneFlow installation (pip, source, dockerhub):pip
> * OS:ubuntu16
> * OneFlow version (run `python3 -m oneflow --doctor`):20111109
> * Python version:
> * CUDA driver version:
> * GPU models:
> * Other info:

具体数据形状能不能给下，单看这个-1看不出来，还需要下载对应的文件

**Comment by kaijieshi7** [comment]
> > ## Summary
> > different results of .view().transpose().contiguous() between cpu and gpu
> > ## Code to reproduce bug
> > `import numpy as np import oneflow as flow
> > x_cpu = flow.tensor(np.load('./vision/x_input3.npy')) x_gpu = flow.tensor(np.load('./vision/x_input3.npy')).cuda() x_cpu = x_cpu.view(64, 256, -1).transpose(-2, -1).contiguous() x_gpu = x_gpu.view(64, 256, -1).transpose(-2, -1).contiguous() print(flow.sum(x_cpu-x_gpu.cpu()))`
> > ## System Information
> > 
> > * What is your OneFlow installation (pip, source, dockerhub):pip
> > * OS:ubuntu16
> > * OneFlow version (run `python3 -m oneflow --doctor`):20111109
> > * Python version:
> > * CUDA driver version:
> > * GPU models:
> > * Other info:
> 
> 具体数据形状能不能给下，单看这个-1看不出来，还需要下载对应的文件

读取的numpy数据是(64, 256, 14, 14)

**Comment by hjchen2** [comment]
有什么不一样么，我跑出来结果是0的。
```python
tensor(0., dtype=oneflow.float32)
```

**Comment by kaijieshi7** [comment]
> 有什么不一样么，我跑出来结果是0的。
> 
> ```python
> tensor(0., dtype=oneflow.float32)
> ```

我录制了视频发到了slack

**Comment by Ldpe2G** [comment]
```python3
import numpy as np
import oneflow as flow
np_rand = np.random.rand(64,256,14,14)
x_cpu = flow.tensor(np_rand)
x_gpu = flow.tensor(np_rand, device="cuda")

x_cpu = x_cpu.view(64, 256, -1).transpose(-2, -1)#.contiguous()
x_gpu = x_gpu.view(64, 256, -1).transpose(-2, -1)#.contiguous()
print(flow.sum(x_cpu-x_gpu.cpu()))
```

我这边跑出来确实不一样

**Comment by hjchen2** [comment]
> ```python
> ```python
> import numpy as np
> import oneflow as flow
> np_rand = np.random.rand(64,256,14,14)
> x_cpu = flow.tensor(np_rand)
> x_gpu = flow.tensor(np_rand, device="cuda")
> 
> x_cpu = x_cpu.view(64, 256, -1).transpose(-2, -1)#.contiguous()
> x_gpu = x_gpu.view(64, 256, -1).transpose(-2, -1)#.contiguous()
> print(flow.sum(x_cpu-x_gpu.cpu()))
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 我这边跑出来确实不一样，view 的结果是一致的，加上 transpose 就不一样了
> ```

感觉像是primitive transpose导致的，最近就这个PR https://github.com/Oneflow-Inc/oneflow/pull/6715 更新了transpose的kernel

**Comment by guo-ran** [comment]
看起来像是batch permute有些边界条件没处理好
```
import numpy as np
import oneflow as flow

np_rand = np.random.rand(64,256,14*14)
x_gpu = flow.tensor(np_rand, device="cuda")
x_cpu = flow.tensor(np_rand)
x_gpu = x_gpu.transpose(-2, -1)
x_cpu = x_cpu.transpose(-2, -1)
print(flow.sum(x_cpu-x_gpu.cpu()))
```
`np_rand = np.random.rand(64,256,14*14)`会出错，`np.random.rand(64,256,14*15)`不会
