### ISSUE TITLE
Different results of flow.mean between CPU and GPU under FLOAT32

### ISSUE THREAD

**Issue by kaijieshi7** [Oneflow-Inc/oneflow#6917]
## Summary

Under float32, CPU's results seem right, but GPU returns NAN. 
![image](https://user-images.githubusercontent.com/19171201/144544813-07438ac3-636e-4c57-81b7-8b0d45155832.png)

## Code to reproduce bug

```import oneflow as flow
import numpy as np
x = flow.tensor(np.random.randn(1, 1, 16, 16)*10, dtype=flow.float32)
flow.mean((x-0)**2)
flow.mean((x.cuda()-0)**2)
```

## System Information

- What is your OneFlow installation (pip, source, dockerhub): pip
- OS: ubuntu16.04
- OneFlow version (run `python3 -m oneflow --doctor`):0.6.0.dev20211114+cu102
- Python version:3.8
- CUDA driver version:10.2
- GPU models:2080Ti
- Other info:

**Comment by kaijieshi7** [comment]
float64沒有這個bug

**Comment by kaijieshi7** [comment]
可替代的解决方案是
```
flow.mean(x.cuda().square())
```

**Comment by kaijieshi7** [comment]
flow.pow(x.cuda(), 2)也有mean的bug
```
import numpy as np
x = flow.tensor(np.random.randn(1, 256, 64, 64), dtype=flow.float32)
flow.mean(flow.pow(x.cuda(), 2))
```

**Comment by kaijieshi7** [comment]
这个问题反映了这么就没人来解决吗？？？

**Comment by BBuf** [comment]
这个问题是因为pow kernel的实现使用了__powf导致，改成powf就可以解决。（By @MARD1NO ，他会提个pr解决。
