### ISSUE TITLE
std::vector<bool> bug in ccl

### ISSUE THREAD

**Issue by simonJJJ** [Oneflow-Inc/oneflow#6927]
When I add bool type in POD_DATA_TYPE_SEQ, there is a bug in the compilation: 
**error: void value not ignored as it ought to be
    T\* recv_ptr = recv_buffer.data();**
It is related to the std::vector<bool> specialization does not support the method:
https://stackoverflow.com/questions/16568986/what-happens-when-you-call-data-on-a-stdvectorbool

**Comment by lixinqi** [comment]
是不是我们就完全抛弃std::vector<T>，直接使用 std::unique_ptr<T[]>？

**Comment by lixinqi** [comment]
> 是不是我们就完全抛弃std::vector，直接使用 std::unique_ptr<T[]>？

我重新表述一下，在ccl那个场景下，基本上只是需要一段可以随机访问的buffer，所以std::unique_ptr<T[]>或者std::shared_ptr<T[]>看上去是够用的。

**Comment by simonJJJ** [comment]
solved by
std::make_unique<T[]>(size);
