### ISSUE TITLE
变量同名bug

### ISSUE THREAD

**Issue by kaijieshi7** [Oneflow-Inc/oneflow#6985]
## Summary
详见代码, output变量只能被用一次
![Screenshot from 2021-12-09 12-20-11](https://user-images.githubusercontent.com/19171201/145333835-714f2efc-395a-4394-9572-fafbd7677a89.png)

## Code to reproduce bug
```
import oneflow as flow
import oneflow.nn as nn

x = flow.ones([64, 10]).cuda()
model = nn.Linear(10, 10)
output = model(x)
print(output)
loss_fn = nn.MSELoss()
optimizer = flow.optim.SGD(model.parameters(), lr=0.001)
labels = flow.zeros(64, 10).cuda()
loss_fn(output, labels).backward()
optimizer.step()
output1 = model(x) #无bug
# output = model(x) #有bug
print(output)
print(flow.sum(output))
```
Please post a minimal example to repro the bug. GitHub Gist or repo is highly recommended.

## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS:
- OneFlow version (run `python3 -m oneflow --doctor`):
- Python version:
- CUDA driver version:
- GPU models:
- Other info:

**Comment by Ldpe2G** [comment]
`model = nn.Linear(10, 10)` 这里没有把 linear 的参数放到 cuda 上，为什么能跑起来呢

**Comment by kaijieshi7** [comment]
这个好像不是tocuda引起的，这边测试渐渐发现是一个有点迷bug

**Comment by BBuf** [comment]
我试了一下，可以正常运行。

**Comment by chengtbf** [comment]
这个提示信息是 OOM 了啊 😂  跟 output 有什么关系呢
