### ISSUE TITLE
混合并行训练出现物理和逻辑节点不一致

### ISSUE THREAD

**Issue by muzhailong** [Oneflow-Inc/oneflow#7045]
代码：[https://github.com/muzhailong/pddl](https://github.com/muzhailong/pddl)（参考oneflow/models ,修改了一部分）
执行：run_ppl.sh
环境：2台服务器，每一台2张A100，使用节点内数据并行，节点间模型并行+流水并行方式
报错：
`Creating Dataloader
Building BERT Model
F1217 09:39:23.176839 88430 parallel_desc.cpp:76] 
  File "/root/muzhailong/oneflow/oneflow/core/job/parallel_desc.cpp", line 76, in ParallelDesc
    CheckWithResourceDesc(*(Global<ResourceDesc, ForSession>::Get()))
  File "/root/muzhailong/oneflow/oneflow/core/job/parallel_desc.cpp", line 298, in CheckWithResourceDesc
    Check failed: (dev_phy_id) < (resource_desc.GpuDeviceNum()) (3 vs 2)
*** Check failure stack trace: ***
    @     0x2b7f7796544d  google::LogMessage::Fail()
    @     0x2b7f77966cca  google::LogMessage::SendToLog()
    @     0x2b7f77964f0d  google::LogMessage::Flush()
    @     0x2b7f779680f9  google::LogMessageFatal::~LogMessageFatal()
    @     0x2b7f7311e5fd  oneflow::ParallelDesc::ParallelDesc()
F1217 09:39:23.199110 88431 parallel_desc.cpp:76] 
  File "/root/muzhailong/oneflow/oneflow/core/job/parallel_desc.cpp", line 76, in ParallelDesc
    CheckWithResourceDesc(*(Global<ResourceDesc, ForSession>::Get()))
  File "/root/muzhailong/oneflow/oneflow/core/job/parallel_desc.cpp", line 298, in CheckWithResourceDesc
    Check failed: (dev_phy_id) < (resource_desc.GpuDeviceNum()) (3 vs 2)
*** Check failure stack trace: ***
    @     0x2b09efef844d  google::LogMessage::Fail()
    @     0x2b09efef9cca  google::LogMessage::SendToLog()
    @     0x2b7f7313f7c3  (unknown)
    @     0x2b09efef7f0d  google::LogMessage::Flush()
    @     0x2b09efefb0f9  google::LogMessageFatal::~LogMessageFatal()
    @     0x2b09eb6b15fd  oneflow::ParallelDesc::ParallelDesc()
    @     0x2b7f7313fe60  (unknown)
    @     0x2b7f7313c769  oneflow::RankGroup::GetDefaultParallelDesc()
    @     0x2b09eb6d27c3  (unknown)
    @     0x2b09eb6d2e60  (unknown)
    @     0x2b7f7192631a  (unknown)
    @     0x2b7f72db4390  _ZNSt17_Function_handlerIFN7oneflow5MaybeINS0_3one6TensorEvEERKSt10shared_ptrIS3_ERKNS0_6SymbolINS0_12ParallelDescEEERKSt6vectorINS9_INS0_3cfg11SbpParallelEEESaISH_EESL_EZNS2_10functional18PackedFunctorMakerIFS4_S8_SB_SL_SL_EE4makeINSN_4impl19ToConsistentFunctorELi0EEENSN_13PackedFunctorISM_EERKSsRKT_EUlS8_SD_SL_SL_E_E9_M_invokeERKSt9_Any_dataS8_SD_SL_SL_
    @     0x2b09eb6cf769  oneflow::RankGroup::GetDefaultParallelDesc()
    @     0x2b7f756cb1d0  oneflow::one::functional::ToConsistent()
    @     0x2b09e9eb931a  (unknown)
    @     0x2b7f7251f142  (unknown)
    @     0x2b09eb347390  _ZNSt17_Function_handlerIFN7oneflow5MaybeINS0_3one6TensorEvEERKSt10shared_ptrIS3_ERKNS0_6SymbolINS0_12ParallelDescEEERKSt6vectorINS9_INS0_3cfg11SbpParallelEEESaISH_EESL_EZNS2_10functional18PackedFunctorMakerIFS4_S8_SB_SL_SL_EE4makeINSN_4impl19ToConsistentFunctorELi0EEENSN_13PackedFunctorISM_EERKSsRKT_EUlS8_SD_SL_SL_E_E9_M_invokeERKSt9_Any_dataS8_SD_SL_SL_
    @     0x2b09edc5e1d0  oneflow::one::functional::ToConsistent()
    @     0x2b7f72218ce0  (unknown)
    @     0x2b09eaab2142  (unknown)
    @     0x2b7f71ff3f47  (unknown)
    @     0x2b7d5d9897e7  _PyCFunction_FastCallDict
    @     0x2b7d5d9f514f  (unknown)
    @     0x2b7d5d9e9a17  _PyEval_EvalFrameDefault
    @     0x2b7d5d9f4317  (unknown)
    @     0x2b7d5d9f4fea  (unknown)
    @     0x2b7d5d9f5273  (unknown)
    @     0x2b7d5d9eac91  _PyEval_EvalFrameDefault
    @     0x2b7d5d9f44f9  (unknown)
    @     0x2b7d5d9f4fea  (unknown)
    @     0x2b7d5d9f5273  (unknown)
    @     0x2b7d5d9e9a17  _PyEval_EvalFrameDefault
    @     0x2b7d5d9f4f3a  (unknown)
    @     0x2b7d5d9f5273  (unknown)
    @     0x2b7d5d9e9a17  _PyEval_EvalFrameDefault
    @     0x2b7d5d9f4f3a  (unknown)
    @     0x2b7d5d9f5273  (unknown)
    @     0x2b7d5d9e9a17  _PyEval_EvalFrameDefault
    @     0x2b7d5d9f4f3a  (unknown)
    @     0x2b09ea7abce0  (unknown)
    @     0x2b09ea586f47  (unknown)
    @     0x2b07d5f1c7e7  _PyCFunction_FastCallDict
    @     0x2b07d5f8814f  (unknown)
    @     0x2b07d5f7ca17  _PyEval_EvalFrameDefault
    @     0x2b07d5f87317  (unknown)
    @     0x2b07d5f87fea  (unknown)
    @     0x2b07d5f88273  (unknown)
    @     0x2b07d5f7dc91  _PyEval_EvalFrameDefault
    @     0x2b07d5f874f9  (unknown)
    @     0x2b07d5f87fea  (unknown)
    @     0x2b07d5f88273  (unknown)
    @     0x2b07d5f7ca17  _PyEval_EvalFrameDefault
    @     0x2b07d5f87f3a  (unknown)
    @     0x2b07d5f88273  (unknown)
    @     0x2b07d5f7ca17  _PyEval_EvalFrameDefault
    @     0x2b07d5f87f3a  (unknown)
    @     0x2b07d5f88273  (unknown)
    @     0x2b07d5f7ca17  _PyEval_EvalFrameDefault
    @     0x2b07d5f87f3a  (unknown)
Killing subprocess 88430
Killing subprocess 88431
`

**Comment by chengtbf** [comment]
这里的报错信息显示是当前物理机器只有2张卡，但是配置的 placement 包含了 CUDA:2 （实际上只能配置 CUDA:0 和  CUDA1）。 所以检查失败了。

**Comment by muzhailong** [comment]
> 这里的报错信息显示是当前物理机器只有2张卡，但是配置的 placement 包含了 CUDA:2 （实际上只能配置 CUDA:0 和 CUDA1）。 所以检查失败了。

没有的，你看我代码里面没有配置cuda:2

**Comment by chengtbf** [comment]
> (

嗯嗯 报错是 RankGroup 启动的时候就报错了，其实还没有走到 graph 的构图里。

@clackhan 彬彬可以看一下。报错位置是：

https://github.com/Oneflow-Inc/oneflow/blob/c071635f707767707c3d0bbd7db2a37beb872d2f/oneflow/core/job/rank_group.cpp#L55


```
Maybe<Symbol<ParallelDesc>> CalcDefaultParallelDesc(DeviceType device_type,
                                                    Symbol<RankGroup> rank_group) {
  ParallelConf parallel_conf;
  parallel_conf.set_device_tag(*JUST(DeviceTag4DeviceType(device_type)));
  JUST(rank_group->ForEachRank([&](int64_t rank) -> Maybe<void> {
    int64_t local_rank = GlobalProcessCtx::LocalRank(rank);
    parallel_conf.add_device_name(std::string("@") + std::to_string(rank) + ":"
                                  + std::to_string(local_rank));
    return Maybe<void>::Ok();
  }));
  return SymbolOf(ParallelDesc(parallel_conf));
}
```

这里的 local rank 的结果是 3。 但实际上应该是 0，1，0，1。

用户的启动脚本是:

```
export PYTHONUNBUFFERED=1
python3 -m oneflow.distributed.launch \
    --nproc_per_node 2 \
    --nnodes 2 \
    --node_rank 1 \
    --master_addr cn16 \
    run_eager_pretraining.py \
    --num_hidden_layers 12 \
    --num_attention_heads 12 \
    --max_position_embeddings 512 \
    --seq_length 128 \
    --vocab_size 30522 \
    --type_vocab_size 2 \
    --attention_probs_dropout_prob 0.1 \
    --hidden_dropout_prob 0.1 \
    --max_predictions_per_seq 20 \
    --train-batch-size 32 \
    --train-global-batch-size 64 \
    --learning_rate 0.00005 \
    --ofrecord_path ./data/wiki_ofrecord_seq_len_128 \
    2>&1 | tee bert_eager_pretrain.log
```

**Comment by muzhailong** [comment]
> 

所以是oneflow的bug吗？

**Comment by muzhailong** [comment]
> > > 这里的报错信息显示是当前物理机器只有2张卡，但是配置的 placement 包含了 CUDA:2 （实际上只能配置 CUDA:0 和 CUDA1）。 所以检查失败了。
> > 
> > 
> > 没有的，你看我代码里面没有配置cuda:2
> 
> 嗯嗯 报错是 RankGroup 启动的时候就报错了，其实还没有走到 graph 的构图里。
> 
> @clackhan 彬彬可以看一下。报错位置是：
> 
> https://github.com/Oneflow-Inc/oneflow/blob/c071635f707767707c3d0bbd7db2a37beb872d2f/oneflow/core/job/rank_group.cpp#L55
> 
> ```
> Maybe<Symbol<ParallelDesc>> CalcDefaultParallelDesc(DeviceType device_type,
>                                                     Symbol<RankGroup> rank_group) {
>   ParallelConf parallel_conf;
>   parallel_conf.set_device_tag(*JUST(DeviceTag4DeviceType(device_type)));
>   JUST(rank_group->ForEachRank([&](int64_t rank) -> Maybe<void> {
>     int64_t local_rank = GlobalProcessCtx::LocalRank(rank);
>     parallel_conf.add_device_name(std::string("@") + std::to_string(rank) + ":"
>                                   + std::to_string(local_rank));
>     return Maybe<void>::Ok();
>   }));
>   return SymbolOf(ParallelDesc(parallel_conf));
> }
> ```
> 
> 这里的 local rank 的结果是 3。 但实际上应该是 0，1，0，1。
> 
> 用户的启动脚本是:
> 
> ```
> export PYTHONUNBUFFERED=1
> python3 -m oneflow.distributed.launch \
>     --nproc_per_node 2 \
>     --nnodes 2 \
>     --node_rank 1 \
>     --master_addr cn16 \
>     run_eager_pretraining.py \
>     --num_hidden_layers 12 \
>     --num_attention_heads 12 \
>     --max_position_embeddings 512 \
>     --seq_length 128 \
>     --vocab_size 30522 \
>     --type_vocab_size 2 \
>     --attention_probs_dropout_prob 0.1 \
>     --hidden_dropout_prob 0.1 \
>     --max_predictions_per_seq 20 \
>     --train-batch-size 32 \
>     --train-global-batch-size 64 \
>     --learning_rate 0.00005 \
>     --ofrecord_path ./data/wiki_ofrecord_seq_len_128 \
>     2>&1 | tee bert_eager_pretrain.log
> ```

所以是oneflow的bug吗？

**Comment by clackhan** [comment]
> 所以是oneflow的bug吗？

您好，这个需要看一下日志才能确认，可以贴一下日志吗，在执行脚本的目录中有个 log 目录，在 ```log/{机器名}/```目录中有个```oneflow.INFO```文件，可以贴一下里面的内容吗？

**Comment by muzhailong** [comment]
> > 所以是oneflow的bug吗？
> 
> 您好，这个需要看一下日志才能确认，可以贴一下日志吗，在执行脚本的目录中有个 log 目录，在 `log/{机器名}/`目录中有个`oneflow.INFO`文件，可以贴一下里面的内容吗？

`Log file created at: 2021/12/17 09:38:12
Running on machine: cn16
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1217 09:38:12.975025 88813 global.h:36] NewGlobal N7oneflow7EnvDescE
I1217 09:38:12.976976 88813 global.h:36] NewGlobal N7oneflow10ProcessCtxE
I1217 09:38:12.977001 88813 env_global_objects_scope.cpp:157] using rpc backend: gRPC
I1217 09:38:12.977015 88813 global.h:36] NewGlobal N7oneflow10CtrlServerE
I1217 09:38:12.977730 88813 ctrl_server.cpp:40] CtrlServer listening on 0.0.0.0:35109
I1217 09:38:12.977864 88813 rank_info_bootstrap_server.cpp:47] RankInfoBootstrapServer listening on 0.0.0.0:40282
I1217 09:38:46.876663 88813 rpc_client.cpp:187] LoadServer cn16 Successful at 0 times
I1217 09:38:46.878870 88813 ctrl_bootstrap.cpp:77] 
ctrl_addr {
  host: "cn16"
  port: 35262
}
ctrl_addr {
  host: "172.16.0.26"
  port: 33742
}
ctrl_addr {
  host: "172.16.0.26"
  port: 35109
}
ctrl_addr {
  host: "172.16.0.26"
  port: 45218
}
rank: 2
node_size: 1
I1217 09:39:16.884075 88813 rpc_client.cpp:187] LoadServer cn16 Successful at 0 times
I1217 09:39:16.885440 88813 rpc_client.cpp:187] LoadServer 172.16.0.26 Successful at 0 times
I1217 09:39:16.886965 88813 rpc_client.cpp:187] LoadServer 172.16.0.26 Successful at 0 times
I1217 09:39:16.888304 88813 rpc_client.cpp:187] LoadServer 172.16.0.26 Successful at 0 times
I1217 09:39:16.956300 88813 global.h:36] NewGlobal N7oneflow12ResourceDescE
I1217 09:39:16.956411 88813 global.h:36] NewGlobal N7oneflow12ResourceDescE
I1217 09:39:16.963418 88813 net_ib_device_descriptor.cpp:110] Inactivate port: device mlx5_0 port 
I1217 09:39:16.967567 88813 net_ib_device_descriptor.cpp:110] Inactivate port: device mlx5_1 port 
I1217 09:39:16.976408 88813 net_ib_device_descriptor.cpp:110] Inactivate port: device mlx5_3 port 
I1217 09:39:17.263284 88813 global.h:36] NewGlobal N7oneflow2ep21DeviceManagerRegistryE
I1217 09:39:17.263350 88813 global.h:36] NewGlobal N7oneflow10ThreadPoolE
I1217 09:39:17.264904 88813 global.h:36] NewGlobal N7oneflow16EagerNcclCommMgrE
I1217 09:39:17.264932 88813 global.h:36] NewGlobal N7oneflow18CudnnConvAlgoCacheE
I1217 09:39:17.264945 88813 global.h:36] NewGlobal N7oneflow2vm19VirtualMachineScopeE
I1217 09:39:17.264961 88813 global.h:36] NewGlobal N7oneflow14VirtualMachineE
I1217 09:39:17.265286 88813 virtual_machine.cpp:80] transport stream type: N7oneflow2vm13CpuStreamTypeE
I1217 09:39:17.265308 88813 virtual_machine.cpp:80] transport stream type: N7oneflow2vm14CudaStreamTypeE
I1217 09:39:17.265321 88813 virtual_machine.cpp:80] transport stream type: N7oneflow2vm19AsyncCudaStreamTypeE
I1217 09:39:17.265552 88813 global.h:36] NewGlobal N7oneflow27EagerJobBuildAndInferCtxMgrE
I1217 09:39:17.265612 88813 global.h:36] NewGlobal N7oneflow12EpollCommNetE
I1217 09:39:17.265784 88813 epoll_comm_network.cpp:63] CommNet:Epoll listening on 0.0.0.0:42264
I1217 09:39:17.271167 88813 epoll_comm_network.cpp:197] machine 0 sockfd 56
I1217 09:39:17.271205 88813 epoll_comm_network.cpp:197] machine 1 sockfd 58
I1217 09:39:17.271215 88813 epoll_comm_network.cpp:197] machine 2 sockfd -1
I1217 09:39:17.271224 88813 epoll_comm_network.cpp:197] machine 3 sockfd 54
I1217 09:39:17.271335 88813 global.h:36] NewGlobal N7oneflow9TransportE
I1217 09:39:17.271438 88813 global.h:43] DeleteGlobal N7oneflow17ForeignLockHelperE
I1217 09:39:17.271571 88813 global.h:36] NewGlobal N7oneflow25MultiClientSessionContextE
F1217 09:39:23.075722 88813 parallel_desc.cpp:76] 
  File "/root/muzhailong/oneflow/oneflow/core/job/parallel_desc.cpp", line 76, in ParallelDesc
    CheckWithResourceDesc(*(Global<ResourceDesc, ForSession>::Get()))
  File "/root/muzhailong/oneflow/oneflow/core/job/parallel_desc.cpp", line 298, in CheckWithResourceDesc
    Check failed: (dev_phy_id) < (resource_desc.GpuDeviceNum()) (3 vs 2)
`

**Comment by clackhan** [comment]
```
ctrl_addr {
  host: "cn16"
  port: 35262
}
ctrl_addr {
  host: "172.16.0.26"
  port: 33742
}
ctrl_addr {
  host: "172.16.0.26"
  port: 35109
}
ctrl_addr {
  host: "172.16.0.26"
  port: 45218
}
node_size: 1
```
从日志中看，您好像是在同一台机器上启动了两次脚本，如果您想要跑两机的话需要在两台机器上分别执行启动脚本的

**Comment by muzhailong** [comment]
> 

但是我确实是启动了一次脚本，我试了好几次都是这个错误

**Comment by muzhailong** [comment]
> > ```
> > ctrl_addr {
> >   host: "cn16"
> >   port: 35262
> > }
> > ctrl_addr {
> >   host: "172.16.0.26"
> >   port: 33742
> > }
> > ctrl_addr {
> >   host: "172.16.0.26"
> >   port: 35109
> > }
> > ctrl_addr {
> >   host: "172.16.0.26"
> >   port: 45218
> > }
> > node_size: 1
> > ```
> 
> 从日志中看，您应该是在同一台机器上启动了两次脚本，如果您想要跑两机的话需要在两台机器上分别执行启动脚本的

但是我确实值启动了一次脚本，试了好几次都是这个错误，加个QQ聊一下?

**Comment by clackhan** [comment]
> 但是我确实值启动了一次脚本，试了好几次都是这个错误，加个QQ聊一下?

好的。578502734

**Comment by muzhailong** [comment]
> > 但是我确实值启动了一次脚本，试了好几次都是这个错误，加个QQ聊一下?
> 
> 好的。578502734

好像打脸了，确实在一个节点上哈哈哈，我zz了

**Comment by clackhan** [comment]
> > > 但是我确实值启动了一次脚本，试了好几次都是这个错误，加个QQ聊一下?
> > 
> > 
> 
> 好像打脸了，确实在一个节点上哈哈哈，我zz了

好的。
