### ISSUE TITLE
混合并行训练，同一台机子上，其中一张显卡显存占用比另一张多了一倍

### ISSUE THREAD

**Issue by muzhailong** [Oneflow-Inc/oneflow#7084]
代码：https://gitee.com/mzl2020/oneflow_models/tree/master/bert
执行：./run_distribute.sh

**Comment by lixiang007666** [comment]
在https://gitee.com/mzl2020/oneflow_models/blob/master/bert/train.py中：

<img width="399" alt="image" src="https://user-images.githubusercontent.com/54010254/147082550-0d0f0473-2505-4b71-919b-2c936d7e558c.png">

0号机的0号卡和0号机的1号卡不在同一个placement，就会导致显存不一样。
改成注释掉的方式，就一致了。
