### ISSUE TITLE
[BUG] 在graph里跑 reshape op的0 size tensor testcase报错

### ISSUE THREAD

**Issue by grybd** [Oneflow-Inc/oneflow#7120]
把test_reshape.py的test_reshape_with_0_size_data testcase自动测试的第2个参数设置为 check_graph=True，然后跑test_reshape.py报错

报错信息：

FAIL: test_reshape_with_0_size_data (__main__.TestModule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fengdaochao/fdz/oneflow/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 631, in new_f
    res = f(test_case)
  File "/home/fengdaochao/fdz/oneflow/python/oneflow/test/modules/test_reshape.py", line 109, in test_reshape_with_0_size_data
    y = torch.reshape(
  File "/home/fengdaochao/fdz/oneflow/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 320, in dual_method
    test_g_res = test_g()
  File "/home/fengdaochao/fdz/oneflow/python/oneflow/nn/graph/graph.py", line 258, in __call__
    self._compile(*args)
  File "/home/fengdaochao/fdz/oneflow/python/oneflow/nn/graph/graph.py", line 497, in _compile
    eager_outputs = self._build_graph(*args)
  File "/home/fengdaochao/fdz/oneflow/python/oneflow/nn/graph/graph.py", line 605, in _build_graph
    ) = self._build_io("output", graph_build_util.build_graph_output, *outputs)
  File "/home/fengdaochao/fdz/oneflow/python/oneflow/nn/graph/graph.py", line 809, in _build_io
    build_args.append(build_tensor_or_none(arg, name, repr_str))
  File "/home/fengdaochao/fdz/oneflow/python/oneflow/nn/graph/graph.py", line 789, in build_tensor_or_none
    build_arg = build_func(name, tensor)
  File "/home/fengdaochao/fdz/oneflow/python/oneflow/framework/graph_build_util.py", line 167, in build_graph_output
    assert out.is_lazy
AssertionError

**Comment by strint** [comment]
看一下ReShapeFunctor的实现，贴到这里。然后分析下。大概率是这个层面的问题

**Comment by grybd** [comment]
> 看一下ReShapeFunctor的实现，贴到这里。然后分析下。大概率是这个层面的问题

好的

**Comment by Flowingsun007** [comment]
和我在issue：https://github.com/Oneflow-Inc/OneTeam/issues/913 里遇到的是同类问题，把ReshapeFunctor里的`if (x->is_eager() && x->is_local())` 改成`if (x->is_local() && !(LazyMode::is_enabled()))`
应该就可以了

**Comment by grybd** [comment]
> 和我在issue：[Oneflow-Inc/OneTeam#913](https://github.com/Oneflow-Inc/OneTeam/issues/913) 里遇到的是同类问题，把ReshapeFunctor里的`if (x->is_eager() && x->is_local())` 改成`if (x->is_local() && !(LazyMode::is_enabled()))` 应该就可以了

是的，把`if (x->is_eager() && x->is_local())` 改成`if (x->is_local() && !(LazyMode::is_enabled()))` 问题得到了解决

**Comment by grybd** [comment]
#### 报错的原因和处理办法
graph reshape op autotest 会调用ReshapeFunctor函数执行体对reshape op做测试，但是当输入ReshapeFunctortensor()的tensor是eager&&local tensor 时ReshapeFunctor 会直接调用view::view::Reshape(x, shape) 执行完这部分逻辑就返回一个tensor，而不会继续设置 attrs,调用OpInterpUtil::Dispatch<Tensor>(*op_, {x}, attrs)，完成对lazy 模式下的reshape op计算，所以需要加入if (x->is_local() && !(LazyMode::is_enabled())) 避免在graph reshape op的autotest 走到view::shape()分支进行计算
ReshapeFunctor的实现：
```cpp

class ReshapeFunctor {
 public:
  ReshapeFunctor() {
    op_ = CHECK_JUST(one::OpBuilder("reshape").Input("in").Output("out").Build());
  }
  Maybe<Tensor> operator()(const std::shared_ptr<one::Tensor>& x, const Shape& shape) const {
    // if input tensor is eager local, than return tensor's view
    std::cout<<"(LazyMode::is_enabled())"<<LazyMode::is_enabled()<<"x->is_lazy():"<<x->is_lazy()<<"x->is_eager():"<<x->is_eager()<<"x->is_local():"<<x->is_local()<<std::endl;
    if (x->is_eager() && x->is_local()) { return view::Reshape(x, shape); }
    int need_infer_axis = -1;
    size_t count = 1;
    for (int i = 0; i < shape.NumAxes(); ++i) {
      if (shape.At(i) < -1) {
        return Error::RuntimeError() << "Invalid shape dimension " << shape.At(i);
      } else if (shape.At(i) == -1) {
        CHECK_EQ_OR_RETURN(need_infer_axis, -1)
            << "Shape " << shape.ToString() << " has more than 1 axis that needs to be infered.";
        need_infer_axis = i;
      } else {
        count *= shape.At(i);
      }
    }
    size_t x_count = x->shape()->Count(0);
    MutableAttrMap attrs;
    if (need_infer_axis == -1) {
      CHECK_EQ_OR_RETURN(shape.Count(0), x_count)
          << "\n Shape " << shape.ToString() << " is invalid for input shape "
          << x->shape()->ToString();
      JUST(attrs.SetAttr<Shape>("shape", shape));
    } else {
      Shape infered_shape = shape;
      infered_shape.Set(need_infer_axis, x_count / count);
      CHECK_EQ_OR_RETURN(infered_shape.Count(0), x_count)
          << "\n Shape " << shape.ToString() << " is invalid for input shape "
          << x->shape()->ToString();
      JUST(attrs.SetAttr<Shape>("shape", infered_shape));
    }
    return OpInterpUtil::Dispatch<Tensor>(*op_, {x}, attrs);
  }

 private:
  std::shared_ptr<OpExpr> op_;
};
```
