### ISSUE TITLE
[BUG] 跑test_eye.py中的testcase报错

### ISSUE THREAD

**Issue by grybd** [Oneflow-Inc/oneflow#7133]
####  背景信息
 将test_eye.py文件中的check_graph=False改为check_graph=True，再跑test_eye.py报错

报错信息：

Traceback (most recent call last):
  File "/home/fengdaochao/fdz/oneflow/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 706, in new_f
    test_case.assertTrue(
AssertionError: False is not true : test_eye_with_random_data cannot find module to check graph.

**Comment by grybd** [comment]
这个bug可能需要 @BBuf 处理一下

**Comment by BBuf** [comment]
好，我会在我最新的pr里面处理。

**Comment by BBuf** [comment]
我正在依次处理这些graph的问题，你碰到的这个问题在这个列表里面：https://github.com/Oneflow-Inc/OneTeam/issues/885#issuecomment-1001357244
