### ISSUE TITLE
[BUG] 跑test_var.py中的0 size data testcase报错

### ISSUE THREAD

**Issue by grybd** [Oneflow-Inc/oneflow#7141]
#### 背景信息

将test_var.py 第45行@unittest.skip("var not support 0-shape tensor currently")去掉，并设置check_graph=True,此时test_flow_var_0_size_data_with_random_data这个testcase 报错
报错信息：Check failed: (reduce_count) > (0) (0 vs 0)

出错原因：
目前的ReduceMeanFunctor还未支持 0 size tensor 可以看ReduceMeanFunctor的实现：
```cpp
class ReduceMeanFunctor {
 public:
  ReduceMeanFunctor() {}
  Maybe<Tensor> operator()(const std::shared_ptr<one::Tensor>& x, const std::vector<int32_t>& axis,
                           const bool& keepdims) const {
    // ReduceMean only calculate floating values.
    CHECK_OR_RETURN(IsFloatingDataType(x->dtype()->data_type()))
        << "RuntimeError: Can only calculate the mean of floating types.";
    const auto& sum = JUST(functional::ReduceSum(x, axis, keepdims));
    size_t reduce_count = 1;
    if (axis.empty()) {
      reduce_count = x->shape()->Count(0);
    } else {
      for (const int32_t& i : axis) { reduce_count *= x->shape()->At(i); }
    }
    if (reduce_count == 1) { return sum; }
    CHECK_GT_OR_RETURN(reduce_count, 0);
    return functional::ScalarMul(sum, 1.0 / reduce_count, false);
  }
};
```
当 x 是0 size tensor reduce_count=0，所以CHECK_GT_OR_RETURN(reduce_count, 0)会报错，所以这里可能需要提供support 0 size tensor的ReduceMeanFunctor

解决思路：
对齐torch 的mean()接口实现，目前torch  mean op kernel对于 0size tensor的处理是返回nan ，但是目前还没找到具体实现，明天编译pytorch 代码跟一下
torch mean()接口说明：
             torch.mean(input, dim, keepdim=False, *, dtype=None, out=None) → Tensor
Returns the mean value of each row of the input tensor in the given dimension dim. If dim is a list of dimensions, reduce over all of them.
If keepdim is True, the output tensor is of the same size as input except in the dimension(s) dim where it is of size 1. Otherwise, dim is squeezed (see torch.squeeze()), resulting in the output tensor having 1 (or len(dim)) fewer dimension(s).

torch mean接口实现：(目测是这个，继续跟进确认)
```cpp
TORCH_IMPL_FUNC(mean_out)
(const Tensor& self,
 IntArrayRef dim,
 bool keepdim,
 c10::optional<ScalarType> opt_dtype,
 const Tensor& result) {
  ScalarType dtype = result.scalar_type();
  // TODO: the TensorIterator reduction implementation of mean
  // (mean_kernel_impl()) is unvectorized and leads to very poor performance
  // for production workloads. Once that's fixed, the following code can be used
  // in lieu of the sum + divide implementation below.
  if (self.device().is_cpu()) {
    int64_t dim_prod = 1;
    if (dim.size() == 0 || self.ndimension() == 0) {
      dim_prod = self.numel();
    } else {
      for (auto d : dim) {
        dim_prod *= self.size(d);
      }
    }
    auto& result_mut = const_cast<Tensor&>(result);
    at::sum_out(result_mut, self, dim, keepdim, dtype).div_(dim_prod);
  } else {
    DimVector dims(dim);
    auto iter = at::meta::make_reduction_from_out_ty(
        self, result, dims, keepdim, dtype);
    if (iter.numel() == 0) {
      result.fill_(std::numeric_limits<double>::quiet_NaN());
    } else {
      mean_stub(iter.device_type(), iter);
    }
  }
}

示例：

 x = torch.rand((2,0,3))
 x
tensor([], size=(2, 0, 3))

x.mean()
tensor(nan)

**Comment by strint** [comment]
```
>>> x = torch.tensor([[torch.nan,1,2],[1,2,3]])
>>> print(x)
tensor([[nan, 1., 2.],
        [1., 2., 3.]])
>>> x.size
<built-in method size of Tensor object at 0x7f874a4fe230>
>>> x.size()
torch.Size([2, 3])
```

torch.tensor([[torch.nan,1,2],[1,2,3]])构造出的并不是一个0 size tensor。

另外后面的示例可以改下，改成交互式的，一行代码对应一行结果

**Comment by strint** [comment]
torch.nan类型调研下看看，它的内部表达是什么

oneflow当前的数据类型
```
enum DataType : int {
  kInvalidDataType = 0,  // 看看能否使用这个，还是要新建一个
  kChar = 1,
  kFloat = 2,
  kDouble = 3,
  kInt8 = 4,
  kInt32 = 5,
  kInt64 = 6,
  kUInt8 = 7,
  kOFRecord = 8,
  kFloat16 = 9,
  kTensorBuffer = 10,
  kBFloat16 = 11,
  kBool = 12,
  kUInt16 = 13,
  kUInt32 = 14,
  kUInt64 = 15,
  kUInt128 = 16,
  kInt16 = 17,
  kInt128 = 18,
  kComplex32 = 19,
  kComplex64 = 20,
  kComplex128 = 21
};
```

**Comment by grybd** [comment]
> ```
> >>> x = torch.tensor([[torch.nan,1,2],[1,2,3]])
> >>> print(x)
> tensor([[nan, 1., 2.],
>         [1., 2., 3.]])
> >>> x.size
> <built-in method size of Tensor object at 0x7f874a4fe230>
> >>> x.size()
> torch.Size([2, 3])
> ```
> 
> torch.tensor([[torch.nan,1,2],[1,2,3]])构造出的并不是一个0 size tensor。
> 
> 另外后面的示例可以改下，改成交互式的，一行代码对应一行结果

好的，我修改一下，示例里提供的是两个特例x = torch.tensor([[torch.nan,1,2],[1,2,3]])这是其中一个，用来说明torch对这种tensor的支持效果，还有最后一个torcn.tensor([])是0size的输入，输出为nan

**Comment by grybd** [comment]
> torch.nan类型调研下看看，它的内部表达是什么
> 
> oneflow当前的数据类型
> 
> ```
> enum DataType : int {
>   kInvalidDataType = 0,  // 看看能否使用这个，还是要新建一个
>   kChar = 1,
>   kFloat = 2,
>   kDouble = 3,
>   kInt8 = 4,
>   kInt32 = 5,
>   kInt64 = 6,
>   kUInt8 = 7,
>   kOFRecord = 8,
>   kFloat16 = 9,
>   kTensorBuffer = 10,
>   kBFloat16 = 11,
>   kBool = 12,
>   kUInt16 = 13,
>   kUInt32 = 14,
>   kUInt64 = 15,
>   kUInt128 = 16,
>   kInt16 = 17,
>   kInt128 = 18,
>   kComplex32 = 19,
>   kComplex64 = 20,
>   kComplex128 = 21
> };
> ```

好的

**Comment by strint** [comment]
参考资料：
https://github.com/pytorch/pytorch/issues/4767
https://github.com/pytorch/pytorch/pull/5273

调研下情况
