### ISSUE TITLE
之前可以完美执行的，今天想再跑一下突然就启动的地方一直卡住

### ISSUE THREAD

**Issue by muzhailong** [Oneflow-Inc/oneflow#7149]
单机不用distribute模块可以跑，单机用了distribute模块跑不了
`muzhailong@cn5 bert]$ ./run_distribute.sh 0
loaded library: /lib64/libibverbs.so.1
`

**Comment by muzhailong** [comment]
> 单机不用distribute模块可以跑，单机用了distribute模块跑不了 `muzhailong@cn5 bert]$ ./run_distribute.sh 0 loaded library: /lib64/libibverbs.so.1 `

很迷呀，心态炸裂

**Comment by chengtbf** [comment]
我看了一下脚本，这里的脚本是 3 机启动？

https://gitee.com/mzl2020/oneflow_models/blob/master/bert/run_distribute.sh#L5

```sh
#!/bin/bash
export PYTHONUNBUFFERED=1
python3 -m oneflow.distributed.launch \
    --nproc_per_node 3 \
    --nnodes 3 \
    --node_rank $1 \
    --master_addr cn5 \
    --master_port 7788 \
    train.py \
    --use_consistent True \
    --num_hidden_layers 24 \
    --num_attention_heads 32 \
    --max_position_embeddings 512 \
    --gpu_num_per_node 3 \
    --grad-acc-steps 1 \
    --seq_length 128 \
    --vocab_size 30522 \
    --type_vocab_size 2 \
    --attention_probs_dropout_prob 0.1 \
    --train-data-part 1 \
    --hidden_dropout_prob 0.1 \
    --max_predictions_per_seq 20 \
    --train-global-batch-size 24 \
    --learning_rate 0.00005 \
    --ofrecord_path ../data/wiki_ofrecord_seq_len_128 \
    --nums_split 3 \
    --strategy inter_first \
    2>&1 | tee bert_eager_pretrain.log
```

但是你只启动了一个机器，所以找不到其他机器一直在等待中吧

**Comment by muzhailong** [comment]
> 我看了一下脚本，这里的脚本是 3 机启动？
> 
> https://gitee.com/mzl2020/oneflow_models/blob/master/bert/run_distribute.sh#L5
> 
> ```shell
> #!/bin/bash
> export PYTHONUNBUFFERED=1
> python3 -m oneflow.distributed.launch \
>     --nproc_per_node 3 \
>     --nnodes 3 \
>     --node_rank $1 \
>     --master_addr cn5 \
>     --master_port 7788 \
>     train.py \
>     --use_consistent True \
>     --num_hidden_layers 24 \
>     --num_attention_heads 32 \
>     --max_position_embeddings 512 \
>     --gpu_num_per_node 3 \
>     --grad-acc-steps 1 \
>     --seq_length 128 \
>     --vocab_size 30522 \
>     --type_vocab_size 2 \
>     --attention_probs_dropout_prob 0.1 \
>     --train-data-part 1 \
>     --hidden_dropout_prob 0.1 \
>     --max_predictions_per_seq 20 \
>     --train-global-batch-size 24 \
>     --learning_rate 0.00005 \
>     --ofrecord_path ../data/wiki_ofrecord_seq_len_128 \
>     --nums_split 3 \
>     --strategy inter_first \
>     2>&1 | tee bert_eager_pretrain.log
> ```
> 
> 但是你只启动了一个机器，所以找不到其他机器一直在等待中吧

不是，这里我改了，之前那个脚本我是可以跑通的。现在三机也跑不通了，也是卡这里

**Comment by chengtbf** [comment]
可以看一下 `./log/cn5/oneflow.INFO` 里的信息吗

**Comment by muzhailong** [comment]
> 可以看一下 `./log/cn5/oneflow.INFO` 里的信息吗

`Log file created at: 2021/12/30 15:31:46
Running on machine: cn5
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1230 15:31:46.939850 93621 global.h:36] NewGlobal N7oneflow7EnvDescE
I1230 15:31:46.942122 93621 global.h:36] NewGlobal N7oneflow10ProcessCtxE
I1230 15:31:46.942148 93621 env_global_objects_scope.cpp:150] using rpc backend: local
I1230 15:32:03.211805 93621 global.h:36] NewGlobal N7oneflow12ResourceDescE
I1230 15:32:03.212733 93621 global.h:36] NewGlobal N7oneflow12ResourceDescE
I1230 15:32:03.218744 93621 net_ib_device_descriptor.cpp:110] Inactivate port: device mlx5_0 port 
I1230 15:32:03.223521 93621 net_ib_device_descriptor.cpp:110] Inactivate port: device mlx5_1 port 
I1230 15:32:03.228672 93621 net_ib_device_descriptor.cpp:110] Inactivate port: device mlx5_3 port 
I1230 15:32:03.291414 93621 global.h:36] NewGlobal N7oneflow2ep21DeviceManagerRegistryE
I1230 15:32:03.291455 93621 global.h:36] NewGlobal N7oneflow10ThreadPoolE
I1230 15:32:03.292594 93621 global.h:36] NewGlobal N7oneflow16EagerNcclCommMgrE
I1230 15:32:03.292618 93621 global.h:36] NewGlobal N7oneflow18CudnnConvAlgoCacheE
I1230 15:32:03.292632 93621 global.h:36] NewGlobal N7oneflow2vm19VirtualMachineScopeE
I1230 15:32:03.292652 93621 global.h:36] NewGlobal N7oneflow14VirtualMachineE
I1230 15:32:03.293006 93621 virtual_machine.cpp:80] transport stream type: N7oneflow2vm13CpuStreamTypeE
I1230 15:32:03.293023 93621 virtual_machine.cpp:80] transport stream type: N7oneflow2vm14CudaStreamTypeE
I1230 15:32:03.293042 93621 virtual_machine.cpp:80] transport stream type: N7oneflow2vm19AsyncCudaStreamTypeE
I1230 15:32:03.293184 93621 global.h:36] NewGlobal N7oneflow27EagerJobBuildAndInferCtxMgrE
I1230 15:32:03.293231 93621 global.h:36] NewGlobal N7oneflow12EpollCommNetE
I1230 15:32:03.293397 93621 epoll_comm_network.cpp:63] CommNet:Epoll listening on 0.0.0.0:34117
I1230 15:32:03.293437 93621 epoll_comm_network.cpp:197] machine 0 sockfd -1
I1230 15:32:03.293527 93621 global.h:36] NewGlobal N7oneflow9TransportE
I1230 15:32:03.293648 93621 global.h:43] DeleteGlobal N7oneflow17ForeignLockHelperE
I1230 15:32:03.293788 93621 global.h:36] NewGlobal N7oneflow25MultiClientSessionContextE
`

**Comment by muzhailong** [comment]
> > 可以看一下 `./log/cn5/oneflow.INFO` 里的信息吗
> 
> `Log file created at: 2021/12/30 15:31:46 Running on machine: cn5 Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg I1230 15:31:46.939850 93621 global.h:36] NewGlobal N7oneflow7EnvDescE I1230 15:31:46.942122 93621 global.h:36] NewGlobal N7oneflow10ProcessCtxE I1230 15:31:46.942148 93621 env_global_objects_scope.cpp:150] using rpc backend: local I1230 15:32:03.211805 93621 global.h:36] NewGlobal N7oneflow12ResourceDescE I1230 15:32:03.212733 93621 global.h:36] NewGlobal N7oneflow12ResourceDescE I1230 15:32:03.218744 93621 net_ib_device_descriptor.cpp:110] Inactivate port: device mlx5_0 port � I1230 15:32:03.223521 93621 net_ib_device_descriptor.cpp:110] Inactivate port: device mlx5_1 port � I1230 15:32:03.228672 93621 net_ib_device_descriptor.cpp:110] Inactivate port: device mlx5_3 port � I1230 15:32:03.291414 93621 global.h:36] NewGlobal N7oneflow2ep21DeviceManagerRegistryE I1230 15:32:03.291455 93621 global.h:36] NewGlobal N7oneflow10ThreadPoolE I1230 15:32:03.292594 93621 global.h:36] NewGlobal N7oneflow16EagerNcclCommMgrE I1230 15:32:03.292618 93621 global.h:36] NewGlobal N7oneflow18CudnnConvAlgoCacheE I1230 15:32:03.292632 93621 global.h:36] NewGlobal N7oneflow2vm19VirtualMachineScopeE I1230 15:32:03.292652 93621 global.h:36] NewGlobal N7oneflow14VirtualMachineE I1230 15:32:03.293006 93621 virtual_machine.cpp:80] transport stream type: N7oneflow2vm13CpuStreamTypeE I1230 15:32:03.293023 93621 virtual_machine.cpp:80] transport stream type: N7oneflow2vm14CudaStreamTypeE I1230 15:32:03.293042 93621 virtual_machine.cpp:80] transport stream type: N7oneflow2vm19AsyncCudaStreamTypeE I1230 15:32:03.293184 93621 global.h:36] NewGlobal N7oneflow27EagerJobBuildAndInferCtxMgrE I1230 15:32:03.293231 93621 global.h:36] NewGlobal N7oneflow12EpollCommNetE I1230 15:32:03.293397 93621 epoll_comm_network.cpp:63] CommNet:Epoll listening on 0.0.0.0:34117 I1230 15:32:03.293437 93621 epoll_comm_network.cpp:197] machine 0 sockfd -1 I1230 15:32:03.293527 93621 global.h:36] NewGlobal N7oneflow9TransportE I1230 15:32:03.293648 93621 global.h:43] DeleteGlobal N7oneflow17ForeignLockHelperE I1230 15:32:03.293788 93621 global.h:36] NewGlobal N7oneflow25MultiClientSessionContextE `

没事儿了没事儿了，我傻了！！！！！

**Comment by chengtbf** [comment]
> 没事儿了没事儿了，我傻了！！！！！

是什么原因呢 😂

**Comment by muzhailong** [comment]
> 原因

特别智障，之前有人问我matplotlib这个库一闪而过，我利用ide的提示功能加了一句plt.waitforbuttonpress(),后来忘记删了。。。我蠢了

**Comment by chengtbf** [comment]
> > 原因
> 
> 特别智障，之前有人问我matplotlib这个库一闪而过，我利用ide的提示功能加了一句plt.waitforbuttonpress(),后来忘记删了。。。我蠢了

哦哦哦 原来如此。我还以为是卡在 Multi-Client session context 里了。。还准备本地复现一下的 😂

**Comment by muzhailong** [comment]
> 一下

打扰了打扰了，特别感谢感谢
