### ISSUE TITLE
nn.functional.dropout BUG

### ISSUE THREAD

**Issue by kaijieshi7** [Oneflow-Inc/oneflow#7234]
## Summary

最新的nightly版本会报错，12月31的也会，TypeError: dropout(): argument 'addend' must be tensor, not float

## Code to reproduce bug

```python
import oneflow as flow
x = flow.randn(1, 3, 4, 4)
y = flow.nn.functional.dropout(x, 0.1)
```

**Comment by MARD1NO** [comment]
Will be fixed in https://github.com/Oneflow-Inc/oneflow/pull/7237
