### ISSUE TITLE
IsInplaceValid(x) a leaf Tensor that requires grad is being used in an in-place operation

### ISSUE THREAD

**Issue by kaijieshi7** [Oneflow-Inc/oneflow#7248]
## Summary

module可导的时候，参数不能inplace，这个设计和torch是不一样的，是搞错了，还是就这样设计的？
x.weight.data = x.weight.data + 1 却还是能够达到效果，这个方法和inplace在细节方面有什么不同吗？
## Code to reproduce bug

```python
import oneflow as flow
#import torch as flow
x = torch.nn.Conv2d(3, 3, 3)
x.weight.data.add_(1)
```

**Comment by wyg1997** [comment]
> module可导的时候，参数不能inplace，这个设计和torch是不一样的

![image](https://user-images.githubusercontent.com/39889784/149260914-80ec6b15-976a-44a0-960a-bb06dd1c1df6.png)

为什么说和 torch 设计不一样呢？torch 的例子是怎么样的呢？

**Comment by wyg1997** [comment]
```python
import oneflow as flow
#import torch as flow
x = torch.nn.Conv2d(3, 3, 3)
x.weight.data.add_(1)
```

这个例子直接操作 tensor.data 是比较危险的，我们不允许用data 的 getter 方法

**Comment by kaijieshi7** [comment]
> ```python
> import oneflow as flow
> #import torch as flow
> x = torch.nn.Conv2d(3, 3, 3)
> x.weight.data.add_(1)
> ```
> 
> 这个例子直接操作 tensor.data 是比较危险的，我们不允许用data 的 getter 方法

但是x.weight.data = x.weight.data + 1 还是能操作tensor.data。。。

**Comment by wyg1997** [comment]
> > ```python
> > import oneflow as flow
> > #import torch as flow
> > x = torch.nn.Conv2d(3, 3, 3)
> > x.weight.data.add_(1)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这个例子直接操作 tensor.data 是比较危险的，我们不允许用data 的 getter 方法
> 
> 但是x.weight.data = x.weight.data + 1 还是能操作tensor.data。。。

这个是 setter 方法，setter 是允许的，另外这个地方应该写成：`x.weight.data = x.weight + 1`

**Comment by kaijieshi7** [comment]
![image](https://user-images.githubusercontent.com/19171201/149262534-fa7accf0-fef0-4834-967b-a18b9c060434.png)
getter是直接checkfailed，不能跑了。不是警告

**Comment by kaijieshi7** [comment]
> ```python
> import oneflow as flow
> #import torch as flow
> x = torch.nn.Conv2d(3, 3, 3)
> x.weight.data.add_(1)
> ```
> 
> 这个例子直接操作 tensor.data 是比较危险的，我们不允许用data 的 getter 方法

还有个问题，权重初始化的inplace操作是很常见的啊，oneflow我记的不会checkfailed

**Comment by kaijieshi7** [comment]
为啥要写成 `x.weight.data = x.weight + 1`;而不是 `x.weight.data = x.weight.data + 1`? 我的直觉告诉我应该写第二种。

**Comment by wyg1997** [comment]
也有道理，对于 Parameter 的话确实可以支持一下 inplace 设置数据，在权重初始化的时候会好理解一些。普通的 Tensor 不支持影响不太大。

**Comment by wyg1997** [comment]
上面的 PR 已经支持了 issue 中的用法，可以再试一下 @kaijieshi7
