### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by mc622426** [Oneflow-Inc/oneflow#7272]
运行https://gitee.com/zhijiangtianshu/ts-cv/tree/master/Visions/detection/CSRNet ，
oneflow=0.5.0与0.6.0中问题回溯：
出错的代码行：https://gitee.com/zhijiangtianshu/ts-cv/blob/master/Visions/detection/CSRNet/train.py#L120
```
File "train.py", line 120, in train
img = flow.Tensor(img, dtype=flow.float32, device="cuda")
oneflow._oneflow_internal.exception.TypeException: 
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/api/python/functional/py_function.h", line 69, in call
    TypeError: _legacy_tensor_ctor(): received an invalid combination of arguments. The valid signatures are:
	*0: Tensor (*, Device device=None)
	*1: Tensor (*, Placement placement, SbpList sbp)
	*2: Tensor (Tensor other)
	*3: Tensor (PyObject* data, *, Device device=None)
	*4: Tensor (PyObject* data, *, Placement placement, SbpList sbp)
	*5: Tensor (Shape size, *, Device device=None)
	*6: Tensor (Shape size, *, Placement placement, SbpList sbp)
F0113 17:13:33.003460 11407 cuda_stream.cpp:110] Check failed: cudnnCreate(&cudnn_handle_) : CUDNN_STATUS_INTERNAL_ERROR (4)       
```               
切换至oneflow=0.4.0报错：AttributeError: module 'oneflow.nn' has no attribute 'Sequential'
大多算法的问题与之类似，在0.5.0与0.6.0中有回溯没有明确报错信息，更滑0.4.0后会出现找不到模块的请情况，例如：https://gitee.com/zhijiangtianshu/ts-cv/tree/master/Visions/segmentation/FaceSeg中：module 'oneflow.nn' has no attribute 'Conv2d'，https://gitee.com/zhijiangtianshu/ts-nlp/tree/master/NLP/rnn：ImportError: cannot import name 'optim' from 'oneflow' (/root/anaconda3/envs/rnn/lib/python3.8/site-packages/oneflow/__init__.py)

**Comment by strint** [comment]
这个需要at下之江的小伙伴，更新下用法：
```
img = flow.Tensor(img, dtype=flow.float32, device="cuda")
```
假设img类型是numpy，则代码应该改为：
```
img = flow.Tensor(img, device="cuda")
```

**Comment by doombeaker** [comment]
解决方案如上面所说，主要是 `Tensor` 和 `tensor` 混用导致的错误（之前检查不严，现在加了严格检查导致报错）。具体区别的解释在这里：https://docs.oneflow.org/master/basics/02_tensor.html#tensor-tensor

版本的话，用 `0.6.0` 应该就可以，用 `0.4.0` 是不可以的，因为看 https://gitee.com/zhijiangtianshu/ts-cv/tree/master/Visions/detection/CSRNet 里的代码，写法是 0.5 及之后的，OneFlow 0.4. 不支持。

**Comment by mc622426** [comment]
@strint 这种情况问题出在哪里？
oneflow=0.5报错：AttributeError: module 'oneflow' has no attribute 'global_function'                                                                                                   oneflow=0.4报错：WARNING: 'flow.train.CheckPoint' is deprecated. Please use the new API:
flow.train.CheckPoint().save(path) => flow.checkpoint.save(path)
flow.train.CheckPoint().load(path) => flow.load_variables(flow.checkpoint.get(path))
flow.train.CheckPoint().init() is not needed any more.

WARNING: oneflow.optimizer.PolynomialSchduler will be removed in the future, use oneflow.optimizer.PolynomialScheduler instead.
  File "/home/tianshu/ts-nlp/LanguageModeling/BERT/util.py", line 167, in CreateOptimizer
    lr_scheduler = flow.optimizer.PolynomialSchduler(args.learning_rate, args.iter_num, 0.0,

F0114 15:44:17.193714   526 posix_file_system.cpp:94] Check failed: fd >= 0 Fail to open file part-0: No such file or directory [2]                               oneflow=0.6报错：AttributeError: module 'oneflow' has no attribute 'global_function'

**Comment by mc622426** [comment]
@strint 当我Tensor改为tensor，或者将dtype=flow.float32删除 ，将会出现如下报错，Traceback (most recent call last):
  File "train.py", line 212, in <module>
    main()
  File "train.py", line 80, in main
    train(train_list, model, criterion, optimizer, epoch)
  File "train.py", line 127, in train
    loss.backward()
  File "/root/anaconda3/envs/csrnet/lib/python3.8/site-packages/oneflow/framework/tensor.py", line 82, in _backward
    flow.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/root/anaconda3/envs/csrnet/lib/python3.8/site-packages/oneflow/autograd/autograd.py", line 48, in backward
    backward_api(
oneflow._oneflow_internal.exception.CheckFailedException: 
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/api/python/autograd/autograd.cpp", line 73, in Backward
    CheckAndInitOutGrads(outputs, out_grads)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/api/python/autograd/autograd.cpp", line 52, in CheckAndInitOutGrads
    Check failed: outputs.at(i)->requires_grad() All output tensors `.requires_grad` should be true
之后将requires_grad=True加入，报错并无变化。

**Comment by strint** [comment]
>  Check failed: outputs.at(i)->requires_grad() All output tensors `.requires_grad` should be true 之后将requires_grad=True加入，报错并无变化。

这个能提供下脚本链接么

**Comment by mc622426** [comment]
@strint 源代码如下，在train.py中并没有发现 requires_grad，line 120原来也是没有的。
```
118     for i, (img, target) in enumerate(train_loader):
119         data_time.update(time.time() - end)
120         img = flow.tensor(img, dtype=flow.float32, device="cuda", requires_grad=True)
121         output = model(img).to("cuda")
122         output = flow.Tensor(output, device="cuda")
123         target = flow.Tensor(target, device="cuda").unsqueeze(0)
124         loss = criterion(output, target)
125         losses.update(loss.numpy(), img.size(0))
126         optimizer.zero_grad()
127         loss.backward()
128         optimizer.step()
129         batch_time.update(time.time() - end)
130         end = time.time()
```

**Comment by wyg1997** [comment]
问题在 122 行，这里用网络输出的 output 重新生成一个新的 output ，这样原来的后向图就断掉了，backward 就回不去了。直接把 122 行删掉试试呢？

**Comment by mc622426** [comment]
@wyg1997 多谢，方法是可行的

**Comment by strint** [comment]
如果还有问题，可以新建一个issue我们跟进。这个issue先关闭了哈~
