### ISSUE TITLE
Remove `register_tensor_op` decorator and use `add_docstr`

### ISSUE THREAD

**Issue by MARD1NO** [Oneflow-Inc/oneflow#7297]
High Level

**Comment by lixiang007666** [comment]
把遗留的通过register_tensor_op注册Tensor方法的例子搬到tensor.py，文档转移到tensor.rst。

目前通过register_tensor_op注册Tensor方法的例子共有76个，依次批量解决。 @thinksoso @lixiang007666 

- [ ] argwhere_tensor_op
- [ ] eq_op
- [ ] ne_op
- [ ] less_op
- [ ] less_equal_op
- [ ] to_consistent_op
- [ ] to_local_op
- [ ] new_ones_op
- [ ] expand_op
- [ ] flip_op_tensor
- [ ] in_top_k_op_tensor
- [ ] index_select_op_tensor
- [ ] logical_and_op_tensor
- [ ] logical_or_op_tensor
- [ ] logical_xor_op_tensor
- [ ] masked_fill_op
- [ ] tensor_masked_select_op
- [ ] _sub
- [ ] _div
- [ ] _reciprocal
- [ ] _add
- [ ] _add_inplace
- [ ] asin_op_tensor
- [ ] arcsin_op_tensor
- [ ] arcsinh_op_tensor
- [ ] sin_op_tensor
- [ ] inplace_sin_op_tensor
- [ ] cos_op
- [ ] atan_op_tensor
- [ ] arctan_op_tensor
- [ ] fmod_op_tensor
- [ ] log_op
- [ ] log2_op
- [ ] rsqrt_op
- [ ] sqrt_op
- [ ] square_op
- [ ] addmm_op_tensor
- [ ] cosh_op
- [ ] erf_op
- [ ] erfc_op
- [ ] erf_op_tensor
- [ ] ceil_op_tensor
- [ ] expm1_op_tensor
- [ ] topk_op
- [ ] nms_op
- [ ] nonzero_tensor_op
- [ ] max_tensor_op
- [ ] min_tensor_op
- [ ] sum_tensor_op
- [ ] mean_tensor_op
- [ ] prod_tensor_op
- [ ] repeat_op
- [ ] reshape_tensor_op
- [ ] view_op
- [ ] sort_op
- [ ] type_as_op
- [ ] int
- [ ] long
- [ ] float
- [ ] double
- [ ] is_floating_point
- [ ] cpu
- [ ] cuda
- [ ] item_op
- [ ] tolist_op
- [ ] tile_op
- [ ] sign_op_tensor
- [ ] sinh_op_tensor
- [ ] tan_op_tensor
- [ ] acos_op
- [ ] acosh_op_tensor
- [ ] arccosh_op_tensor
- [ ] where_op

**Comment by lixiang007666** [comment]
例子：https://github.com/Oneflow-Inc/oneflow/pull/7306 @thinksoso

**Comment by lixiang007666** [comment]
PR：

- [ ] https://github.com/Oneflow-Inc/oneflow/pull/7306
- [ ] https://github.com/Oneflow-Inc/oneflow/pull/7321
- [ ] https://github.com/Oneflow-Inc/oneflow/pull/7329
- [ ] https://github.com/Oneflow-Inc/oneflow/pull/7345
