### ISSUE TITLE
flow.optim.Adam has no keyword argument 'params'

### ISSUE THREAD

**Issue by Ancientshi** [Oneflow-Inc/oneflow#7313]
## Summary

When we import onefow as torch, the function torch.optim.Adam has keyword argument 'parameters' instead of 'params'.

Besides, the [documentation](https://start.oneflow.org/oneflow-api-cn/optim.html?highlight=adam#oneflow.optim.Adam) also has a issue.

![image](https://user-images.githubusercontent.com/63179313/150285289-aae05afa-2458-42cb-bdec-fb25c8556a39.png)

## Code to reproduce bug

```python
import oneflow as torch
optimizer= torch.optim.Adam(params=xxxx)
```
bug:
```text
__init__() got an unexpected keyword argument 'params' 
```

## System Information

- oneflow 0.6.0

**Comment by doombeaker** [comment]
@lixiang007666 麻烦修正下这个问题，谢谢~
