### ISSUE TITLE
matmul doesn't align Pytorch

### ISSUE THREAD

**Issue by Ancientshi** [Oneflow-Inc/oneflow#7334]
## Summary

flow.matmul(a,b) doen't support different shape of tensor a and b

## Code to reproduce bug

documentation 
https://start.oneflow.org/oneflow-api-cn/oneflow.html?highlight=matmul#oneflow.matmul

```python
import oneflow as flow

input1 = flow.randn(2, 6, dtype=flow.float32)
input2 = flow.randn(6, 5, 4, dtype=flow.float32)
of_out = flow.matmul(input1, input2)

print(of_out.shape)
```

```text
Traceback (most recent call last):
  File "eval.py", line 48, in <module>
    sr_imgs_y = convert_image(sr_imgs, source='[-1, 1]', target='y-channel').squeeze(
  File "/workspace/OneFlow_SRGAN/utils.py", line 103, in convert_image
    img = torch.matmul(255. * img.permute(0, 2, 3, 1)[:, 4:-4, 4:-4, :], rgb_weights) / 255. + 16.
oneflow._oneflow_internal.exception.CheckFailedException:
```
![image](https://user-images.githubusercontent.com/63179313/150517531-ee03dca3-2036-4a38-b4c1-d7cb2a0166fd.png)

## System Information

- oneflow 0.6

**Comment by MARD1NO** [comment]
This problem will be fixed in PR: https://github.com/Oneflow-Inc/oneflow/pull/6937, waiting for someone to review
