### ISSUE TITLE
ModuleNotFoundError: No module named 'oneflow._oneflow_internal'

### ISSUE THREAD

**Issue by KyrieHee** [Oneflow-Inc/oneflow#7392]
OS system: macOS 12.0.1
Python version: 3.7

when I run " pip3 install oneflow", It's successful.

`WARNING: Ignoring invalid distribution -mportlib-metadata (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages)
Requirement already satisfied: oneflow in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (0.6.0)
Requirement already satisfied: tqdm in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from oneflow) (4.62.3)
Requirement already satisfied: protobuf>=3.9.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from oneflow) (3.19.1)
Requirement already satisfied: numpy>=1.20.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from oneflow) (1.21.5)
Requirement already satisfied: pillow in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from oneflow) (8.3.2)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from oneflow) (2.26.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests->oneflow) (2.0.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests->oneflow) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in /Users/yunhe/Library/Python/3.7/lib/python/site-packages (from requests->oneflow) (2019.11.28)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests->oneflow) (3.3)
WARNING: Ignoring invalid distribution -mportlib-metadata (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -mportlib-metadata (/Library/Frameworks/P"`

but when I import "import oneflow as of" has a error, just like the title.

**Comment by jackalcooper** [comment]
Currently the package on PyPI is a placeholder without actual binary. (prevent others taking the name)
You need to compile from source to run OneFlow on macOS.

**Comment by KyrieHee** [comment]
ok， Thanks.
