### ISSUE TITLE
Optimize Pooling NCHW Kernel

### ISSUE THREAD

**Issue by MARD1NO** [Oneflow-Inc/oneflow#7412]

**Comment by MARD1NO** [comment]
问题定位到是使用int64_t作为索引计算，其中涉及到大量的除法取余，解决方案是dispatch，根据elem_cnt来分发到int32/int64的分支

**Comment by simonJJJ** [comment]
感觉大部分kernel都不会用到int64_t索引？往往都是CUDA_1D_KERNEL_LOOP里的int32_t的索引来做一些列推导

**Comment by MARD1NO** [comment]
> 感觉大部分kernel都不会用到int64_t索引？往往都是CUDA_1D_KERNEL_LOOP里的int32_t的索引来做一系列推导

嗯没特殊情况就直接int32吧
