### ISSUE TITLE
num_workers导致数据读取问题

### ISSUE THREAD

**Issue by kaijieshi7** [Oneflow-Inc/oneflow#7497]
## Summary

下列代码直接运行会报错，尝试有两种方法能绕过：
1. 令batch_size=2
2. 令num_workers=0

## Code to reproduce bug

```
from oneflow.utils.data import DataLoader
from flowvision.datasets import ImageFolder
import os
from flowvision import transforms


class ImageNetDataLoader(DataLoader):
    def __init__(
        self,
    ):
        split = 'val'
        data_dir = '/dataset/extract'
        batch_size = 64
        transform = transforms.Compose(
                [
                    transforms.Resize(
                        256, interpolation=3
                    ),  # 3: bibubic
                    transforms.CenterCrop(224),
                    transforms.ToTensor(),
                    transforms.Normalize(0.5, 0.5),
                ]
            )
        self.dataset = ImageFolder(
            root=os.path.join(data_dir, split), transform=transform
        )
        super(ImageNetDataLoader, self).__init__(
            dataset=self.dataset,
            batch_size=batch_size,
            shuffle=True if split == "train" else False,
            num_workers=8,
        )

data_loader = ImageNetDataLoader()
for data, target in data_loader:
    print(1)
```

## System Information

- What is your OneFlow installation (pip, source, dockerhub):pip
- OS:
- OneFlow version (run `python3 -m oneflow --doctor`): 0.7.0+cu102.git.1a36668 
- Python version:
- CUDA driver version:
- GPU models:
- Other info:

**Comment by BBuf** [comment]
我在vs08运行了，是正常的，你的报错是什么呢？

**Comment by kaijieshi7** [comment]
![image](https://user-images.githubusercontent.com/19171201/153976635-b6bc4318-e68b-4fc7-95a3-06da3570d86f.png)
是这样的

**Comment by Ldpe2G** [comment]
是不是和flowvision版本有关，可以定位一下，回退一下commit试试

**Comment by BBuf** [comment]
gdb看下stack

**Comment by kaijieshi7** [comment]
没修改上面的代码，oneflow0.6.0稳定版不会有问题；nightly版本都是有问题的。

**Comment by BBuf** [comment]
我这里复现不了，可以gdb看一下stack信息贴上来

**Comment by kaijieshi7** [comment]
vs001上述代码依旧报错

**Comment by kaijieshi7** [comment]
![image](https://user-images.githubusercontent.com/19171201/155323203-22eaf1b4-ad9f-42c2-9d5a-e3bbe20a9b44.png)
![image](https://user-images.githubusercontent.com/19171201/155323244-cee65418-d20a-44f9-b935-72990275a954.png)

**Comment by kaijieshi7** [comment]
oneflow0.6.0稳定版 + flowvision 0.1.0 能跑
oneflownightly + flowvision 0.1.0 不能跑

**Comment by BBuf** [comment]
@Flowingsun007 可能要重视这个问题了，dataloader最近经常工作不正常。

**Comment by kaijieshi7** [comment]
关键是别人好像复现不出来。。。我vs008和011都能复现

**Comment by Flowingsun007** [comment]
> @Flowingsun007 可能要重视这个问题了，dataloader最近经常工作不正常。

我上vs011试试看能不能复现

**Comment by kaijieshi7** [comment]
好的，github我不一定能及时回复

**Comment by kaijieshi7** [comment]
你能复现吗

**Comment by Flowingsun007** [comment]
> 你能复现吗

我这里表现会卡住，好像确实是worker里遭遇了segmentfault，怀疑和最近合入的shm有关系，我再试试这个commit之前的情况

**Comment by Flowingsun007** [comment]
dataloader有概率卡住的问题已经修复了，用最新oneflow:https://github.com/Oneflow-Inc/oneflow/commit/a33a82553d3bda26ad787934689c5b8ee7f9924e 跑这个case已经可以正常跑通了。

- 相关issue：https://github.com/Oneflow-Inc/OneTeam/issues/1091
- 相关pr: https://github.com/Oneflow-Inc/oneflow/pull/7663
