### ISSUE TITLE
反向的上游梯度数据类型要求与输入一致，torch未要求

### ISSUE THREAD

**Issue by liufengwei0103** [Oneflow-Inc/oneflow#7550]
复现代码：
```
>>> import oneflow as flow
>>> a = flow.tensor([1, 1], dtype=flow.float, requires_grad=True)
>>> sa = a.sum()
>>> sa.backward(flow.tensor(2))
```
报错信息：

> F20220221 15:17:09.141747 36373 user_op_tensor.h:64] tensor data_type mismatched. value: kInt64, template T:kFloat
> *** Check failure stack trace: ***
>     @     0x7f0efc4c07bd  google::LogMessage::Fail()
>     @     0x7f0efc4c2a4c  google::LogMessage::SendToLog()
>     @     0x7f0efc4c025a  google::LogMessage::Flush()
>     @     0x7f0efc4c33a9  google::LogMessageFatal::~LogMessageFatal()
>     @     0x7f0f02dc06b3  oneflow::(anonymous namespace)::BroadcastLikeKernel<>::Compute()
>     @     0x7f0f00c6fb0d  oneflow::vm::LocalCallOpKernelUtil::Compute()
>     @     0x7f0f00c3b3b4  oneflow::vm::LocalCallOpKernelInstructionType::Compute()
>     @     0x7f0f02b7fa6d  oneflow::vm::CpuStreamType::Compute()
>     @     0x7f0f02ba695e  oneflow::vm::StreamType::Run()
>     @     0x7f0f02bad3da  oneflow::vm::ThreadCtx::MoveAndRun<>()
>     @     0x7f0f02bacd47  oneflow::vm::ThreadCtx::ReceiveAndRun()
>     @     0x7f0f02bb02e0  oneflow::(anonymous namespace)::WorkerLoop()
>     @     0x7f0f043111af  execute_native_thread_routine
>     @     0x7f0f4832ee25  start_thread
>     @     0x7f0f4805c34d  __clone

    
    
相同的torch代码可以运行
```
>>> import torch
>>> a = torch.tensor([1, 1], dtype=torch.float, requires_grad=True)
>>> sa = a.sum()
>>> sa.backward(torch.tensor(2))
```

**Comment by wyg1997** [comment]
fixed in #8233
