### ISSUE TITLE
autograd中报出tensor 索引bug

### ISSUE THREAD

**Issue by liufengwei0103** [Oneflow-Inc/oneflow#7551]
复现代码：
```
import oneflow as flow
from oneflow.autograd import grad
a = flow.randn(3, 4)
a.requires_grad_()
b = a.sum()
autograd.grad(b, a)
```
报错信息：

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/liufengwei/pytorch/torch/autograd/__init__.py", line 207, in grad
>     outputs = (outputs,) if isinstance(outputs, torch.Tensor) else tuple(outputs)
>   File "/home/liufengwei/src/oneflow/python/oneflow/framework/tensor.py", line 78, in _getitem
>     return flow._C.tensor_getitem(self, key)
> oneflow._oneflow_internal.exception.CheckFailedException: 
>   File "/home/liufengwei/src/oneflow/oneflow/core/functional/impl/array_functor.cpp", line 1762, in operator()
>     PrepareSliceIndices(index, *(x->shape()), &slice_indices, &tensor_indices, &expand_dims, &target_dims)
>   File "/home/liufengwei/src/oneflow/oneflow/core/functional/tensor_index.cpp", line 201, in PrepareSliceIndices
>     Check failed: (specified_ndims) <= (ndims) (1 vs 0) Too many indices for tensor of dimension 0

torch相同的代码没有问题：
```
import torch
from torch import autograd
x = torch.randn(3, 4)
x.requires_grad_()
y = x.sum()
autograd.grad(y, x)
```

**Comment by wyg1997** [comment]
在 master 已经无法复现，关闭此 issue
