### ISSUE TITLE
Oneflow和PyTorch接口命名不一致：Oneflow: .zeros_()  PyTorch: .zero_()

### ISSUE THREAD

**Issue by ZiqiuChi** [Oneflow-Inc/oneflow#7573]
Oneflow: .zeros_()  

PyTorch: .zero_()

### 复现代码：

**Oneflow**

```
import oneflow as flow
a_flow = flow.randn(10)
a_flow.zero_()
```
报错信息：

> Traceback (most recent call last):
> File "\<stdin\>", line 1, in \<module\>
> AttributeError: 'oneflow._oneflow_internal.Tensor' object has no attribute 'zero_'

改成.zeros_()后没问题
```
a_flow.zeros_()
a_flow
```

输出：

> tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=oneflow.float32)

**PyTorch**
```
import torch
a_torch = torch.randn(10)
a_torch.zeros_()
```

报错信息：

> Traceback (most recent call last):
> File "\<stdin\>", line 1, in \<module\>
> AttributeError: 'Tensor' object has no attribute 'zeros_'

改成.zero_()后没问题

```
a_torch.zero_()
a_torch
```

输出：

> tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

对应文档：

Oneflow https://oneflow.readthedocs.io/en/master/tensor.html#oneflow.Tensor.zeros_
![image](https://user-images.githubusercontent.com/34954782/155260583-e90ce880-075f-4569-9a53-a6a08d1ff535.png)

PyTorch https://pytorch.org/docs/stable/generated/torch.Tensor.zero_.html#torch.Tensor.zero_
![image](https://user-images.githubusercontent.com/34954782/155260552-f609311b-b956-46f3-a477-96f506bf6b0a.png)

**Comment by BBuf** [comment]
你提一个pr解决吧。
