### ISSUE TITLE
OneFlow amp 显存问题

### ISSUE THREAD

**Issue by L1aoXingyu** [Oneflow-Inc/oneflow#7649]
## Summary

测试 LiBai T5 模型和 Megatron 的性能指标，发现 amp 的显存问题

<table>
<tr>
	<td> 
	<td> Memory
<tr>
	<td> Megatron/fp32
	<td> 7038MB
<tr>
	<td> OneFlow/fp32
	<td> 5756MB
<tr>
	<td> Megatron/fp16
	<td> 3662MB
<tr>
	<td> OneFlow/fp16
	<td> 4334MB
</table>

可以发现 fp32 下 oneflow 显存比 Megatron 小，但是打开 fp16 之后，却比 Megatron 更大了。

## System Information

```
version: 0.7.0.dev20220228+cu112
git_commit: b769add
cmake_build_type: Release
rdma: True
mlir: True

```

**Comment by chengtbf** [comment]
这个和 欧阳宇的测试，是不是 grad acc 、 Checkpointing 都没开？
