### ISSUE TITLE
Different action between flow.pow and torch.pow

### ISSUE THREAD

**Issue by kaijieshi7** [Oneflow-Inc/oneflow#7722]
pow(input, exponent,)有个情况：input为1个float，exponent为多个组成的tensor，此时torch能运行，flow会报错
```
import torch
import oneflow as flow
a = 2.09
e1 = torch.tensor([1.0, 2.0, 3.0, 4.0])
e2 = flow.tensor([1.0, 2.0, 3.0, 4.0])
torch.pow(a, e1)
flow.pow(a, e2)
```

**Comment by BBuf** [comment]
@Flowingsun007 我感觉和上次那个问题有点像？

**Comment by Flowingsun007** [comment]
> @Flowingsun007 我感觉和上次那个问题有点像？

：）是说上次哪个问题？

**Comment by BBuf** [comment]
> > @Flowingsun007 我感觉和上次那个问题有点像？
> 
> ：）是说上次哪个问题？

就是list slice tensor那个，你回忆下

**Comment by Flowingsun007** [comment]
我这里试了一下，这种情况下bug的原因，是我们flow.pow的functional api其实是接受tensor作输入的：
```shell
- name: "pow"
  signature:
    [
      "Tensor (Tensor input, Tensor exponent) => Pow",
      "Tensor (Tensor input, Scalar exponent, *, Bool inplace=False) => ScalarPow",
      "Tensor (Tensor input, Scalar exponent) => ScalarPow",
    ]
  bind_python: True
```
这里一个scalar a作为输入会报错：
```python
>>> flow.pow(a, exponent=e2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
oneflow._oneflow_internal.exception.TypeException: 
  File "/home/zhaoluyang/Oneflow/oneflow/oneflow/api/python/functional/py_function.h", line 76, in call
    TypeError: pow(): received an invalid combination of arguments. The valid signatures are:
        *0: Tensor (Tensor input, Tensor exponent)
        *1: Tensor (Tensor input, Scalar exponent, *, Bool inplace=False)
        *2: Tensor (Tensor input, Scalar exponent)
```

**Comment by Flowingsun007** [comment]
这里是不是在yaml里应该加一个`"Tensor (Scalar input, Scalar exponent) => ScalarPow", `就行了，我来加一下吧

**Comment by Flowingsun007** [comment]
#### 这个问题，本质是因为我们缺了一个op
1.普通情况下，我们期待的pow的输入一个input tensor以及一个常数exponent，譬如：
```python
input = flow.tensor([1.0, 2.0, 3.0, 4.0])
exponent = 2.09
flow.pow(input, exponent)
```
计算时，对tensor做elementwise的乘方操作，`[1.0^2.09, 2.0^2.09, 3.0^2.09, 4.0^2.09]`

2.而此issue中的case需要的pow，则输入是：`flow.pow(exponent, input)`，期待的行为是：
`[2.09^1,  2.09^2,  2.09^3,  2.09^4]`，这从计算逻辑上就和1.中是不同的。

#### 我在这个pr：https://github.com/Oneflow-Inc/oneflow/pull/7729 实现了2.中需要的 pow op，修复了此问题
![image](https://user-images.githubusercontent.com/28823622/157411563-ea6aec41-22ee-4f8f-80a9-dd467ce88246.png)



​

**Comment by Flowingsun007** [comment]
The bug has been solved in pr:https://github.com/Oneflow-Inc/oneflow/pull/7729

<img width="520" alt="image" src="https://user-images.githubusercontent.com/28823622/158003615-6e25a7d8-b5b4-4275-aa77-8421f5047347.png">
