### ISSUE TITLE
`cudaMemset` or `cudaMemsetAsync`?

### ISSUE THREAD

**Issue by Panlichen** [Oneflow-Inc/oneflow#7762]
上午和 @liujuncheng review我写的代码的时候，讨论到了除了在初始化等一些特殊的地方，一般情况下使用cuda API的时候应该使用传递stream参数的Async版本。
我发现当前代码中，一些kernel里直接使用了`cudaMemset`，这些地方是应该改成`cudaMemsetAsync`吗，还是说有其他原因导致了这样的选择？注意到我下边引用的两行代码的作者都是 @daquexian ，方便的话希望可以探讨一下。

https://github.com/Oneflow-Inc/oneflow/blob/277e7a3f7236ef1f2af05a9ce54f19e6d5f49eb3/oneflow/user/kernels/slice_kernel.cpp#L339
https://github.com/Oneflow-Inc/oneflow/blob/277e7a3f7236ef1f2af05a9ce54f19e6d5f49eb3/oneflow/user/kernels/softmax_cross_entropy_kernel.cu#L106

**Comment by daquexian** [comment]
这里当时没有特殊的考虑，可能是该改成 cudaMemsetAsync ：）
