### ISSUE TITLE
set_grad_enabled 

### ISSUE THREAD

**Issue by zhongshsh** [Oneflow-Inc/oneflow#7789]
### 需求场景描述

部分计算可能不需要梯度更新，部分可能需要，此时在 torch 中可以使用 `set_grad_enabled` 并通过 `is_train` 参数进行判断。

```
with torch.set_grad_enabled(is_train):
 ...
```
本质上，`torch.set_grad_enabled(False)` 等同于 `torch.no_grad()`，但是 `set_grad_enabled` 因为参数原因更为灵活一些。

### 解决方案

```
if is_train:
 with flow.grad_enable():
  ...
else:
 with flow.no_grad():
  ...
```

### 其他问题

为啥 torch 叫 [enable_grad](https://pytorch.org/docs/stable/generated/torch.enable_grad.html?highlight=enable_grad#torch.enable_grad)，oneflow 叫 [grad_enable](https://start.oneflow.org/oneflow-api-cn/oneflow.html?highlight=grad_enable#oneflow.grad_enable) ？二者是存在什么区别吗？

**Comment by BBuf** [comment]
@wyg1997 这个问题需要你解答和解决

**Comment by wyg1997** [comment]
好的，只是接口上的没对齐，改一下就好
