### ISSUE TITLE
单价4卡ddp训练resnet50，core dump

### ISSUE THREAD

**Issue by s0okiym** [Oneflow-Inc/oneflow#7804]
## Summary

单价4卡ddp训练resnet50，core dump.  
堆栈信息如下：

F0315 15:02:10.932755 32655 memcpy.cpp:38] Check failed: cudaMemcpyAsync(dst, src, count, cudaMemcpyDefault, cuda_stream->cuda_stream()) : an illegal memory access was encountered (77)
*** Check failure stack trace: ***
    @     0x7febd783b3fd  google::LogMessage::Fail()
    @     0x7febd783cc7a  google::LogMessage::SendToLog()
    @     0x7febd783aebd  google::LogMessage::Flush()
    @     0x7febd783e0a9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7febd1a9464a  (unknown)
    @     0x7febd2320606  oneflow::AutoMemcpy()
    @     0x7febd30d3def  (unknown)
    @     0x7febd0c03e75  oneflow::vm::LocalCallOpKernelUtil::Compute()
    @     0x7febd0bd087b  oneflow::vm::LocalCallOpKernelInstructionType::Compute()
    @     0x7febd2df48a2  oneflow::vm::CudaCopyH2DStreamType::Compute()
    @     0x7febd2e156ae  oneflow::vm::StreamType::Run()
    @     0x7febd2e2bfa5  oneflow::vm::VirtualMachineEngine::DispatchInstruction()
    @     0x7febd2e2e40a  oneflow::vm::VirtualMachineEngine::DispatchAndPrescheduleInstructions()
    @     0x7febd2e1fe18  oneflow::VirtualMachine::Loop()
    @     0x7febd7cb1a6f  (unknown)
    @     0x7fec455afea5  start_thread
    @     0x7fec44bcf8dd  __clone
    @              (nil)  (unknown)
Killing subprocess 31597
Killing subprocess 31598
Killing subprocess 31599
Killing subprocess 31600
Traceback (most recent call last):
  File "/usr/local/python3.7.4/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/python3.7.4/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/python3.7.4/lib/python3.7/site-packages/oneflow/distributed/launch.py", line 221, in <module>
    main()
  File "/usr/local/python3.7.4/lib/python3.7/site-packages/oneflow/distributed/launch.py", line 209, in main
    sigkill_handler(signal.SIGTERM, None)
  File "/usr/local/python3.7.4/lib/python3.7/site-packages/oneflow/distributed/launch.py", line 178, in sigkill_handler

## Code to reproduce bug

resnet50程序：https://github.com/Oneflow-Inc/models.git  里的resnet50. 
启动脚本也是上述仓库里的examples/train_ddp_fp32.sh

python3 -m oneflow.distributed.launch --nproc_per_node 4 --nnodes 1 --node_rank 0 --master_addr 127.0.0.1 --master_port 8043  train.py --save ./ddp_fp32_checkpoints --ofrecord-path ./ofrecord --ofrecord-part-num 1 --num-devices-per-node 4 --lr 0.768 --momentum 0.875 --num-epochs 50 --train-batch-size 96 --val-batch-size 50 --ddp
## System Information

- What is your OneFlow installation (pip, source, dockerhub):   来自这里的whl安装稳健：https://release.oneflow.info/  
- OS: CentOS Linux release 7.2.1511 (Core)
- OneFlow version (run `python3 -m oneflow --doctor`):   0.6.0+cu100
path: ['/usr/local/python3.7.4/lib/python3.7/site-packages/oneflow']
version: 0.6.0+cu100
git_commit: eabe79e
cmake_build_type: Release
rdma: True
mlir: False
- CUDA driver version: libcudart.so.10.0.130
- GPU models: Nvidia Tesla P40 
- Other info:

**Comment by strint** [comment]
@s14n

**Comment by s14n** [comment]
在这个案例中，这个问题是由 CUDA 10.0 引发的。在 OneFlow 0.6.0 版本发布的 whl 格式的安装包中，oneflow==0.6.0+cu102 和 oneflow==0.6.0+cu112 都是可以正常运行的。此外，考虑到 CUDA 10.0 已经过于陈旧，OneFlow 自 0.7.0 开始将不再官方发布基于 CUDA 10.0 编译的安装包。同时，因为 OneFlow 发布的安装包都是静态链接第三方库，只要您的环境下的驱动版本支持 CUDA 10.2，您就可以直接下载基于 CUDA 10.2 编译的安装包进行安装。

如果有任何问题欢迎在评论区留言，我们会积极响应，谢谢您的反馈。
