### ISSUE TITLE
SoftPlus 算子没有对齐

### ISSUE THREAD

**Issue by wyg1997** [Oneflow-Inc/oneflow#7817]
[OneFlow softplus 算子文档](https://oneflow.readthedocs.io/en/master/functional.html?highlight=softplus#oneflow.nn.functional.softplus) 公式中有一个 Beta 参数是没有接口的，https://pytorch.org/docs/stable/generated/torch.nn.functional.softplus.html?highlight=softplus#torch.nn.functional.softplus 对于 torch 也有个 threshold 参数没对齐。

**Comment by BBuf** [comment]
@lixiang007666 是否有空解决一下？

**Comment by lixiang007666** [comment]
> @lixiang007666 是否有空解决一下？

嗯嗯～

**Comment by lixiang007666** [comment]
functional下softplus的实现是`unary_elementwise`做的，这样还能支持添加beta和threshold参数么？@BBuf

**Comment by BBuf** [comment]
> functional下softplus的实现是`unary_elementwise`做的，这样还能支持添加beta和threshold参数么？@BBuf

是可以的，你看看其它类似例子吧。
