### ISSUE TITLE
易用性，环境变量的用法

### ISSUE THREAD

**Issue by shangguanshiyuan** [Oneflow-Inc/oneflow#7865]
哪里可以查询环境变量的用法：

我要指定ib网卡的一些设置，可以通过环境变量指定么？我看它默认用了我的roce网卡 端口1，其实我的rdma网络在设备的端口2，gid 3的设备上。或者我强制指定用tcp网络，忽略rdma网络该咋设置呢？

奥，我知道了，可以设置NCCL的宏，你们底层用了NCCL，其他的环境变量用法去哪里查呢？

易用性：

你们这个感觉用法的门槛不低，小白算法工程师能搞定你们的用法么。
我设置了好几个环境变量才把单机4卡跑通：OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES="0,1,2,3" NCCL_IB_DISABLE=1 NCCL_SOCKET_IFNAME="lo"

OMP_NUM_THREADS这个貌似不是必须的，其他的三个如果不设置就卡住了。也可能和我的网络设置相关，我两块网卡，有tcp的，还有一块roce网络的，还配置了vlan的网口。
如果不指定网口，NCCL可能会有点问题；所以保险期间，还是用NCCL_SOCKET_IFNAME 指定它用哪个网口。我记不清nccl的默认行为是咋弄的了，它貌似会尝试用所有可用的。

## System Information

- What is your OneFlow installation (pip, source, dockerhub): pip
- OS:
- OneFlow version (run `python3 -m oneflow --doctor`): 0.7.0
- Python version: 3.9
- CUDA driver version:
- GPU models:
- Other info:

**Comment by s14n** [comment]
相关环境变量的整理我们会尽快整理，上线到文档网址上；
第二个问题需要配置多个环境变量才能使用，可能跟您的网络环境有定制化限制有关，这个可以参考一下我们即将上线的环境变量相关文档和nccl的文档，指定可用网卡和可用端口

**Comment by shangguanshiyuan** [comment]
关于环境变量的介绍已上线文档网址：https://oneflow.readthedocs.io/en/master/environment_variables.html

**Comment by yuanms2** [comment]
> 关于环境变量的介绍已上线文档网址：https://oneflow.readthedocs.io/en/master/environment_variables.html

不错，有时间的话其实可以形成一篇博客
