### ISSUE TITLE
CI Failed because of "don't support non-contiguous array now".

### ISSUE THREAD

**Issue by simonJJJ** [Oneflow-Inc/oneflow#8098]
![image](https://user-images.githubusercontent.com/32785733/165254766-92a50b56-8cc6-49a8-90a7-c5286b8989a0.png)

**Comment by lixinqi** [comment]
能稳定复现吗？

**Comment by jackalcooper** [comment]
这是warning？实际的错误是死锁超时？

**Comment by simonJJJ** [comment]
> 能稳定复现吗？

我第一次碰到这个，之前peihong也碰到过

**Comment by simonJJJ** [comment]
> 这是warning？实际的错误是死锁超时？

很可能是死锁，有什么办法验证一下么

**Comment by lixinqi** [comment]
> > 这是warning？实际的错误是死锁超时？
> 
> 很可能是死锁，有什么办法验证一下么

先看看能不能稳定复现。我有一个Pr在尝试解决此类问题。

**Comment by simonJJJ** [comment]
> > > 这是warning？实际的错误是死锁超时？
> > 
> > 
> > 很可能是死锁，有什么办法验证一下么
> 
> 先看看能不能稳定复现。我有一个Pr在尝试解决此类问题。

那我再跑一遍

**Comment by mosout** [comment]
这个问题看起来已经没了

**Comment by jackalcooper** [comment]
> 这个问题看起来已经没了

昨天我把超时时间从45分钟增加到了1小时
