### ISSUE TITLE
InplaceScalarDivFunctor的op_type_name存在拼写错误？

### ISSUE THREAD

**Issue by fpzh2011** [Oneflow-Inc/oneflow#8149]
## Summary

[InplaceScalarDivFunctor](https://github.com/Oneflow-Inc/oneflow/blob/release/0.7.0/oneflow/core/functional/impl/math_functor.cpp#L229)构造函数的参数应该是`scalar_div`？
感觉像是拷贝粘贴忘记修改了？

## System Information

- OneFlow version: v0.7.0 and master

**Comment by MARD1NO** [comment]
这里我们是用 乘法 来做除法

比如
```
a / b -> a * (1 / b)
```

相对来说乘法计算比较快，但是精度可能比除法稍差一点点

**Comment by fpzh2011** [comment]
抱歉，没仔细看实现逻辑 :)
