### ISSUE TITLE
oneflow.Tensor.fill_ is so slow

### ISSUE THREAD

**Issue by basicv8vc** [Oneflow-Inc/oneflow#8278]
## Summary

不论是CPU还是CUDA环境，`oneflow.Tensor.fill_`都比`torch.Tensor.fill_`慢很多，我只能使用`flow.ones() * fill_value`作为替代。

看了下代码，发现`_fill`涉及copy_from_numpy的操作？

https://github.com/Oneflow-Inc/oneflow/blob/7476de9abdbcfdb61344a49de174a85198b95315/python/oneflow/framework/tensor.py#L858-L860

## Code to reproduce bug

```python
import torch
import oneflow as flow

########### CPU version #####################
x_flow = flow.rand(10000, 1000, device=flow.device("cpu"))
x_torch = torch.rand(10000, 1000, device=torch.device("cpu"))

# %%timeit     # uncomment this line in Jupyter Notebook
x_flow.fill_(1.)
# 155 ms ± 1.88 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

# %%timeit     # uncomment this line in Jupyter Notebook
x_torch.fill_(1.)
# 799 µs ± 71.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

########### CUDA version #####################
x_flow = flow.rand(10000, 1000, device=flow.device("cuda:0"))
x_torch = torch.rand(10000, 1000, device=torch.device("cuda:0"))

# %%timeit     # uncomment this line in Jupyter Notebook
x_flow.fill_(1.)
# 141 ms ± 10.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

# %%timeit     # uncomment this line in Jupyter Notebook
x_torch.fill_(1.)
# 99.5 µs ± 6.88 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


```
## System Information

- What is your OneFlow installation (pip, source, dockerhub): pip
- OS: Ubuntu 20.04.3 LTS
- OneFlow version (run `python3 -m oneflow --doctor`): 0.7.0+cu112
- Python version: Python 3.8.10
- CUDA driver version:  495.44
- CUDA runtime version: Build cuda_11.3.r11.3/compiler.29920130_0
- GPU models:
- Other info:
- PyTorch version: 1.11.0+cu113

**Comment by BBuf** [comment]
谢谢反馈，我们将尽快修复此问题。
