### ISSUE TITLE
The conversion of one element tensors to Python scalars is inconsistent in torch and oneflow

### ISSUE THREAD

**Issue by s14n** [Oneflow-Inc/oneflow#8325]
in torch:
a = torch.tensor([3.5])
float(a)
3.5

in oneflow:
a = oneflow.tensor([3.5])
float(a)
AssertionError: Only integer tensors of a single element can be converted to an index

version: stable 0.7.0+cu112

**Comment by Flowingsun007** [comment]
Thank you for this isssue!
I just tried it use latest commit of oneflow and found it works well. 

#### my oneflow version:
`python3 -m oneflow --doctor`
```shell
version: 0.8.0+cu112.git.07e9f2c3b2
git_commit: 07e9f2c3b2
cmake_build_type: RelWithDebInfo
rdma: False
mlir: False
```
#### result:

<img width="584" alt="image" src="https://user-images.githubusercontent.com/28823622/170825535-0c34c0ca-1833-4f41-ade4-b8580d38c24e.png">

It could be related to the oneflow version, may be you can try it again with the latest version？
Looking forward to your feedback, thanks again!

**Comment by s14n** [comment]
I reported it in the stable version 0.7.0+cu112. After trying again, it was correct behavior in the nightly release version.
Thanks for your response.
