### ISSUE TITLE
'oneflow._oneflow_internal.Tensor' object has no attribute 'log2'

### ISSUE THREAD

**Issue by lmyybh** [Oneflow-Inc/oneflow#8386]
## Summary
'oneflow._oneflow_internal.Tensor' object has no attribute 'log2'

## Code to reproduce bug

```python
torch.tensor(25.2).log2()
# output: tensor(4.6554)

flow.tensor(25.2).log2()
# error: AttributeError: 'oneflow._oneflow_internal.Tensor' object has no attribute 'log2'
```
## Error Info of OneFlow
```
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_3636/1807945582.py in <module>
----> 1 flow.tensor(25.2).log2()

AttributeError: 'oneflow._oneflow_internal.Tensor' object has no attribute 'log2'
```

## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS: linux
- OneFlow version (run `python3 -m oneflow --doctor`):  0.7.0+cu112
- Python version: Python3.7
- CUDA driver version: cuda11.2
- GPU models: 6core-42Gi-3090(1Card)
- Other info:

**Comment by lmyybh** [comment]
> This bug has been fixed in master. You can solve the problem by upgrade you oneflow version to nightly.
> 
> The upgrade command is as follows:
> 
> ```shell
> python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu102
> ```

I installed oneflow+cu112 with the following command:
```
python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu112
```

But a new error has occurred:
```
Exception                                 Traceback (most recent call last)
/tmp/ipykernel_14153/1176533890.py in <module>
----> 1 import oneflow as flow

/usr/local/miniconda3/lib/python3.7/site-packages/oneflow/__init__.py in <module>
     21 import oneflow._oneflow_internal
     22 
---> 23 oneflow._oneflow_internal.InitNumpyCAPI()
     24 oneflow._oneflow_internal.CheckAndClearRegistryFlag()
     25 Size = oneflow._oneflow_internal.Size

Exception: 
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/extension/python/numpy.cpp", line 112, in InitNumpyCAPI
    Check failed: (_import_array()) == (0) (-1 vs 0) . Unable to import Numpy array, try to upgrade Numpy version!
```

I have updated Numpy to the latest version 1.21.6, but the error still exists. I'm not sure if this is a bug. Please have a look. Thanks. @BBuf

**Comment by daquexian** [comment]
> I have updated Numpy to the latest version 1.21.6, but the error still exists. I'm not sure if this is a bug. Please have a look. Thanks.

The latest version is 1.22.4. Could you please reinstall and try again? @lmyybh

**Comment by s14n** [comment]
> I installed oneflow+cu112 with the following command:
> 
> ```
> python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu112
> ```
> 
> But a new error has occurred:
> 
> ```
> Exception                                 Traceback (most recent call last)
> /tmp/ipykernel_14153/1176533890.py in <module>
> ----> 1 import oneflow as flow
> 
> /usr/local/miniconda3/lib/python3.7/site-packages/oneflow/__init__.py in <module>
>      21 import oneflow._oneflow_internal
>      22 
> ---> 23 oneflow._oneflow_internal.InitNumpyCAPI()
>      24 oneflow._oneflow_internal.CheckAndClearRegistryFlag()
>      25 Size = oneflow._oneflow_internal.Size
> 
> Exception: 
>   File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/extension/python/numpy.cpp", line 112, in InitNumpyCAPI
>     Check failed: (_import_array()) == (0) (-1 vs 0) . Unable to import Numpy array, try to upgrade Numpy version!
> ```
> 

Thanks for your feedback. This exception has been fixed in nightly version, you can reinstall it by this command:
```
python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu102
```
