### ISSUE TITLE
Build error: delete called on unallocated object `cache` in cached_caller.h 

### ISSUE THREAD

**Issue by wangkuiyi** [Oneflow-Inc/oneflow#8397]
Building OneFlow (the master branch) on a Ubuntu VirtualBox VM (so, no GPU nor CUDA, **without using conda**), failed at 

```
/home/wkyi/w/oneflow/oneflow/core/common/cached_caller.h:33:5: error: ‘void operator delete(void*, std::size_t)’ called on unallocated object ‘cache’ [-Werror=free-nonheap-object]
   33 |     delete ptr;
      |     ^~~~~~~~~~
/home/wkyi/w/oneflow/oneflow/core/common/cached_caller.h: In member function ‘void oneflow::RuntimeBlobShapeInferHelper::InferShape(const std::function<oneflow::Blob*(const std::__cxx11::basic_string<char>&)>&)’:
/home/wkyi/w/oneflow/oneflow/core/common/cached_caller.h:50:32: note: declared here
   50 |   static thread_local HashMap* cache = nullptr;
      |                                ^~~~~
cc1plus: all warnings being treated as errors
```

The Ubuntu version is

```
wkyi@oneflow:~/w/oneflow$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

The GCC/G++ versions are

```
wkyi@oneflow:~/w/oneflow$ gcc --version
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

wkyi@oneflow:~/w/oneflow$ g++ --version
g++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by daquexian** [comment]
Thanks for your report! It looks like a false positive of gcc 11. https://github.com/Oneflow-Inc/oneflow/pull/8401 fixes it.

**Comment by wangkuiyi** [comment]
Thank you @daquexian for the fixing. I realized from my building experience these days that if we use a modern version of G++, we might need to update the source code accordingly. For example, in a few places, we will need to add `#include <limits>` to prevent G++ from erroring. I will keep posting these findings in other issues. At the same time, I will keep using Conda/Docker-based building, which helps me fixing the version of the build toolchain.

Please feel free to close this issue after the merge of #8401 .

**Comment by yuanms2** [comment]
Thanks @wangkuiyi for the bug reports and for sharing the journey of debugging oneflow with GDB. It is very useful indeed.

**Comment by daquexian** [comment]
> I realized from my building experience these days that if we use a modern version of G++, we might need to update the source code accordingly. For example, in a few places, we will need to add #include <limits> to prevent G++ from erroring. 

It seems that we should upgrade abseil-cpp https://github.com/grpc/grpc/issues/25114. I tried `cmake -DRPC_BACKEND=LOCAL` to build a single-machine-no-grpc version and it succeeded.
