### ISSUE TITLE
Inconsistent result when creating global tensor with `sbp.broadcast`

### ISSUE THREAD

**Issue by yhcharles** [Oneflow-Inc/oneflow#8465]
## Summary

When creating global tensor with `flow.randn` and `sbp=flow.sbp.broadcast`, the returned tensors are not the same on different ranks. If change the code to `sbp=flow.sbp.split(0)`, the returned tensors are the same.

Should we expect global tensor has the same value on different ranks?

## Code to reproduce bug

```
import oneflow as flow
print(flow.randn(2, 3, placement=flow.placement('cpu', [0, 1]), sbp=flow.sbp.broadcast)
```

## System Information

- pip installed oneflow
- OS: linux
- OneFlow version (run `python3 -m oneflow --doctor`):
version: 0.7.0+cu102
git_commit: 6e15405
cmake_build_type: Release
rdma: True
mlir: True
- Python version: 3.9.12

**Comment by s14n** [comment]
If you want to create a global_tensor through sbp.broadcast on multiple ranks, you need to ensure that the state of each rank is consistent.

You can do it in this way:
```
import oneflow as flow
gen = flow.Generator()
gen.manual_seed(111)
x = flow.randn(2, 3, placement=flow.placement('cpu', [0, 1]), sbp=flow.sbp.broadcast, generator=gen)
```

And a more user-friendly way is already under development, which does not require users to maintain the state of different ranks.

**Comment by yhcharles** [comment]
Thanks @s14n for the explanation! Sounds good to me.
