### ISSUE TITLE
安装oneflow时提示Invalid argument

### ISSUE THREAD

**Issue by drxmy** [Oneflow-Inc/oneflow#8497]
## Summary

用python3 -m pip install -f https://release.oneflow.info oneflow==0.7.0+cu102
或者换成cu112都会报这个错

**Comment by s14n** [comment]
你好，您的系统是什么？
这个错误一般是在Windows环境下容易发生，OneFlow目前不支持Windows系统。
是否方便提供更多的信息，包括系统版本、python版本等，谢谢。

**Comment by s14n** [comment]
OneFlow提供了docker镜像，您看看能不能解决您的问题。
docker pull oneflowinc/oneflow:nightly-cuda10.2
docker pull oneflowinc/oneflow:nightly-cuda11.2

**Comment by drxmy** [comment]
> OneFlow提供了docker镜像，您看看能不能解决您的问题。 docker pull oneflowinc/oneflow:nightly-cuda10.2 docker pull oneflowinc/oneflow:nightly-cuda11.2

我试试，谢谢
