### ISSUE TITLE
在View模式下，某些情况会ilegal memory access

### ISSUE THREAD

**Issue by MARD1NO** [Oneflow-Inc/oneflow#8637]
### 可复现代码
```python
import oneflow as t

s = t.triu(t.ones(804, 804).cuda(), diagonal=1).repeat(32, 1, 1).byte()
print(s.numpy())
```

当关闭view，代码可以正常跑通
```text
export ONEFLOW_DISABLE_VIEW=1
```

**Comment by Flowingsun007** [comment]
这个case里用到了repeat，RepeatFunctor里又用到了reshape、expand。猜测是repeat里对expand、reshape的不当使用导致会导致隐晦bug，后面我跟进一下。

**Comment by Flowingsun007** [comment]
这里，对比了一下oneflow和torch的实现，torch的repeat op输出始终为contiguous tensor，而oneflow在functor层面最后使用了reshape，导致输出是non-contiguous的，做contiguous()处理后结果就正常了

**Comment by wyg1997** [comment]
> 这里，对比了一下oneflow和torch的实现，torch的repeat op输出始终为contiguous tensor，而oneflow在functor层面最后先使用了Expand，然后使用了reshape，导致输出是non-contiguous的，做contiguous()处理后结果就正常了：#8645

好像不太合理，为什么 expand + reshape 会改变 is_contiguous 属性呢？
