### ISSUE TITLE
oneflow.tensor initialization error in distribute mode

### ISSUE THREAD

**Issue by reygu** [Oneflow-Inc/oneflow#8668]
## Summary

distribute 模式下 oneflow.tensor() 传入非 oneflow 的 tensor  时 device 会出错

## Code to reproduce bug

```python
import oneflow

a = oneflow.randn(2, 2)
b = oneflow.tensor([[1, 2], [1, 2]])  # or b = oneflow.tensor(torch.randn(2, 2))
print(a.device, b.device)

c = oneflow.add(a, b)
print(a.device, b.device, c.device)
```

`python -m oneflow.distributed.launch --nproc_per_node 2 test.py`  运行得到输出：

```
cpu:0 cpu:0
cpu:0 cpu:1
cpu:0 cpu:0 cpu:0
Traceback (most recent call last):
  File "/path/to/test.py", line 7, in <module>
    c = oneflow.add(a, b)
RuntimeError: Check failed: *default_device == *input_device Expected all tensors to be on the same device, but found at least two devices, cpu:0 (positional 0) and cpu:1 (positional 1)!
```

以下代码是可以正常运行的

```python
import oneflow

a = oneflow.randn(2, 2)
b = oneflow.randn(2, 2)
print(a.device, b.device)

c = oneflow.add(a, b)
print(a.device, b.device, c.device)
```

## System Information

- OneFlow version : version: 0.8.0.dev20220704+cu102

**Comment by lixinqi** [comment]
不论rank多少，cpu的张量默认在cpu:0上。这应该就是pytorch的逻辑。

**Comment by lixinqi** [comment]
@liujuncheng 我记得你曾经建议过cpu张量默认就应该在cpu:0上，当时有什么考虑吗？

**Comment by lixinqi** [comment]
> @liujuncheng 我记得你曾经建议过cpu张量默认就应该在cpu:0上，当时有什么考虑吗？

没印象了，忘了之前的语境

**Comment by lixinqi** [comment]
应该改 
```
RuntimeError: Check failed: *default_device == *input_device Expected
```
这个报错的位置。如果是cpu的话不比较设备id

**Comment by clackhan** [comment]
这个的关键是要统一所有 src op的行为，device为cpu时，不能出现 https://github.com/Oneflow-Inc/oneflow/issues/8668#issue-1305920509 中flow. randn的id为0，flow. tensor为local_rank的矛盾
