### ISSUE TITLE
docsV0.8.0 删除接口check list

### ISSUE THREAD

**Issue by laoliu97** [Oneflow-Inc/oneflow#8695]
## PR：https://github.com/Oneflow-Inc/oneflow/pull/8392
|  task   | 负责人  |
|  ----  | ----  |
| oneflow  | Chengguoliang|
| oneflow.nn  | Chengguoliang |
|oneflow.Tensor| Chengguoliang |
|oneflow.linalg| Chengguoliang |
|oneflow.nn.init| Chengguoliang |
|oneflow.utils.data|Chengguoliang|
|oneflow.optim|Chengguoliang|
|oneflow.autograd|Chengguoliang|
|tensor attribute|Liuxuan 无|
|oneflow.cuda|Liuxuan| 
|oneflow.nn.functional|Liuxuan|
|oneflow.nn.graph|ChenQiaoLing https://github.com/Oneflow-Inc/oneflow/issues/8695#issuecomment-1190967869|
|oneflow.distributed|ChenQiaoLing 无|
|oneflow.oneEmbedding| ChenQiaoLing 无|

**Comment by laoliu97** [comment]
## oneflow.cuda 删除的接口
| oneflow.cuda 接口 | 接口删除情况说明 |处理办法|
| -------------------- | ---------- | -------------- |
| cuda.empty_cache| 文档重构时以`docsv0.8`分支作为参考，而此接口于3周前添加文档，重构时并未发现该接口。也许在重构后有同事添加，或者是`docsv0.8`分支未merge `master`获取更新。https://github.com/Oneflow-Inc/oneflow/pull/8514/files#diff-fa1840d691e1cc1768c6cd2b2d296cd68e7052861a5b6cac85e949cb347815ee |补充增加|

## oneflow.nn.functional删除的接口
| oneflow.nn.functional接口 | 接口删除情况说明 |处理办法|
| -------------------- | ---------- | -------------- |
| functional.ctc_greedy_decoder| 文档重构时以`docsv0.8`分支作为参考，文档重构于2周前完成，重构时并未发现该接口。也许在重构后有同事添加，或者是`docsv0.8`分支未merge `master`获取更新。PR: https://github.com/Oneflow-Inc/oneflow/pull/8514/files#diff-2c9d00219c966a687953069d2e4e18e113c3068d4cd0be023bb4fcdd248e82c7  重构时的接口检查：https://github.com/Oneflow-Inc/OneTeam/issues/1452#issuecomment-1168297596|补充增加|
| functional.upsample| 文档重构时以`docsv0.8`分支作为参考，而此接口于2周前添加，文档重构已完成，重构过程中该接口并未实现。也许在重构后有同事添加，或者是`docsv0.8`分支未merge `master`获取更新。PR:https://github.com/Oneflow-Inc/oneflow/pull/8514/files#diff-2c9d00219c966a687953069d2e4e18e113c3068d4cd0be023bb4fcdd248e82c7 重构时的接口检查：https://github.com/Oneflow-Inc/OneTeam/issues/1452#issuecomment-1168297596|补充增加|

## Tensor Attributes 删除的接口
| oneflow.cuda 接口 | 接口删除情况说明 |处理办法|
| -------------------- | ---------- | -------------- |
|无|||

**Comment by Chenqll** [comment]
# nn.graph v0.8.0 重构时漏下的 oneflow 特有接口
            set_zero_redundancy_optimizer_mode,
            set_zero_redundancy_optimizer_min_size_after_split,
            enable_xla_jit,
            enable_tensorrt,
            enable_openvino,
# 疑问？？
上述接口在 0.7.0 版本中被引入，但在重构前的 master 版本又被删除，是否是已经被弃用的接口？
验证如下：
```
>>> import oneflow
>>> oneflow.nn.graph.graph_config.GraphConfig.enable_xla_jit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'GraphConfig' has no attribute 'enable_xla_jit'
>>> oneflow.nn.graph.graph_config.GraphConfig.enable_xla_jit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'GraphConfig' has no attribute 'enable_xla_jit'
>>> oneflow.nn.graph.graph_config.GraphConfig.enable_tensorrt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'GraphConfig' has no attribute 'enable_tensorrt'
```

**Comment by strint** [comment]
> # nn.graph v0.8.0 重构时漏下的 oneflow 特有接口
> ```
>         set_zero_redundancy_optimizer_mode,
>         set_zero_redundancy_optimizer_min_size_after_split,
>         enable_xla_jit,
>         enable_tensorrt,
>         enable_openvino,
> ```
> 
> # 疑问？？
> 上述接口在 0.7.0 版本中被引入，但在重构前的 master 版本又被删除，是否是已经被弃用的接口？ 验证如下：

没错，上面的5个接口已经废弃。

**Comment by laoliu97** [comment]
## 检查oneflow、oneflow.nn、oneflow.optim、oneflow.Tensor遗漏接口的docstring情况
![image](https://user-images.githubusercontent.com/85344642/180127696-68580d8e-ff85-43aa-92b4-f809933ca40a.png)

不含docstring的接口有：
oneflow.roc_auc_score
nn.OFRecordImageDecoder
nn.OFRecordImageDecoderRandomCrop
nn.OFRecordRawDecoder
nn.OFRecordReader
nn.Parameter
oneflow.optim.Optimizer
