### ISSUE TITLE
oneflow.eq() crashed

### ISSUE THREAD

**Issue by EaglewithFire** [Oneflow-Inc/oneflow#8701]
## Summary

crashed while trying to run oneflow.eq() to compare float16 Tensor

Error Message:
terminate called after throwing an instance of 'dnnl::error'
  what():  could not create a primitive descriptor iterator
Aborted (core dumped)

## Code to reproduce bug

```python
import oneflow

init = oneflow.empty([2, 3, 4, 5], dtype=oneflow.float64)
init.uniform_(0, 3)
t1 = oneflow.HalfTensor(init)
t2 = oneflow.HalfTensor(init)
print("init OK")
res = oneflow.eq(t1, t2)
print(res)
```

## System Information

- What is your OneFlow installation (pip, source, dockerhub): pip
- OS: Ubuntu 18.04.1
- OneFlow version (run `python3 -m oneflow --doctor`): version: 0.7.0+cu112
- Python version: 3.9.12(64 bit)
- CUDA driver version:  470.129.06
- GPU models: Nvidia RTX-2060
- Other info: CPU model Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

**Comment by s14n** [comment]
Thanks for your feedback. This code works well in oneflow v0.8.0. Please try to update oneflow to v0.8.0 by `pip3 install oneflow`.
