### ISSUE TITLE
oneflow.nn.UpsamplingNearest2d produces cudaGetLastError when executed on cuda

### ISSUE THREAD

**Issue by xxxyyyzzz12345** [Oneflow-Inc/oneflow#8765]
## Summary

oneflow.nn.UpsamplingNearest crashes (core dumped) when runned on cuda.

The following code snippet produces cudaGetLastError() only when it is runned on cuda:
```
t = oneflow.tensor([[[[ 3.6097, -2.1757],[ 3.9655,  1.9233]]]], dtype=oneflow.float32).cuda()
mod = oneflow.nn.UpsamplingNearest2d(scale_factor=0.49)
output = mod(t)
```

Output:
```
F20220727 20:10:10.712666 2908952 cuda_stream_type.cpp:61] Check failed: cudaGetLastError() : invalid configuration argument (9) 
*** Check failure stack trace: ***
    @     0x7f6a1a6e849a  (unknown)
    @     0x7f6a1a6e8782  (unknown)
    @     0x7f6a1a6e8007  (unknown)
    @     0x7f6a1a6eab79  (unknown)
    @     0x7f6a13e8e459  oneflow::vm::CudaStreamType::Compute()
    @     0x7f6a13ea3674  oneflow::vm::VirtualMachineEngine::DispatchInstruction()
    @     0x7f6a13ea422f  oneflow::vm::VirtualMachineEngine::DispatchAndPrescheduleInstructions()
    @     0x7f6a13ea95f8  oneflow::vm::VirtualMachineEngine::Schedule()
    @     0x7f6a13e9a2f0  oneflow::VirtualMachine::ScheduleLoop()
    @     0x7f6a1d0dbecf  (unknown)
    @     0x7f6a8622e609  start_thread
    @     0x7f6a86153133  clone
Aborted (core dumped)
```
## System Information

- What is your OneFlow installation (pip, source, dockerhub): pip
- OS: Ubuntu 20.04.2 LTS
- OneFlow version (run `python3 -m oneflow --doctor`): 0.7.0+cu112
- Python version: 3.8.8
- CUDA driver version: 11.4

**Comment by xxxyyyzzz12345** [comment]
Other apis like oneflow.nn.functional.interpolate also produce the same error when one or some of the dimensions of the output tensor is 0.

**Comment by MARD1NO** [comment]
In PyTorch，this example is ilegal:
```text
  File "/home/zzk/miniconda3/envs/oneflow-dev-clang10-v2/lib/python3.8/site-packages/torch/nn/modules/upsampling.py", line 153, in forward
    return F.interpolate(input, self.size, self.scale_factor, self.mode, self.align_corners,
  File "/home/zzk/miniconda3/envs/oneflow-dev-clang10-v2/lib/python3.8/site-packages/torch/nn/functional.py", line 3910, in interpolate
    return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
RuntimeError: Input and output sizes should be greater than 0, but got input (H: 2, W: 2) output (H: 0, W: 0)
```

**Comment by daquexian** [comment]
> In PyTorch，this example is ilegal:
> 
> ```
>   File "/home/zzk/miniconda3/envs/oneflow-dev-clang10-v2/lib/python3.8/site-packages/torch/nn/modules/upsampling.py", line 153, in forward
>     return F.interpolate(input, self.size, self.scale_factor, self.mode, self.align_corners,
>   File "/home/zzk/miniconda3/envs/oneflow-dev-clang10-v2/lib/python3.8/site-packages/torch/nn/functional.py", line 3910, in interpolate
>     return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
> RuntimeError: Input and output sizes should be greater than 0, but got input (H: 2, W: 2) output (H: 0, W: 0)
> ```

是不是显示出我们这里缺少对形状的检查
