### ISSUE TITLE
暂时不支持nn.pairwisedistance() 及 Variable

### ISSUE THREAD

**Issue by wjy3326** [Oneflow-Inc/oneflow#8841]
暂时不支持nn.pairwisedistance() 及 Variable，然后我就用torch.nn.pairwisedistance() 代替了，Variable也使用了torch的，请问这对训练结果或者训练速度有影响吗？

**Comment by yuanms2** [comment]
我们还没有混合使用过 torch 和 oneflow ，无论是效率还是正确性应该都是没有保证的

Variable 是不是在torch 未来的版本要废弃的，统一使用parameter? 

方便说是哪个模型里需要pairwisedistance 吗? 我们看看怎么尽快支持起来

**Comment by BBuf** [comment]
> 暂时不支持nn.pairwisedistance() 及 Variable，然后我就用torch.nn.pairwisedistance() 代替了，Variable也使用了torch的，请问这对训练结果或者训练速度有影响吗？

回复到这里吧。https://github.com/Oneflow-Inc/OneTeam/issues/1207#issuecomment-1073432125 Variable这个是过时的用法就不用写了，用Tensor代替吧

**Comment by wjy3326** [comment]
> > 暂时不支持nn.pairwisedistance() 及 Variable，然后我就用torch.nn.pairwisedistance() 代替了，Variable也使用了torch的，请问这对训练结果或者训练速度有影响吗？
> 
> 回复到这里吧。https://github.com/Oneflow-Inc/OneTeam/issues/1207#issuecomment-1073432125 Variable这个是过时的用法就不用写了，用Tensor代替吧

抱歉这个链接打不开

**Comment by wjy3326** [comment]
> 我们还没有混合使用过 torch 和 oneflow ，无论是效率还是正确性应该都是没有保证的
> 
> Variable 是不是在torch 未来的版本要废弃的，统一使用parameter?
> 
> 方便说是哪个模型里需要pairwisedistance 吗? 我们看看怎么尽快支持起来

您好，是TransE, TransH模型里面用到的，我现在用torch.nn.pairwisedistance()可以跑通，但是不知道

> > > 暂时不支持nn.pairwisedistance() 及 Variable，然后我就用torch.nn.pairwisedistance() 代替了，Variable也使用了torch的，请问这对训练结果或者训练速度有影响吗？
> > 
> > 
> > 回复到这里吧。https://github.com/Oneflow-Inc/OneTeam/issues/1207#issuecomment-1073432125 Variable这个是过时的用法就不用写了，用Tensor代替吧
> 
我用variable是在这里
if self.args.usegpu:
     with torch.cuda.device(self.args.gpunum):
          posX = Variable(torch.LongTensor(posX).cuda())
          negX = Variable(torch.LongTensor(negX).cuda())
请问把这里的Variable改成Tensor就行吗，但是好像不是可训练的参数吧？

**Comment by wjy3326** [comment]
> 我们还没有混合使用过 torch 和 oneflow ，无论是效率还是正确性应该都是没有保证的
> 
> Variable 是不是在torch 未来的版本要废弃的，统一使用parameter?
> 
> 方便说是哪个模型里需要pairwisedistance 吗? 我们看看怎么尽快支持起来

你好，是TransH, TransE模型需要的，在最后计算距离的时候

**Comment by yuanms2** [comment]
> > 我们还没有混合使用过 torch 和 oneflow ，无论是效率还是正确性应该都是没有保证的
> > Variable 是不是在torch 未来的版本要废弃的，统一使用parameter?
> > 方便说是哪个模型里需要pairwisedistance 吗? 我们看看怎么尽快支持起来
> 
> 您好，是TransE, TransH模型里面用到的，我现在用torch.nn.pairwisedistance()可以跑通，但是不知道
> 
> > > > 暂时不支持nn.pairwisedistance() 及 Variable，然后我就用torch.nn.pairwisedistance() 代替了，Variable也使用了torch的，请问这对训练结果或者训练速度有影响吗？
> > > 
> > > 
> > > 回复到这里吧。[Oneflow-Inc/OneTeam#1207 (comment)](https://github.com/Oneflow-Inc/OneTeam/issues/1207#issuecomment-1073432125) Variable这个是过时的用法就不用写了，用Tensor代替吧
> 
> 我用variable是在这里 if self.args.usegpu: with torch.cuda.device(self.args.gpunum): posX = Variable(torch.LongTensor(posX).cuda()) negX = Variable(torch.LongTensor(negX).cuda()) 请问把这里的Variable改成Tensor就行吗，但是好像不是可训练的参数吧？

关于从Variable 改成 Tensor，可以参考pytorch文档，有例子
https://pytorch.org/blog/pytorch-0_4_0-migration-guide/

谢谢，我们研究一下TransH, TransE模型，并把缺失的算子尽快补齐。

**Comment by wjy3326** [comment]
import oneflow as torch

posX = [[4185651,     166,     622],
        [1520396,      31, 1253465],
        [3353699,      46,  518777],
        [ 410635,     479,  812141]]
posX = torch.LongTensor(posX).cuda()
print("pos",posX) 
上述程序没有反应，也不报错

**Comment by BBuf** [comment]
> 

我本地试了一下是正常的，python3 -m oneflow --doctor 可以查看一下你的oneflow版本，另外可以直接用torch跑一下确认一下gpu是否正常工作。

**Comment by wjy3326** [comment]
> python3 -m oneflow --doctor

您好，我的oneflow版本是0.8.0，我的torch gpu可以正常工作。但是运行还是没有出结果

**Comment by BBuf** [comment]
> > python3 -m oneflow --doctor
> 
> 您好，我的oneflow版本是0.8.0，我的torch gpu可以正常工作。但是运行还是没有出结果

意思是oneflow运行的时候没有出结果，pytorch正常出结果吗？

**Comment by wjy3326** [comment]
是的，目前一直没有显示结果。就显示下面一句话

python test_.py 
loaded library: /lib64/libibverbs.so.1

**Comment by ShiyuanResearch** [comment]
你好，这种情况多数是因为之前设置了一些环境变量，比如 WORLD_SIZE。您检查一下是否有类似的环境变量未清理？

**Comment by ouyangyu** [comment]
> > python3 -m oneflow --doctor
> 
> 您好，我的oneflow版本是0.8.0，我的torch gpu可以正常工作。但是运行还是没有出结果

您能粘贴一下输出吗？想看一下安装的cuda版本

**Comment by wjy3326** [comment]
> 你好，这种情况多数是因为之前设置了一些环境变量，比如 WORLD_SIZE。您检查一下是否有类似的环境变量未清理？

我的代码只有上述几行，没有额外的环境变量呢，不转cuda可以正常输出，转cuda就没有结果

**Comment by wjy3326** [comment]
> > > python3 -m oneflow --doctor
> > 
> > 
> > 您好，我的oneflow版本是0.8.0，我的torch gpu可以正常工作。但是运行还是没有出结果
> 
> 您能粘贴一下输出吗？想看一下安装的cuda版本。以及nvidia-smi结果中的Driver Version

torch输出结果：
>>> posX = [[4185651,     166,     622],
        [1520396,      31, 1253465],
        [3353699,      46,  518777],
        [ 410635,     479,  812141]]
>>> posX = torch.LongTensor(posX).cuda()
>>> print(posX)
tensor([[4185651,     166,     622],
        [1520396,      31, 1253465],
        [3353699,      46,  518777],
        [ 410635,     479,  812141]], device='cuda:0')

**Comment by wjy3326** [comment]
cuda 11.4版本

**Comment by ouyangyu** [comment]
> > > > python3 -m oneflow --doctor
> > > 
> > > 
> > > 您好，我的oneflow版本是0.8.0，我的torch gpu可以正常工作。但是运行还是没有出结果
> > 
> > 
> > 您能粘贴一下输出吗？想看一下安装的cuda版本。以及nvidia-smi结果中的Driver Version
> 
> torch输出结果：
> 
> > > > posX = [[4185651,     166,     622],
> > > > [1520396,      31, 1253465],
> > > > [3353699,      46,  518777],
> > > > [ 410635,     479,  812141]]
> > > > posX = torch.LongTensor(posX).cuda()
> > > > print(posX)
> > > > tensor([[4185651,     166,     622],
> > > > [1520396,      31, 1253465],
> > > > [3353699,      46,  518777],
> > > > [ 410635,     479,  812141]], device='cuda:0')

`python3 -m oneflow --doctor `这个输出以及，`nvidia-smi`命令结果中的Driver Version

**Comment by wjy3326** [comment]
loaded library: /lib64/libibverbs.so.1
path: ['/u01/wangjunyan/anaconda3/envs/recommendation/lib/python3.7/site-packages/oneflow']
version: 0.8.0
git_commit: fa6edf31
cmake_build_type: Release
rdma: True
mlir: True

| NVIDIA-SMI 470.63.01    Driver Version: 470.63.01    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |

**Comment by ouyangyu** [comment]
`python3 -m pip uninstall -y oneflow`
`python3 -m pip install --find-links https://release.oneflow.info oneflow==0.8.0+cu112`
麻烦您再试试。

**Comment by wjy3326** [comment]
现在可以出结果了。
我现在需要用import torch.nn.functional as F  ，即F中的relu函数，但是把torch改为oneflow报错，
TypeError: relu(): missing required argument x
请问这个函数可以用原来torch的吗还是需要重新写relu函数呢？

**Comment by ouyangyu** [comment]
> 现在可以出结果了。 我现在需要用import torch.nn.functional as F ，即F中的relu函数，但是把torch改为oneflow报错， TypeError: relu(): missing required argument x 请问这个函数可以用原来torch的吗还是需要重新写relu函数呢？

您可以参考一下我们的API文档 ：
https://oneflow.readthedocs.io/en/master/generated/oneflow.nn.functional.relu.html?highlight=oneflow.nn.functional.relu#
https://oneflow.readthedocs.io/en/master/generated/oneflow.nn.ReLU.html#oneflow.nn.ReLU

**Comment by wjy3326** [comment]
谢谢。现在又有一个问题，torch.norm 改为oneflow遇到错误：
AttributeError: module 'oneflow' has no attribute 'norm'

**Comment by ouyangyu** [comment]
> 谢谢。现在又有一个问题，torch.norm 改为oneflow遇到错误： AttributeError: module 'oneflow' has no attribute 'norm'

您可能需要安装一下最新master（[Nightly版本](https://github.com/Oneflow-Inc/oneflow#install-with-pip-package)）的OneFlow了：`python3 -m pip uninstall -y oneflow && python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu112`

**Comment by wjy3326** [comment]
您好，现在程序应该可以跑了，但是显示oom的错误，我之前就是因为模型参数太大 一张卡跑不了，请问oneflow怎么设置只加载一部分模型参数到GPU，剩下的放到CPU上呢？

W20220804 17:55:20.659793  6255 ep_backend_allocator.cpp:37] OOM error is detected, process will exit. And it will start to reset CUDA device for releasing device memory.
F20220804 17:55:20.659757  6255 virtual_machine_engine.cpp:382] out of memory
Error message from /home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/virtual_machine_engine.cpp:382
        instruction->Prepare(): reset device

  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/virtual_machine_engine.cpp", line 382, in DispatchInstruction
    instruction->Prepare()
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/fuse_instruction_policy.h", line 70, in Prepare
    instruction->Prepare()
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/op_call_instruction_policy.cpp", line 34, in Prepare
    TryAllocateTempStorageThenDeallocate(op_call_instruction_policy, allocator)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/op_call_instruction_policy.cpp", line 96, in TryAllocateTempStorageThenDeallocate
    allocator->Allocate(&mem_ptr, byte_size)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/bin_allocator.h", line 392, in Allocate
    AllocateBlockToExtendTotalMem(aligned_size)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/bin_allocator.h", line 305, in AllocateBlockToExtendTotalMem
    backend_->Allocate(&mem_ptr, final_allocate_bytes)
Error Type: oneflow.ErrorProto.out_of_memory_error

**Comment by ShiyuanResearch** [comment]
你好，可以参考 https://docs.oneflow.org/master/cookies/one_embedding.html 将大规模embedding分层存储

**Comment by wjy3326** [comment]
您好，请问配置表参数中的 make_table_options 有什么作用呢？就是给embedding进行参数初始化的吗

**Comment by wjy3326** [comment]
您好，配置表参数中的make_table_options 函数有什么作用呢？就是用来给embedding初始化吗？

**Comment by ShiyuanResearch** [comment]
是的，用来指定初始化方法

**Comment by ShawnXuan** [comment]
可以参考[这一小段](https://github.com/Oneflow-Inc/models/blob/ctr_benchmark_test/RecommenderSystems/dlrm/dlrm_train_eval.py#L273-L279)

```
        scales = np.sqrt(1 / np.array(table_size_array))
        tables = [
            flow.one_embedding.make_table(
                flow.one_embedding.make_uniform_initializer(low=-scale, high=scale)
            )
            for scale in scales
        ]
```
@wjy3326

**Comment by wjy3326** [comment]
嗯嗯，请问one_embedding.make_cached_host_mem_store_options()函数中的capacity是指什么含义呢？是指embedding的第一个维度的大小吗或者是embedding的个数吗？

**Comment by ShiyuanResearch** [comment]
vocab_size，总词表大小。
您可以搭配样例 https://github.com/Oneflow-Inc/models/tree/main/RecommenderSystems 和API文档 https://oneflow.readthedocs.io/en/master/one_embedding.html 来理解、使用OneEmbedding。

**Comment by ShawnXuan** [comment]
是的

**Comment by wjy3326** [comment]
您好，我测试了官方代码给的one_embedding的例子，出现这个错误：

F20220805 17:11:34.562752 63261 persistent_table.cpp:86] Check failed: generate/0-1/VALUE_SIZE
*** Check failure stack trace: ***
    @     0x7f3380ce2c9a  google::LogMessage::Fail()
    @     0x7f3380ce2f82  google::LogMessage::SendToLog()
    @     0x7f3380ce2807  google::LogMessage::Flush()
    @     0x7f3380ce5379  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f33768da76f  oneflow::embedding::(anonymous namespace)::InitOrCheckMetaValue()
    @     0x7f33768dfb04  oneflow::embedding::NewPersistentTable()
    @     0x7f33768eb4bd  oneflow::embedding::NewPersistentTableKeyValueStore()
    @     0x7f33768622db  oneflow::embedding::EmbeddingManager::CreateKeyValueStore()
    @     0x7f34419c5741  (unknown)
    @     0x7f3441bd507f  (unknown)
    @     0x5587e7ded3f4  _PyMethodDef_RawFastCallDict
    @     0x5587e7dbe2ee  _PyObject_FastCallDict
    @     0x5587e7dd3141  method_call
    @     0x5587e7dbeb94  PyObject_Call
    @     0x5587e7d61f94  slot_tp_init.cold.2275
    @     0x5587e7dde847  type_call
    @     0x7f3441bd4743  (unknown)
    @     0x5587e7e2316c  _PyObject_FastCallKeywords
    @     0x5587e7e6b6b5  _PyEval_EvalFrameDefault
    @     0x5587e7dbd3fd  _PyEval_EvalCodeWithName
    @     0x5587e7ddccd3  _PyFunction_FastCallKeywords
    @     0x5587e7e239c5  call_function
    @     0x5587e7e6b702  _PyEval_EvalFrameDefault
    @     0x5587e7dbd3fd  _PyEval_EvalCodeWithName
    @     0x5587e7dbe83e  _PyObject_FastCallDict
    @     0x5587e7e2a0ff  slot_tp_init
    @     0x5587e7e233fc  _PyObject_FastCallKeywords
    @     0x5587e7e23bd1  call_function
    @     0x5587e7e683a1  _PyEval_EvalFrameDefault
    @     0x5587e7dbce85  _PyEval_EvalCodeWithName
    @     0x5587e7dbe273  PyEval_EvalCode
    @     0x5587e7ecbc82  run_mod

**Comment by guo-ran** [comment]
您好，这个错误原因是两次运行value_size配置参数可能不一致，可以删除generate文件夹重试一下

**Comment by wjy3326** [comment]
您好，关于make_table_options指定embedding初始化方法，如果想用固定的矩阵初始化embedding应该怎么写呢，比如将每个词语的Bert的embedding作为初始化，而不是随机初始化，谢谢

**Comment by wjy3326** [comment]
请问用 oneflow.one_embedding.MultiTableEmbedding生成embedding之后，如何保存该embedding的值到txt文件呢？我试过直接保存embedding到txt，但是结果没有值，只有tensor(..., device='cuda:0', is_lazy='True', size=(2, 3, 6), dtype=oneflow.float32) 这一行。也试过用save_snapshot和load_snapshot，也没有生成值。我想得到每个id对应的embedding的值，并写入到txt文件，应该用哪个函数呢？

**Comment by ShawnXuan** [comment]
# OneEmbedding模型的外部保存与读取

OneEmbedding Snapshot的保存不同于其他variable。

### 模型保存

我们先从一般的模型保存开始说起，模型的保存一般是保存的state_dict，如下面的操作从module中提取state_dict并保存到指定目录`saved_snapshot`：

```python
flow.save(module.state_dict(), "saved_snapshot", global_dst_rank=0)
```

### OneEmbedding的模型长啥样

假设module中含有OneEmbedding，让我们看看里面存了啥？

```python
>>> import oneflow as flow
loaded library: /lib/x86_64-linux-gnu/libibverbs.so.1
>>> state_dict = flow.load("saved_snapshot")
>>> state_dict.keys()
odict_keys(['bottom_mlp.linear_layers.weight_0', 'bottom_mlp.linear_layers.bias_0', 'bottom_mlp.linear_layers.weight_1', 'bottom_mlp.linear_layers.bias_1', 'bottom_mlp.linear_layers.weight_2', 'bottom_mlp.linear_layers.bias_2', 'embedding.one_embedding.OneEmbedding', 'top_mlp.linear_layers.weight_0', 'top_mlp.linear_layers.bias_0', 'top_mlp.linear_layers.weight_1', 'top_mlp.linear_layers.bias_1', 'top_mlp.linear_layers.weight_2', 'top_mlp.linear_layers.bias_2', 'top_mlp.linear_layers.weight_3', 'top_mlp.linear_layers.bias_3', 'top_mlp.linear_layers.weight_4', 'top_mlp.linear_layers.bias_4'])
>>> state_dict['embedding.one_embedding.OneEmbedding']
'2022-04-15-22-53-04-270525'
```

其中`embedding.one_embedding.OneEmbedding`就是OneEmbedding的模型，但是里面存的是一个字符串'2022-04-15-22-53-04-270525'，我们去persistent_path看看：

```bash
$ tree -d persistent_path
persistent_path
├── 0-4
│   ├── keys
│   ├── snapshots
│   │   └── 2022-04-15-22-53-04-270525
│   └── values
├── 1-4
│   ├── keys
│   ├── snapshots
│   │   └── 2022-04-15-22-53-04-270525
│   └── values
├── 2-4
│   ├── keys
│   ├── snapshots
│   │   └── 2022-04-15-22-53-04-270525
│   └── values
└── 3-4
    ├── keys
    ├── snapshots
    │   └── 2022-04-15-22-53-04-270525
    └── values
```

发现里面有四个子目录，`0-4` `1-4` `2-4` `3-4`，这是为4个GPU设备分别准备的4个目录，这四个目录的`snapshots`中都有一个`2022-04-15-22-53-04-270525`目录。

### 读出来看看

到此信息就足够了，我们可以根据这些信息编写一个程序，把这个oneembedding模型读取出来看看:

```python
import os
from oneflow.one_embedding import make_persistent_table_reader

tables = [os.path.join('persistent_path', f'{i}-4') for i in range(4)]
with make_persistent_table_reader(tables, "2022-04-15-22-53-04-270525", flow.int64, flow.float, 128) as reader:
    for ks, vs in reader:
        print(ks.shape, vs.shape)
        print(ks[:10])
        print(vs[0])
        break
```

运行之后是下面的效果

```
(65536,) (65536, 128)
[412031366 410693431  66097299 918940899 912720051  78947352 812427704
 425200005 887394658  51432061]
[-9.00889499e-05 -1.10312161e-04 -5.38181630e-05 -2.25749449e-04
  5.30043289e-05  7.47279337e-05  5.05750031e-05 -1.25098493e-04
...
 -3.67888970e-05 -8.75042460e-05 -9.16112549e-05  2.15454929e-05
  8.09440680e-05 -2.22518083e-05  1.06374908e-04 -1.26190993e-04]
```

注：

- reader是循环读的，并不是把完整的模型都读出来，遍历完之后才能拿到完整模型。
- `make_persistent_table_reader`的第一个参数传入的是`tables`对应的是`0-4` `1-4` `2-4` `3-4`这几个目录的地址。
- `make_persistent_table_reader`的第二个参数传入的是`"2022-04-15-22-53-04-270525"`，对应了state_dict里面的值。

### 写模型

有时我们会有写入模型的需求，比如，和其他框架的某个实现对标时，需要把其他框架的模型转成oneflow的模型。下面给一个写模型的例子：

```python
import os
from oneflow.one_embedding import make_persistent_table_writer

tables = [os.path.join('persistent_path', f'{i}-4') for i in range(4)]
with make_persistent_table_writer(tables, "2022-04-15-22-53-04-270525", flow.int64, flow.float, 128) as writer:
    keys = np.arange(1024).astype(np.int64)
    values = np.arange(128*1024).reshape((1024, 128)).astype(np.float32)
    writer.write(keys, values)
```

执行上面的脚本，会往4个"2022-04-15-22-53-04-270525"目录下追加1024个keys的embedding，这样可以一直`writer.write(keys, values)`追加下去。如果出现重复的key，原来老的key对应的value会被自动丢弃。

回到转模型的场景，还是多个表，原始每张表的keys都是从0到本表的tabel_size-1，转换的时候第一个表的keys可以用[0, table_size)，后面的表的key必须加上前面表所有id数量的和，这样才能符合OneEmbedding的要求，和转数据集的原因一样。

@wjy3326 您看这段能解决您的问题吗？读出来之后可以保存numpy，或者txt都行。

**Comment by wjy3326** [comment]
> https://oneflow.readthedocs.io/en/master/generated/oneflow.nn.ReLU.html#oneflow.nn.ReLU

请问运行之后的结果为什么是(65536,) (65536, 128)，这里的65536代表什么意思呢？128代表embedding的维度吗？

**Comment by ShawnXuan** [comment]
嗯，128是embedding的维度，65536对应的是词表大小的那个维度，因为整个表有可能会很大，make_persistent_table_reader每次返回固定65536个，所以用for循环读的。

**Comment by wjy3326** [comment]
我按照上述代码保存之后，得到的结果好像不是embedding的值，我的代码如下：
table_size_array = [8, 3, 2, 7]
vocab_size = sum(table_size_array)
num_tables = len(table_size_array)
embedding_size = 6
scales = np.sqrt(1 / np.array(table_size_array))

tables = [
    flow.one_embedding.make_table_options(
        flow.one_embedding.make_uniform_initializer(low=-scale, high=scale)
    )
    for scale in scales
]
print("table",tables)
store_options = flow.one_embedding.make_cached_host_mem_store_options(
    cache_budget_mb=8192, persistent_path="generate", capacity=vocab_size,
)

embedding = flow.one_embedding.MultiTableEmbedding(
    name="my_embedding",
    embedding_dim=embedding_size,
    dtype=flow.float,
    key_type=flow.int64,
    tables=None,  # 原来是tables
    store_options=store_options,
    default_initializer=None,
)

embedding.to("cuda")
mlp = flow.nn.FusedMLP(
    in_features=embedding_size * num_tables,
    hidden_features=[512, 256, 128,12],
    out_features=1,
    skip_final_activation=True,
)
mlp.to("cuda")

class TrainGraph(flow.nn.Graph):
    def __init__(self,):
        super().__init__()
        self.embedding_lookup = embedding
        self.mlp = mlp
        self.add_optimizer(
            flow.optim.SGD(self.embedding_lookup.parameters(), lr=0.1, momentum=0.0)
        )
        self.add_optimizer(
            flow.optim.SGD(self.mlp.parameters(), lr=0.1, momentum=0.0)
        )
    def build(self, ids):
        embedding = self.embedding_lookup(ids)
        loss = self.mlp(flow.reshape(embedding, (-1, num_tables * embedding_size)))
        loss = loss.sum()
        loss.backward()
        return loss
ids = np.random.randint(0, 1000, (2, num_tables), dtype=np.int64)
ids = [[1,2,3,2]]
print("ids",ids)
ids_tensor = flow.tensor(ids, requires_grad=False).to("cuda")
graph = TrainGraph()
loss = graph(ids_tensor)
print(loss)

state_dict = graph.state_dict()
flow.save(state_dict, 'generate/save')  # 加上global_dst_rank=0报错
state_dict=flow.load('generate/save')
print("state_dict.keys()",state_dict.keys())

tables = [os.path.join('generate', f'{i}-{i+1}') for i in range(1)]
print("tables",tables)
vss=[]
with make_persistent_table_reader(tables, "2022-08-09-10-10-47-938898", flow.int64, flow.float, 6) as reader:
    for ks, vs in reader:
        print(ks.shape, vs.shape)
        vss.extend(vs)
        print('ks[:10]',ks[:10])
        print('vs[0]',vs[0])

print("vss",vss)

最后展示的结果是：
tables ['generate/0-1']
(3,) (3, 6)
ks[:10] [3 1 2]
vs[0] [-0.05288414 -0.0729652  -0.08009089  0.01716503  0.10170611 -0.0044054 ]
vss [array([-0.05288414, -0.0729652 , -0.08009089,  0.01716503,  0.10170611,
       -0.0044054 ], dtype=float32), array([-0.05769017,  0.0573694 , -0.00868923,  0.04936837,  0.02195129,
        0.09376588], dtype=float32), array([ 0.1348534 , -0.02759682,  0.01351091, -0.04478907,  0.05675033,
       -0.02849939], dtype=float32)]
请问ks.shape, vs.shape为什么是(3,) (3, 6)，3是什么意思呢，不应该是embedding的总个数20吗？

**Comment by ShawnXuan** [comment]
因为ids = [[1,2,3,2]]，里面有三个不重复的id，这唯一的一轮训练只更新了三个，即oneembedding 表里只有三条记录。只有所有的id都被更新过之后，表才是完整的。

**Comment by wjy3326** [comment]
请问ks返回的值  [3 1 2] 是embedding的索引吗？vs 返回的embedding矩阵中，第一行是索引是3的元素的embedding吗，第二行是索引为1的元素的embedding吗？如果没有全部更新索引，那保存的embedding都是不完整的吗

**Comment by ShawnXuan** [comment]
> 请问ks返回的值 [3 1 2] 是embedding的索引吗？vs 返回的embedding矩阵中，第一行是索引是3的元素的embedding吗，第二行是索引为1的元素的embedding吗？

是的

> 如果没有全部更新索引，那保存的embedding都是不完整的吗

是的。正常情况下，训练完一个epoch，所有索引都会被更新。

**Comment by wjy3326** [comment]
您好，假如我的embedding中创建了三个表[A, B, C] ，然后我输入的数据是[id1, id2, id3]，其中id1跟id3想查询表A，id2想查询表B和表C，应该怎么输入模型呢？因为我看例子都是随机初始化的id，谢谢

**Comment by wjy3326** [comment]
您好，请问能再回复一个问题吗？假如我的embedding中创建了三个表[A, B, C] ，然后我输入的数据是[id1, id2, id3]，其中id1跟id3想查询表A，id2想查询表B和表C，应该怎么输入模型呢？因为我看例子都是随机初始化的id，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Oneflow-Inc/oneflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月9日(星期二) 下午3:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Oneflow-Inc/oneflow] 暂时不支持nn.pairwisedistance() 及 Variable (Issue #8841)





  
请问ks返回的值 [3 1 2] 是embedding的索引吗？vs 返回的embedding矩阵中，第一行是索引是3的元素的embedding吗，第二行是索引为1的元素的embedding吗？
  
是的
  
如果没有全部更新索引，那保存的embedding都是不完整的吗
  
是的。正常情况下，训练完一个epoch，所有索引都会被更新。

**Comment by ShawnXuan** [comment]
id不是随机的，根据id查询到的embedding vector value是随机初始化的。OneEmbedding的设计中，首先会对id进行hash得到一个key，然后根据这个key去查询得到的embedding vector value，也就是说整体维护的是一张hash表，没有严格的A B C三个表的物理界限。回到您的问题，如果id1和id3是相同的值，那么查寻到的embedding也是同一个。再进一步，如果id1和id3的取值属于同一个set（表A的id），那么无论是id1还是id3查询到的embedding也属于这个set能够查到的embedding（表A的values）。同样，id2的取值范围如果就是B和C表id的范围，也就相当于在B和C中查询。

**Comment by wjy3326** [comment]
table_size_array=[8, 3, 7]的话是创建了3张表对吗，那3张表的索引都是从0开始吗？您说的整体维护的是一张hash表，是3张表的索引是依次递增吗？因为我的数据默认是三张单独的表，数据的索引都是从0开始的。另外，查询的ids=[[1,2,3]] , 这里三个值是分别从三个表里查询吗，第一张表查询id为1的embedding返回，第二张表查询id为2的embedding返回，那我想让ids的第一个id跟第三个id都查询表1，第二个id查询表2跟表3，就是返回4个向量，怎么让模型知道我想查的是哪个表呢

**Comment by ShawnXuan** [comment]
OneEmbedding只维护一张hash table（hash map），可以看成是所有表拼接起来的
假设有三张表，输入的ids = [1, 3, 0]，分别从三张表里查询数据。
<img width="600" alt="image" src="https://user-images.githubusercontent.com/16327185/183854571-c4f47fa0-4092-4287-8622-56eaeaec12e8.png">

现在是一张拼起来的表，如下：
<img width="609" alt="image" src="https://user-images.githubusercontent.com/16327185/183854809-db6742f6-7f1e-44b3-ae9f-90324eeb7921.png">
就需要改变输入的ids=[1, 5, 6]，能查到同样的数据。

进一步，OneEmbedding维护的是hash table，对索引没有非要从0开始且连续的要求。只要能够保证不同表里的索引不同就可以了。


> 那我想让ids的第一个id跟第三个id都查询表1，第二个id查询表2跟表3，就是返回4个向量，怎么让模型知道我想查的是哪个表呢

如果确实有这种需求，建议表1用一个oneembedding或embedding，表2表3用一个oneembedding（参考[deepfm的例子](https://github.com/Oneflow-Inc/models/blob/main/RecommenderSystems/deepfm/deepfm_train_eval.py#L288)），把输入数据分开传入。

**Comment by wjy3326** [comment]
> > 谢谢。现在又有一个问题，torch.norm 改为oneflow遇到错误： AttributeError: module 'oneflow' has no attribute 'norm'
> 
> 您可能需要安装一下最新master（[Nightly版本](https://github.com/Oneflow-Inc/oneflow#install-with-pip-package)）的OneFlow了：`python3 -m pip uninstall -y oneflow && python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu112`

现在用这个链接下载的oneflow版本是0.7，好像安装了还是提示需要安装oneflow

**Comment by ShiyuanResearch** [comment]
你好，可能是缓存或者其他原因导致的
您尝试`python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu112 -U`是否可以升级安装

**Comment by marigoold** [comment]
> 暂时不支持nn.pairwisedistance() 及 Variable，然后我就用torch.nn.pairwisedistance() 代替了，Variable也使用了torch的，请问这对训练结果或者训练速度有影响吗？

您好，`oneflow.nn.PairwiseDistance` 以及 `oneflow.nn.functional.pairwise_distance` 已经实现，可以更新 nightly 的 oneflow 来使用这两个算子
