### ISSUE TITLE
请问有没有考虑在oneflow.nn.CrossEntropyLoss的参数中增加label_smoothing？

### ISSUE THREAD

**Issue by WanShaw** [Oneflow-Inc/oneflow#8857]
增加label_smoothing用于标签平滑。

**Comment by leaves-zwx** [comment]
这个功能是在未来工作计划之中的。

**Comment by WanShaw** [comment]
期待0.9.0版本增加这个参数，谢谢

**Comment by yuanms2** [comment]
> 期待0.9.0版本增加这个参数，谢谢，如果你看到了，那就可以关闭这个issue了

谢谢您的建议

**Comment by yuanms2** [comment]
这个label smoothing 在pytorch中是不是支持？

**Comment by leaves-zwx** [comment]
> 这个label smoothing 在pytorch中是不是支持？

https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html#torch.nn.CrossEntropyLoss
 
是支持的。

**Comment by yuanms2** [comment]
好的，那我们应该是在未来的版本对齐的
