### ISSUE TITLE
Could you please add the "inverse" method to the Tensor object just like PyTorch?

### ISSUE THREAD

**Issue by proceder-test** [Oneflow-Inc/oneflow#8893]
## Summary

Could you please add the "inverse" method to the Tensor object just like PyTorch?
>>> import torch
>>> torch.Tensor.inverse

<method 'inverse' of 'torch._C._TensorBase' objects>

>>> import oneflow
>>> oneflow.Tensor.inverse

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'Tensor' has no attribute 'inverse'

## Code to reproduce bug
>>> import oneflow
>>> oneflow.Tensor.inverse

## System Information

- What is your OneFlow installation (pip, source, dockerhub): pip
- OS: CentOS 7
- OneFlow version (run `python3 -m oneflow --doctor`):
version: 0.8.1+cu112.git.2e3ebb16
git_commit: 2e3ebb16
cmake_build_type: Release
rdma: True
mlir: True
(I didn't use the master branch due to the reduce_max issue)

- Python version: 3.7.12
- CUDA driver version: 11.3

**Comment by chengtbf** [comment]
Thank you for your feedback !  This feature will be added by :  https://github.com/Oneflow-Inc/oneflow/pull/8183
