### ISSUE TITLE
oneflow.linalg.norm produces inconsistent values on cuda when setting requires_grad=True

### ISSUE THREAD

**Issue by xxxyyyzzz12345** [Oneflow-Inc/oneflow#8904]
## Summary

The following code snippet produces inconsistent and unstable values (output1 &ne; output2). However, the results are always the same when the same code snippet is run on cpu.

## Code to reproduce bug
```
x = oneflow.rand(9,dtype=oneflow.float32).cuda()
y = x.clone().detach().cuda().requires_grad_()
out1 = oneflow.linalg.norm(x)
out2 = oneflow.linalg.norm(y)
print(out1-out2)
#-2.3842e-07 (unstable)
```
## System Information

- OneFlow version (run `python3 -m oneflow --doctor`): 0.7.0+cu112
- Python version: 4.8.8
- CUDA driver version: 11.4

**Comment by BBuf** [comment]
在master上没有这个问题。

![图片](https://user-images.githubusercontent.com/35585791/191445870-76dc91ec-ab1f-4cbc-9de8-af9964f28b43.png)
