### ISSUE TITLE
oneflow.distributed_partial_fc_sample always produces "Segmentation fault (core dumped)" error

### ISSUE THREAD

**Issue by xxxyyyzzz12345** [Oneflow-Inc/oneflow#8931]
## Summary
The following code snippet  produces core dump error. The api fails on both gpu and cpu.

```
x = oneflow.rand(5000,128,dtype=oneflow.float32).cuda()
y = oneflow.randint(-5,5,(500,)).cuda()
oneflow.distributed_partial_fc_sample(x,y,500)
```
```
Segmentation fault (core dumped)
```
## System Information

- OneFlow version (run `python3 -m oneflow --doctor`): 0.7.0+cu112

**Comment by ShiyuanResearch** [comment]
The distributed_partial_fc_sample() can only be used for global_tensor, and you can convert x and y to global_tensor via to_global(). We will improve the error message.

**Comment by xxxyyyzzz12345** [comment]
> The distributed_partial_fc_sample() can only be used for global_tensor, and you can convert x and y to global_tensor via to_global(). We will improve the error message.

**Comment by xxxyyyzzz12345** [comment]
Got it! Thanks for your reply!!
