### ISSUE TITLE
linespace op error

### ISSUE THREAD

**Issue by yoonlee888** [Oneflow-Inc/oneflow#8935]
pytorch里的linspace支持start和end为scalar，oneflow不支持，报错：`
![image](https://user-images.githubusercontent.com/96570234/185057821-1ea245a2-a163-42e7-8b86-ea9b34486d6d.png)

复现例子：
```python
import oneflow as flow

a = flow.tensor(3)
b = flow.tensor(10)
output = flow.linspace(a, b, steps=5)
print(output)
```

**Comment by chengtbf** [comment]
感谢反馈~ 这个问题我们会尽快修复到 nightly oneflow 上

**Comment by chengtbf** [comment]
这个问题已经在：

https://github.com/Oneflow-Inc/oneflow/pull/8941 

修复了，您可以使用最新的 nightly 验证一下~
