### ISSUE TITLE
oneflow.sum produces wrong results with oneflow.diagonal

### ISSUE THREAD

**Issue by EaglewithFire** [Oneflow-Inc/oneflow#8940]
## Summary

After using oneflow.diagonal to get some tensors, oneflow.sum could produce wrong results for these tensors.
It seems that oneflow.diagonal works well, but oneflow.sum doesn't.
This problem could be produced when dytpe for initial tensor for oneflow.diagonal is oneflow.bool or oneflow.int32
and could be easily saw if there exists a loop to compare results.
Also, tensor on both cpu or cuda platform could trigger this issue. 

one wront result is like this:
```shell
a =  tensor([[[6, 7, 6, 0],
         [3, 6, 8, 5],
         [6, 5, 9, 1],
         [5, 2, 5, 8]]], dtype=oneflow.int32)
b =  tensor([[[6, 7, 6, 0],
         [3, 6, 8, 5],
         [6, 5, 9, 1],
         [5, 2, 5, 8]]], dtype=oneflow.int32)
tensor(20, dtype=oneflow.int64) tensor(26, dtype=oneflow.int64)
error
```

## Code to reproduce bug
```python
import oneflow
tensor_1 = oneflow.randint(0, 10, [1, 5, 5, 4], dtype=oneflow.int32)
tensor_2 = tensor_1.clone().cpu()
for i in range(10):
    a = oneflow.diagonal(tensor_1, 1, 1, 2)
    b = oneflow.diagonal(tensor_2, 1, 1, 2)
    print("a = ", a)
    print("b = ", b)
    sum_1 = oneflow.sum(a)
    sum_2 = oneflow.sum(b)
    print(sum_1, sum_2)
    
    if(sum_1 != sum_2):
        print("error")
        break
```

## System Information

- What is your OneFlow installation (pip, source, dockerhub):  pip 
- OS: Ubuntu 18.04.1
- OneFlow version (run `python3 -m oneflow --doctor`): 0.8.0+cu112
- Python version:  3.9.12
- CUDA driver version: 11.4
- GPU models: Nvidia RTX 2060
- Other info:

**Comment by ShiyuanResearch** [comment]
Thanks for your feedback. This issue has been fixed in the nightly version of oneflow. You update oneflow by `python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu112 -U`.

**Comment by EaglewithFire** [comment]
Thanks for the reply. I will try this update.
