### ISSUE TITLE
Can oneflow eager support amp eager mode ?

### ISSUE THREAD

**Issue by tiancaidagongrenwangdoudou** [Oneflow-Inc/oneflow#8951]
Hi, I want to train a neural network with oneflow eager amp mode, but I found oneflow can't support it. When will eager amp mode be supported? I don't want to use nn.Graph mode now.

**Comment by BBuf** [comment]
Good question, maybe we will support amp eager mode in v0.9.0.

**Comment by tiancaidagongrenwangdoudou** [comment]
> Good question, maybe we will support amp eager mode in v0.9.0? @chengtbf

Thanks!

**Comment by BBuf** [comment]
已经支持amp。
