### ISSUE TITLE
'Tensor' object has no attribute 'bool'

### ISSUE THREAD

**Issue by ShiyuanResearch** [Oneflow-Inc/oneflow#9031]
用户反馈：

在将基于pytorch实现的模型迁移到oneflow，遇到：'Tensor' object has no attribute 'bool'
虽然可以用 .to(oneflow.bool) 的方式绕过，不过确实是一个与pytorch接口不一致的地方。

version: 0.8.1.dev20220830+cu112

**Comment by marigoold** [comment]
我来加吧
