### ISSUE TITLE
wsl ubuntu20.04 编译报 liboneflow.so: undefined symbol: udev_device_get_property_value

### ISSUE THREAD

**Issue by luotf89** [Oneflow-Inc/oneflow#9050]
## Summary

wsl ubuntu20.04 编译报 liboneflow.so: undefined symbol: udev_device_get_property_value

## System Information

- What is your OneFlow installation (pip, source, dockerhub): source
- OS: wsl ubuntu 20.04
- OneFlow version (run `python3 -m oneflow --doctor`):
- Python version: 3.8.10
- CUDA driver version: 无
- GPU models: 无
- Other info: 
- oneflow 版本 下载 2022/9/3号的代码采用的是 master主线当前的分支 commit 92d3d9823b145f492d677d0ddedd9652a7644d55
- 编译过程：
- sudo apt install -y libopenblas-dev nasm g++ gcc python3-pip cmake autoconf libtool
- cmake .. -DCMAKE_BUILD_TYPE=Debug -C ../cmake/caches/cn/cpu.cmake
- make -j 16

**Comment by ShiyuanResearch** [comment]
你好，在ubuntu 20.04环境下编译oneflow未能复现该问题。
udev主要用于用户空间的设备管理，猜测该问题与windows下的子系统wsl有关，wsl对udev的支持还不充分。
参考：https://docs.microsoft.com/zh-cn/windows/wsl/troubleshooting
oneflow目前不支持在windows环境下编译、安装、使用，请尝试在原生linux环境下编译、使用oneflow。
感谢您的反馈。
