### ISSUE TITLE
在二分法确定bug时，发现很长一段时间oneflow的·to_global算子失效，会卡在那（4月-6月）

### ISSUE THREAD

**Issue by shaoshitong** [Oneflow-Inc/oneflow#9056]
我测试了5月11日，5月12日，5月14日，5月26日，7月5日 发布的 oneflow 都不行，但是7月22日开始之后都是可以的。

5月12日的oneflow版本运行以下代码会卡住：
![image](https://user-images.githubusercontent.com/85086735/188447443-4aeed814-ded0-4be3-aa81-5f1a5c6340eb.png)

我想知道这个该怎么解决呢？不可以用最新的oneflow,因为我在确定oneflow无法对齐精度的bug，或者说这个问题有人知道吗

**Comment by yuanms2** [comment]
之前应该有bug没发现，后来修复了。  @shaoshitong 是需要知道这个bug的原因吗？ 为什么需要找到这个具体的版本呢？ 使用最新版本是否满足需求

**Comment by shaoshitong** [comment]
具体来说，我发现了现在最新的oneflow训练存在问题，使得swin和swinv2在精度上差0.7.0版本 10-15个点（ImageNet），所以需要二分法查找，但是在找的过程中发现跑不起来，很头疼。

**Comment by yuanms2** [comment]
使用0.7 版本的oneflow，模型库的实现是不是也要使用那时候的版本？ 

你上面的实验是说  0.7版本 即使不使用swin，连最基本的to_global 都不能运行？以前的测试肯定也是包含to_global的，那时是怎么跑过的呢？  现在你是单卡运行，在单卡上调用to_global 这种特殊的用法有没有问题？ 

@Ldpe2G @strint

**Comment by Ldpe2G** [comment]
> 使用0.7 版本的oneflow，模型库的实现是不是也要使用那时候的版本？
> 
> 你上面的实验是说 0.7版本 即使不使用swin，连最基本的to_global 都不能运行？以前的测试肯定也是包含to_global的，那时是怎么跑过的呢？ 现在你是单卡运行，在单卡上调用to_global 这种特殊的用法有没有问题？
> 
> @Ldpe2G @strint

我重新复述一下问题吧，shaoshitong 他现在在做的事情是，基于 0.8 的oneflow和最新的libai上面调 swin 和 swin v2 的精度，目标是和官方精度对齐。
之前完整训imagenet和官方精度还是差一点，之前安排他来做这个。

然后目前发现的问题是，用0.8的版本的 oneflow，和官方的精度差很多，以前只是差一点点。 

所以就让他先试试 0.7 版本的 oneflow ，发现 0.7 版本的oneflow 和 [这版本的libai](https://github.com/Oneflow-Inc/libai/commit/f02edc0d4016c0f2a9202ec9e9775c319e25183b) 精度是正常的。
具体讨论见： https://github.com/Oneflow-Inc/libai/discussions/366#discussioncomment-3532507


所以就想着用二分法找是从什么时候开始 oneflow 出现问题，然后现在二分查找过程中就发现了中间好多个oneflow的版本 to_global 操作运行会卡住的问题。

**Comment by shaoshitong** [comment]
> 使用0.7 版本的oneflow，模型库的实现是不是也要使用那时候的版本？
> 
> 你上面的实验是说 0.7版本 即使不使用swin，连最基本的to_global 都不能运行？以前的测试肯定也是包含to_global的，那时是怎么跑过的呢？ 现在你是单卡运行，在单卡上调用to_global 这种特殊的用法有没有问题？
> 
> @Ldpe2G @strint

有 0.7.0是可以的，没有问题，但是中间却出现了问题，会卡在那，用的是A100

**Comment by liujuncheng** [comment]
中间的包是怎么安装的，是自己编译的还是下载编译好的？如果是下载的，发一个命令看看。

**Comment by shaoshitong** [comment]
python3 -m pip install -f https://staging.oneflow.info/canary/commit/[COMMIT]/cu112 oneflow

**Comment by shaoshitong** [comment]
> 中间的包是怎么安装的，是自己编译的还是下载编译好的？如果是下载的，发一个命令看看。

就是这个，在oneflow找到对应commit后安装

**Comment by liujuncheng** [comment]
这个应该是因为在oss上没有找到对应的包，然后fallback到pip，下载了8.0+cu102的包，CUDA 10.2 不支持 A100，所以在创建cuda context 时会触发jit，看来像卡住一样
