### ISSUE TITLE
The data parallel example problem

### ISSUE THREAD

**Issue by DarrenYing** [Oneflow-Inc/oneflow#9081]
## Summary

I test the example given in https://docs.oneflow.org/master/parallelism/05_ddp.html, but got problems as following:

```
loaded library: /usr/lib/x86_64-linux-gnu/libibverbs.so.1
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
loaded library: /usr/lib/x86_64-linux-gnu/libibverbs.so.1
loaded library: /usr/lib/x86_64-linux-gnu/libibverbs.so.1
W20220911 09:09:57.704074 11959 rpc_client.cpp:190] LoadServer 127.0.0.1 Failed at 0 times error_code 14 error_message failed to connect to all addresses
Using cuda device
Using cuda device
Epoch 1
-------------------------------
Epoch 1
-------------------------------
Killing subprocess 11958
Killing subprocess 11959
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/distributed/launch.py", line 237, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/oneflow/distributed/launch.py", line 225, in main
    sigkill_handler(signal.SIGTERM, None)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/distributed/launch.py", line 193, in sigkill_handler
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['/opt/conda/bin/python3', '-u', 'train_parallel.py']' died with <Signals.SIGBUS: 7>.
```

## Code to reproduce bug

The code in the same as the given example

## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS: ubuntu 18.04
- OneFlow version (run `python3 -m oneflow --doctor`): 0.8.1.dev20220906+cu112
- Python version: 3.8.13
- CUDA driver version: 11.2
- GPU models: 
- Other info:

**Comment by ShiyuanResearch** [comment]
Thanks for your feedback. Which code snippet is you executed? The first code snippet will automatically download the cifar dataset from `https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz`. Can your environment download the dataset normally? This problem may be caused by a file download error.

**Comment by DarrenYing** [comment]
The first snippet, I have already downloaded the cifar dataset and put it at the right path.
You can see the console print "Epoch 1", means the code is interrupted in the training for-loop.

**Comment by DarrenYing** [comment]
> Thanks for your feedback. Which code snippet is you executed? The first code snippet will automatically download the cifar dataset from `https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz`. Can your environment download the dataset normally? This problem may be caused by a file download error.

The first snippet, I have already downloaded the cifar dataset and put it at the right path.
You can see the console print "Epoch 1", means the code is interrupted in the training for-loop.

**Comment by ShiyuanResearch** [comment]
Has the dataset you downloaded been extracted to the `./data/cifar-10-batches-py/`? If these files exist, it should output `Files already downloaded and verified`. You can set `download=False` in the code to verify that the dataset is loaded locally.

**Comment by DarrenYing** [comment]
> Has the dataset you downloaded been extracted to the `./data/cifar-10-batches-py/`? If these files exist, it should output `Files already downloaded and verified`. You can set `download=False` in the code to verify that the dataset is loaded locally.

Yes, I set the download=True again, the output in console is as following:
```
loaded library: /usr/lib/x86_64-linux-gnu/libibverbs.so.1
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
loaded library: /usr/lib/x86_64-linux-gnu/libibverbs.so.1
loaded library: /usr/lib/x86_64-linux-gnu/libibverbs.so.1
Using cuda device
Using cuda device
Files already downloaded and verified
Files already downloaded and verified
Epoch 1
-------------------------------
Epoch 1
-------------------------------
Killing subprocess 18172
Killing subprocess 18173
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/distributed/launch.py", line 237, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/oneflow/distributed/launch.py", line 225, in main
    sigkill_handler(signal.SIGTERM, None)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/distributed/launch.py", line 193, in sigkill_handler
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['/opt/conda/bin/python3', '-u', 'train_parallel.py']' died with <Signals.SIGBUS: 7>.

```

**Comment by ShiyuanResearch** [comment]
The <Signals.SIGBUS: 7> prompts a `bus error`. Are you running in  the docker?

**Comment by DarrenYing** [comment]
> The <Signals.SIGBUS: 7> prompts a "bus error". Are you running in the docker?

Yes, I use the official docker image, do you know the reason of the problem? Can you give me some advice, thanks a lot.

**Comment by ShiyuanResearch** [comment]
It might be caused by shared memory. Try setting `--ipc=host` when starting the container.

**Comment by DarrenYing** [comment]
> It might be caused by shared memory. Try setting `--ipc=host` when starting the container.

Thanks a lot, I will try tomorrow.

**Comment by DarrenYing** [comment]
> It might be caused by shared memory. Try setting `--ipc=host` when starting the container.

You are right, shared memory is the reason. Thanks.
