### ISSUE TITLE
atanh backward cpu/cuda 计算误差大

### ISSUE THREAD

**Issue by reygu** [Oneflow-Inc/oneflow#9089]
## Summary

似乎是 cuda 的某种计算机制引发的 atanh backward cpu/cuda 精度误差较大（下面的 case1/case2），cuda 的实际表现与 case6 的结果一致

对应的 kAtanhBackwardWithDyX kernel 实现 
https://github.com/Oneflow-Inc/oneflow/blob/a9d6f7624ba00cfade5a14ffd3ebc5a27c3114ad/oneflow/core/ep/common/primitive/binary_functor.h#L422-L429

## Code to reproduce bug

```
import torch
import oneflow as torch

value = 0.99983

# case1: 2941.3071
x = torch.tensor(value).to(torch.device('cpu')).requires_grad_()
y = x.atanh()
dx = torch.autograd.grad(y, x, torch.ones_like(y), True, True)[0]
print('autograd dx cpu \t', dx.detach().cpu().numpy())

# case2: 2941.5571 (oneflow)  2941.3071(pytorch)
x = torch.tensor(value).to(torch.device('cuda')).requires_grad_()
y = x.atanh()
dx = torch.autograd.grad(y, x, torch.ones_like(y), True, True)[0]
print('autograd dx cuda\t', dx.detach().cpu().numpy())

# case3: 2941.4264918395374
x = value
dx = 1./(1-x*x)
print('manual dx python\t', dx)

x = torch.tensor(value).to(torch.device('cuda'))
one = torch.tensor(1.0).to(torch.device('cuda'))

# case4: 2941.3071
dx = 1./(1-x*x)
print('manual dx cuda1\t', dx.detach().cpu().numpy())

# case5: 2941.3071
dx = one/(one-x*x)
print('manual dx cuda2\t', dx.detach().cpu().numpy())

# case6: 2941.5571 
dx = one/(one-x)/(one+x)
print('manual dx cuda3\t', dx.detach().cpu().numpy())
```

## System Information

- OneFlow version (run `python3 -m oneflow --doctor`): 0.8.1.dev20220912+cu112

**Comment by MARD1NO** [comment]
> ## Summary
> 似乎是 cuda 的某种计算机制引发的 atanh backward cpu/cuda 精度误差较大（下面的 case1/case2），cuda 的实际表现与 case6 的结果一致
> 
> 对应的 kAtanhBackwardWithDyX kernel 实现
> 
> https://github.com/Oneflow-Inc/oneflow/blob/a9d6f7624ba00cfade5a14ffd3ebc5a27c3114ad/oneflow/core/ep/common/primitive/binary_functor.h#L422-L429
> 
> ## Code to reproduce bug
> ```
> import torch
> import oneflow as torch
> 
> value = 0.99983
> 
> # case1: 2941.3071
> x = torch.tensor(value).to(torch.device('cpu')).requires_grad_()
> y = x.atanh()
> dx = torch.autograd.grad(y, x, torch.ones_like(y), True, True)[0]
> print('autograd dx cpu \t', dx.detach().cpu().numpy())
> 
> # case2: 2941.5571 (oneflow)  2941.3071(pytorch)
> x = torch.tensor(value).to(torch.device('cuda')).requires_grad_()
> y = x.atanh()
> dx = torch.autograd.grad(y, x, torch.ones_like(y), True, True)[0]
> print('autograd dx cuda\t', dx.detach().cpu().numpy())
> 
> # case3: 2941.4264918395374
> x = value
> dx = 1./(1-x*x)
> print('manual dx python\t', dx)
> 
> x = torch.tensor(value).to(torch.device('cuda'))
> one = torch.tensor(1.0).to(torch.device('cuda'))
> 
> # case4: 2941.3071
> dx = 1./(1-x*x)
> print('manual dx cuda1\t', dx.detach().cpu().numpy())
> 
> # case5: 2941.3071
> dx = one/(one-x*x)
> print('manual dx cuda2\t', dx.detach().cpu().numpy())
> 
> # case6: 2941.5571 
> dx = one/(one-x)/(one+x)
> print('manual dx cuda3\t', dx.detach().cpu().numpy())
> ```
> 
> ## System Information
> * OneFlow version (run `python3 -m oneflow --doctor`): 0.8.1.dev20220912+cu112

我看pytorch的求导是：

https://github.com/pytorch/pytorch/blob/master/tools/autograd/derivatives.yaml#L302-L304

```cpp
- name: atanh(Tensor self) -> Tensor
  self: grad * 1 / (1 - self.pow(2)).conj()
  result: auto_element_wise
```

他把 x * x 换成power运算。

如果你想尝试的话，可以改成 
```cpp
template<DeviceType device, typename Src, typename Dst> 
 struct BinaryFunctor<device, BinaryOp::kAtanhBackwardWithDyX, Src, Dst> { 
   OF_DEVICE_FUNC BinaryFunctor(Scalar attr0, Scalar attr1) {} 
   OF_DEVICE_FUNC Dst operator()(Src dy, Src x) const { 
     const Src one = static_cast<Src>(1.0); 
     return dy * (one / (one - pow(x, 2))); 
   } 
 };
```

**Comment by MARD1NO** [comment]
可以试试这样，我改成如下公式可以和torch匹配上：
```cpp
template<DeviceType device, typename Src, typename Dst>
struct BinaryFunctor<device, BinaryOp::kAtanhBackwardWithDyX, Src, Dst> {
  OF_DEVICE_FUNC BinaryFunctor(Scalar attr0, Scalar attr1) {}
  OF_DEVICE_FUNC Dst operator()(Src dy, Src x) const {
    const Src one = static_cast<Src>(1.0);
    return dy * one / (one - static_cast<Src>(pow(x, 2)));
  }
};
```

然后需要在 binary_functor.cuh 里加两个特化：
```cpp
SPECIALIZATION_PSEUDO_BFLOAT16_BINARY_FUNCTOR(BinaryOp::kAtanhBackwardWithDyX);

SPECIALIZATION_PSEUDO_HALF_BINARY_FUNCTOR(BinaryOp::kAtanhBackwardWithDyX);
```

**Comment by reygu** [comment]
嗯，这样倒是可以，用 pow 就是扩充了位数避免了溢出。要修改的话是统一改还是只特化一个 cuda 版本的？这里 cpu 计算没有误差

**Comment by MARD1NO** [comment]
> 嗯，这样倒是可以，用 pow 就是扩充了位数避免了溢出。要修改的话是统一改还是只特化一个 cuda 版本的？这里 cpu 计算没有误差

那就只在 binary_functor.cuh 里这么改：
```cpp
template<typename Src, typename Dst>
struct BinaryFunctor<DeviceType::kCUDA, BinaryOp::kAtanhBackwardWithDyX, Src, Dst> {
  OF_DEVICE_FUNC BinaryFunctor(Scalar attr0, Scalar attr1) {}
  OF_DEVICE_FUNC Dst operator()(Src dy, Src x) const {
    const Src one = static_cast<Src>(1.0);
    return dy * one / (one - static_cast<Src>(pow(x, 2)));
  }
};

SPECIALIZATION_PSEUDO_BFLOAT16_BINARY_FUNCTOR(BinaryOp::kAtanhBackwardWithDyX);

SPECIALIZATION_PSEUDO_HALF_BINARY_FUNCTOR(BinaryOp::kAtanhBackwardWithDyX);

```
只对齐DeviceType特化，CPU就还是走的binary_functor.h 里的公式

**Comment by reygu** [comment]
这里 `dy * one` 中的 `* one` 有什么特殊的用途吗，其他算子也有这样的，pytorch 的实现也是

**Comment by MARD1NO** [comment]
> 这里 `dy * one` 中的 `* one` 有什么特殊的用途吗，其他算子也有这样的，pytorch 的实现也是

应该没有特别用途，当时我只是把旧公式原样迁移（避免自己改出现大范围误差错误）。dy 和 one 都是 Src类型，相乘应该是结果不会变

**Comment by reygu** [comment]
OK
