### ISSUE TITLE
magic function of bool doesn't support reduce

### ISSUE THREAD

**Issue by jackalcooper** [Oneflow-Inc/oneflow#9157]
## Summary

usually it requires an extra `torch.all` in oneflow when a boolean tensor is used as a boolean value
<img width="778" alt="image" src="https://user-images.githubusercontent.com/5133557/192480819-6966d541-b341-4ad4-81c0-f53a00b738da.png">

## Code to reproduce bug

Please post a minimal example to repro the bug. GitHub Gist or repo is highly recommended.

## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS:
- OneFlow version (run `python3 -m oneflow --doctor`):
- Python version:
- CUDA driver version:
- GPU models:
- Other info:

**Comment by BBuf** [comment]
debug了一下，问题的原因在于flow.equal和torch.equal在两个输入都是Tensor时返回值不一样，flow.equal返回和原始Tensor一样大小的tensor，而pytorch返回一个scalar（只有全部元素相等才为True，否则为False），并且equal算子的广播逻辑也是错误的，后续需要重构下equal算子解决这个问题。
