### ISSUE TITLE
Add op doesn't support mixed inputs of fp16 and fp32

### ISSUE THREAD

**Issue by jackalcooper** [Oneflow-Inc/oneflow#9174]
## Summary

```python3
>       hidden_states = (hidden_states + residual) / self.rescale_output_factor
E       RuntimeError: add_n151 expected all tenser to have same type, but found kFloat and kFloat16
```

## Code to reproduce bug

Please post a minimal example to repro the bug. GitHub Gist or repo is highly recommended.

## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS:
- OneFlow version (run `python3 -m oneflow --doctor`):
- Python version:
- CUDA driver version:
- GPU models:
- Other info:

**Comment by hhhfccz** [comment]
Python 3.7.10 (default, Feb 26 2021, 18:47:35) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import oneflow
>>> a = oneflow.rand((3, 3))
>>> b = a.to(oneflow.float16)
>>> a
tensor([[0.0110, 0.4496, 0.3643],
        [0.7790, 0.8029, 0.7813],
        [0.8193, 0.1584, 0.0414]], dtype=oneflow.float32)
>>> b
tensor([[0.0110, 0.4497, 0.3643],
        [0.7788, 0.8027, 0.7812],
        [0.8193, 0.1583, 0.0414]], dtype=oneflow.float16)
>>> a + b
tensor([[0.0221, 0.8993, 0.7286],
        [1.5578, 1.6056, 1.5625],
        [1.6387, 0.3167, 0.0829]], dtype=oneflow.float32)
>>> c = oneflow.rand((3, 3))
>>> d = c.to(oneflow.float16)
>>> a / d
tensor([[ 0.0114,  1.2100, 11.0226],
        [ 0.8237,  3.2465,  1.4363],
        [ 2.4213,  0.2060,  0.0770]], dtype=oneflow.float32)
>>> (a + b) / c
tensor([[ 0.0229,  2.4202, 22.0466],
        [ 1.6472,  6.4925,  2.8730],
        [ 4.8440,  0.4121,  0.1540]], dtype=oneflow.float32)
>>> (a + b) / d
tensor([[ 0.0229,  2.4202, 22.0438],
        [ 1.6471,  6.4923,  2.8726],
        [ 4.8427,  0.4120,  0.1540]], dtype=oneflow.float32)
