### ISSUE TITLE
clamp op: NotImplementedError: Only support floating or integral data type.

### ISSUE THREAD

**Issue by jackalcooper** [Oneflow-Inc/oneflow#9175]
## Summary

```
>       image = image.clamp(0, 1)
E       NotImplementedError: Only support floating or integral data type.
```

## Code to reproduce bug

Please post a minimal example to repro the bug. GitHub Gist or repo is highly recommended.

## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS:
- OneFlow version (run `python3 -m oneflow --doctor`):
- Python version:
- CUDA driver version:
- GPU models:
- Other info:

**Comment by marigoold** [comment]
这里没看到变量 `image` 的 dtype，我猜是 half 类型？这个 bug 我来改吧

**Comment by MARD1NO** [comment]
> 这里没看到变量 `image` 的 dtype，我猜是 half 类型？这个 bug 我来改吧

应该还是 IsFloatingDataType 这个漏判断fp16了

**Comment by jackalcooper** [comment]
> 这里没看到变量 `image` 的 dtype，我猜是 half 类型？这个 bug 我来改吧

这个现在有PR了吗
