### ISSUE TITLE
block of subclass NN graph has attribute with name `config`

### ISSUE THREAD

**Issue by jackalcooper** [Oneflow-Inc/oneflow#9184]
## Summary

```
  File "/home/caishenghang/diffusers/src/diffusers/models/unet_2d_condition_oneflow.py", line 227, in forward
    if self.config.center_input_sample:
AttributeError: 'BlockConfig' object has no attribute 'center_input_sample'
```

## Code to reproduce bug

Please post a minimal example to repro the bug. GitHub Gist or repo is highly recommended.

## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS:
- OneFlow version (run `python3 -m oneflow --doctor`):
- Python version:
- CUDA driver version:
- GPU models:
- Other info:

**Comment by jackalcooper** [comment]
@chengtbf @strint nn graph 和 block 用 config 这个属性名太容易和用户的实现冲突了

**Comment by jackalcooper** [comment]
> 这个名字，可以再想想办法，难道命名成和oneflow 相关的？

不一定非得和 oneflow 相关，但是叫 config 一定不行，太常见了。

**Comment by strint** [comment]
> > 这个名字，可以再想想办法，难道命名成和oneflow 相关的？
> 
> 不一定非得和 oneflow 相关，但是叫 config 一定不行，太常见了。

可以，后面做个兼容的更改

**Comment by strint** [comment]
Fixed in PR: https://github.com/Oneflow-Inc/oneflow/pull/9351
