### ISSUE TITLE
Add progress bar when nn.graph is compiling a module

### ISSUE THREAD

**Issue by jackalcooper** [Oneflow-Inc/oneflow#9217]
## Summary

For better UX

## Code to reproduce bug

Please post a minimal example to repro the bug. GitHub Gist or repo is highly recommended.

## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS:
- OneFlow version (run `python3 -m oneflow --doctor`):
- Python version:
- CUDA driver version:
- GPU models:
- Other info:

**Comment by strint** [comment]
把 graph 的第一次编译分成 10 个左右的阶段，打开 debug(0) 时，可以看到这 10 个阶段的进度。

**Comment by jackalcooper** [comment]
```
[4/15] IRRoundTrip
```
屏幕输出这样的

**Comment by strint** [comment]
我们的 logical graph ￼pass compile和 task graph compile and init runtime在两个大的 cpp 函数里。和 Python层没有细粒度的交互。

没有细节阶段的和 Python 的交互，这个 Python 层做编译的progress bar 实现就很麻烦。

一个办法就是 cpp 层直接写到std out。

第二个办法依赖我们后续的重构，把graph 的编译拆分得更模块化，所有阶段 Python层都可以调用。

**Comment by jackalcooper** [comment]
> 我们的 logical graph ￼pass compile和 task graph compile and init runtime在两个大的 cpp 函数里。和 Python层没有细粒度的交互。
> 
> 没有细节阶段的和 Python 的交互，这个 Python 层做编译的progress bar 实现就很麻烦。
> 
> 一个办法就是 cpp 层直接写到std out。
> 
> 第二个办法依赖我们后续的重构，把graph 的编译拆分得更模块化，所有阶段 Python层都可以调用。

直接cpp写，不需要和python交互，这个log C++ API也可能需要的。

**Comment by daquexian** [comment]
可以写一个 ForeignProgressNotifier 类和 PythonProgressNotifier 子类，并在 python 层调用 c++ 接口注册全局的 Singleton<PythonProgressNotifier>，在编译的每个阶段调用 `Singleton<PythonProgressNotifier>::Get()` 的成员方法。类似于回调

**Comment by strint** [comment]
> ForeignLockHelper 

这个听起来比较合适

**Comment by strint** [comment]
Done in https://github.com/Oneflow-Inc/oneflow/pull/9537
