### ISSUE TITLE
IndexError: Too many indices for tensor of dimension 0

### ISSUE THREAD

**Issue by jackalcooper** [Oneflow-Inc/oneflow#9222]
## Summary

```
t = tensor(3.0320, device='cuda:0', dtype=oneflow.float32)

    def set_nan_tensor_to_zero(t):
>       t[t != t] = 0
E       IndexError: Too many indices for tensor of dimension 0

tests/test_modeling_oneflow_common.py:1484: IndexError
```

## Code to reproduce bug

```python
def set_nan_tensor_to_zero(t):
    t[t != t] = 0
```
Please post a minimal example to repro the bug. GitHub Gist or repo is highly recommended.

## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS:
- OneFlow version (run `python3 -m oneflow --doctor`):
- Python version:
- CUDA driver version:
- GPU models:
- Other info:

**Comment by wyg1997** [comment]
问题是 scalar tensor 的 scalar setitem/getitem 没有支持，我来做一下

```python
import oneflow as flow

t = flow.tensor(3.0320)
b = flow.tensor(False)
print(t[b])
t[b] = 0
print(t)
```
