### ISSUE TITLE
Slice update should support fp16

### ISSUE THREAD

**Issue by jackalcooper** [Oneflow-Inc/oneflow#9239]
## Summary

Slice update is used in weight initialization, an unimplemented exception is raised if it is a fp16 weight.

## Code to reproduce bug

in `_init_by_initializer_conf`
```
tensor[...] = shared_mem_tensor
```

## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS:
- OneFlow version (run `python3 -m oneflow --doctor`):
- Python version:
- CUDA driver version:
- GPU models:
- Other info:

**Comment by wyg1997** [comment]
fixed in #9247
