### ISSUE TITLE
build error on Ubuntu 22.04, gcc 11.2

### ISSUE THREAD

**Issue by zhaoyongke** [Oneflow-Inc/oneflow#9289]
## Summary
......
[ 95%] Linking CXX shared library liboneflow.so
/usr/lib/gcc/x86_64-linux-gnu/11/../../.
./×86_64-linux-gnu/crti.o: in function '_init':
(.init+Oxb): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against undefined symbol
_gmon_start.
MakeFiles/oneflow.dir/oneflow/core/auto_parallel/binary_set.cpp.o:in function
"oneflow: :auto_parallel: :BinarySet: :QuickOutput(std: :vector‹int
std: :allocator<int> >&) const':
binary_set. cpp: (. text+Oxc1a) : relocation truncated to fit: R_X86_64_PC32 against
_bes
binary_set. cpp: (.text+0xc21): relocation truncated to fit: R_X86_64_PC3Z against
.bss
binary_set.cpp: (.text+0xcc3): relocation truncated to fit: R_X86_64_PC32 against
. bss
MakeFiles/oneflow.dir/oneflow/core/auto_parallel/binary_set.cpp.o:in function
_GLOBAL__sub_I_binary_set.cpp.cold':
binary_set.cpp:(.text.unlikely+0x45): relocation truncated to fit: R_X86_64_PC32 against
-bss
binary_set.cpp:(.text.unlikely+0x6d): relocation truncated to fit: R_X86_64_PC32 against
.bss'
binary_set.cpp:(.text.unlikely+0x79): relocation truncated to fit: R_X86_64_PC32 against
• bss
binary-set.cpp:C.text.unlikely+0x80):relocation truncated to fit： R_x86_64_PC32 against
bsS
binary_set.cpp:(.text.unlikely+0x96): relocation truncated to fit: R_X86_64_PC32 against
•bss'
binary_set.cpp:(.text.unlikely+0x9d): relocation truncated to fit: R_X86_64_PC32 against
bss
binary_set.cpp:(.text.unlikely+@xa4): additional relocation overflows omitted from the output
CMakeFiles/oneflow.dir/oneflow/core/comm_network/epoll/epoll_comm_network.cpp.o:infunction
"oneflow::EpollCommNet::~EpollCommNet()':
epoll_comm_network. cpp: (.text+0x5bb): failed to convert GOTPCREL relocation against '_ZN3fLI7FLAGS_VE'; relink with --no-relax
CMakeFiles/oneflow.dir/oneflow/core/comm_network/epoll/epoll_comm_network.cpp.o:infunction
"oneflow::EpollCommNet::InitSockets()":
epoll_comm_network.cpp: (. text+0x211a): failed to convert GOTPCREL relocation against '
_ZN3fLI7FLAGS_VE'; relink with --no-relax
collect: error:
ld returned 1 exit status
make[2]:
*** [MakeFiles/oneflow.dir/build.make:22668: liboneflow.so] Error 1
make[1]:
*** [CMakeFiles/Makefile2:1656: CMakeFiles/oneflow.dir/all] Error
make: *** [Makefile: 166: all] Error 2
A short description about the bug/issue

## Code to reproduce bug

Please post a minimal example to repro the bug. GitHub Gist or repo is highly recommended.
master branch, no changes
## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS: Ubuntu 22.04.1 LTS
- OneFlow version (run `python3 -m oneflow --doctor`):0.8.1+cu118.git.047a856114
- Python version:3.10.6
- CUDA driver version:520.61.05
- GPU models:4090
- Other info:None

**Comment by ShiyuanResearch** [comment]
Too many generated symbols cause the linking failed. You can use `cmake -DCMAKE_CUDA_ARCHITECTURES=89-real -C .. /cmake/caches/cn/cuda.cmake` specifies the target cuda arch for 4090 instead of generating object code for all architectures. And we will adjust the compilation strategy.
