### ISSUE TITLE
flow.cuda.manual_seed_all() 会占用所有显卡的部分显存

### ISSUE THREAD

**Issue by BBuf** [Oneflow-Inc/oneflow#9382]
```python
import oneflow as flow

flow.cuda.manual_seed_all(1)
```

程序调用了flow.cuda.manual_seed_all之后会立刻占用每一张显卡的部分显存，我这里每张卡都被占用了500-600MiB，可能是异常现象。pytorch调用这个接口并没有观察到会占用显卡的显存。

**Comment by shangguanshiyuan** [comment]
这个几百兆应该是cuda context占用的，这个现象原因应该是oneflow和pytorch创建cuda context的时机区别造成的。
oneflow应该是在此处直接初始化cuda了，而pytorch应该是存起来延迟初始化，导致的。
