### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by yaoxinthu** [Oneflow-Inc/oneflow#9425]
## Summary

A short description about the bug/issue

## Code to reproduce bug

Please post a minimal example to repro the bug. GitHub Gist or repo is highly recommended.

## System Information

- What is your OneFlow installation (pip, source, dockerhub): pip
- OS:Linux version 5.8.0-63-generic (buildd@lgw01-amd64-035) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34)
- OneFlow version (run `python3 -m oneflow --doctor`):
- version: 0.8.1+cu112.git.5610333
git_commit: 5610333
cmake_build_type: Release
rdma: True
mlir: True
- Python version:3.7.13
- CUDA driver version:11.6
- GPU models:NVIDIA A30
- Other info:

我个人想把ESRGAN（[Real-ESRGAN-colab](https://github.com/boomb0om/Real-ESRGAN-colab)）转成oneflow版本使用。在oneflow官网的torch模型转oneflow的指引下也成功做到。但是在使用oneflow模型进行predict的时候。就出现了问题

<img width="474" alt="image" src="https://user-images.githubusercontent.com/20432547/202110744-4db99465-7285-4f57-a765-61eef8f8e580.png">
python直接报错Floating point exception (core dumped)退出
据我的定位，发生错误的大概是realesrgan.py 的44、45行
也就是
sr_image = res.permute((0,2,3,1)).clamp_(0, 1).cpu()
np_sr_image = sr_image.numpy()
这两个简单的操作
相关的日志如下：
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/20432547/202111420-c1bd4952-4e3b-40af-8dcb-f745b98044cc.png">
同时，同样转好的模型文件和代码，在A100的GPU上却又能成功运行，但是sr_image的shape并不大，只是500 * 500左右的图片，不是很理解发生这个错误的原因。

**Comment by shangguanshiyuan** [comment]
你好，感谢您的反馈，如截图所示报了两个问题，一个是“Floating point exception”，一个是“out of memory”，这两个应该是不同的问题。
我看您运行的版本的commit是十天之前的版本，是否方便通过`python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu102`的方式更新oneflow到最新版本，观察问题是否依旧存在。
以及您运行“out of memory”的脚本时，可以通过nvidia-smi观察一下gpu显存的利用情况。
如果您方便的话，可以将最小可复现代码贴到此处，我来复现一下您的问题。
谢谢您的帮助。

**Comment by yaoxinthu** [comment]
更新了一下oneflow版本就可以了

**Comment by shangguanshiyuan** [comment]
好的，谢谢您的反馈。该issue将被关闭，如果您有其他疑问需要帮助的话，欢迎随时交流。
