### ISSUE TITLE
Missing package

### ISSUE THREAD

**Issue by go-with-me000** [Oneflow-Inc/oneflow#9443]
## Summary

A short description about the bug/issue

Hello, when I used the model library of oneflow, I saw that **oneflow.compatible** was used in the pre training model of bert provided by oneflow. However, when I use different versions of oneflow, I am prompted that the package cannot be found. In what version of oneflow can I use this package?

**Comment by shangguanshiyuan** [comment]
Thanks for your feedback. The `oneflow.compatible` interface exists in the 0.6.0 version to be compatible with older APIs before 0.4.0 version and has been deprecated. The code of BERT you using may no longer be maintained. You can use the BERT in the libai repository, which is maintained.

libai: https://github.com/Oneflow-Inc/libai
tutorial: https://libai.readthedocs.io/en/latest/tutorials/index.html

**Comment by shangguanshiyuan** [comment]
Thanks for your feedback. This issue will be closed. If you have any other questions, you can reopen this or open a new issue at any time.
