### ISSUE TITLE
oneflow create a log folder at running

### ISSUE THREAD

**Issue by strint** [Oneflow-Inc/oneflow#9461]
## Summary

oneflow create a `log` folder at running.  When it's not in debug mode, the log folder is useless and introduces an extra cost.

## System Information
- OneFlow version (run `python3 -m oneflow --doctor`):0.8.1

**Comment by Yaodada12** [comment]
same problem, confused！

**Comment by strint** [comment]
> same problem, confused！

The log floder will be removed recently.

**Comment by strint** [comment]
Done in: https://github.com/Oneflow-Inc/oneflow/pull/9552
