### ISSUE TITLE
[stable diffusion] flow.empty 指定device为cuda时缺错误创建了cpu上的tensor

### ISSUE THREAD

**Issue by BBuf** [Oneflow-Inc/oneflow#9525]
![图片](https://user-images.githubusercontent.com/35585791/205497805-5472d65d-9468-467f-99b8-e0de493eeea5.png)

**Comment by daquexian** [comment]
复现步骤是神马，我本地没有复现出来

```python
>>> flow.empty(2,3,4,device='cuda:0',dtype=flow.float16).device
device(type='cuda', index=0)
>>> flow.empty(2,3,4,device='cuda:0',dtype=flow.float32).device
device(type='cuda', index=0)
>>> flow.empty(2,3,4,device='cuda:0',dtype=flow.int32).device
device(type='cuda', index=0)
```

**Comment by BBuf** [comment]
> 复现步骤是神马，我本地没有复现出来
> 
> ```python
> >>> flow.empty(2,3,4,device='cuda:0',dtype=flow.float16).device
> device(type='cuda', index=0)
> >>> flow.empty(2,3,4,device='cuda:0',dtype=flow.float32).device
> device(type='cuda', index=0)
> >>> flow.empty(2,3,4,device='cuda:0',dtype=flow.int32).device
> device(type='cuda', index=0)
> ```

我尝试了很久也没复现出来，但在diffuser里就是这样，等我写完周报我么拉个会看看。

**Comment by clackhan** [comment]
> 复现步骤是神马，我本地没有复现出来

下面脚本可以复现，看起来graph interpreter的逻辑和eager不太一样。 @strint @leaves-zwx 

```python
import oneflow as flow
from oneflow import nn

class TestGraph(nn.Graph):
    def __init__(self):
        super().__init__()
    
    def build(self):
        x = flow.empty(2, 3, 4,device='cuda:0',dtype=flow.float)
        print(x.device)
        return x


m = TestGraph()

x = m()
```
