### ISSUE TITLE
ci/test文件夹下的部分脚本运行失败

### ISSUE THREAD

**Issue by AsakusaRinne** [Oneflow-Inc/oneflow#9530]
ci/test文件夹下有一些自动化测试脚本，但是部分脚本运行有问题。

复现方法是直接在oneflow根目录下运行`./ci/test/xxx.sh`（也有可能是因为直接这样做不正确，请指出），目前大部分这个文件夹下的脚本运行都不成功，以下面几个为例：

- generic_test.sh: `cp: cannot stat '/data/home/liuyaohui/code/with_conda/oneflow/python/oneflow/test/ops': No such file or directory`
- 1node_benchmark_test_fp_16.sh: `cp: cannot stat 'python/oneflow/compatible/single_client/benchmarks': No such file or directory`
- 1node_benchmark_test.sh: `cp: cannot stat 'python/oneflow/compatible/single_client/benchmarks': No such file or directory`
- 1node_custom_op_test.sh: `cp: cannot stat 'python/oneflow/compatible/single_client/test/custom_ops': No such file or directory`
- 1node_model_test.sh: `cp: cannot stat 'python/oneflow/compatible/single_client/test': No such file or directory`

看脚本里面也是`python3 -m unittest discover`这种方式，只不过有一些路径不存在，会不会是因为后来测试部分文件结构变了导致脚本过时了呢？

**Comment by AsakusaRinne** [comment]
也可能是因为本地和ci的环境不一样，待验证

**Comment by BBuf** [comment]
> 也可能是因为本地和ci的环境不一样，待验证

ci环境和本地有一些区别，可以直接用ci跑pr。
