### ISSUE TITLE
'Tensor' object has no attribute 'unique

### ISSUE THREAD

**Issue by ccssu** [Oneflow-Inc/oneflow#9540]
## Summary
'Tensor' object has no attribute 'unique
## Code to reproduce bug
![image](https://user-images.githubusercontent.com/109639975/205824677-e98e0773-5f51-44b2-9fc2-9f543c97abaf.png)
## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- 机器: a100
- OS:
- OneFlow version (run `python3 -m oneflow --doctor`):编译安装: 复现 oneflow master分支即可 （commit 号 4d969e4278d8ca51a9411574c2d915fcb76f513e)
- Python version:3.8
- CUDA driver version:
- GPU models:
- Other info:

**Comment by marigoold** [comment]
麻烦添加到 https://github.com/Oneflow-Inc/OneTeam/issues/1207#issuecomment-1073432125 中，如果这个算子没人添加的话我来写吧

**Comment by ccssu** [comment]
> 麻烦添加到 [Oneflow-Inc/OneTeam#1207 (comment)](https://github.com/Oneflow-Inc/OneTeam/issues/1207#issuecomment-1073432125) 中，如果这个算子没人添加的话我来写吧
谢谢，添加好了
![image](https://user-images.githubusercontent.com/109639975/206064824-1c9f1744-4266-4e16-a2cc-5bc00854f275.png)

**Comment by marigoold** [comment]
https://github.com/Oneflow-Inc/oneflow/pull/9593
这个 PR 已经添加
