### ISSUE TITLE
 InferDataType Failed. Expected kFloat, but got kDouble 

### ISSUE THREAD

**Issue by ccssu** [Oneflow-Inc/oneflow#9551]
## Summary
使用 `F.binary_cross_entropy_with_logits(pred_mask, gt_mask, reduction="none")`
⚠️RuntimeError: InferDataType Failed. Expected kFloat, but got kDouble

## Code to reproduce bug

<details open>
<summary> F_flow.py </summary> 

```python
import oneflow as flow 
import oneflow.nn.functional as F
import numpy as np
# RuntimeError: InferDataType Failed. Expected kFloat, but got kDouble 
flow.set_default_dtype(flow.float64)
arr = np.random.randn(48,160,160)
pred_mask = flow.Tensor(arr).float().cuda()
gt_mask = flow.Tensor(arr).cuda()
print(f"{pred_mask.shape=} {gt_mask.shape=} ")
print(f"{pred_mask.is_cuda=} {gt_mask.is_cuda=} ")
print(f"{pred_mask.dtype=} {gt_mask.dtype=}")
loss = F.binary_cross_entropy_with_logits(pred_mask, gt_mask, reduction="none")
print(f"{loss.shape=}")
```
</details>

<details close>
<summary> F_flow.py 输出 </summary>

![image](https://user-images.githubusercontent.com/109639975/205912342-ee1252f8-e423-492d-adce-ff94de1cb12e.png)

</details>

<details open> 
<summary> F_torch.py </summary>

```
import torch as flow 
import torch.nn.functional as F
import numpy as np
# RuntimeError: InferDataType Failed. Expected kFloat, but got kDouble 
flow.set_default_dtype(flow.float64)
arr = np.random.randn(48,160,160)
pred_mask = flow.Tensor(arr).float().cuda()
gt_mask = flow.Tensor(arr).cuda()
print(f"{pred_mask.shape=} {gt_mask.shape=} ")
print(f"{pred_mask.is_cuda=} {gt_mask.is_cuda=} ")
print(f"{pred_mask.dtype=} {gt_mask.dtype=}")
loss = F.binary_cross_entropy_with_logits(pred_mask, gt_mask, reduction="none")
print(f"{loss.shape=}")
```
</details>

<details open>
<summary> F_torch.py 输出 </summary>

```shell
pred_mask.shape=torch.Size([48, 160, 160]) gt_mask.shape=torch.Size([48, 160, 160]) 
pred_mask.is_cuda=True gt_mask.is_cuda=True 
pred_mask.dtype=torch.float32 gt_mask.dtype=torch.float64
loss.shape=torch.Size([48, 160, 160])
```
</details>

注意⚠️
 - oneflow 使用 F.binary_cross_entropy_with_logits 会报错 `InferDataType Failed. Expected kFloat, but got kDouble` 
 - pytorch使用没有报错，对应 `F_torch.py` 
 -使用的 torch.__version__ '1.10.0+cu113'

## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- 机器 oneflow27-root
- OS:
- OneFlow version (pip安装): 版本号 ` 0.8.1.dev20221205+cu112`
- Python version:3.8
- CUDA driver version:
- GPU models:
- Other info:

**Comment by BBuf** [comment]
可以先把gt_mask to到float32，然后加一下TODO。胡伽魁来处理一下本问题吧 @hhhfccz

**Comment by hhhfccz** [comment]
在master上有个比较离谱的问题，不知道谁把to改坏了，我后续去提个issue看看能不能解决一下

code:

```python
import oneflow as flow 
# import oneflow.nn.functional as F
import numpy as np
# RuntimeError: InferDataType Failed. Expected kFloat, but got kDouble 
# flow.set_default_dtype(flow.float64)
arr = np.random.randn(48,160,160)
pred_mask = flow.Tensor(arr).float().cuda()
# gt_mask = flow.Tensor(arr).cuda()
# print(f"{pred_mask.shape} {gt_mask.shape} ")
# print(f"{pred_mask.is_cuda} {gt_mask.is_cuda} ")
# print(f"{pred_mask.dtype} {gt_mask.dtype}")
# loss = F.binary_cross_entropy_with_logits(pred_mask, gt_mask, reduction="none")
# print(f"{loss.shape}")
```

output

```shell
*** Check failure stack trace: ***
    @     0x7fdee1619eca  google::LogMessage::Fail()
    @     0x7fdee161c832  google::LogMessage::SendToLog()
    @     0x7fdee1619a37  google::LogMessage::Flush()
    @     0x7fdee161d9a9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fded7a30270  _ZZSt9call_onceIZN7oneflow19InitCudaContextOnceEiEUlvE_JEEvRSt9once_flagOT_DpOT0_ENUlvE0_4_FUNEv
    @     0x7fdf56bd14df  __pthread_once_slow
    @     0x7fded7a303d2  oneflow::InitCudaContextOnce()
    @     0x7fdedb0ec09c  _ZNSt17_Function_handlerIFN7oneflow5MaybeINS0_3one6TensorEvEERKSt10shared_ptrIS3_ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKlRKbEZNS2_10functional18PackedFunctorMakerIFS4_S8_SG_SI_bEE4makeINSM_4impl11CopyFunctorELi0EEENSM_13PackedFunctorISL_EESG_RKT_EUlS8_SG_SI_SK_E_E9_M_invokeERKSt9_Any_dataS8_SG_SI_SK_
    @     0x7fdede18ea33  oneflow::one::functional::Copy()
    @     0x7fdedb07e1b3  oneflow::one::functional::impl::(anonymous namespace)::LocalTensorTo()
    @     0x7fdedb17ddd9  oneflow::one::functional::impl::ToFunctor::operator()()
    @     0x7fdedb17e3ad  _ZNSt17_Function_handlerIFN7oneflow5MaybeINS0_3one6TensorEvEERKSt10shared_ptrIS3_ERKNS0_8OptionalINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEERKNS9_INS0_6SymbolINS0_5DTypeEEEEERKbEZNS2_10functional18PackedFunctorMakerIFS4_S8_SI_SO_bEE4makeINSS_4impl9ToFunctorELi0EEENSS_13PackedFunctorISR_EERKSF_RKT_EUlS8_SI_SO_SQ_E_E9_M_invokeERKSt9_Any_dataS8_SI_SO_SQ_
    @     0x7fdede18e271  oneflow::one::functional::To()
    @     0x7fdf55abdcb2  (unknown)
    @     0x555d1d35e8b4  _PyMethodDef_RawFastCallKeywords
    @     0x555d1d36577f  _PyMethodDescr_FastCallKeywords
    @     0x555d1d3cac3c  _PyEval_EvalFrameDefault
    @     0x555d1d30dd09  _PyEval_EvalCodeWithName
    @     0x555d1d30ebe4  PyEval_EvalCodeEx
    @     0x555d1d30ec0c  PyEval_EvalCode
    @     0x555d1d425a74  run_mod
    @     0x555d1d42fde1  PyRun_FileExFlags
    @     0x555d1d42ffd3  PyRun_SimpleFileExFlags
    @     0x555d1d431105  pymain_main
    @     0x555d1d43122c  _Py_UnixMain
    @     0x7fdf569f2083  __libc_start_main
    @     0x555d1d3d5e90  (unknown)
Aborted (core dumped)
```

**Comment by BBuf** [comment]
> 在master上有个比较离谱的问题，不知道谁把to改坏了，我后续去提个issue看看能不能解决一下
> 
> code:
> 
> ```python
> import oneflow as flow 
> # import oneflow.nn.functional as F
> import numpy as np
> # RuntimeError: InferDataType Failed. Expected kFloat, but got kDouble 
> # flow.set_default_dtype(flow.float64)
> arr = np.random.randn(48,160,160)
> pred_mask = flow.Tensor(arr).float().cuda()
> # gt_mask = flow.Tensor(arr).cuda()
> # print(f"{pred_mask.shape} {gt_mask.shape} ")
> # print(f"{pred_mask.is_cuda} {gt_mask.is_cuda} ")
> # print(f"{pred_mask.dtype} {gt_mask.dtype}")
> # loss = F.binary_cross_entropy_with_logits(pred_mask, gt_mask, reduction="none")
> # print(f"{loss.shape}")
> ```
> 
> output
> 
> ```shell
> *** Check failure stack trace: ***
>     @     0x7fdee1619eca  google::LogMessage::Fail()
>     @     0x7fdee161c832  google::LogMessage::SendToLog()
>     @     0x7fdee1619a37  google::LogMessage::Flush()
>     @     0x7fdee161d9a9  google::LogMessageFatal::~LogMessageFatal()
>     @     0x7fded7a30270  _ZZSt9call_onceIZN7oneflow19InitCudaContextOnceEiEUlvE_JEEvRSt9once_flagOT_DpOT0_ENUlvE0_4_FUNEv
>     @     0x7fdf56bd14df  __pthread_once_slow
>     @     0x7fded7a303d2  oneflow::InitCudaContextOnce()
>     @     0x7fdedb0ec09c  _ZNSt17_Function_handlerIFN7oneflow5MaybeINS0_3one6TensorEvEERKSt10shared_ptrIS3_ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKlRKbEZNS2_10functional18PackedFunctorMakerIFS4_S8_SG_SI_bEE4makeINSM_4impl11CopyFunctorELi0EEENSM_13PackedFunctorISL_EESG_RKT_EUlS8_SG_SI_SK_E_E9_M_invokeERKSt9_Any_dataS8_SG_SI_SK_
>     @     0x7fdede18ea33  oneflow::one::functional::Copy()
>     @     0x7fdedb07e1b3  oneflow::one::functional::impl::(anonymous namespace)::LocalTensorTo()
>     @     0x7fdedb17ddd9  oneflow::one::functional::impl::ToFunctor::operator()()
>     @     0x7fdedb17e3ad  _ZNSt17_Function_handlerIFN7oneflow5MaybeINS0_3one6TensorEvEERKSt10shared_ptrIS3_ERKNS0_8OptionalINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEERKNS9_INS0_6SymbolINS0_5DTypeEEEEERKbEZNS2_10functional18PackedFunctorMakerIFS4_S8_SI_SO_bEE4makeINSS_4impl9ToFunctorELi0EEENSS_13PackedFunctorISR_EERKSF_RKT_EUlS8_SI_SO_SQ_E_E9_M_invokeERKSt9_Any_dataS8_SI_SO_SQ_
>     @     0x7fdede18e271  oneflow::one::functional::To()
>     @     0x7fdf55abdcb2  (unknown)
>     @     0x555d1d35e8b4  _PyMethodDef_RawFastCallKeywords
>     @     0x555d1d36577f  _PyMethodDescr_FastCallKeywords
>     @     0x555d1d3cac3c  _PyEval_EvalFrameDefault
>     @     0x555d1d30dd09  _PyEval_EvalCodeWithName
>     @     0x555d1d30ebe4  PyEval_EvalCodeEx
>     @     0x555d1d30ec0c  PyEval_EvalCode
>     @     0x555d1d425a74  run_mod
>     @     0x555d1d42fde1  PyRun_FileExFlags
>     @     0x555d1d42ffd3  PyRun_SimpleFileExFlags
>     @     0x555d1d431105  pymain_main
>     @     0x555d1d43122c  _Py_UnixMain
>     @     0x7fdf569f2083  __libc_start_main
>     @     0x555d1d3d5e90  (unknown)
> Aborted (core dumped)
> ```

我这里好像没问题，我拉一下最新的master试试

**Comment by BBuf** [comment]
> 在master上有个比较离谱的问题，不知道谁把to改坏了，我后续去提个issue看看能不能解决一下
> 
> code:
> 
> ```python
> import oneflow as flow 
> # import oneflow.nn.functional as F
> import numpy as np
> # RuntimeError: InferDataType Failed. Expected kFloat, but got kDouble 
> # flow.set_default_dtype(flow.float64)
> arr = np.random.randn(48,160,160)
> pred_mask = flow.Tensor(arr).float().cuda()
> # gt_mask = flow.Tensor(arr).cuda()
> # print(f"{pred_mask.shape} {gt_mask.shape} ")
> # print(f"{pred_mask.is_cuda} {gt_mask.is_cuda} ")
> # print(f"{pred_mask.dtype} {gt_mask.dtype}")
> # loss = F.binary_cross_entropy_with_logits(pred_mask, gt_mask, reduction="none")
> # print(f"{loss.shape}")
> ```
> 
> output
> 
> ```shell
> *** Check failure stack trace: ***
>     @     0x7fdee1619eca  google::LogMessage::Fail()
>     @     0x7fdee161c832  google::LogMessage::SendToLog()
>     @     0x7fdee1619a37  google::LogMessage::Flush()
>     @     0x7fdee161d9a9  google::LogMessageFatal::~LogMessageFatal()
>     @     0x7fded7a30270  _ZZSt9call_onceIZN7oneflow19InitCudaContextOnceEiEUlvE_JEEvRSt9once_flagOT_DpOT0_ENUlvE0_4_FUNEv
>     @     0x7fdf56bd14df  __pthread_once_slow
>     @     0x7fded7a303d2  oneflow::InitCudaContextOnce()
>     @     0x7fdedb0ec09c  _ZNSt17_Function_handlerIFN7oneflow5MaybeINS0_3one6TensorEvEERKSt10shared_ptrIS3_ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKlRKbEZNS2_10functional18PackedFunctorMakerIFS4_S8_SG_SI_bEE4makeINSM_4impl11CopyFunctorELi0EEENSM_13PackedFunctorISL_EESG_RKT_EUlS8_SG_SI_SK_E_E9_M_invokeERKSt9_Any_dataS8_SG_SI_SK_
>     @     0x7fdede18ea33  oneflow::one::functional::Copy()
>     @     0x7fdedb07e1b3  oneflow::one::functional::impl::(anonymous namespace)::LocalTensorTo()
>     @     0x7fdedb17ddd9  oneflow::one::functional::impl::ToFunctor::operator()()
>     @     0x7fdedb17e3ad  _ZNSt17_Function_handlerIFN7oneflow5MaybeINS0_3one6TensorEvEERKSt10shared_ptrIS3_ERKNS0_8OptionalINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEERKNS9_INS0_6SymbolINS0_5DTypeEEEEERKbEZNS2_10functional18PackedFunctorMakerIFS4_S8_SI_SO_bEE4makeINSS_4impl9ToFunctorELi0EEENSS_13PackedFunctorISR_EERKSF_RKT_EUlS8_SI_SO_SQ_E_E9_M_invokeERKSt9_Any_dataS8_SI_SO_SQ_
>     @     0x7fdede18e271  oneflow::one::functional::To()
>     @     0x7fdf55abdcb2  (unknown)
>     @     0x555d1d35e8b4  _PyMethodDef_RawFastCallKeywords
>     @     0x555d1d36577f  _PyMethodDescr_FastCallKeywords
>     @     0x555d1d3cac3c  _PyEval_EvalFrameDefault
>     @     0x555d1d30dd09  _PyEval_EvalCodeWithName
>     @     0x555d1d30ebe4  PyEval_EvalCodeEx
>     @     0x555d1d30ec0c  PyEval_EvalCode
>     @     0x555d1d425a74  run_mod
>     @     0x555d1d42fde1  PyRun_FileExFlags
>     @     0x555d1d42ffd3  PyRun_SimpleFileExFlags
>     @     0x555d1d431105  pymain_main
>     @     0x555d1d43122c  _Py_UnixMain
>     @     0x7fdf569f2083  __libc_start_main
>     @     0x555d1d3d5e90  (unknown)
> Aborted (core dumped)
> ```

master也没问题，你是不是搞错了

**Comment by hhhfccz** [comment]
> > 在master上有个比较离谱的问题，不知道谁把to改坏了，我后续去提个issue看看能不能解决一下
> > code:
> > ```python
> > import oneflow as flow 
> > # import oneflow.nn.functional as F
> > import numpy as np
> > # RuntimeError: InferDataType Failed. Expected kFloat, but got kDouble 
> > # flow.set_default_dtype(flow.float64)
> > arr = np.random.randn(48,160,160)
> > pred_mask = flow.Tensor(arr).float().cuda()
> > # gt_mask = flow.Tensor(arr).cuda()
> > # print(f"{pred_mask.shape} {gt_mask.shape} ")
> > # print(f"{pred_mask.is_cuda} {gt_mask.is_cuda} ")
> > # print(f"{pred_mask.dtype} {gt_mask.dtype}")
> > # loss = F.binary_cross_entropy_with_logits(pred_mask, gt_mask, reduction="none")
> > # print(f"{loss.shape}")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > output
> > ```shell
> > *** Check failure stack trace: ***
> >     @     0x7fdee1619eca  google::LogMessage::Fail()
> >     @     0x7fdee161c832  google::LogMessage::SendToLog()
> >     @     0x7fdee1619a37  google::LogMessage::Flush()
> >     @     0x7fdee161d9a9  google::LogMessageFatal::~LogMessageFatal()
> >     @     0x7fded7a30270  _ZZSt9call_onceIZN7oneflow19InitCudaContextOnceEiEUlvE_JEEvRSt9once_flagOT_DpOT0_ENUlvE0_4_FUNEv
> >     @     0x7fdf56bd14df  __pthread_once_slow
> >     @     0x7fded7a303d2  oneflow::InitCudaContextOnce()
> >     @     0x7fdedb0ec09c  _ZNSt17_Function_handlerIFN7oneflow5MaybeINS0_3one6TensorEvEERKSt10shared_ptrIS3_ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKlRKbEZNS2_10functional18PackedFunctorMakerIFS4_S8_SG_SI_bEE4makeINSM_4impl11CopyFunctorELi0EEENSM_13PackedFunctorISL_EESG_RKT_EUlS8_SG_SI_SK_E_E9_M_invokeERKSt9_Any_dataS8_SG_SI_SK_
> >     @     0x7fdede18ea33  oneflow::one::functional::Copy()
> >     @     0x7fdedb07e1b3  oneflow::one::functional::impl::(anonymous namespace)::LocalTensorTo()
> >     @     0x7fdedb17ddd9  oneflow::one::functional::impl::ToFunctor::operator()()
> >     @     0x7fdedb17e3ad  _ZNSt17_Function_handlerIFN7oneflow5MaybeINS0_3one6TensorEvEERKSt10shared_ptrIS3_ERKNS0_8OptionalINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEERKNS9_INS0_6SymbolINS0_5DTypeEEEEERKbEZNS2_10functional18PackedFunctorMakerIFS4_S8_SI_SO_bEE4makeINSS_4impl9ToFunctorELi0EEENSS_13PackedFunctorISR_EERKSF_RKT_EUlS8_SI_SO_SQ_E_E9_M_invokeERKSt9_Any_dataS8_SI_SO_SQ_
> >     @     0x7fdede18e271  oneflow::one::functional::To()
> >     @     0x7fdf55abdcb2  (unknown)
> >     @     0x555d1d35e8b4  _PyMethodDef_RawFastCallKeywords
> >     @     0x555d1d36577f  _PyMethodDescr_FastCallKeywords
> >     @     0x555d1d3cac3c  _PyEval_EvalFrameDefault
> >     @     0x555d1d30dd09  _PyEval_EvalCodeWithName
> >     @     0x555d1d30ebe4  PyEval_EvalCodeEx
> >     @     0x555d1d30ec0c  PyEval_EvalCode
> >     @     0x555d1d425a74  run_mod
> >     @     0x555d1d42fde1  PyRun_FileExFlags
> >     @     0x555d1d42ffd3  PyRun_SimpleFileExFlags
> >     @     0x555d1d431105  pymain_main
> >     @     0x555d1d43122c  _Py_UnixMain
> >     @     0x7fdf569f2083  __libc_start_main
> >     @     0x555d1d3d5e90  (unknown)
> > Aborted (core dumped)
> > ```
> 
> master也没问题，你是不是搞错了

我这边问题出在.cuda()这一步，nvidia-smi是正常的，我再看看
