### ISSUE TITLE
eager模式能正常运行，graph模式下，mut twice相关报错

### ISSUE THREAD

**Issue by DarrenYing** [Oneflow-Inc/oneflow#9566]
## Summary

在将https://github.com/thuml/MotionRNN 该模型改为使用oneflow运行过程中，注释掉未实现的register_backward_hook接口调用，eager模式能正常运行，但是使用graph模式运行时，报错信息如下：
```
F20221208 16:08:27.755779 19446 job_builder.cpp:336] Check failed: modified_op_conf_op_names_.emplace(op_conf.name()).second model.motion_list.0-add_n-15315 is mut twice.
*** Check failure stack trace: ***
    @     0x7f37a9619fda  google::LogMessage::Fail()
    @     0x7f37a961a2c2  google::LogMessage::SendToLog()
    @     0x7f37a9619b47  google::LogMessage::Flush()
    @     0x7f37a961c6b9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f37a1b61157  oneflow::JobBuilder::MutOpsOnlyOnce()
    @     0x7f37a1c71ce3  _ZZNK7oneflow12_GLOBAL__N_122FuseConsecutiveAddPass5ApplyERKNS_7OpGraphEPNS_10JobBuilderEENKUlPKNS_6OpNodeEE_clES9_
    @     0x7f37a1c72cc5  oneflow::(anonymous namespace)::FuseConsecutiveAddPass::Apply()
    @     0x7f37a1b47b3e  _ZZN7oneflow23LazyJobBuildAndInferCtx8CompleteEvENKUlRKSsiE2_clES2_i
    @     0x7f37a1b4d68c  oneflow::LazyJobBuildAndInferCtx::Complete()
    @     0x7f38778d1d9e  oneflow::CurJobBuildAndInferCtx_Complete()
    @     0x7f38778c6839  (unknown)
    @     0x7f3877723cd9  (unknown)
    @     0x557f1cfbb00e  cfunction_call_varargs
    @     0x557f1cfb013f  _PyObject_MakeTpCall
    @     0x557f1d05add4  _PyEval_EvalFrameDefault
    @     0x557f1d04b600  _PyEval_EvalCodeWithName
    @     0x557f1d04cbc4  _PyFunction_Vectorcall
    @     0x557f1cfe5bf8  method_vectorcall
    @     0x557f1cfb620d  PyObject_Call
    @     0x557f1d0578a7  _PyEval_EvalFrameDefault
    @     0x557f1d04b600  _PyEval_EvalCodeWithName
    @     0x557f1d04cbc4  _PyFunction_Vectorcall
    @     0x557f1cfe5bf8  method_vectorcall
    @     0x557f1cfb620d  PyObject_Call
    @     0x557f1d0578a7  _PyEval_EvalFrameDefault
    @     0x557f1d04b600  _PyEval_EvalCodeWithName
    @     0x557f1d04cbc4  _PyFunction_Vectorcall
    @     0x557f1cfe5bf8  method_vectorcall
    @     0x557f1cfb620d  PyObject_Call
    @     0x557f1d0578a7  _PyEval_EvalFrameDefault
    @     0x557f1d04c0ff  _PyEval_EvalCodeWithName
    @     0x557f1d04cbc4  _PyFunction_Vectorcall
Killing subprocess 19446
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/distributed/launch.py", line 237, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/oneflow/distributed/launch.py", line 225, in main
    sigkill_handler(signal.SIGTERM, None)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/distributed/launch.py", line 193, in sigkill_handler
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['/opt/conda/bin/python3', '-u', 'motionrnn_base.py']' died with <Signals.SIGABRT: 6>.

```

想请教一下，mut twice具体是什么意思，可能是什么地方报错呢？

## Code to reproduce bug

我写了个能复现该问题的demo，地址如下：
https://github.com/DarrenYing/MinDemo/tree/motionrnn

## System Information

- What is your OneFlow installation (pip, source, dockerhub): dockerhub (oneflowinc/oneflow:nightly-cuda11.2 )
- OS:  ubuntu 18.04
- OneFlow version (run `python3 -m oneflow --doctor`): 0.8.1.dev20220906+cu112
- Python version: 3.8.13
- CUDA driver version: 11.2
- GPU models:
- Other info:

**Comment by strint** [comment]
收到，看起来是触发了 fuse add 的编译 pass 里面的一个 bug。我们修一下。

**Comment by strint** [comment]
这个问题在 10 月修复了（https://github.com/Oneflow-Inc/oneflow/pull/9281），你可以更新下 oneflow 版本看看。
```
python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu112
```

安装后可能会报一个 config 的兼容性问题，可以参考这里改一下：https://github.com/Oneflow-Inc/oneflow/issues/9457

**Comment by DarrenYing** [comment]
> 看你的版本是9月份的（0.8.1.dev20220906），这个问题在 10 月修复了（ #9281 ），你可以更新下 oneflow 版本看看。
> 
> ```
> python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu112
> ```
> 
> 安装后可能会报一个 config 的兼容性问题，可以参考这里改一下：#9457

好的，感谢，我试试

**Comment by DarrenYing** [comment]
我把调用 ```nn.init.xavier_normal_()``` 函数的部分都注释掉后，graph模式也能正常运行了

**Comment by strint** [comment]
```
File "/workplace/projects/mindemo/models/MotionRNN_PredRNN.py", line 75, in forward
    nn.init.xavier_normal_(zeros)
```

https://github.com/thuml/MotionRNN/blob/main/core/models/MotionRNN_PredRNN.py#L75

这个问题我们复现下看看

**Comment by strint** [comment]
## 常规的带 input 和 output 的 opexpr 的 inplace 处理逻辑
python 层
```
tensor_a
flow.inplace_op_m(tensor_a)
op_n(tensor_a)
```
functor 层
```
op_m_functor(/* input tensor*/ tensor_a, /* output_tensor */ tensor_a)
```
 laza interpreter
```
op_m(/* input tensor*/ tensor_a, /* output_tensor */ tensor_b)
// 然后 tensor_a 会被指向 op_m/tensor_b
// 这样 op_n 消费 tensor_a 时，就消费的是 op_m 的输出，即 tensor_b
```

**Comment by lixiang007666** [comment]
> > 看你的版本是9月份的（0.8.1.dev20220906），这个问题在 10 月修复了（ #9281 ），你可以更新下 oneflow 版本看看。
> > ```
> > python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu112
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 安装后可能会报一个 config 的兼容性问题，可以参考这里改一下：#9457
> 
> 我换了`oneflowinc/oneflow:0.8.1.dev20221207-cuda11.2`这个版本的镜像，然后这个接口`nn.init.xavier_normal_`报错了，报错信息如下：
> 
> ```
> [ERROR](GRAPH:MotionRNNGraph_0:MotionRNNGraph) building graph got error.
>   0%|                                                                                                                                                                         | 0/100 [00:03<?, ?it/s]
> Traceback (most recent call last):
>   File "motionrnn_base.py", line 151, in <module>
>     train_graph()
>   File "motionrnn_base.py", line 95, in train_graph
>     loss = base_graph(batch_data, mask)
>   File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 234, in __call__
>     self._compile(*args, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 797, in _compile
>     _, eager_outputs = self.build_graph(*args, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 816, in build_graph
>     outputs = self.__build_graph(*args, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 920, in __build_graph
>     outputs = self.build(*lazy_args, **lazy_kwargs)
>   File "/workplace/projects/mindemo/models/MotionRNN_PredRNN.py", line 148, in build
>     out = self.model(inputs, mask)
>   File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 186, in __call__
>     result = self.__block_forward(*args, **kwargs)
>   File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 229, in __block_forward
>     result = unbound_forward_of_module_instance(self, *args, **kwargs)
>   File "/workplace/projects/mindemo/models/MotionRNN_PredRNN.py", line 75, in forward
>     nn.init.xavier_normal_(zeros)
>   File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/init.py", line 171, in xavier_normal_
>     return normal_(tensor, 0.0, std)
>   File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/init.py", line 101, in normal_
>     return flow.normal(mean=mean, std=std, size=tensor.shape, out=tensor)
> RuntimeError: Check failed: !(*outputs)[i]
>   File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/functional/impl/random_functor.cpp", line 354, in operator()
>     OpInterpUtil::Dispatch(*op_, {}, outputs.get(), ctx)
>   File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/op_interpreter.cpp", line 96, in Apply
>     internal_->Apply(op_expr, inputs, outputs, ctx)
>   File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp", line 688, in LazyInterpreterApplyImplForSourceUserOpExpr
> 
> Error Type: oneflow.ErrorProto.check_failed_error
> Killing subprocess 18237
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/opt/conda/lib/python3.8/site-packages/oneflow/distributed/launch.py", line 237, in <module>
>     main()
>   File "/opt/conda/lib/python3.8/site-packages/oneflow/distributed/launch.py", line 225, in main
>     sigkill_handler(signal.SIGTERM, None)
>   File "/opt/conda/lib/python3.8/site-packages/oneflow/distributed/launch.py", line 193, in sigkill_handler
>     raise subprocess.CalledProcessError(
> subprocess.CalledProcessError: Command '['/opt/conda/bin/python3', '-u', 'motionrnn_base.py']' returned non-zero exit status 1.
> ```
> 
> 但eager模式是能正常运行的，请问这个是版本问题吗？

您好，这个问题已经解决了（https://github.com/Oneflow-Inc/oneflow/actions/runs/3688068803）。
可以安装最新的 **nightly** 版本试一下。
```
python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu112
```

**Comment by DarrenYing** [comment]
好的，我去试试，感谢

**Comment by shangguanshiyuan** [comment]
你好，您使用的是cu102的安装包还是cu112的安装包，cuda 10不支持30系显卡的86架构，需要安装cuda 11的安装包。
您可以使用这个命令更新：
`python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu112 -U`

**Comment by DarrenYing** [comment]
> 你好，您使用的是cu102的安装包还是cu112的安装包，cuda 10不支持30系显卡的86架构，需要安装cuda 11的安装包。 您可以使用这个命令更新： `python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu112 -U`

噢噢是的，我换了11.2的镜像，能正常运行了，谢谢。
