### ISSUE TITLE
cpu tensor支持和numpy混合计算

### ISSUE THREAD

**Issue by BBuf** [Oneflow-Inc/oneflow#9604]
吕泽康在使用one-yolov5训练自己的模型时帮助我们发现了一个错误，pytorch的cpu tensor支持和numpy混合计算，而我们是不支持的。最小复现代码如下：

```python
import numpy as np
import oneflow as flow

x = flow.randn(2)
y = np.random.randn(2)

z = x/y
print(z)
```

![图片](https://user-images.githubusercontent.com/35585791/207527571-a97e5b4e-ad30-4053-8f7c-f90d881c1716.png)

pytorch可以正常运行。

**Comment by BBuf** [comment]
以及： ERROR: type Tensor doesn't define __round__ method 这个错误。

**Comment by BBuf** [comment]
@hhhfccz  可以处理下这里的问题么

**Comment by BBuf** [comment]
以及 Tensor.copy() 缺失

**Comment by wyg1997** [comment]
OneFlow Tensor 和 ndarray 兼容计算的事，昨天也有提到：https://github.com/Oneflow-Inc/OneTeam/issues/1827#issuecomment-1346207226 后面我来处理吧

**Comment by daquexian** [comment]
我之前有简单试过，貌似是只有 +-*/ 二元运算符（甚至不是二元算子）支持混合计算

```
>>> import torch
>>> x=torch.ones(1,2)
>>> import numpy as np
>>> y=np.ones((1,2))
>>> x+y
tensor([[2., 2.]], dtype=torch.float64)
>>> torch.add(x,y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: add(): argument 'other' (position 2) must be Tensor, not numpy.ndarray
>>> x/y
tensor([[1., 1.]], dtype=torch.float64)
>>> torch.div(x,y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: div(): argument 'other' (position 2) must be Tensor, not numpy.ndarray
>>>
```

**Comment by hhhfccz** [comment]
> OneFlow Tensor 和 ndarray 兼容计算的事，昨天也有提到：[Oneflow-Inc/OneTeam#1827 (comment)](https://github.com/Oneflow-Inc/OneTeam/issues/1827#issuecomment-1346207226) 后面我来处理吧

应该还有这里的问题，https://github.com/Oneflow-Inc/oneflow/issues/8840 我之前打算在 https://github.com/Oneflow-Inc/oneflow/pull/9521 修，那我在 9521 这里把Tensor.copy() 加一下，这个 Tesnor 和 ndarray 计算的问题麻烦你修改了

**Comment by clackhan** [comment]
fix in https://github.com/Oneflow-Inc/oneflow/pull/9511 and https://github.com/Oneflow-Inc/oneflow/pull/9360

**Comment by wyg1997** [comment]
这个问题应该在 https://github.com/Oneflow-Inc/oneflow/pull/9617 中修复，好像还没合并，可以再检察一下

**Comment by BBuf** [comment]
问题已经被解决。
