### ISSUE TITLE
How to set the conv heuristic parameter to False？

### ISSUE THREAD

**Issue by HangJie720** [Oneflow-Inc/oneflow#9646]
We can use torch.backends.cudnn.benchmark to enable ExhaustiveSearch for better performance in pytorch, Does oneflow provide corresponding environment variables for switching？

**Comment by strint** [comment]
https://oneflow.readthedocs.io/en/master/generated/oneflow.nn.graph.graph_config.GraphConfig.enable_cudnn_conv_heuristic_search_algo.html#oneflow.nn.graph.graph_config.GraphConfig.enable_cudnn_conv_heuristic_search_algo

```python
self.config.enable_cudnn_conv_heuristic_search_algo(False)
```

@liujuncheng @leaves-zwx Please help to confirm this.

**Comment by HangJie720** [comment]
I found that variable doesn't seem to work.
`
from oneflow.nn.graph.graph_config import GraphConfig
config = GraphConfig()
config.enable_cudnn_conv_heuristic_search_algo(False)
`

**Comment by lixiang007666** [comment]
> I found that variable doesn't seem to work. `from oneflow.nn.graph.graph_config import GraphConfig config = GraphConfig() config.enable_cudnn_conv_heuristic_search_algo(False)`

Why? Doesn't seem to be working?
You should use and verify it in Graph as in doc. EX: https://github.com/Oneflow-Inc/oneflow/blob/29ba7f64fd16cef0a4a83a44698ad1f78775b52c/python/oneflow/test/graph/test_optimization_conf.py#L69
Or can you provide a detailed Demo?

**Comment by HangJie720** [comment]
I doesn't verify it in Graph; I just ran a resnet50, modified from a pytorch script, so I mean there is an environment variable that is globally effective，like setting torch.backends.cudnn.benchmark=True;

**Comment by lixiang007666** [comment]
> I doesn't verify it in Graph; I just ran a resnet50, modified from a pytorch script, so I mean there is an environment variable that is globally effective，like setting torch.backends.cudnn.benchmark=True;

In eager mode, oneflow does not provide this global func.

But in Oneflow's graph mode, you have richer optimization options.
https://oneflow.readthedocs.io/en/master/graph.html#id1

**Comment by lixiang007666** [comment]
@HangJie720 
Hi, we provide a switch of `flow.backends.cudnn.enable_conv_heuristic_search_algo(False)`.
Now you can use it in eager mode of oneflow, see: https://github.com/Oneflow-Inc/oneflow/blob/25d2514c29f2d8fe81bc496b7cd57f15b876ca79/python/oneflow/framework/config_util.py#L120


You can install the latest nightly version for testing~
```
python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu112
```
Also, remember to change the cuda version according to your device.🤟
