### ISSUE TITLE
topk op issue

### ISSUE THREAD

**Issue by ice-tong** [Oneflow-Inc/oneflow#9695]
## Summary

The topk ops could be failed if the dim is not specified in oneflow `v0.8.1.dev20221226+cu112`.

## Code to reproduce bug
Install nightly oneflow:
```
pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu112
```
```python
>>> import oneflow as flow
>>> flow.__version__
'0.8.1.dev20221226+cu112'
>>> a = flow.randint(0, 10, (10, 10))
>>> a.topk(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miniconda3/envs/torch1.8/lib/python3.7/site-packages/oneflow/framework/tensor.py", line 398, in _topk
    return flow.topk(self, k, dim, largest, sorted)
TypeError: Error: topk(): argument 'dim' must be int32, not <class 'NoneType'>

>>> 
```

## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS: Ubuntu
- OneFlow version (run `python3 -m oneflow --doctor`):
```
version: 0.8.1.dev20221226+cu112
git_commit: 8aa8522
cmake_build_type: Release
rdma: True
mlir: True
```
- Python version: 3.7.15
- CUDA driver version:
- GPU models:
- Other info:

**Comment by marigoold** [comment]
Thanks for feedback. This bug will be fixed after PR https://github.com/Oneflow-Inc/oneflow/pull/9703 merged to master.

**Comment by marigoold** [comment]
Hi, @ice-tong , this bug has been fixed, please upgrade your oneflow to nightly later (because the fixing will be updated to nightly oneflow tomorrow), or compile oneflow master (if you want to use the bug fixed oneflow immediately). : )
