### ISSUE TITLE
[BUG] OneEmbedding返回异常维度的数据

### ISSUE THREAD

**Issue by PYNing** [Oneflow-Inc/oneflow#9699]
## Summary

最小复现程序内有for循环，前几次循环（次数不定）返回数据的维度符合预期，直至某一次循环返回异常维度的数据，如截图

<img width="384" alt="bug_report" src="https://user-images.githubusercontent.com/11667149/210753780-a079bf8c-0c66-458d-98f7-120ccd4538da.png">

## Code to reproduce bug

https://github.com/PYNing/ttt/blob/main/124.py

## System Information

**- What is your OneFlow installation (pip, source, dockerhub):**  python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu112
**- OS:** Linux 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
**- OneFlow version (run `python3 -m oneflow --doctor`):**
version: 0.8.0+cu112
git_commit: a6d4cb80
cmake_build_type: Release
rdma: True
mlir: True
**- Python version:**  3.10.8
**- CUDA driver version:**  470.141.03
**- GPU models:** NVIDIA GeForce RTX 3090 * 1
**- Other info:**
CUDA version：11.4

**Comment by liujuncheng** [comment]
你好，目前 OneEmbedding 在一个图内只能查询一次，这个是由 OneEmbedding 的实现机制决定的，虽然一部分情况可以正常执行，是因为目前 OneEmbedding 没有完善这部分的检查机制，后续我们会完善这部分的错误检查机制，在检测到一个iter内多次查询同一个 embedding 时及时提示，目前如果需要查询多次，我们推荐的做法是通过将输入concat起来的方式，只查询一次embedding。

**Comment by ShawnXuan** [comment]
Thanks PYNing，
在oneflow 0.8.0 git_commit: a6d4cb8上复现了，
但在0.9.0正常没有复现，如果没有版本要求的话，建议使用新版本。

**Comment by PYNing** [comment]
感谢二位解答。经测试在0.9.0上功能正常，问题解决。
