### ISSUE TITLE
RuntimeError: Each rank must have same input sequence or numpy array

### ISSUE THREAD

**Issue by DarrenYing** [Oneflow-Inc/oneflow#9704]
## Summary

在尝试数据并行时，遇到一个问题，先调用np.reshape，再调用flow.tensor接口创建global tensor时，会报```Each rank must have same input sequence or numpy array```，复现代码如下：

另外关于数据并行，我的预期是：无并行时，batch-size为2，加上```flow.sbp.split(dim=0)```后，每个rank的batch-size为1；但这段代码跑出来的结果是加上split(0)后，```print(batch_data.shape, b1.shape)``` 得到 ```oneflow.Size([4, 20, 1, 100, 100]) oneflow.Size([2, 20, 1, 100, 100])```，想请教一下应该如何修改，十分感谢。

## Code to reproduce bug

```
import oneflow as flow
import numpy as np
from tqdm import tqdm


class FakeDataset(flow.utils.data.Dataset):

    def __getitem__(self, index):
        return flow.randn(20, 1, 100, 100)

    def __len__(self):
        return 100


S0 = flow.sbp.split(dim=0)
P0 = flow.placement("cuda", ranks=[0, 1])

train_dataset = FakeDataset()

train_dataloader = flow.utils.data.DataLoader(
    dataset=train_dataset,
    batch_size=2,
    shuffle=True,
    drop_last=True,
)

if flow.env.get_rank() == 0:
    train_dataloader = tqdm(train_dataloader)

for batch_idx, batch_data in enumerate(train_dataloader, 1):
    batch_data = np.reshape(batch_data, [2, 20, 16, 25, 25])   # 去掉这行就不会报错
    batch_data = flow.tensor(batch_data, placement=P0, sbp=S0)
    if flow.env.get_rank() == 0:
        b1 = batch_data.to_local()
        print(batch_data.shape, b1.shape)

```

## System Information

- What is your OneFlow installation (pip, source, dockerhub): dockerhub
- OS: ubuntu 18.04
- OneFlow version (run `python3 -m oneflow --doctor`):  0.8.1.dev20221214+cu112
- Python version:
- CUDA driver version: 11.2
- GPU models:
- Other info:

**Comment by DarrenYing** [comment]
我又写了个例子，想再请教一下sbp的问题
```
import oneflow as flow

S0 = flow.sbp.split(dim=0)
P01 = flow.placement("cuda", ranks=[0, 1])

data1 = flow.randn(4, 5, placement=P01, sbp=S0)
data2 = flow.tensor(flow.randn(4, 5), placement=P01, sbp=S0)

y = flow.randn(4, 5)
data3 = y.to_global(placement=P01, sbp=S0)

if flow.env.get_rank() == 0:
    x1 = data1.to_local()
    print(x1.shape)  # 2*5

    x2 = data2.to_local()
    print(x2.shape)  # 4*5

    x3 = data3.to_local()
    print(x3.shape)  # 4*5

```
请问```data2```和```data3```这两种情况，应该怎么写，```to_local()```后能得到```2*5```呢

**Comment by shangguanshiyuan** [comment]
> 我又写了个例子，想再请教一下sbp的问题
> 
> import oneflow as flow
> 
> S0 = flow.sbp.split(dim=0)
> P01 = flow.placement("cuda", ranks=[0, 1])
> 
> data1 = flow.randn(4, 5, placement=P01, sbp=S0)
> data2 = flow.tensor(flow.randn(4, 5), placement=P01, sbp=S0)
> 
> y = flow.randn(4, 5)
> data3 = y.to_global(placement=P01, sbp=S0)
> 
> 请问data2和data3这两种情况，应该怎么写，to_local()后能得到2*5呢


您好，在您的这个例子中，`data2`和`data3`由`flow.randn(4, 5)`和`y`这两个local_tensor经过`placement=flow.placement("cuda", ranks=[0, 1]), S0 = flow.sbp.split(dim=0)`构造所得。

`flow.randn(4, 5)`和`y`这两个local_tensor的shape是[4, 5]，同时您设置的sbp为s0，所以经过to_global后得到的`data2`和`data3`的shape为[8, 5]。

如果你希望得到shape为[2, 5]的local_tensor和shape为[4, 5]的global_tensor，可以修改data2和data3的构造过程。

**Comment by DarrenYing** [comment]
> > 我又写了个例子，想再请教一下sbp的问题
> > import oneflow as flow
> > S0 = flow.sbp.split(dim=0)
> > P01 = flow.placement("cuda", ranks=[0, 1])
> > data1 = flow.randn(4, 5, placement=P01, sbp=S0)
> > data2 = flow.tensor(flow.randn(4, 5), placement=P01, sbp=S0)
> > y = flow.randn(4, 5)
> > data3 = y.to_global(placement=P01, sbp=S0)
> > 请问data2和data3这两种情况，应该怎么写，to_local()后能得到2*5呢
> 
> 您好，在您的这个例子中，`data2`和`data3`由`flow.randn(4, 5)`和`y`这两个local_tensor经过`placement=flow.placement("cuda", ranks=[0, 1]), S0 = flow.sbp.split(dim=0)`构造所得。
> 
> `flow.randn(4, 5)`和`y`这两个local_tensor的shape是[4, 5]，同时您设置的sbp为s0，所以经过to_global后得到的`data2`和`data3`的shape为[8, 5]。
> 
> 如果你希望得到shape为[2, 5]的local_tensor和shape为[4, 5]的global_tensor，可以修改data2和data3的构造过程。

请问应该怎么修改，可以举个例子吗？比如已有```local_tensor```的shape为[4, 5]，怎么让其两个变成shape为[2, 5]的```local_tensor```和shape为[4, 5]的```global_tensor```呢

**Comment by shangguanshiyuan** [comment]
您好，从语义上讲，shape为[4, 5]的local_tensor，以s0的形式只能拼接成[8, 5]的global_tensor。如果您希望由s0得到[4, 5]的global_tensor，那您可以由[2, 5]的local_tensor和s0进行构造。

**Comment by DarrenYing** [comment]
> 您好，从语义上讲，shape为[4, 5]的local_tensor，以s0的形式只能拼接成[8, 5]的global_tensor。如果您希望由s0得到[4, 5]的global_tensor，那您可以由[2, 5]的local_tensor和s0进行构造。

谢谢解答。那加载数据集，想数据并行的话，从dataloader中拿到一个batch，让他分发到两张卡上，每张卡上分到一半的batch-size，我原来以为是类似调用```to_global(placement=P01, sbp=S0)```这样就行的，但现在我就不太清楚应该怎么做了，可以请教一下吗，感谢

**Comment by shangguanshiyuan** [comment]
您好，数据并行下各进程是对称执行的，每个进程均会读取dataloader，如果您希望在两张卡上做数据并行，那您只需要在每张卡上读取一半的batch_size，然后通过`to_global(placement=P01, sbp=S0)`拼接成完整的逻辑张量。

**Comment by DarrenYing** [comment]
> 您好，数据并行下各进程是对称执行的，每个进程均会读取dataloader，如果您希望在两张卡上做数据并行，那您只需要在每张卡上读取一半的batch_size，然后通过`to_global(placement=P01, sbp=S0)`拼接成完整的逻辑张量。

谢谢。请问按官方给的这个例子，https://docs.oneflow.org/master/parallelism/05_ddp.html
实际运行的batch-size是128吗？每个迭代，cuda-0号卡和cuda-1号卡，都拿到batch-size=64的数据运行，是这样吗？

**Comment by shangguanshiyuan** [comment]
是的，global_batch_size是128。谢谢您的反馈，后续会一致相关概念。

**Comment by shangguanshiyuan** [comment]
你好，在数据并行中64是每个进程每次读取的数据量大小，使用两个gpu进行数据并行的时候，会将两个进程各64的数据拼到一起作为global_batch_size，训练时每轮用128的数据更新模型，所以 50000/(64+64) 是使用该数据集时每个epoch的迭代次数， 50000/64 是所有进程每个epoch读取数据的总次数。

**Comment by DarrenYing** [comment]
> 你好，在数据并行中64是每个进程每次读取的数据量大小，使用两个gpu进行数据并行的时候，会将两个进程各64的数据拼到一起作为global_batch_size，训练时每轮用128的数据更新模型，所以 50000/(64+64) 是使用该数据集时每个epoch的迭代次数， 50000/64 是所有进程每个epoch读取数据的总次数。

感谢解答！那就是说和单卡的batch-size=64训练比较的话，我应该用batch-size=32，配合split(0)的双卡训练，这两者是等效的，不管是比较精度还是加速比，请问是这样理解吗？

**Comment by DarrenYing** [comment]
> > 你好，在数据并行中64是每个进程每次读取的数据量大小，使用两个gpu进行数据并行的时候，会将两个进程各64的数据拼到一起作为global_batch_size，训练时每轮用128的数据更新模型，所以 50000/(64+64) 是使用该数据集时每个epoch的迭代次数， 50000/64 是所有进程每个epoch读取数据的总次数。
> 
> 感谢解答！那就是说和单卡的batch-size=64训练比较的话，我应该用batch-size=32，配合split(0)的双卡训练，这两者是等效的，不管是比较精度还是加速比，请问是这样理解吗？

好像不对，这样的话，同样训练一个epoch，双卡和单卡比，模型更新的次数是不是翻了一倍呢？

**Comment by shangguanshiyuan** [comment]
数据并行时，使用global_batch_size更新模型。当多卡和单卡的global_batch_size相同时，模型更新次数一致。

**Comment by DarrenYing** [comment]
> 数据并行时，使用global_batch_size更新模型。当多卡和单卡的global_batch_size相同时，模型更新次数一致。

感谢！理解了
