### ISSUE TITLE
[0.9.0, Bug] 打开调试日志导致Segmentation fault

### ISSUE THREAD

**Issue by PYNing** [Oneflow-Inc/oneflow#9708]
## Summary
按以下链接操作
https://github.com/Oneflow-Inc/oneflow/issues/9021

添加环境变量
export ONEFLOW_DEBUG_MODE=1
export GLOG_v=3

在建立静态图时出现Segmentation fault

不加环境变量正常

附日志：
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20230106 17:26:56.969116 2076706 singleton.h:43] DeleteGlobal N7oneflow17ForeignLockHelperE
Segmentation fault (core dumped)

## Code to reproduce bug

https://github.com/PYNing/ttt/blob/main/bug_report_230106.py

## System Information

- What is your OneFlow installation (pip, source, dockerhub): python3 -m pip install --find-links https://release.oneflow.info oneflow==0.9.0+cu117
- OS: Linux 5.4.0-122-generic Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- OneFlow version (run python3 -m oneflow --doctor):
path: ['/home/ningpeiyang/miniconda3/envs/libai2/lib/python3.10/site-packages/oneflow']
version: 0.9.0+cu117
git_commit: df8aa87
cmake_build_type: Release
rdma: True
mlir: True
- Python version: 3.10.8
- CUDA driver version: 470.141.03
- GPU models: NVIDIA GeForce RTX 3090 * 1
- Other info:
CUDA version：11.7

**Comment by daquexian** [comment]
您好！可以用最新的 nightly 版本试一试吗

**Comment by PYNing** [comment]
python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu117 

这个命令安装的Nightly版本是0.8.1，但我们需要使用0.9.0及以上的版本，需要怎样修改命令安装更新版本的Nightly呢？

**Comment by PYNing** [comment]
Downloading https://oneflow-staging.oss-cn-beijing.aliyuncs.com/branch/master/cu117/7de22e9869ded4699a996d8ff32de56478461a00/oneflow-0.8.1.dev20230105%2Bcu117-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (964.8 MB)

**Comment by daquexian** [comment]
> Downloading https://oneflow-staging.oss-cn-beijing.aliyuncs.com/branch/master/cu117/7de22e9869ded4699a996d8ff32de56478461a00/oneflow-0.8.1.dev20230105%2Bcu117-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (964.8 MB)

这个已经是 0.9 以上的版本了，可能版本号还没有改过来

**Comment by PYNing** [comment]
谢谢大老师，用上述nightly版解决了问题。
