### ISSUE TITLE
[Bug]Ones() is called in a nn.Graph, but not registered into a nn.Graph

### ISSUE THREAD

**Issue by strint** [Oneflow-Inc/oneflow#9717]
## Summary

```
oneflow/test/expensive/test_conv3d.py::TestConv3DModule::test_nn_functional_conv3d
  /opt/conda/lib/python3.7/site-packages/oneflow/nn/modules/module.py:154: UserWarning: Ones() is called in a nn.Graph, but not registered into a nn.Graph.
    + " is called in a nn.Graph, but not registered into a nn.Graph."
```

## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS:
- OneFlow version (run `python3 -m oneflow --doctor`):0.9
- Python version:
- CUDA driver version:
- GPU models:
- Other info:

**Comment by strint** [comment]
之前增加了一个功能，没有注册到 graph 里面的 module，在 graph build 里面被调用时，就提示一下。

后来发现，有些 functional 的 op，如Ones、Zeros，为了继承，用 继承 module 实现的。但是这些 op 使用时，又不是作为子 module 存在，而是当做 functional 来调用，导致一般都没被注册到 graph 里面。

这样虽然没有正确性问题，但是导致会弹出很多 warning：UserWarning: Ones() is called in a nn.Graph, but not registered into a nn.Graph.

**Comment by strint** [comment]
一个思路是，让 ones 这样的 op，基类不用继承 Module，这样就避免了这个问题，也不影响正确性。

**Comment by BBuf** [comment]
只需要把constant.py都迁移到用functor实现就可以了。
