### ISSUE TITLE
Invalid 2D placement 

### ISSUE THREAD

**Issue by gusye1234** [Oneflow-Inc/oneflow#9727]
## Summary
Changing the 2D placement won't affect the local tensor. I tried two kinds of placement
```
placement2 = flow.placement("cpu", ranks=[[0, 1], [2, 3]])
placement = flow.placement("cpu", ranks=[[0, 3], [1, 2]])
```
and my sbp is `sbp = (flow.sbp.broadcast, flow.sbp.split(1))`.

According to the [docs](https://docs.oneflow.org/master/parallelism/04_2d-sbp.html), the following should happen:
*  for the `placement`, `device:0` and `device:2`, `device:1` and `device:3` share the same local data, respectively. and `device:0` and `device:1`,  `device:2` and `device:3` is `split(1)`, respectively.
* for the `placemen2`, `device:0` and `device:1`, `device:3` and `device:2` share the same local data, respectively. and `device:0` and `device:3`,  `device:1` and `device:2` is `split(1)`, respectively.

However, two different placements have the same local tensor pattern for each device, all following the pattern of `flow.placement("cpu", ranks=[[0, 1], [2, 3]])`, which seems to indicate that set 2D placement is an invalid move.

## Code to reproduce bug

```python
# oneflow_2d.py
import oneflow as flow
rank = flow.env.get_rank()

a = flow.randn(1, 2)
print(f"{rank}-{a}")

placement2 = flow.placement("cpu", ranks=[[0, 1], [2, 3]])
placement = flow.placement("cpu", ranks=[[0, 3], [1, 2]])
sbp = (flow.sbp.broadcast, flow.sbp.split(1))
a_to_global = a.to_global(placement=placement, sbp=sbp)
a_to_global2 = a.to_global(placement=placement2, sbp=sbp)
# print(a_to_global.shape)

print("---")
print(f"{rank}-{a_to_global.to_local()}-{a_to_global2.to_local()}")
```
with launch command `python3 -m oneflow.distributed.launch --nproc_per_node=4 oneflow_2d.py`

Attach output here:
```
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
0-tensor([[-0.2985, -1.1006]], dtype=oneflow.float32)
3-tensor([[0.6814, 1.4043]], dtype=oneflow.float32)
1-tensor([[0.4060, 0.1193]], dtype=oneflow.float32)
2-tensor([[-0.5272,  1.4969]], dtype=oneflow.float32)
---
------

---
3-tensor([[0.4060, 0.1193]], dtype=oneflow.float32)-tensor([[0.4060, 0.1193]], dtype=oneflow.float32)
1-tensor([[0.4060, 0.1193]], dtype=oneflow.float32)-tensor([[0.4060, 0.1193]], dtype=oneflow.float32)
0-tensor([[-0.2985, -1.1006]], dtype=oneflow.float32)-tensor([[-0.2985, -1.1006]], dtype=oneflow.float32)
2-tensor([[-0.2985, -1.1006]], dtype=oneflow.float32)-tensor([[-0.2985, -1.1006]], dtype=oneflow.float32)
```
## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS: Linux
- OneFlow version (run `python3 -m oneflow --doctor`): 0.8.1.dev20221219+cu112
- Python version: 3.8.13
- CUDA driver version: no cuda used
- GPU models: no cuda used
- Other info:

**Comment by wangxicoding** [comment]
![image](https://user-images.githubusercontent.com/10208305/211488578-61505a5d-3e60-47a9-9156-d8156c3f328c.png)
默认会给placement排序

**Comment by gusye1234** [comment]
Close issue as it's solved
