### ISSUE TITLE
Oneflow arm64训练loss值为nan

### ISSUE THREAD

**Issue by icefox888** [Oneflow-Inc/oneflow#9739]
### Description

采用官方quick start案例，训练时loss值为nan.
Win10启动Qemu命令：qemu-system-aarch64.exe -m 4096 -cpu cortex-a72 -smp 2 -M virt -bios D:\qemu\QEMU_EFI.fd -device nec-usb-xhci -device usb-kbd -device usb-mouse -device VGA -device virtio-scsi-device -drive if=none,file=D:\qemu\yhs.qcow2,id=hd0 -device virtio-blk-device,drive=hd0 -device virtio-scsi-device -drive if=none,file=D:\qemu\yh1.qcow2,id=hd1 -device virtio-blk-device,drive=hd1 --net nic -net tap,ifname=tap0
![onflow_bug](https://user-images.githubusercontent.com/107667129/211964260-f839b923-f6f3-4b13-b9d6-20a619c35d2e.jpg)

**Comment by shangguanshiyuan** [comment]
你好，测试在飞腾arm芯片上使用master运行该样例代码是可以输出正常的loss的。
经查询Qemu是Windows环境下一个模拟arm环境的工具，您最终是希望在windows上运行oneflow还是希望在arm环境上运行oneflow？
现阶段，oneflow在windows环境下仅以实验性质支持在wsl2下有限地运行。如果您的目的是希望在arm运行cpu版本的oneflow，您可以尝试在arm芯片下使用原生linux进行测试。

**Comment by shangguanshiyuan** [comment]
你好，测试在飞腾arm芯片上使用master运行该样例代码是可以输出正常的loss的。
经查询Qemu是Windows环境下一个模拟arm环境的工具，您最终是希望在windows上运行oneflow还是希望在arm环境上运行oneflow？
现阶段，oneflow在windows环境下仅以实验性质支持在wsl2下有限地运行。如果您的目的是希望在arm运行cpu版本的oneflow，您可以尝试在arm芯片下使用原生linux进行测试。

**Comment by icefox888** [comment]
谢谢回复，我目前测试采用的时v0.8.0版，根据您的反馈，尝试升级到master测试下。
