### ISSUE TITLE
内存崩溃

### ISSUE THREAD

**Issue by cat6523** [Oneflow-Inc/oneflow#9783]
## Summary
运行推理很长一段时间(超过1天)后，突然崩溃
## Code to reproduce bug
F20230121 23:05:30.138254 13499 op_call_instruction_policy.cpp:209] out of memory
Error message from /home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/op_call_instruction_policy.cpp:209
	OpCallInstructionUtil::Compute(this, instruction): conv2d:OpCall:s_compute

  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/op_call_instruction_policy.cpp", line 209, in Compute
    OpCallInstructionUtil::Compute(this, instruction)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/op_call_instruction_policy.cpp", line 43, in Compute
    TryAllocateTempStorage(op_call_instruction_policy, allocator)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/op_call_instruction_policy.cpp", line 104, in TryAllocateTempStorage
    allocator->Allocate(&mem_ptr, byte_size)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/bin_allocator.h", line 392, in Allocate
    AllocateBlockToExtendTotalMem(aligned_size)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/bin_allocator.h", line 305, in AllocateBlockToExtendTotalMem
    backend_->Allocate(&mem_ptr, final_allocate_bytes)
Error Type: oneflow.ErrorProto.out_of_memory_error
*** Check failure stack trace: ***
    @     0x7f679c71ef3a  google::LogMessage::Fail()
    @     0x7f679c71f222  google::LogMessage::SendToLog()
    @     0x7f679c71eaa7  google::LogMessage::Flush()
    @     0x7f679c721619  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f67954ca7f0  oneflow::vm::OpCallInstructionPolicy::Compute()
    @     0x7f67954c774f  oneflow::vm::EpStreamPolicyBase::Run()
    @     0x7f67954d20b6  oneflow::vm::StreamPolicy::RunIf()
    @     0x7f67954d970e  oneflow::vm::ThreadCtx::TryReceiveAndRun()
    @     0x7f67954dbd5d  oneflow::(anonymous namespace)::WorkerLoop()
    @     0x7f67954dc14f  _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJPFvPN7oneflow2vm9ThreadCtxERKSt8functionIFvS6_EEES6_ZNS3_14VirtualMachine15CreateThreadCtxENS3_6SymbolINS3_6DeviceEEENS3_10StreamTypeEmEUlS6_E3_EEEEE6_M_runEv
    @     0x7f679c73397f  execute_native_thread_routine
    @     0x7f6891f0d6db  start_thread
    @     0x7f6891c36a3f  clone
已放弃 (核心已转储)

 

## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS: ubuntu 1804
- OneFlow version (run `python3 -m oneflow --doctor`):
  version: 0.8.1.dev20221210+cu112
git_commit: 65bd5f52
cmake_build_type: Release
rdma: True
mlir: True

- Python version: 3.8.5
- CUDA driver version: 11.4
- GPU models: 
- Other info:

**Comment by yuanms2** [comment]
It seems to be a memory leak

**Comment by shangguanshiyuan** [comment]
你好，谢谢您的反馈。您使用oneflow进行哪个模型的推理？是否方便提供一个最小代码片段用于问题复现？
另外，OneFlow最近发布了一个新版本0.9.0，您可以通过 `python3 -m pip install oneflow` 安装最新的stable版本的oneflow，也可以通过 `python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu117` 安装nightly版本的oneflow。
nightly版本会每日发布，会更激进的获取oneflow代码上的更新。不过，nightly版本的测试没有stable版本完全，稳定性不如stable版本。

**Comment by cat6523** [comment]
目前复现存在困难，水平有限。。
经过几天的观察和测试，正常使用相当长的时间后，发现隔几个小时似乎有一次显存波动，然后显存有几M的上涨，似乎是显存回收操作？
我短期单独测试却没有任何问题
我是双oneflow模型共用在一张显卡上同时做推理测试，模型推理挺简单的，感觉和pytorch差不多
不知道oneflow是否有关于显存消耗的api或相关的显存调试技巧，便于排查错误
如果有QQ加好友可以进行更详细的说明
今后会持续排查
祝oneflow越来越好~~

**Comment by yuanms2** [comment]
谢谢，提供的信息很有帮助。 

> 正常使用相当长的时间后，发现隔几个小时似乎有一次显存波动，然后显存有几M的上涨，似乎是显存回收操作？

是从开头就每隔几个小时波动一次，还是在正常使用相当长时间之后才每过几个小时波动一次？

**Comment by cat6523** [comment]
[log.zip](https://github.com/Oneflow-Inc/oneflow/files/10528971/log.zip)
提供一份约10+小时的推理和显存消耗的对应关系的日志采样 
比随机肉眼观测要稍微严谨一些
看起来总体显存消耗在增加?
log1.txt对应pid:29097
log2.txt是每间隔1s的显存采样
希望有点儿帮助

**Comment by ouyangyu** [comment]
您好，这个问题我们在oneflow最新commit上进行了测试。在单张3090卡上起了三个stable_diffusion_v1_5的推理进程，超过12小时也未出现显存增加现象。这可能是之前的bug，后续在具体查到后，跟您进一步沟通。此外，为不影响您使用，建议您更新OneFlow版本。感谢。

# System Information
- OneFlow version
```
version: 0.9.1.dev20230129+cu116
git_commit: 1442b30a
cmake_build_type: Release
rdma: True
mlir: True
```

**Comment by cat6523** [comment]
[log2.zip](https://github.com/Oneflow-Inc/oneflow/files/10576224/log2.zip)
升级oneflow后，感觉内存稳定了许多，仍然有点波动(感觉....无尽折腾中,可能是自己的问题,水平有限,无法下结论><,)，不过够我玩耍了
为了严谨一些，这是我折腾2天,在云主机上面重建的环境...跑了近一天的显存分析采样
如果该日志看起来无问题，就关闭该issue吧
如果需要进一步分析，可以留一个email,可以私发复现云环境的链接信息
感谢oneflow团队的付出 ♥♥♥

OneFlow version:
path: ['/root/miniconda3/envs/ldo2_2/lib/python3.8/site-packages/oneflow']
version: 0.9.1.dev20230201+cu117
git_commit: 4bfef84
cmake_build_type: Release
rdma: True
mlir: True

**Comment by cat6523** [comment]
又崩溃了，现在崩溃只有：已放弃 (核心已转储)
没有错误信息了，都没法排错了
oneflow能不能像pytorch一样，出错了能给个大致的问题方向呀，现在遇到问题只能靠抓瞎。。
累了
暂时不想继续该问题了
oneflow version: 0.9.1
最后祝oneflow越来越好。

**Comment by ouyangyu** [comment]
您好，我这边复现一下，麻烦您私信发下我云信息。多谢了。
邮箱：ouyangyu@oneflow.org
