### ISSUE TITLE
flow.nn.Linear 耗时不正常

### ISSUE THREAD

**Issue by ccssu** [Oneflow-Inc/oneflow#9789]
## Summary
> 背景 : 在使用oneflow通codegeex，出现耗时不正常： https://github.com/Oneflow-Inc/one-codegeex/issues/

## Code to reproduce bug

```python
import oneflow as flow 
import math
import time
class SelfAttention(flow.nn.Module):
    def __init__(
        self, 
        hidden_size,
    ):
        super(SelfAttention, self).__init__()
        self.hidden_size = hidden_size
        self.value = flow.nn.Linear(self.hidden_size, self.hidden_size)


if __name__ == '__main__':
    # model = Transformer(hidden_size=5120,num_attention_heads=40,num_layers=39)
    # [build_layer(i+1) for i in range(2)]    
    [SelfAttention(5120) for i in range(10)]    
    print('start:')
    t0 = time.time()
    print(f'{flow.cuda.LongTensor([127])=}',time.time()-t0)

```
<details open>
<summary> 输出 </summary>

```
start:
flow.cuda.LongTensor([127])=tensor([127], device='cuda:0', dtype=oneflow.int64) 18.411341190338135
```
</detail>

<details open>
<summary> import torch as flow后输出</summary>

```shell
start:
flow.cuda.LongTensor([127])=tensor([127], device='cuda:0') 1.4477059841156006
```
</details>

## System Information
- 机器 a100
- What is your OneFlow installation (pip, source, dockerhub):
- torch.__version__ = 1.13.0+cu117 (pip 安装）
- oneflow版本:2023.01.28编译安装 commit 9ad538c2989b4070d04c05b640ea96a0373c4d7e (HEAD -> master）
- Python version: 3.8 
注意：
下图代表，根据仓库https://github.com/THUDM/CodeGeeX 代码修改复现代码的地方
![image](https://user-images.githubusercontent.com/109639975/215304055-a96b8412-42cb-45cc-ac2e-6bd65cdcc3ec.png)

**Comment by BBuf** [comment]
这个和linear没有关系吧，应该是延迟初始化的原因导致的。

**Comment by BBuf** [comment]
如果你初始化的这个模型有forward并且调用了forward应该就不会有问题
