### ISSUE TITLE
oneflow.cuda.amp.GradScaler is not implemented,please help me.

### ISSUE THREAD

**Issue by randompaga** [Oneflow-Inc/oneflow#9822]
### Description

Traceback (most recent call last):
  File "server.py", line 8, in <module>
    import app as user_src
  File "/app.py", line 2, in <module>
    from diffusers import (
  File "/src/diffusers/src/diffusers/__init__.py", line 22, in <module>
    from transformers import CLIPTextModel, CLIPFeatureExtractor
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1101, in __getattr__
    value = getattr(module, name)
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1100, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1112, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
oneflow.cuda.amp.GradScaler is not implemented, please submit an issue at  
'https://github.com/Oneflow-Inc/oneflow/issues' including the log information of the error, the 
minimum reproduction code, and the system information.

**Comment by daquexian** [comment]
Thanks for your issue. It is a known problem. Please uninstall accelerator library by `pip uninstall accelerator`.

**Comment by randompaga** [comment]
Thanks for your reply.
**I runned this command:**
    docker container run -d -it -p 8000:8000 --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 one_flow:1 
**tips:**  
     one_flow:1  is new image what i created.

**The container was builed :**
           CONTAINER ID   IMAGE        COMMAND                    CREATED               STATUS                                PORTS     NAMES
        b88815738a7b   one_flow:1   "/opt/nvidia/nvidia_…"   2 minutes ago    Exited (0) 2 minutes ago              nifty_kalam
**### But the logs of the contaner is below,I can't restart my container,please help me:**

=============
== PyTorch ==
=============

NVIDIA Release 22.09 (build 44877844)
PyTorch Version 1.13.0a0+d0d6b1f

Container image Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

Copyright (c) 2014-2022 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

NOTE: CUDA Forward Compatibility mode ENABLED.
  Using CUDA 11.8 driver version 520.61.03 with kernel driver version 450.102.04.
  See https://docs.nvidia.com/deploy/cuda-compatibility/ for details.


This is use method in github's guide：
docker run --rm -it \
  --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 \
  -v ${HF_HOME}:${HF_HOME} \
  -v ${PWD}:${PWD} \
  -w ${PWD} \
  -e HF_HOME=${HF_HOME} \
  -e HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN} \
  oneflowinc/oneflow-sd:cu117 \
  python3 /demos/oneflow-t2i.py # --prompt "a photo of an astronaut riding a horse on mars"

What is the mean of  "-w ${PWD} \ " ?

**Comment by randompaga** [comment]
> Thanks for your issue. It is a known problem. Please uninstall accelerator library by `pip uninstall accelerator`.

I have solve the problem.THX.

**Comment by randompaga** [comment]
> I have solve the problem.THX.

I have solve the problem.THX.

**Comment by carlitoselmago** [comment]
When I try this i get
```
WARNING: Skipping accelerator as it is not installed.
```
which doesn't fix the problem

> Thanks for your issue. It is a known problem. Please uninstall accelerator library by `pip uninstall accelerator`.
