### ISSUE TITLE
oneflow.tensor 与 numpy.sum 相加存在问题

### ISSUE THREAD

**Issue by x54-729** [Oneflow-Inc/oneflow#9828]
## Summary

您好！我最近发现 oneflow 在与 numpy array 的运算中存在 bug，如果 oneflow 张量和 numpy.sum 的运算结果相加时，如果后者的类型为 numpy.float32 会报错

## Code to reproduce bug

```python
import oneflow
import numpy as np

a = oneflow.tensor([3.0])
b = np.sum([3.0, 4.0], dtype=np.float32)
print(a + b)
```
报错内容为：
```bash
RuntimeError: Error: The object is not scalar, but is numpy.float32
```

经过测试，如果b为np.float64，或者 `b = np.array([4.0])` 的情况都不会报错
## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS: Linus
- OneFlow version (run `python3 -m oneflow --doctor`): 0.9.1.dev20230203+cu116
- Python version: 3.7.13
- CUDA driver version:11.2
- GPU models:
- Other info:

**Comment by BBuf** [comment]
感谢反馈，在 https://github.com/Oneflow-Inc/oneflow/pull/9830 这个pr修复了，等待合并master之后可以再尝试下。

**Comment by x54-729** [comment]
谢谢，问题解决了！
