### ISSUE TITLE
[Question]: conv_cutlass_kernels.cu:138] Check failed: operation != nullptr

### ISSUE THREAD

**Issue by Garnett1314** [Oneflow-Inc/oneflow#9843]
### Description

import oneflow as torch
from diffusers import OneFlowStableDiffusionPipeline as StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained(
  "IDEA-CCNL/Taiyi-Stable-Diffusion-1B-Chinese-v0.1",
  torch_dtype=torch.float16,)
pipe.to('cuda')

prompt = '飞流直下三千尺，水墨画。'
image = pipe(prompt, guidance_scale=7.5).images[0]
print('test')
image.save(f"飞流.png")
出现一下错误：
 0%|          | 0/50 [00:00<?, ?it/s]F20230207 22:52:52.161425  5806 conv_cutlass_kernels.cu:138] Check failed: operation != nullptr 
*** Check failure stack trace: ***
    @     0x7fac8e39a61a  google::LogMessage::Fail()
    @     0x7fac8e39d551  google::LogMessage::SendToLog()
    @     0x7fac8e39a149  google::LogMessage::Flush()
    @     0x7fac8e39de39  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fac87f0c643  oneflow::(anonymous namespace)::Conv2dCutlassKernel::Compute()
    @     0x7fac8748d2ad  oneflow::UserKernel::ForwardUserKernel()
    @     0x7fac8748d47b  oneflow::UserKernel::ForwardDataContent()
    @     0x7fac87459ed3  oneflow::Kernel::Forward()
    @     0x7fac87459fd9  oneflow::Kernel::Launch()
    @     0x7fac875243c1  oneflow::(anonymous namespace)::LightActor<>::ProcessMsg()
    @     0x7fac87ae531f  oneflow::Thread::PollMsgChannel()
    @     0x7fac87ae59b1  _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN7oneflow6ThreadC4ERKNS3_8StreamIdEEUlvE_EEEEE6_M_runEv
    @     0x7fac8e3af890  execute_native_thread_routine
    @     0x7fad6a1b0609  start_thread
    @     0x7fad69f7d103  clone

**Comment by liujuncheng** [comment]
你好，还麻烦你提供一下更具体的环境信息，主要是 oneflow 的版本信息，可以通过 `python3 -m oneflow --doctor` ，以及对应的 GPU 信息，可以通过 nvidia-smi 查看
目前，OneFlow 的 Stable Diffusion 推理优化针对 7.0 以后的架构，如果你是在 Pascal 架构的 GPU ，比如 1080 或者 P100 上执行，便会出现上述错误，可以通过手动将这一行代码删除，https://github.com/Oneflow-Inc/diffusers/blob/oneflow-fork/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_oneflow.py#L150 ， 但是因为Pascal 没有 tensor core 的原因，性能会比较差

**Comment by Garnett1314** [comment]
显卡是1080Ti，我去试试看

**Comment by Garnett1314** [comment]
解决错误了。

**Comment by longgui0318** [comment]
@liujuncheng 我根据上面的做法 注释了那一行，但是还是报错 ，请问该如何处理呢，是新版本做了其他的改动了吗。显卡是P40， oneflow是最新版
