### ISSUE TITLE
Getting error while loading graphs for multiple pipes at once

### ISSUE THREAD

**Issue by diagonalge** [Oneflow-Inc/oneflow#9898]
### Description

Is it possible to run multiple pipes with loaded graphs at once? I am trying to load graphs for multiple sizes, and multiple models into 4 different pipes on RTX 4090. Getting this error:

F20230224 10:26:34.445281 1897542 buffer_manager.h:31] Check failed: name2buffer_.emplace(buffer_name, std::make_unique<Buffer<T>>(buffer_size)).second 
*** Check failure stack trace: ***
    @     0x7fa4568e9eca  google::LogMessage::Fail()
    @     0x7fa4568ece01  google::LogMessage::SendToLog()
    @     0x7fa4568e99f9  google::LogMessage::Flush()
    @     0x7fa4568ed6e9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fa44ec39c77  oneflow::BufferMgr<>::NewBuffer()
    @     0x7fa44ec187aa  oneflow::NNGraph::NewRuntimeBuffers()
    @     0x7fa44ec32c8a  oneflow::NNGraph::InitRuntime()
    @     0x7fa52a5c8b53  (unknown)
    @     0x7fa52a444f3a  (unknown)
    @           0x4e1172  PyCFunction_Call
    @           0x4d207b  _PyObject_MakeTpCall
    @           0x4e974b  method_vectorcall
    @           0x4cce88  _PyEval_EvalFrameDefault
    @           0x4c6fe5  _PyEval_EvalCodeWithName
    @           0x4e9674  method_vectorcall
    @           0x4cce88  _PyEval_EvalFrameDefault
    @           0x4db216  _PyFunction_Vectorcall
    @           0x4c8b7d  _PyEval_EvalFrameDefault
    @           0x4c6fe5  _PyEval_EvalCodeWithName
    @           0x4db2ac  _PyFunction_Vectorcall
    @           0x4c8b7d  _PyEval_EvalFrameDefault
    @           0x4c6fe5  _PyEval_EvalCodeWithName
    @           0x4e9674  method_vectorcall
    @           0x4c9865  _PyEval_EvalFrameDefault
    @           0x4c6fe5  _PyEval_EvalCodeWithName
    @           0x4c6de9  PyEval_EvalCodeEx
    @           0x56d93b  PyEval_EvalCode
    @           0x58cc71  run_eval_code_obj
    @           0x586a2f  run_mod
    @           0x590072  pyrun_file
    @           0x58f422  PyRun_SimpleFileExFlags
    @           0x5842cc  Py_RunMain
Aborted (core dumped)

**Comment by JettHu** [comment]
load two graph with `load_runtime_state_dict`.

```python
import oneflow as flow
  
state_dict = flow.load('oneflow_engine/VaeGraph_1.oneflow')
g1 = flow.nn.Graph()
g1.load_runtime_state_dict(state_dict)

state_dict = flow.load('oneflow_engine/VaeGraph_2oneflow')
g2 = flow.nn.Graph()
g2.load_runtime_state_dict(state_dict)
```

got
```bash
F20230309 19:59:29.216259 37403 buffer_manager.h:31] Check failed: name2buffer_.emplace(buffer_name, std::make_unique<Buffer<T>>(buffer_size)).second 
*** Check failure stack trace: ***
    @     0x7f9525783bea  google::LogMessage::Fail()
    @     0x7f9525786b21  google::LogMessage::SendToLog()
    @     0x7f9525783719  google::LogMessage::Flush()
    @     0x7f9525787409  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f951d836d37  oneflow::BufferMgr<>::NewBuffer()
    @     0x7f951d81596a  oneflow::NNGraph::NewRuntimeBuffers()
    @     0x7f951d82fd8a  oneflow::NNGraph::InitRuntime()
    @     0x7f96009a7933  (unknown)
    @     0x7f960081c830  (unknown)
    @     0x7f96092fc783  cfunction_call
    @     0x7f96092ab693  _PyObject_MakeTpCall.localalias.3
    @     0x7f96092af155  method_vectorcall
    @     0x7f960924b021  call_function
    @     0x7f96092529a6  _PyEval_EvalFrameDefault
    @     0x7f96093ada34  _PyEval_Vector
    @     0x7f96092af10b  method_vectorcall
    @     0x7f960924b021  call_function
    @     0x7f96092529a6  _PyEval_EvalFrameDefault
    @     0x7f96093ada34  _PyEval_Vector
    @     0x7f96093adbed  PyEval_EvalCode
    @     0x7f96093f7244  run_mod
    @     0x7f96093f8307  _PyRun_SimpleFileObject.localalias.11
    @     0x7f96093f891c  _PyRun_AnyFileObject
    @     0x7f96094191de  pymain_run_python.constprop.7
    @     0x7f9609419818  Py_BytesMain
    @     0x7f9608274873  __libc_start_main
    @           0x40107e  _start
Aborted
```

**Comment by JettHu** [comment]
遇到了另一个错误
```bash
F20230309 22:08:36.764286 49442 chunk_manager.cpp:61] Check failed: chunk.mem_size() == store_proto.mem_size() (469762048 vs. 274192384) 
*** Check failure stack trace: ***
    @     0x7fb499352bea  google::LogMessage::Fail()
    @     0x7fb499355b21  google::LogMessage::SendToLog()
    @     0x7fb499352719  google::LogMessage::Flush()
    @     0x7fb499356409  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb4922f0f30  oneflow::ChunkMgr::FindOrCreateChunk()
    @     0x7fb49287bf57  oneflow::RegstMgr::AddPlan()
    @     0x7fb491f6716a  oneflow::Runtime::Runtime()
    @     0x7fb4913ff113  oneflow::NNGraph::InitRuntime()
    @     0x7fb570a56933  (unknown)
    @     0x7fb5708cb830  (unknown)
    @     0x7fb58bc73783  cfunction_call
    @     0x7fb58bc22693  _PyObject_MakeTpCall.localalias.3
    @     0x7fb58bc26155  method_vectorcall
    @     0x7fb58bbc2021  call_function
    @     0x7fb58bbc99a6  _PyEval_EvalFrameDefault
    @     0x7fb58bd24a34  _PyEval_Vector
    @     0x7fb58bc2610b  method_vectorcall
    @     0x7fb58bbc2021  call_function
    @     0x7fb58bbc99a6  _PyEval_EvalFrameDefault
    @     0x7fb58bd24a34  _PyEval_Vector
    @     0x7fb58bd24bed  PyEval_EvalCode
    @     0x7fb58bd1f91d  builtin_exec
    @     0x7fb58bc73f3d  cfunction_vectorcall_FASTCALL
    @     0x7fb58bbc2021  call_function
    @     0x7fb58bbc3e83  _PyEval_EvalFrameDefault
    @     0x7fb58bc37608  gen_send_ex2
    @     0x7fb58bc03633  PyIter_Send
    @     0x7fb58bbcb986  _PyEval_EvalFrameDefault
    @     0x7fb58bc37608  gen_send_ex2
    @     0x7fb58bc03633  PyIter_Send
    @     0x7fb58bbcb986  _PyEval_EvalFrameDefault
    @     0x7fb58bc37608  gen_send_ex2
Aborted
```

**Comment by strint** [comment]
> Check failed: name2buffer_.emplace(buffer_name, std::make_unique<Buffer>(buffer_size)).second

Did you save and load a graph's runtime_state_dict in the same process?  @diagonalge @JettHu

**Comment by JettHu** [comment]
> > Check failed: name2buffer_.emplace(buffer_name, std::make_unique(buffer_size)).second
> 
> Did you save and load a graph's runtime_state_dict in the same process? @diagonalge @JettHu

No, I save graph's runtime_state_dict by a script, and load both with server code.

**Comment by strint** [comment]
> > > Check failed: name2buffer_.emplace(buffer_name, std::make_unique(buffer_size)).second
> > 
> > 
> > Did you save and load a graph's runtime_state_dict in the same process? @diagonalge @JettHu
> 
> No, I save graph's runtime_state_dict by a script, and load both with server code.

Did you save the two graphs in one process call ?

**Comment by JettHu** [comment]
> Did you save the two graphs in one process call?

No. I'll try it.

**Comment by JettHu** [comment]
> Did you save the two graphs in one process call?
thx! It works!
So if I need multi graphs for different inputs' shapes of a same model, I also need to save them in one process call.

**Comment by strint** [comment]
> > Did you save the two graphs in one process call?

> thx! It works!

Great!

> So if I need multi graphs for different inputs' shapes of a same model, I also need to save them in one process call. 

Yes, saving all graph in one process can make each graph has a different ID.  

Limitations like this are not very good, we will try to improve it later.
