### ISSUE TITLE
（ReOpen）[Eager, Tensor Load API] Paramerters reload fail

### ISSUE THREAD

**Issue by PYNing** [Oneflow-Inc/oneflow#9911]
## Code to reproduce bug

https://github.com/PYNing/ttt/blob/main/bug_report_230228.py

## Summary
如复现代码，考虑了一个显存有限情况下的模型集成场景。**使用了load、offload、is_offloaded** 。

问题：第一次推理正常，第二次推理在模型推理处崩溃。从报错信息猜测，**offload的显存没能重新load回去，执行时引用了非法地址**。
另外，第二次推理时，**已被offload的Tensor，is_offloaded()查询的结果为False**。根源可能在这里。

报错如下
> test_offload_load.py(53)<module>()
-> y0 = model0(x)
(Pdb) n
F20230228 10:35:46.363626 3704811 broadcast_matmul.cpp:178] Check failed: cublasGemmEx( cuda_stream->cublas_handle(), cublas_trans_a, cublas_trans_b, cublas_m, cublas_n, cublas_k, &sp_alpha, cublas_a, cuda_data_type, cublas_lda, cublas_b, cuda_data_type, cublas_ldb, &sp_beta, cublas_c, cuda_data_type, cublas_ldc, compute_type, algo) : CUBLAS_STATUS_INVALID_VALUE (7) 
> /home/ningpeiyang/chatgpt/test_offload_load.py(54)<module>()
-> offload_eager_model(model0)
*** Check failure stack trace: ***
(Pdb)     @     0x7ff9fd066eca  google::LogMessage::Fail()
    @     0x7ff9fd069e01  google::LogMessage::SendToLog()
    @     0x7ff9fd0669f9  google::LogMessage::Flush()
    @     0x7ff9fd06a6e9  google::LogMessageFatal::~LogMessageFatal()
    @     0x7ff9f43243af  oneflow::ep::primitive::broadcast_matmul::internal::(anonymous namespace)::BroadcastMatmulImpl<>::Launch()
    @     0x7ff9f16e248f  oneflow::ep::primitive::(anonymous namespace)::BatchMatmulImpl::Launch()
    @     0x7ff9f16e2e26  oneflow::ep::primitive::(anonymous namespace)::MatmulImpl::Launch()
    @     0x7ff9f7d92954  oneflow::(anonymous namespace)::MatmulKernel::Compute()
    @     0x7ff9f87e7a0b  oneflow::one::StatefulOpKernel::Compute()
    @     0x7ff9f679b188  oneflow::vm::OpCallInstructionUtil::Compute()
    @     0x7ff9f67959eb  _ZZN7oneflow2vm23OpCallInstructionPolicy7ComputeEPNS0_11InstructionEENKUlPKcE_clES5_.constprop.0
    @     0x7ff9f6796389  oneflow::vm::OpCallInstructionPolicy::Compute()
    @     0x7ff9f6792bad  oneflow::vm::Instruction::Compute()
    @     0x7ff9f6791295  oneflow::vm::EpStreamPolicyBase::Run()
    @     0x7ff9f67a2aa0  oneflow::vm::ThreadCtx::TryReceiveAndRun()
    @     0x7ff9f67a41f8  oneflow::(anonymous namespace)::WorkerLoop()
    @     0x7ff9f67a49f8  _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJPFvPN7oneflow2vm9ThreadCtxERKSt8functionIFvS6_EEES6_ZNS3_14VirtualMachine15CreateThreadCtxENS3_6SymbolINS3_6DeviceEEENS3_10StreamTypeEmEUlS6_E3_EEEEE6_M_runEv
    @     0x7ff9fd07c170  execute_native_thread_routine
    @     0x7ffadc516609  start_thread
    @     0x7ffadc2d7133  clone
Aborted (core dumped)

## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS: Ubuntu 22.04
- OneFlow version (run `python3 -m oneflow --doctor`): 
path: ['/home/ningpeiyang/miniconda3/envs/of9/lib/python3.10/site-packages/oneflow']
version: 0.9.1.dev20230226+cu117
git_commit: 2c3a05d
cmake_build_type: Release
rdma: True
mlir: True

- Python version: 3.10
- CUDA driver version: 515.48.07
- GPU models: 3090
- Other info: CUDA 11.7

**Comment by strint** [comment]
@lixiang007666 帮忙看下这个问题

**Comment by strint** [comment]
> 已被offload的Tensor，is_offloaded()查询的结果为False

这个比较异常。

is_offloaded()  false 就会导致 load 被跳过。

**Comment by strint** [comment]
Fixed in： https://github.com/Oneflow-Inc/oneflow/pull/9935

**Comment by strint** [comment]
把 
```
param.data.offload()
param.data.load()
```
都替换成 
```
param.offload()
param.load()
```
@PYNing

**Comment by PYNing** [comment]
感谢提醒，经修改代码已经可以跑了
