### ISSUE TITLE
[Bug] A LSTM Model run PP and  DP with graph raise an error

### ISSUE THREAD

**Issue by strint** [Oneflow-Inc/oneflow#9925]
## Summary

https://github.com/DarrenYing/MinDemo/tree/motionrnn

复现以下问题，测试convlstm_2stage.py的流水线并行+数据并行
eager模式能正常运行，graph模式下，会报错， 报错信息如下

```
(GRAPH:ConvLSTMGraph_0:ConvLSTMGraph) start building plan.
F20230302 11:10:01.653455 49675 exec_graph.cpp:121]  Stack Grad expects the shape of input tensor is equal to like tensor's. , but got (8,19,8,50,50) at input and (8,16,25,50)at like
Error message from /home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/graph/exec_graph.cpp:121
        op_->InferBlobDescsIf(GetBlobDesc4BnInOp, parallel_ctx, &GlobalJobDesc()):  infer blob descs if failed, op name

  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/graph/exec_graph.cpp", line 121, in InferBlobDescs
    op_->InferBlobDescsIf(GetBlobDesc4BnInOp, parallel_ctx, &GlobalJobDesc())
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/operator/operator.cpp", line 349, in InferBlobDescsIf
    InferOutBlobDescsIf(GetBlobDesc4BnInOp, parallel_ctx)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/operator/operator.cpp", line 357, in InferOutBlobDescsIf
    InferOutBlobDescs(GetBlobDesc4BnInOp, parallel_ctx)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/operator/user_op.cpp", line 671, in InferOutBlobDescs
    val_->physical_tensor_desc_infer_fn(&infer_ctx)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/user/ops/stack_op.cpp", line 177, in InferLogicalTensorDesc
```

## Code to reproduce bug

Please post a minimal example to repro the bug. GitHub Gist or repo is highly recommended.

## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS:
- OneFlow version (run `python3 -m oneflow --doctor`):
- Python version:
- CUDA driver version:
- GPU models:
- Other info:

**Comment by DarrenYing** [comment]
oneflow镜像版本为version: 0.8.1.dev20220906+cu112

**Comment by lixiang007666** [comment]
下面的 179 后两行代码改为新的 api：
https://github.com/DarrenYing/MinDemo/blob/449520278c6c6540ec5abd77b4173ec33ebc4cb1/models/TwoStageConvLSTM.py#L179
![image](https://user-images.githubusercontent.com/54010254/222462428-e6810011-f167-4587-ab89-2014d8a41c8c.png)

我在 nightly 版本上，测试并行没有问题。

@DarrenYing 更新版本后不会报这个错误了。

**Comment by strint** [comment]
请参考这里 https://github.com/Oneflow-Inc/oneflow#install-with-pip-package 安装 nightly release 试试，估计是新版本修复了一个 bug
```
python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/[PLATFORM]
```

**Comment by DarrenYing** [comment]
> 下面的 179 后两行代码改为新的 api 后： https://github.com/DarrenYing/MinDemo/blob/449520278c6c6540ec5abd77b4173ec33ebc4cb1/models/TwoStageConvLSTM.py#L179 ![image](https://user-images.githubusercontent.com/54010254/222462428-e6810011-f167-4587-ab89-2014d8a41c8c.png)
> 
> 我在 nightly 版本上，测试并行没有问题。
> 
> @DarrenYing 更新版本后已经不会报这个错误了。

我pull了新版本的镜像，能正常运行了，感谢
