### ISSUE TITLE
the effect of using ZeRO is less than expected

### ISSUE THREAD

**Issue by DarrenYing** [Oneflow-Inc/oneflow#9931]
## Summary

我在dp2+pp2（数据并行+流水线并行）和 dp4 两种情况下对比了 开启/关闭 ZeRO 的显存情况，开启：```self.config.enable_zero(True, stage=2)``` 后，使用SGD优化器时，显存节约了约100M左右，使用ADAM优化器，节约了300M左右，具体情况如下：
以下对比图中，上方为没开启ZeRO的，下方为开启了ZeRO的。

dp2+pp2，SGD，显存对比：
![image](https://user-images.githubusercontent.com/38713820/222624108-2bb0b7cf-cf03-4882-baf7-4fa0a69a6a02.png)

dp2+pp2，ADAM，显存对比：
![image](https://user-images.githubusercontent.com/38713820/222624284-1da31e0d-4ae0-4ace-94f4-79e445f0e826.png)

dp4，SGD，显存对比：
![ab8715f3ce559fe8348791ca2138214](https://user-images.githubusercontent.com/38713820/222624362-7ba4631c-6798-4909-b423-7fdb18411c42.png)

dp4，ADAM，显存对比：
![image](https://user-images.githubusercontent.com/38713820/222624839-630f84dc-b595-4829-9315-7bb4170a9bbe.png)

## Code to reproduce bug

最小复现代码及说明，可见 https://github.com/DarrenYing/MinDemo/tree/motionrnn

## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS: ubuntu
- OneFlow version (run `python3 -m oneflow --doctor`):
- Python version:
- CUDA driver version:
- GPU models:
- Other info:

**Comment by chengtbf** [comment]
可以开启：

```
export ONEFLOW_DEBUG_MODE=true
export GLOG_v=3
```

然后把 `./log/local_rank_0/xx_machine/oneflow.INFO`  文件贴一下，里面有详细的内存日志。

**Comment by DarrenYing** [comment]
> 可以开启：
> 
> ```
> export ONEFLOW_DEBUG_MODE=true
> export GLOG_v=3
> ```
> 
> 然后把 `./log/local_rank_0/xx_machine/oneflow.INFO` 文件贴一下，里面有详细的内存日志。

已更新内存日志，https://github.com/DarrenYing/MinDemo/tree/motionrnn/logs

**Comment by DarrenYing** [comment]
输出的内存日志有点大，原来有41M，我把模型参数量调小后，还是有7M

**Comment by chengtbf** [comment]
> 输出的内存日志有点大，原来有41M，我把模型参数量调小后，还是有7M

那改成：
```
export GLOG_v=2
```
再试一下呢？

**Comment by chengtbf** [comment]
```
I20230303 15:34:02.622771 25032 plan_util.cpp:1139] 
 Graph name BaseConvLSTMGraph_0 in Rank: 0, Device: 0 needs to allocate [ 9865.42 MiB ] device memory. 
   In general, Chunk id: 1  memory is [ 9675.98 MiB ] with mem_block_num = 1
        Unreused memory not eager var is  [ 57.6067 MiB ] with mem_block_num = 5182
        Eager Variable Tensor total memory is [ 131.826 MiB ] with mem_block_num = 168
I20230303 15:34:02.623425 25032 plan_util.cpp:1139] 
 Graph name BaseConvLSTMGraph_0 in Rank: 1, Device: 1 needs to allocate [ 9865.42 MiB ] device memory. 
   In general, Chunk id: 3  memory is [ 9675.98 MiB ] with mem_block_num = 1
        Unreused memory not eager var is  [ 57.6067 MiB ] with mem_block_num = 5182
        Eager Variable Tensor total memory is [ 131.826 MiB ] with mem_block_num = 168
I20230303 15:34:02.624047 25032 plan_util.cpp:1139] 
 Graph name BaseConvLSTMGraph_0 in Rank: 2, Device: 2 needs to allocate [ 9865.42 MiB ] device memory. 
   In general, Chunk id: 2  memory is [ 9675.98 MiB ] with mem_block_num = 1
        Unreused memory not eager var is  [ 57.6067 MiB ] with mem_block_num = 5182
        Eager Variable Tensor total memory is [ 131.826 MiB ] with mem_block_num = 168
I20230303 15:34:02.624680 25032 plan_util.cpp:1139] 
 Graph name BaseConvLSTMGraph_0 in Rank: 3, Device: 3 needs to allocate [ 9865.42 MiB ] device memory. 
   In general, Chunk id: 0  memory is [ 9675.98 MiB ] with mem_block_num = 1
        Unreused memory not eager var is  [ 57.6067 MiB ] with mem_block_num = 5182
        Eager Variable Tensor total memory is [ 131.826 MiB ] with mem_block_num = 168
```

这里可以看到， 这个网络的 Variable 占比非常低，只有 131M，但是 activation 却占了 9.6G。 理论上， ZeRO 只能节省 (n-1)/n 的 Variable 显存，这里 n 为 dp 数量 2 或者 4，所以最多节省： 131 * 0.75 的显存 = 98M 的显存。  大头的 activation 并没有减少。

**Comment by DarrenYing** [comment]
> ```
> I20230303 15:34:02.622771 25032 plan_util.cpp:1139] 
>  Graph name BaseConvLSTMGraph_0 in Rank: 0, Device: 0 needs to allocate [ 9865.42 MiB ] device memory. 
>    In general, Chunk id: 1  memory is [ 9675.98 MiB ] with mem_block_num = 1
>         Unreused memory not eager var is  [ 57.6067 MiB ] with mem_block_num = 5182
>         Eager Variable Tensor total memory is [ 131.826 MiB ] with mem_block_num = 168
> I20230303 15:34:02.623425 25032 plan_util.cpp:1139] 
>  Graph name BaseConvLSTMGraph_0 in Rank: 1, Device: 1 needs to allocate [ 9865.42 MiB ] device memory. 
>    In general, Chunk id: 3  memory is [ 9675.98 MiB ] with mem_block_num = 1
>         Unreused memory not eager var is  [ 57.6067 MiB ] with mem_block_num = 5182
>         Eager Variable Tensor total memory is [ 131.826 MiB ] with mem_block_num = 168
> I20230303 15:34:02.624047 25032 plan_util.cpp:1139] 
>  Graph name BaseConvLSTMGraph_0 in Rank: 2, Device: 2 needs to allocate [ 9865.42 MiB ] device memory. 
>    In general, Chunk id: 2  memory is [ 9675.98 MiB ] with mem_block_num = 1
>         Unreused memory not eager var is  [ 57.6067 MiB ] with mem_block_num = 5182
>         Eager Variable Tensor total memory is [ 131.826 MiB ] with mem_block_num = 168
> I20230303 15:34:02.624680 25032 plan_util.cpp:1139] 
>  Graph name BaseConvLSTMGraph_0 in Rank: 3, Device: 3 needs to allocate [ 9865.42 MiB ] device memory. 
>    In general, Chunk id: 0  memory is [ 9675.98 MiB ] with mem_block_num = 1
>         Unreused memory not eager var is  [ 57.6067 MiB ] with mem_block_num = 5182
>         Eager Variable Tensor total memory is [ 131.826 MiB ] with mem_block_num = 168
> ```
> 
> 这里可以看到， 这个网络的 Variable 占比非常低，只有 131M，但是 activation 却占了 9.6G。 理论上， ZeRO 只能节省 (n-1)/n 的 Variable 显存，这里 n 为 dp 数量 2 或者 4，所以最多节省： 131 * 0.75 的显存 = 98M 的显存。 大头的 activation 并没有减少。

噢噢，理解了，感谢！请问那激活重计算，对这类模型，节省显存的效果是不是会好不少？

**Comment by chengtbf** [comment]
> 请问那激活重计算，对这类模型，节省显存的效果是不是会好不少？

可以试一下： https://oneflow.readthedocs.io/en/master/generated/oneflow.nn.graph.graph_block.GraphModule.activation_checkpointing.html#oneflow.nn.graph.graph_block.GraphModule.activation_checkpointing

**Comment by DarrenYing** [comment]
> > 请问那激活重计算，对这类模型，节省显存的效果是不是会好不少？
> 
> 可以试一下： https://oneflow.readthedocs.io/en/master/generated/oneflow.nn.graph.graph_block.GraphModule.activation_checkpointing.html#oneflow.nn.graph.graph_block.GraphModule.activation_checkpointing

我在dp2+pp2的模型graph里加了
 ```
self.module_pipeline.s0_model.to(GraphModule).activation_checkpointing = True
self.module_pipeline.s1_model.to(GraphModule).activation_checkpointing = True
```
显存占用变化如下：（上方是加了activation_checkpointing的，下方是没加的）
![image](https://user-images.githubusercontent.com/38713820/222674773-5b7e3905-9d63-4264-87e2-b8377686aa2b.png)

显存占用反而增加了，推测可能是 LSTM 结构的原因
对应的内存日志可见 https://github.com/DarrenYing/MinDemo/blob/motionrnn/logs/log_v1_with_ac

**Comment by chengtbf** [comment]
```
self.module_pipeline.s0_model.to(GraphModule).activation_checkpointing = True
self.module_pipeline.s1_model.to(GraphModule).activation_checkpointing = True
```

对整个 s0_model 做 Checkpointing 可能是不合理的，相当于一个 gpu 上就只 checkpoint 了一个 tensor，相当于完整执行了一遍前向。  参考 GPT，是至少对其中的每个 transformer layer 都做了一个 checkpoint tensor。 你的这个网络结构里有没有多层的部分，至少每个层都可以做 checkpoint。

不过也确实有可能对于 RNN 这种循环网络，做 checkpoint 是没什么效果的。

**Comment by DarrenYing** [comment]
> ```
> self.module_pipeline.s0_model.to(GraphModule).activation_checkpointing = True
> self.module_pipeline.s1_model.to(GraphModule).activation_checkpointing = True
> ```
> 
> 对整个 s0_model 做 Checkpointing 可能是不合理的，相当于一个 gpu 上就只 checkpoint 了一个 tensor，相当于完整执行了一遍前向。 参考 GPT，是至少对其中的每个 transformer layer 都做了一个 checkpoint tensor。 你的这个网络结构里有没有多层的部分，至少每个层都可以做 checkpoint。
> 
> 不过也确实有可能对于 RNN 这种循环网络，做 checkpoint 是没什么效果的。

嗯嗯，我去参考一下oneflow的GPT实现，再试试，谢谢！
感觉oneflow的sbp视角真的很方便哈哈，值得在我们实验室推广一下！

**Comment by chengtbf** [comment]
嗯嗯，欢迎继续交流~

**Comment by chengtbf** [comment]
LiBai 里有设置 checkpointing 的代码位置，可以参考：

- https://github.com/Oneflow-Inc/libai/blob/31e392929431264a03a0461861c9e834b1583964/libai/models/utils/graph_base.py#L130

**Comment by DarrenYing** [comment]
> LiBai 里有设置 checkpointing 的代码位置，可以参考：
> 
> * https://github.com/Oneflow-Inc/libai/blob/31e392929431264a03a0461861c9e834b1583964/libai/models/utils/graph_base.py#L130

噢噢好的，谢谢指路~

**Comment by DarrenYing** [comment]
> LiBai 里有设置 checkpointing 的代码位置，可以参考：
> 
> * https://github.com/Oneflow-Inc/libai/blob/31e392929431264a03a0461861c9e834b1583964/libai/models/utils/graph_base.py#L130

谢谢大佬，我按这个去试了，每层lstm做一次checkpointing，不加的显存占用是11G，加了之后能降到8G左右，我也截了一下内存日志，如下：
![image](https://user-images.githubusercontent.com/38713820/224008950-ff216580-88c6-477b-a311-d9bbe092e674.png)
![image](https://user-images.githubusercontent.com/38713820/224008885-136df0b0-8cd6-4b37-b089-8238c659c806.png)
感觉效果还可以，十分感谢！

另外想请教一下，这部分的显存节约，如果要通过计算分析，大致应该怎么做呢？

**Comment by chengtbf** [comment]
> 另外想请教一下，这部分的显存节约，如果要通过计算分析，大致应该怎么做呢？

“如果要通过计算分析”，是具体指什么呢？:joy 没理解

是说，通过理论计算出应该节省多少显存吗？

Checkpointing 的算法逻辑是： 对于设置 `activation_checkpointing = True` 的 module， 其 input tensor 会被 checkpoint，其余的 tensor 则会被丢掉，反向重新计算一遍前向 module 得到对应的 tensor。 那么节省的空间就是： 原本 module 中，除 input 以外，反向需要消费前向的 activation tensor 的总大小。

不过受限于内存复用算法 和 module 的执行顺序，我们假设 loss 处达到内存峰值，那么 loss 之前的最近的 module checkpoint 其实是不生效的，因为反向重新计算的 module 的额外开销，和前向 module 的开销相同。 （这也是为什么，如果整个前向都被 checkpoint 到一个 module 里了，那么实际上内存节省的效果也失效了，因为反向重计算的子图等于整个前向，那么仍然会触及内存峰值）。 除了最后一个 module 以外，其他的 checkpointing 效果大致等于： **module 内除 input 以外，反向需要消费前向的 activation tensor 的总大小。**  并不是所有的 activation tensor，因为那些反向计算 grad 时不依赖前向的 op，如 cast、add 等，原本的 activation tensor 就是被立即复用的。

**Comment by DarrenYing** [comment]
> > 另外想请教一下，这部分的显存节约，如果要通过计算分析，大致应该怎么做呢？
> 
> “如果要通过计算分析”，是具体指什么呢？:joy 没理解
> 
> 是说，通过理论计算出应该节省多少显存吗？
> 
> Checkpointing 的算法逻辑是： 对于设置 `activation_checkpointing = True` 的 module， 其 input tensor 会被 checkpoint，其余的 tensor 则会被丢掉，反向重新计算一遍前向 module 得到对应的 tensor。 那么节省的空间就是： 原本 module 中，除 input 以外，反向需要消费前向的 activation tensor 的总大小。
> 
> 不过受限于内存复用算法 和 module 的执行顺序，我们假设 loss 处达到内存峰值，那么 loss 之前的最近的 module checkpoint 其实是不生效的，因为反向重新计算的 module 的额外开销，和前向 module 的开销相同。 （这也是为什么，如果整个前向都被 checkpoint 到一个 module 里了，那么实际上内存节省的效果也失效了，因为反向重计算的子图等于整个前向，那么仍然会触及内存峰值）。 除了最后一个 module 以外，其他的 checkpointing 效果大致等于： **module 内除 input 以外，反向需要消费前向的 activation tensor 的总大小。** 并不是所有的 activation tensor，因为那些反向计算 grad 时不依赖前向的 op，如 cast、add 等，原本的 activation tensor 就是被立即复用的。

嗯嗯，您说的很详细，我理解了，我就是想了解一下checkpointing理论计算大概能节省多少显存，感谢解答！
