### ISSUE TITLE
[Feature Request]: oneflow.exp2

### ISSUE THREAD

**Issue by AsakusaRinne** [Oneflow-Inc/oneflow#9943]
### Background and motivation

Pytorch has an API `torch.exp2` while oneflow not.

### API Proposal

```py
oneflow.exp2(x: Tensor) -> Tensor
```

**Comment by youxiudeshouyeren** [comment]
The operator oneflow.exp2 has been merged into master: https://github.com/Oneflow-Inc/oneflow/pull/9958/
