### ISSUE TITLE
[Question]: OP Benchmark

### ISSUE THREAD

**Issue by Asthestarsfalll** [Oneflow-Inc/oneflow#9954]
### Description

请问如何测试单个OP的性能和精度呢

**Comment by mosout** [comment]
单个算子的性能粗略测试可以使用oneflow.profiler，基础功能和PyTorch是对齐的，使用方法可以参考[profile lenet](https://github.com/Oneflow-Inc/oneflow/blob/master/python/oneflow/test/profiler/test_profile_lenet.py)

更加精确地测量算子性能建议使用 [NVIDIA Nsight Compute](https://developer.nvidia.com/nsight-compute)

至于算子的精度，如果是PyTorch中已经有的算子，可以采取和PyTorch对比的操作，我们有一个框架可以自动完成与PyTorch的对比，详情可以参考我们的测试文件的写法，比如对于[abs](https://github.com/Oneflow-Inc/oneflow/blob/master/python/oneflow/test/modules/test_abs.py)这个算子的测试

如果是PyTorch中没有的算子需要自己使用numpy之类的库模拟计算过程来对比

**Comment by Asthestarsfalll** [comment]
好的 感谢！
